In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json
from scipy import stats as st
import os
import csv

In [35]:
def contains_unicode_char(s):
    for char in s:
        if ord(char) > 127:
            return True
    return False

In [56]:
ban_barta = pd.read_csv("../Dataset/BangalaBarta bangla_spam_sms smishing.csv", encoding='utf-8')
ban_barta.head()

   label                                               text
0  smish  সোনালী ব্যাংক অ্যাকাউন্টে সমস্যা হয়েছে। কল কর...
1  smish  ক্রিপ্টো বিনিয়োগে লাভবান হন! আজই শুরু করুন: h...
2  promo  স্পেশাল ডিল শেষ দিন,৩০জিবি @৩০০৳,৩০দিন! আজই না...
3  promo  ফার্নিচারে মেগা সেল! সব পণ্যে ১৫-৩০% ছাড়। আজই...
4  smish  আপনার ব্যাংক কার্ডটি অবিলম্বে আপডেট করুন। এখান...

In [66]:
print(len(ban_barta))

2772

In [57]:
ban_barta['label'].value_counts()

smish     924
promo     924
normal    924
Name: label, dtype: int64

In [58]:
non_ban_entries = 0
for i in ban_barta['text']:
    if not contains_unicode_char(i):
        print(i)
        non_ban_entries += 1

non_ban_entries

Ads dekhe daily 200-300 tk income korte chaile join korun https://adswork-bd.com/register?ref=140639
100% trusted site Free te kaj korte paben
Call duration 00:00:44, charged 0.92 Taka, remaining balance is   0.41  Taka
Call duration 00:02:51, charged 3.6 Taka, remaining balance is   10.94  Taka
989893 is your verification code for feainternational.com.
989893 is your verification code for feainternational.com.
Assalamualikum!

Apni Ki Barite Boshe Kono Taka Investment Na Kore Taka Income Korte Can?
Tahole Amader Bot E Kaj korun.  Amader Bot E Apni Kono Investment Chara Income Korte Parben

Bot Link :- https://t.me/free_online_income_24bot
Call duration 00:00:44, charged 0.92 Taka, remaining balance is   0.41  Taka
Call duration 00:02:51, charged 3.6 Taka, remaining balance is   10.94  Taka
Call duration 00:02:51, charged 3.6 Taka, remaining balance is   10.94  Taka
989893 is your verification code for feainternational.com.
989893 is your verification code for feainternational.com.
Call duration 00:02:51, charged 3.6 Taka, remaining balance is   10.94  Taka
Call duration 00:02:51, charged 3.6 Taka, remaining balance is   10.94  Taka
Call duration 00:02:51, charged 3.6 Taka, remaining balance is   10.94  Taka

14

In [54]:
ban_spam = pd.read_csv("../Dataset/bangla_spam.csv", encoding='utf-8')
ban_spam = ban_spam.dropna(axis=1)

ban_spam.head()

   type                                               text
0  spam  এই মেসেজটি শেয়ার করুন এবং জিতে নিন আকর্ষণীয় ...
1  spam  আপনার বন্ধুদের রেফার করুন এবং প্রতি রেফারেলে ২...
2   ham  ট্রানজ্যাকশন নম্বর R234321.1554.640085 20 টাকা...
3  spam  নতুন অফার! সীমিত সময়ের জন্য পণ্যের উপর ৯০% পর...
4   ham  নববর্ষের শুভেচ্ছা!! আল্লাহ আপনার সকল কষ্ট দূর ...

In [55]:
ban_spam['type'].value_counts()

spam    1403
ham     1199
Name: type, dtype: int64

In [38]:
non_ban_entries = 0
for i in ban_spam['text']:
    if not contains_unicode_char(i):
        print(i)
        non_ban_entries += 1

non_ban_entries

We have experienced a system problem and are unable to provide some banking services now. Our ATMs are operational. We expect to have our systems up &amp; running shortly. We will keep you updated. We apologise for the inconvenience. Thank you for your patience &amp; understanding.
International online transaction up to $300 is auto-enabled for your BBL Credit Card. Ensure proper endorsement for seamless transaction. To disable dial 16221.
Welcome to BRAC Bank stall at Chattogram Rehab Fair (18-21 Nov &apos;21). Allow us to help you book your dream home with attractive home loan facilities.
Your debit card reward points earned before 7 Jun 2020 will expire on 30 June 2021. Please, redeem your reward points by calling 16221. Details: bit.ly/3yHGSfZ
Dear Customer: BRAC Bank card transactions are cancelled with immediate effect for the listed merchants mentioned in tinyurl.com/BRCO91
Dear Customer: As per the regulatory directive, govt excise duty will be applied to your BRAC Bank account. https://tinyurl.com/bblgth
??? ?????? ???? ????? ???? ?????? ????? ?? ?????+????? ????? ??????+??????+??? ?????????? ?????????? cutt.ly/c600
Akash Standard package(s) activated for your ID 40288583. Your Remaining account balance is BDT 0.00.
Dear Subscriber, you&apos;ve recharged BDT 399.00 to your ID 40288583. Your account balance is now BDT 399.00. Keep enjoying the world-class experience of AKASH.
Akash Standard package(s) deactivated for your ID 40288583. Your Remaining account balance is BDT 0.00. To recharge http://t.ly/srcQ
Your Akash Standard is valid up to 15/02/2022 for ID 40288583. Your remaining account balance is BDT 0.00. For account detail or recharge visit http://t.ly/srcQ
Your OTP is 725378
Pureit
#NAME?
Pureit|

15

In [34]:
rev_india = pd.read_excel("../Dataset/revisedindiandataset.xls", engine='xlrd')
rev_india.head()

   code label                                                msg
0   1.0   ham  Dear Customer, +916300623587 is now available ...
1   1.0   ham  Dear Customer, You have a missed call from +91...
2   1.0  spam  Join Hike to get Rs 40. Earn upto Rs. 10,000 b...
3   1.0  spam  Just sent you some money and invited you to Hi...
4   1.0  spam  Just sent you some money and invited you to Hi...

In [39]:
rev_india['label'].value_counts()

ham     3356
spam    1211
Name: label, dtype: int64

In [40]:
non_ind_entries = 0
for i in rev_india['msg']:
    if not contains_unicode_char(i):
        print(i)
        non_ind_entries += 1

non_ind_entries

Dear Customer, +916300623587 is now available to take calls.
Dear Customer, You have a missed call from +916300623587 The last missed call was at 06:26 PM on 29-Jan-2018 Thankyou, Team Jio.
Join Hike to get Rs 40. Earn upto Rs. 10,000 by inviting your friends - http://go-hike.in/a/GqYeA1m1
Just sent you some money and invited you to Hike. Join now and add to your Wallet for free - http://go-hike.in/a/Vxyucxdm
Just sent you some money and invited you to Hike. Join now and add to your Wallet for free - http://go-hike.in/a/Vxyucxdm
Bayataki vachaka phone cheyandi
Arey Nikhil gadu echina Kotta jars evvi
Dear Customer, +917480032222 is now available to take calls.
Kal Subha sabji jaroor leke ana
Bring vegetables 2mrw mrng while cmng to room
Repu podduna Jogging poye tappudu vegetables ki dabbulu pattukellu
hi
Mama endi ra edi
Just sent you some money and invited you to Hike. Join now and add to your Wallet for free - http://go-hike.in/a/2ZDUm6nR
Just sent you some money and invited you to Hike. Join now and add to your Wallet for free - http://go-hike.in/a/2ZDUm6nR
PNR:4240927205,TRAIN:12791,DOJ:29-01-18,3A,KZJ-DNR,Dep:12:02,
VINAY+1,B3 13,B3 14,
Fare:4380,SC:0.0+PG+INS

Okay cal chey
clg lo una 5 min
Dear Customer, +918074491375 is now available to take calls.
Just invited you to Hike. Join in 24 hours and get Rs. 51 for free in your Wallet. I will get Rs. 51 too. Download Now http://go-hike.in/a/8XRiGCA1
Dear Customer, You have 2 missed calls from +918171535202 The last missed call was at 11:21 AM on 03-Feb-2018 Thankyou, Team Jio.
Dear Customer, +918309108265 is now available to take calls.
Chinna do you drink coffee or tea
Dear Customer, +918309285366 is now available to take calls.
Hehe okie
L
Dear Customer, +918309895880 is now available to take calls.
Dear Customer, +918309895880 is now available to take calls.
Dear Customer, You have a missed call from +918309895880 The last missed call was at 02:48 PM on 13-Dec-2017 Thankyou, Team Jio.
Chinna Jio (+918309108265)
Surender dudyala sir class unda
Class unda
Reply
Reply
Reply
Hy Manu the *odda
Password cheppu ra
Dear Customer, You have a missed call from +918501000927 The last missed call was at 08:12 AM on 02-Jan-2018 Thankyou, Team Jio.
Dear Customer, You have a missed call from +918522810756 The last missed call was at 12:04 PM on 16-Dec-2017 Thankyou, Team Jio.
Call me
WhatsApp Ra ra
WhatsApp ki rara gandimaidan lo guddalu udadesi kodta
Jogging podam
Arey lesinaka Naku missed call evvu
Class ki ravanna
Dear Customer, +918639417540 is now available to take calls.
Dear Customer, +918639417540 is now available to take calls.
Dear Customer, +918639417540 is now available to take calls.
Rey manohar
Dear Customer, +918639417540 is now available to take calls.
Dear Customer, You have 3 missed calls from +918639417540 The last missed call was at 06:14 PM on 30-Oct-2017 Thankyou, Team Jio.
Kindly forword your document on
uniqueemploymentltd@hotmail.com
Document:
1.Photo
2.marksheet
3.ID
4.cv
Reached hostel bye...tc
I'm on my way
Akka nenu Tinku entlo ne unava
PNR:4240927205,TRAIN:12791,DOJ:29-01-18,3A,KZJ-DNR,Dep:12:02,
VINAY+1,B3 13,B3 14,
Fare:4380,SC:0.0+PG+INS

Class EE lo
Enko 10 min lo me plaza mundu unta
Dear Customer, +918919750261 is now available to take calls.
Dear Customer, +918919750261 is now available to take calls.
Dear Customer, +918919750261 is now available to take calls.
Chicken and saman
Dabbulu Lev mere tesukurandi
449 ki 84 days
Repat nunchi 399 ki only 70 days
Recharge chesuko
sare
Malla kanuko Ra tondaraga chey manu
10 min lo
annadu
chesthaa
Reply
Reply
Reply
Me dostu
 Em annadu vya
Dear Customer, +918919750261 is now available to take calls.
naa dagare unnayi
Certificate s
Arey Evadiki echav ra
saree
class ipole
3700+500 anta
 4000 e kadha vyaa
Rent echeyali
Arey 4200 tesukoni ra
Telvad Ra tiyaledhu anukunta
???
chakri gaadu tckt thsndaa
ndhi
Memu class ipoyaka direct velipotham cinepolis
Sare sare
nkaa change kaaledhu kadha raa
naadhi ar215
Dear Customer, +918919967393 is now available to take calls.
Just invited you to Hike and sent you Rs. 51. Join in 24 hours and get more - upto Rs. 1,00,000 for free in your Wallet. Download Now http://go-hike.in/a/_TITlyQw
Just invited you to Hike and sent you Rs. 51. Join in 24 hours and get more - upto Rs. 1,00,000 for free in your Wallet. Download Now http://go-hike.in/a/Kd89r9AT
Dear Customer, +919110561588 is now available to take calls.
Dear Customer, +919110561588 is now available to take calls.
Dear Customer, You have 2 missed calls from +919110561588 The last missed call was at 02:57 PM on 05-Dec-2017 Thankyou, Team Jio.
Dear Customer, +919110561588 is now available to take calls.
Just sent you some money and invited you to Hike. Join now and add to your Wallet for free - http://go-hike.in/a/1j7dTqmO
Call me once done
Just invited you to Hike. Make your first payment and we both get Rs. 51. Download Now http://go-hike.in/a/yYU9DVAz
Just invited you to Hike. Join in 24 hours and get Rs. 51 for free in your Wallet. I will get Rs. 51 too. Download Now http://go-hike.in/a/yYU9DVAz
Arey lift chei Ra nen Akhil
Dear Customer, +919182755860 is now available to take calls.
TRL WHA ICIWC14941B14ED796FA5BCAD07F30D9C44
I'm busy at the moment. Please text me.
Y0U ARE SELECTED T0 GET 4.32 CR0RE FR0M F0RD M0T0RS PR0M0TI0N 2017, T0 RECEIVE SEND Y0UR NAME,AGE,ADDRESS,M0BILE N0 0CCUP,T0: ford.uk7@gmail.com
Just invited you to Hike. Join in 24 hours and get Rs. 51 for free in your Wallet. I will get Rs. 51 too. Download Now http://go-hike.in/a/1IjDjhpy
Attend Free Demo on HADOOP (Big Data), Saturday (04.11.17) @ 10:00 AM & New WEEKEND Batch Starts on HADOOP, Saturday @ 11:30 AM. KELLY TECHNOLOGIES. 9030076789
Attend Free Demo on SPARK & SCALA, Tomorrow (05.11.17) @ 10:00 AM. KELLY TECHNOLOGIES, #101, Swathi Anukar, Beside Aditya Trade Center. 9030076789
Attend Free Demo on SPARK & SCALA, Tomorrow (05.11.17) @ 10:00 AM. KELLY TECHNOLOGIES, #101, Swathi Anukar, Beside Aditya Trade Center. 9030076789
Attend Free Demo on HADOOP (Big Data), Saturday (04.11.17) @ 10:00 AM & New WEEKEND Batch Starts on HADOOP, Saturday @ 11:30 AM. KELLY TECHNOLOGIES. 9030076789
Attend New Weekend Batch Starts on SPARK & SCALA, Tomorrow (23.12.17) @ 10:30 AM. KELLY TECHNOLOGIES, #101, Swathi Anukar, Beside Aditya TradeCenter. 9030076789
Attend New Batch Starts on SPARK & SCALA, Tomorrow (16.11.17) @ 10:00 AM. KELLY TECHNOLOGIES, #101, Swathi Anukar, Beside Aditya Trade Center. 9030076789
Attend Free Demo on SPARK & SCALA, Tomorrow (05.11.17) @ 10:00 AM. KELLY TECHNOLOGIES, #101, Swathi Anukar, Beside Aditya Trade Center. 9030076789
Attend New Batch Starts on SPARK & SCALA, Tomorrow (16.11.17) @ 10:00 AM. KELLY TECHNOLOGIES, #101, Swathi Anukar, Beside Aditya Trade Center. 9030076789
Attend New Weekend Batch Starts on SPARK & SCALA, Tomorrow (23.12.17) @ 10:30 AM. KELLY TECHNOLOGIES, #101, Swathi Anukar, Beside Aditya TradeCenter. 9030076789
1407007
1407028
1407029
1407041
1406035
Cab +918341770211
Arun Dazzling (891 975 0261)
Pirbahore Thane
Opp Subzi Mandi, Ashok Raj Path Rd, Patna, Bihar 800004
I've tagged you as a Bro, Buddy or Bae on Hike. Guess which one, tag me back and get a gift if we match up! - http://hike.in
Just sent you some money and invited you to Hike. Join now and add to your Wallet for free - http://go-hike.in/a/a5kv3I2I
TRL WHA ICIWC14941B14ED796FA5BCAD07F30D9C44
Dear candidate please forward your high qualification document and addres prof id prof and two passport size photo.hr whatsapp -9540210291 ,And mail-hr.airlinerecruiters11@India.com
Wish you and your family a very happy new year 2018.
Naveen, Ramya & Sharan.
K tc
Reached hostel bye..
Going hostel back...bye take care
Hy Bava...I'm Tinku
On my way to home
Dear Customer, your www.flipkart.com "CoD" shipment awb 898414492 is out for delivery by ECOM Executive Ph: 08039514909 PIN: 898414492 Please Keep Rs 10999.0 ready for payment
9963727830 , Rajesham
Order Placed: Your order for Honor 9 Lite (Sapphire... with order ID OD111354431483380000 amounting to Rs.10999 has been received. You can expect delivery by Monday, Feb 05, 2018. We will send you an update when your order is packed/shipped. Manage your order here http://fkrt.it/XNmGZKNNNN
Dear Customer, You have 2 missed calls from +919989905860 The last missed call was at 11:41 AM on 23-Jan-2018 Thankyou, Team Jio.
Dear Customer, You have 2 missed calls from +919989905860 The last missed call was at 08:12 AM on 02-Jan-2018 Thankyou, Team Jio.
10 min daddy
1. Cement: 1362 kg per cubic meters

2. Sand: 1600 kg per cubic meters (dry sand)
2100 kg per cubic meters (wet sand)
Your Google verification code is 898971
Rchrg of MRP Rs 50 on 30/01/18 successful.Tlktime rcvd Rs 39.37,GST Rs 7.63,AccessFee Rs 3,New Bal Rs 39.41.TransID ONR1801300927180224..
Shashank, your friends shared 247 updates this week. Post your own: https://fb.com/l/26SAllz7Beuf8af
Shashank, get back on Facebook by clicking https://fb.com/l/1R4CXY55vxHc4Fl
Shashank, get back on Facebook by clicking https://fb.com/l/2ghytAUPnV7xnYx
WhatsApp code 372-275.

You can also tap on this link to verify your phone: v.whatsapp.com/372275
Shashank, Geethika Gupta shared a photo: https://fb.com/l/1KvfSYMg8PDoQue
Use 156560 as your login code for Saavn. (Account Kit by Facebook)
"Dear Mr/Mrs.SHASHANK: Your Medicine is to be refilled on 03-02-2018. Please call 8736251744  to order medicines and avail our Free home delivery."
Payment for Application ID:G289F34 has been received, Please log in again to see the changes.


GATE 2018 Admin
Your Ola account was logged into from a new device
Login: Ola Cabs android app
Time: 02:57PM, 11 Jan 2018
If you find this suspicious, secure your account by clicking here http://olaca.bs/ZadoOrBWk5
Get around town at Rs 29 for 4km with Ola Auto, your most pocket-friendly ride for short distances! No code required. Auto Ante Ola Auto! Book now: bit.ly/C_SMS
Dear Sai Shashank, Top MNC's are hiring. Complete your profile and apply now. http://msg.mn/hNIs_n/ouo91hI

Team Shine
Gear up for the January Easy '18 now! This event will start at Jan. 1, 2018, 10 p.m. IST. Get on HackerEarth soon. Happy Coding!
Gear up for the December Easy '17 now! This event will start at Dec. 1, 2017, 10 p.m. IST. Get on HackerEarth soon. Happy Coding!
Yashuss Unlimited Business Solutions has sent you an email regarding your internship application. Please check your email (also check spam folder) & reply asap.
Congrats,Ur interview is Fixed For Today(9:30am-5:00Pm) in Paytm Backend/Non Voice/Tech Support/Accounts/Marketing Process,Fixed Sal:13k-28k+Incentives+Meal. Venue:Office No:603,6th Floor,Ganesh Tower,Dada Patil Wadi Road (Thane West Station),Near platform no:1 Call:Simran-9650061432 Ref:KDS
Congrats,Ur interview is Fixed For Today(9:30am-5:00Pm) in Paytm Backend/Non Voice/Tech Support/Accounts/Marketing Process,Fixed Sal:13k-28k+Incentives+Meal. Venue:Office No:603,6th Floor,Ganesh Tower,Dada Patil Wadi Road (Thane West Station),Near platform no:1 Call:Simran-9650061432 Ref:KDS
Thank you for using State Bank Internet Banking. Your Transaction Ref No IGACROJAF2 for Rs.231.51 on 08-Jan-18 20:12
Interview address
YES BANK
Inviting For Interview
Position: Front Desk Executive
Salary: 12500 to 24700
Sanjana: 9867310066/8108546614
Rs 4000 w/d at SBI ATM S1BB014388325 SBI ATM NIT CAMPUS,PATNA fm A/cx3769on07/02/18.Txn#6695.Avl bal Rs20820.3.Download YONO @ www.yonosbi.com
Use SBI ATMs for better security, convenience & faster complaint resolution. As per RBI directive, more than 3 txns in metro & 5 in non-metro are chargeable
Rs 4000 withdrawn from A/c xx 3769 on 29/01/18 at AXS ATM  TPCN1718.Txn# 802911002561 .Avl bal Rs 26224.3.
Thank you for using your SBI Debit Card 559XX4499 for a purchase worth Rs50.0 on POS  PAYTMWAL1210203 at PTM*PAYTM txn# 381854.
Thank you for using your SBI Debit Card 559XX4499 for a purchase worth Rs2200.0 on POS  PAYTMWAL1210203 at PTM*PAYTM txn# 365839.
Thank you for using your SBI Debit Card 559XX4499 for a purchase worth Rs600.0 on POS  PAYTMWAL1210203 at PTM*PAYTM txn# 551503.
Dear Customer, State Bank of India wishes you a Very Happy Birthday and a Great Year ahead!
Thank you for using State Bank Internet Banking. Your Transaction Ref No IGACVBXTR0 for Rs.439.0 on 31-Jan-18 16:58
Thank you for using State Bank Internet Banking. Your Transaction Ref No IGACTUONA4 for Rs.398.0 on 23-Jan-18 11:08
Mobile Number change request for Reference No. EHS009620252 is approved by your branch. Download YONO @ www.yonosbi.com.
Your Mobile Number change (from xxxx to 918919466484) is pending for approval. Download YONO @ www.yonosbi.com.
Welcome to Chhattisgarh BSNL Network. Have a pleasant stay.
Dominos on Train! Order Dominos Pizza for your Lunch/Dinner/Evening Snack at your train Seat/Berth. To order call 1323 or visit www.ecatering.irctc.co.in
PNR:4240927205,TRAIN:12791,DOJ:29-01-18,3A,KZJ-DNR,Dep:12:02,
VINAY+1,B3 13,B3 14,
Fare:4380,SC:0.0+PG+INS

OTP for mobile no verification of user id shshnk158 is 270927
Book tickets now for Varun Tej's THOLI PREMA on Justickets.in and get 25% cashback, only with Paytm wallet. T&C apply.
Book here: https://goo.gl/aJWobh
Book tickets now for Ravi Teja's Touch Chesi Chudu & Chalo on Justickets.in and get 25% cashback with Paytm wallet. T&C apply. Book here: https://goo.gl/gkzNdH
Book tickets now for Bhaagamathie and Padmaavat on Justickets.in and get 25% cashback with Amazon Pay or Paytm Wallet. T&C. Book here: https://goo.gl/aovjfF
Dear Student, Register with us at EasyLrn.com for accessing GATE-18 Online Mocks and Comprehensive Study Material.Mail:info@easylrn.com. +918790885095
MakeMyTrip: 3 Nights Stay @ Price of 2 in Domestic Hotels. Great Service & Awesome Rooms Assured. Book Now @ applinks.makemytrip.com/SMsf/wriW2V0GkF T&Cs apply.
MakeMyTrip: FLAT Rs.3500 OFF on 4 & 5 Star Domestic Hotels. Code STARSALE Book @ applinks.makemytrip.com/SMsf/wriW2V0GkF T&Cs bit.ly/2fSNkwW Valid 21Oct
Congratulations! Get 5 Lakh worth Health Insurance cover that protects your family @ lowest cost and annual health check-up. Know More Sms AB to 5616120.
Rs 150.00 credited to account XXXXX3769 of SBIN linked to saishashank65@okaxis on 2018-01-18. Info: UPI/P2A/801812036276/manohar9600@okicici
Rs 500.00 credited to account XXXXX3769 of SBIN linked to saishashank65@okaxis on 2018-01-15. Info: UPI/P2A/801518912941/krishnachaithanya549@okicici
Rs 600.00 credited to account XXXXX3769 of SBIN linked to saishashank65@okaxis on 2018-01-15. Info: UPI/P2A/801518620743/injamoorirk@okaxis
Rs 200.00 credited to account XXXXX3769 of SBIN linked to saishashank65@okaxis on 2018-01-14. Info: UPI/P2A/801412022410/sairohan2201@okaxis
Rs 150.00 credited to account XXXXX3769 of SBIN linked to saishashank65@okaxis on 2018-01-11. Info: UPI/P2A/801118337983/manohar9600@okicici
Rs 200.00 credited to account XXXXX3769 of SBIN linked to saishashank65@okaxis on 2018-01-04. Info: UPI/P2A/800411501342/malothakhilkumar@okicici
Rs 511.00 credited to account XXXXX3769 of SBIN linked to saishashank65@okaxis on 2018-01-04. Info: UPI/P2A/800408796253/manohar9600@okicici
Rs 150.00 credited to account XXXXX3769 of SBIN linked to saishashank65@okaxis on 2018-01-02. Info: UPI/P2A/800219405858/krishnachaithanya549@okicici
Rs 150.00 credited to account XXXXX3769 of SBIN linked to saishashank65@okaxis on 2018-01-02. Info: UPI/P2A/800219405858/krishnachaithanya549@okicici
Rs 26.00 credited to account XXXXX3769 of SBIN linked to saishashank65@okaxis on 2018-01-02. Info: UPI/P2A/800218821009/goog-payment@okaxis
Rs 51.00 credited to account XXXXX3769 of SBIN linked to saishashank65@okaxis on 2018-01-02. Info: UPI/P2A/800218816078/goog-payment@okaxis
Rs 500.00 credited to account XXXXX3769 of SBIN linked to saishashank65@okaxis on 2018-01-02. Info: UPI/P2A/800218815544/injamoorirk@okaxis
Rs 150.00 credited to account XXXXX3769 of SBIN linked to saishashank65@okaxis on 2018-01-02. Info: UPI/P2A/800218532280/imgauti3@okhdfcbank
Rs 51.00 credited to account XXXXX3769 of SBIN linked to saishashank65@okaxis on 2018-01-02. Info: UPI/P2A/800218799321/goog-payment@okaxis
The all new Domino's has an all new number! Call us on 1860 210 0000 from 11 am to 11 pm for your favourite pizza!
Rs. 200 credited to your Fynd Cash.*Expires in 3 Hours
Total Bal: Rs.200
Use Code: SANTA20 & Get 20% Cashback!
https://go.fyndi.ng/sxf
Rs. 200 credited to your Fynd Cash.*Expires in 3 Hours
Get 15% SUPERCASH on Mobikwik
Shop Now! https://go.fyndi.ng/pfv
Rs.200 credited to your Fynd Cash.*Expires in 3 Hours
Redeem 50% Fynd Referral Cash!
https://go.fyndi.ng/rbn
Rs. 200 credited to your Fynd Cash.*Expires in 3 Hours
Total Bal: Rs. 200
Get 15% SUPERCASH on Mobikwik
https://go.fyndi.ng/bgd
Rs. 200 credited to your Fynd Cash.*Expires in 3 Hours
Min. 50% off on EVERYTHING!
Total Bal: Rs.200
Get 15% SUPERCASH on Mobikwik
https://go.fyndi.ng/nem
Hi,
Rs.200 is credited to your Fynd account (100% redeemable) expires tonight.
Get Extra 15% cashback on MobiKwik.
Start shopping now! https://go.fyndi.ng/jmj
Rs. 300 credited to your Fynd Cash.*Expires in 3 Hours
Get everything for flat Rs. 699!
Get 15% SUPERCASH on Mobikwik
https://go.fyndi.ng/sts
Rs. 200 credited to your Fynd Cash.*Expires in 3 Hours
Get 15% SUPERCASH on Mobikwik
Total Bal: Rs. 400
https://go.fyndi.ng/fnd
Yay! Everything Under 999!
Shop high street brands like Celio, Globus, Cotton World & more!
Use Fynd Cash Bal. Rs.200
https://go.fyndi.ng/sn
Min 50% Off + Add. 10% Cashback on PAYTM!
Shop your favorite tees & tops today!
HURRY! Shop now!
https://go.fyndi.ng/qef
Rs. 200 credited to your Fynd Cash.*Expires in 3 Hours
Total Bal: Rs.400
Use Code:TERRIFICTWO and get 20% Cashback!
https://go.fyndi.ng/acm
You have Rs.200 in your goCash+ Wallet. Download the Goibibo app or Sign Up to Claim your Discount before it expires. https://go.ibi.bo/W1ad/KhRFv37jaI
<#> 1251 is your login OTP. Treat this as confidential. Goibibo will never call you to verify your OTP. aA7YXnBciKU
747168 is your verification code to verify your Mobile# on Paytm. This is important for safety of your account and must be done before you proceed.
Attend Free Demo on HADOOP (Big Data), Tomorrow (17.02.18) @ 10:00 AM. KELLY TECHNOLOGIES, #101, Swathi Anukar, Beside Aditya Trade Center, Ameerpet. 9030076789
Good Afternoon, Dr. J Srinivas MS, MCH(Neurosrg) is visiting Medilife Hospitals on 17.02.2018. For details call 08736 253108,255104,8121081080
Good Evening, Dr. M Praneeth (Gastro) is visiting to Medilife Hospitals on 16.02.2018(Friday). For details call 08736 253108,255104,8121081080
Good Evening, Dr.Sai Satish MD,DM(Neurophy), Dr.Sunil MD,DM(Cardio) are visiting Medilife Hospitals on 14.02.18. For details call 08736 253108,8121081080
Good Evening, Dr. J Srinivas MS, MCH(Neurosrg) is visiting Medilife Hospitals on 10.02.2018. For details call 08736 253108,255104,8121081080
Good Afternoon, Dr.Sai Satish MD,DM(Neurophy), Dr.Sunil MD,DM(Cardio) are visiting Medilife Hospitals on 07.02.18. For details call 08736 253108,8121081080
Good Evening, Dr. J Srinivas MS, MCH(Neurosrg) is visiting Medilife Hospitals on 03.02.2018. For details call 08736 253108,255104,8121081080
Book your Ola cab today!
5% CB on Ola cab rides!
Use code NOVEMOL5 to avail the offer.
Hurry Up!
Ride Now! goo.gl/1Pnhxf
Need an Ola cab today!
5% CB on Ola cab rides!
Use code NOVMOLA5 to avail the offer.
Hurry Up!
Ride Now! goo.gl/bXXuTR
Enter 144129 as your verification code to verify your mobile number. Valid for 5 minutes. Do not share it with anyone.
Hi, Reset your PayUmoney account password: https://pmny.in/KIxLdMlmjuCu . If you did not request this, report us here http://pmny.in/FI6L8HEhtoCj now.
Your payment(Id-170151005) of Rs 479.0 for Abhishek Narwariya is successful. For queries on your payment visit: http://pmny.in/FI6L8HEhtoCj
Please click here to verify your mobile for PayUMoney - https://pmny.in/zIOLwMQmHu6r

4167

In [36]:
kor_smishing = pd.read_csv("../Dataset/KOR_smishing_data_raw/KOR_phishing_data_raw.csv", encoding='utf-8')

kor_smishing.head()

   index                                            content  class
0      1  엄마 나 폰이 망가져서 수리맡기고 컴퓨터 문자나라로 메시지 보내고 있어 엄마 지금 바뻐?      1
1      2  [국외발신]\n[코인원]\n고객님계정이\n해외IP에서\n로그인되였습니다.해외IP차단...      1
2      3  엄마 입금받을수있는\n은행계좌번호\n하나랑 계좌등록\n본인인증땜에\n계좌 4자리\n...      1
3      4  엄마 바빠?나지금\n핸드폰 고장나서 매장에 수리맡기고\n급한대로 예전에\n내명의로 ...      1
4      5  엄마~ 바빠?\n엄마 나 급한 일이 좀 생겨서…\n지금 98만원만 입금해 줄 수 있...      1

In [37]:
non_kor_entries = 0
for i in kor_smishing['content']:
    if not contains_unicode_char(i):
        print(i)
        non_kor_entries += 1

non_kor_entries

[Multi-culture News] The Korea-Turkey Cultural Exchange Program commemorating the 65th anniversary of diplomatic ties will be held on the 8th of January 2022

The Korea-Turkey Cultural Exchange Pro..
#NAME?
seoseo@kookje.co.kr
BCDE
 60??
Happy brithday to you~!

6

In [3]:
kor_smishing['class'].value_counts()

class
0    42594
1      615
Name: count, dtype: int64

In [4]:
def read_file(file_path):
    with open(file_path, 'r') as file:
        content = file.readlines()
    return content

In [5]:
enron_dataset = {'ham':[], 'spam':[]}
for i in range(6):
    directory_ham = "../Dataset/ENRON Spam Dataset/enron"+str(i+1)+"/ham"
    directory_spam = "../Dataset/ENRON Spam Dataset/enron"+str(i+1)+"/spam"

    # Loop through all files in the directory_ham
    for filename in os.listdir(directory_ham):
        # Check if it's a file (not a directory_ham)
        if os.path.isfile(os.path.join(directory_ham, filename)):
            # Open the file and do something with it
            with open(os.path.join(directory_ham, filename), 'r', encoding='utf-8', errors='ignore') as file:
                content = file.read()
                # print(content)
                # print(''.join(content.split('\n')[1:]))
                enron_dataset['ham'].append(''.join(content.split('\n')[1:]))
                # Process the content of the file here
                # print(content)
                # break
    
    # Loop through all files in the directory_spam
    for filename in os.listdir(directory_spam):
        # Check if it's a file (not a directory_spam)
        if os.path.isfile(os.path.join(directory_spam, filename)):
            # Open the file and do something with it
            with open(os.path.join(directory_spam, filename), 'r', encoding='utf-8', errors='ignore') as file:
                content = file.read()
                # print(content)
                # print(''.join(content.split('\n')[1:]))
                enron_dataset['spam'].append(''.join(content.split('\n')[1:]))
                # Process the content of the file here
                # print(content)
                # break

print(len(enron_dataset['ham']))
print(len(enron_dataset['spam']))

16545
17170

In [6]:
enron_dataset['ham']

['',
 'gary , production from the high island larger block a - 1 # 2 commenced onsaturday at 2 : 00 p . m . at about 6 , 500 gross . carlos expects between 9 , 500 and10 , 000 gross for tomorrow . vastar owns 68 % of the gross production .george x 3 - 6992- - - - - - - - - - - - - - - - - - - - - - forwarded by george weissman / hou / ect on 12 / 13 / 99 10 : 16am - - - - - - - - - - - - - - - - - - - - - - - - - - -daren j farmer12 / 10 / 99 10 : 38 amto : carlos j rodriguez / hou / ect @ ectcc : george weissman / hou / ect @ ect , melissa graves / hou / ect @ ectsubject : vastar resources , inc .carlos ,please call linda and get everything set up .i \' m going to estimate 4 , 500 coming up tomorrow , with a 2 , 000 increase eachfollowing day based on my conversations with bill fischer at bmar .d .- - - - - - - - - - - - - - - - - - - - - - forwarded by daren j farmer / hou / ect on 12 / 10 / 99 10 : 34am - - - - - - - - - - - - - - - - - - - - - - - - - - -enron north america corp .from : george weissman 12 / 10 / 99 10 : 00 amto : daren j farmer / hou / ect @ ectcc : gary bryan / hou / ect @ ect , melissa graves / hou / ect @ ectsubject : vastar resources , inc .darren ,the attached appears to be a nomination from vastar resources , inc . for thehigh island larger block a - 1 # 2 ( previously , erroneously referred to as the# 1 well ) . vastar now expects the well to commence production sometimetomorrow . i told linda harris that we \' d get her a telephone number in gascontrol so she can provide notification of the turn - on tomorrow . linda \' snumbers , for the record , are 281 . 584 . 3359 voice and 713 . 312 . 1689 fax .would you please see that someone contacts linda and advises her how tosubmit future nominations via e - mail , fax or voice ? thanks .george x 3 - 6992- - - - - - - - - - - - - - - - - - - - - - forwarded by george weissman / hou / ect on 12 / 10 / 99 09 : 44am - - - - - - - - - - - - - - - - - - - - - - - - - - -" linda harris " on 12 / 10 / 99 09 : 38 : 43 amto : george weissman / hou / ect @ ectcc :subject : hi a - 1 # 2effective 12 - 11 - 99| - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - || | | || mscf / d | min ftp | time || | | || - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - || | | || 4 , 500 | 9 , 925 | 24 hours || | | || - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - || | | || 6 , 000 | 9 , 908 | 24 hours || | | || - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - || | | || 8 , 000 | 9 , 878 | 24 hours || | | || - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - || | | || 10 , 000 | 9 , 840 | 24 hours || | | || - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - || | | || 12 , 000 | 9 , 793 | 24 hours || | | || - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - || | | || 14 , 000 | 9 , 738 | 24 hours || | | || - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - || | | || 16 , 000 | 9 , 674 | 24 hours || | | || - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - || | | || 18 , 000 | 9 , 602 | 24 hours || | | || - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - || | | || 20 , 000 | 9 , 521 | 24 hours || | | || - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - || | | || 22 , 000 | 9 , 431 | 24 hours || | | || - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - || | | || 24 , 000 | 9 , 332 | 24 hours || | | || - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - || | | || 26 , 000 | 9 , 224 | 24 hours || | | || - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - || | | || 28 , 000 | 9 , 108 | 24 hours || | | || - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - || | | || 30 , 000 | 8 , 982 | 24 hours || | | || - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - || | | || 32 , 000 | 8 , 847 | 24 hours || | | || - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - || | | || 34 , 000 | 8 , 703 | 24 hours || | | || - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - || | | || 36 , 000 | 8 , 549 | 24 hours || | | || - - - - - - - - + - - - - - - - - - - + - - - - - - - - - - - |',
 '- calpine daily gas nomination 1 . doc',
 'fyi - see note below - already done .stella- - - - - - - - - - - - - - - - - - - - - - forwarded by stella l morris / hou / ect on 12 / 14 / 99 10 : 18am - - - - - - - - - - - - - - - - - - - - - - - - - - -from : sherlyn schumack on 12 / 14 / 99 10 : 06 amto : stella l morris / hou / ect @ ectcc : howard b camp / hou / ect @ ectsubject : re : issuestella ,this has already been taken care of . you did this for me yesterday .thanks .howard b camp12 / 14 / 99 09 : 10 amto : stella l morris / hou / ect @ ectcc : sherlyn schumack / hou / ect @ ect , howard b camp / hou / ect @ ect , staceyneuweiler / hou / ect @ ect , daren j farmer / hou / ect @ ectsubject : issuestella ,can you work with stacey or daren to resolvehc- - - - - - - - - - - - - - - - - - - - - - forwarded by howard b camp / hou / ect on 12 / 14 / 99 09 : 08am - - - - - - - - - - - - - - - - - - - - - - - - - - -from : sherlyn schumack 12 / 13 / 99 01 : 14 pmto : howard b camp / hou / ect @ ectcc :subject : issuei have to create accounting arrangement for purchase from unocal energy atmeter 986782 . deal not tracked for 5 / 99 . volume on deal 114427 expired 4 / 99 .',
 'fyi .- - - - - - - - - - - - - - - - - - - - - - forwarded by lauri a allen / hou / ect on 12 / 14 / 99 12 : 17pm - - - - - - - - - - - - - - - - - - - - - - - - - - -kimberly vaughn12 / 10 / 99 02 : 54 pmto : lauri a allen / hou / ect @ ectcc : mary m smith / hou / ect @ ectsubject : meter 7268 nov allocationlauri . . i have put this on strangas gas until i can get a contract fromdaren .- - - - - - - - - - - - - - - - - - - - - - forwarded by kimberly vaughn / hou / ect on 12 / 10 / 99 01 : 52pm - - - - - - - - - - - - - - - - - - - - - - - - - - -lauri a allen12 / 09 / 99 01 : 20 pmto : kimberly vaughn / hou / ect @ ect , anita luong / hou / ect @ ectcc : howard b camp / hou / ect @ ect , mary m smith / hou / ect @ ectsubject : meter 7268 nov allocationkim / anita -a volume of 7247 mm shows to have been allocated to the reliant 201 contractfor november . there was no nomination for reliant at this point in novemberand , therefore , there should be no volume allocated to their contract .please make sure these volumes are moved off the reliant contract prior tonovember close .thanks .',
 'jackie ,since the inlet to 3 river plant is shut in on 10 / 19 / 99 ( the last day offlow ) :at what meter is the mcmullen gas being diverted to ?at what meter is hpl buying the residue gas ? ( this is the gas from teco ,vastar , vintage , tejones , and swift )i still see active deals at meter 3405 in path manager for teco , vastar ,vintage , tejones , and swifti also see gas scheduled in pops at meter 3404 and 3405 .please advice . we need to resolve this as soon as possible so settlementcan send out payments .thanks',
 'george ,i need the following done :jan 13zero out 012 - 27049 - 02 - 001 receipt package id 2666allocate flow of 149 to 012 - 64610 - 02 - 055 deliv package id 392jan 26zero out 012 - 27049 - 02 - 001 receipt package id 3011zero out 012 - 64610 - 02 - 055 deliv package id 392these were buybacks that were incorrectly nominated to transport contracts( ect 201 receipt )let me know when this is donehc',
 "fyi- - - - - - - - - - - - - - - - - - - - - - forwarded by gary l payne / hou / ect on 12 / 14 / 99 02 : 35 pm- - - - - - - - - - - - - - - - - - - - - - - - - - -from : antoine v pierre 12 / 14 / 99 02 : 34 pmto : tommy j yanowski / hou / ect @ ect , kathryn bussell / hou / ect @ ect , gary lpayne / hou / ect @ ect , diane e niestrath / hou / ect @ ect , romeo d ' souza / hou / ect @ ect ,michael eiben / hou / ect @ ect , clem cernosek / hou / ect @ ect , scottygilbert / hou / ect @ ect , dave nommensen / hou / ect @ ect , david rohan / hou / ect @ ect ,kevin heal / cal / ect @ ect , richard pinion / hou / ect @ ectcc : mary g gosnell / hou / ect @ ect , jason moore / hou / ect @ ect , samuelschott / hou / ect @ ect , bernice rodriguez / hou / ect @ ectsubject : duns number changesi will be making these changes at 11 : 00 am on wednesday december 15 .if you do not agree or have a problem with the dnb number change pleasenotify me , otherwise i will make the change as scheduled .dunns number change :counterparty cp id numberfrom tocinergy resources inc . 62163 869279893 928976257energy dynamics management , inc . 69545 825854664 088889774south jersey resources group llc 52109 789118270 036474336transalta energy marketing ( us ) inc . 62413 252050406 255326837philadelphia gas works 33282 148415904 146907159thanks ,rennie3 - 7578",
 'there are two fields of gas that i am having difficulty with in the unifysystem .1 . cage ranch - since there is no processing agreement that accomodates thisgas on king ranch , it is my understanding hpl is selling the liquids andking ranch is re - delivering to stratton . it is also my understanding thatthere is a . 05 cent feeto deliver this gas . we need a method to accomodate the volume flow on hplat meter 415 and 9643 . this gaswill not be reflected on trans . usage ticket # 123395 and # 95394 since it isnot being nominated from a processing agreement . we either , need to inputa point nom ( on hpl or krgp ) at these meters to match the nom at meter 9610 ,or a deal for purchase and sale ( if king ranch is taking title to the gas )needs to be input into sitara at these meters with the appropriate rate . ihave currently input a point nom on krgp to accomodate this flow , so we candivert some of this gas to the current interstate sales that are being made .2 . forest oil - there is a processing agreement that will accomodate flowfrom the meter ( 6396 ) into king ranch . it is myunderstanding that this agreement was originally setup until texaco hadtheir own processing agreement . i need confirmation that the gas from thismeter should be nominated on contract # ( 96006681 ) and that this agreementshould have been reassigned to hplc . ( it is currently still under hplr ) .if this gas is not nominated on the above transport agreement , then onceagain we need to accomodate the flow volume on the hpl pipe with either apoint nom or a sitara deal at meters 415 and 9643 .',
 'thanks so much for the memo . i would like to reiterate my support on two keyissues :1 ) . thu - best of luck on this new assignment . howard has worked hard anddone a great job ! please don \' t be shy on asking questions . entex iscritical to the texas business , and it is critical to our team that we aretimely and accurate .2 ) . rita : thanks for setting up the account team . communication iscritical to our success , and i encourage you all to keep each other informedat all times . the p & l impact to our business can be significant .additionally , this is high profile , so we want to assure top quality .thanks to all of you for all of your efforts . let me know if there isanything i can do to help provide any additional support .rita wynne12 / 14 / 99 02 : 38 : 45 pmto : janet h wallis / hou / ect @ ect , ami chokshi / corp / enron @ enron , howard bcamp / hou / ect @ ect , thu nguyen / hou / ect @ ect , kyle r lilly / hou / ect @ ect , staceyneuweiler / hou / ect @ ect , george grant / hou / ect @ ect , julie meyers / hou / ect @ ectcc : daren j farmer / hou / ect @ ect , kathryn cordes / hou / ect @ ect , ritawynne / hou / ect , lisa csikos / hou / ect @ ect , brenda f herod / hou / ect @ ect , pamelachambers / corp / enron @ enronsubject : entex transistionthe purpose of the email is to recap the kickoff meeting held on yesterdaywith members from commercial and volume managment concernig the entex account :effective january 2000 , thu nguyen ( x 37159 ) in the volume managment group ,will take over the responsibility of allocating the entex contracts . howardand thu began some training this month and will continue to transition theaccount over the next few months . entex will be thu \' s primary accountespecially during these first few months as she learns the allocationsprocess and the contracts .howard will continue with his lead responsibilites within the group and beavailable for questions or as a backup , if necessary ( thanks howard for allyour hard work on the account this year ! ) .in the initial phases of this transistion , i would like to organize an entex" account " team . the team ( members from front office to back office ) wouldmeet at some point in the month to discuss any issues relating to thescheduling , allocations , settlements , contracts , deals , etc . this hopefullywill give each of you a chance to not only identify and resolve issues beforethe finalization process , but to learn from each other relative to yourrespective areas and allow the newcomers to get up to speed on the account aswell . i would encourage everyone to attend these meetings initially as ibelieve this is a critical part to the success of the entex account .i will have my assistant to coordinate the initial meeting for early 1 / 2000 .if anyone has any questions or concerns , please feel free to call me or stopby . thanks in advance for everyone \' s cooperation . . . . . . . . . . .julie - please add thu to the confirmations distributions list',
 'the purpose of the email is to recap the kickoff meeting held on yesterdaywith members from commercial and volume managment concernig the entex account :effective january 2000 , thu nguyen ( x 37159 ) in the volume managment group ,will take over the responsibility of allocating the entex contracts . howardand thu began some training this month and will continue to transition theaccount over the next few months . entex will be thu \' s primary accountespecially during these first few months as she learns the allocationsprocess and the contracts .howard will continue with his lead responsibilites within the group and beavailable for questions or as a backup , if necessary ( thanks howard for allyour hard work on the account this year ! ) .in the initial phases of this transistion , i would like to organize an entex" account " team . the team ( members from front office to back office ) wouldmeet at some point in the month to discuss any issues relating to thescheduling , allocations , settlements , contracts , deals , etc . this hopefullywill give each of you a chance to not only identify and resolve issues beforethe finalization process , but to learn from each other relative to yourrespective areas and allow the newcomers to get up to speed on the account aswell . i would encourage everyone to attend these meetings initially as ibelieve this is a critical part to the success of the entex account .i will have my assistant to coordinate the initial meeting for early 1 / 2000 .if anyone has any questions or concerns , please feel free to call me or stopby . thanks in advance for everyone \' s cooperation . . . . . . . . . . .julie - please add thu to the confirmations distributions list',
 'fyi- - - - - - - - - - - - - - - - - - - - - - forwarded by susan d trevino / hou / ect on 12 / 15 / 99 08 : 40am - - - - - - - - - - - - - - - - - - - - - - - - - - -bob withers on 12 / 14 / 99 05 : 11 : 06 pmto : susan d trevino / hou / ect @ ectcc : stretch brennan , kevin mclarney ," taylor vance ( e - mail ) "subject : lst rev dec . 1999 josey ranch nomsusan : as we discussed , this change was missed but was discussed with youlast week . i apologize for the omission . i am checking with my fieldpersonnel and anticipate a further reduction ( due to well productiondecreases ) effective 12 / 15 which i will send under a separate email for an" intra - day " change wednesday .here \' s revised december 1999 ( effective 12 / 9 / 99 ) setup forjosey : ( using 1 . 081 btu / mcf )* gas deliveries into hpl12 , 300 mmbtu / d for kri ( net reduction of1 , 000 mmbtu / d )12 , 300 mmbtu / d into hplbob withers > <kcs energy , 5555 san felipe , suite 1200houston , tx 77056voice mail / page 713 - 964 - 9434',
 '- - - - - - - - - - - - - - - - - - - - - - forwarded by susan d trevino / hou / ect on 12 / 15 / 99 08 : 41am - - - - - - - - - - - - - - - - - - - - - - - - - - -bob withers on 12 / 15 / 99 08 : 28 : 08 amto : susan d trevino / hou / ect @ ectcc : stretch brennan , kevin mclarney ," \' taylor vance ( e - mail ) \' "subject : 2 nd rev dec . 1999 josey ranch nomhere \' s revised december 1999 ( effective 12 / 15 / 99 ) setup forjosey : ( using 1 . 081 btu / mcf )* gas deliveries into hpl9 , 300 mmbtu / d for kri ( net reduction of3 , 000 mmbtu / d )9 , 300 mmbtu / d into hplbob withers > <kcs energy , 5555 san felipe , suite 1200houston , tx 77056voice mail / page 713 - 964 - 9434',
 'the following is the close schedule for this coming month ( year - end . ) pleasekeep in the mind the following key times . . . .unify to sitara bridge back 1 : 45 p . m . thursday , dec 30 th ( all errors must beclear by this time )mass draft at 6 p . m . thursday evening , dec 30 th .accrual process begins friday morning , dec 31 st at 6 : 30 a . m . ( if your groupimpacts the accrual , please ensure that the necessary people are availablefor support if needed , as this is an enron holiday . )please feel free to contact me should you have any questions .thank you , melissa x 35615',
 'aimee ,sitara deal 92943 for meter 1431 has expired on oct 31 , 1999 . settlementsis unable to draft an invoice for this deal . this deal either needs to beextended or a new deal needs to be set up . please let me know when this isresolved . we need it resolved by friday , dec 17 .hc',
 'daren -could you please resolve this issue for howard ? i will be out of the officethe next two days .when this is done , please let george know . thanks .aimee- - - - - - - - - - - - - - - - - - - - - - forwarded by aimee lannou / hou / ect on 12 / 15 / 99 01 : 27 pm- - - - - - - - - - - - - - - - - - - - - - - - - - -howard b camp12 / 15 / 99 01 : 01 pmto : aimee lannou / hou / ect @ ectcc : daren j farmer / hou / ect @ ect , stacey neuweiler / hou / ect @ ect , mary msmith / hou / ect @ ectsubject : meter 1431 - nov 1999aimee ,sitara deal 92943 for meter 1431 has expired on oct 31 , 1999 . settlementsis unable to draft an invoice for this deal . this deal either needs to beextended or a new deal needs to be set up . please let me know when this isresolved . we need it resolved by friday , dec 17 .hc',
 'name home pagergeorge grant 281 - 282 - 9084 713 - 764 - 5128charlotte hawkins 281 - 655 - 0952 713 - 506 - 4006aimee lannou 713 - 594 - 6562 713 - 698 - 7722robert lloyd 281 - 847 - 2808 713 - 698 - 5446stella morris 281 - 448 - 9067 713 - 200 - 8376susan trevino 713 - 688 - 6186 713 - 200 - 8368kim vaughn 281 - 586 - 0910 713 - 761 - 8153jackie young 713 - 528 - 4562 713 - 990 - 6400carlos rodriguez 281 - 344 - 0991 713 - 761 - 2722mandy allen 281 - 970 - 6561 713 - 990 - 8332',
 'my latest understanding is the buyback will be in place through 12 / 31 / 99 .a new deal for 15 , 000 / day begins 1 / 1 / 00 and currently has no buybackprovision .kenhoward b camp12 / 16 / 99 12 : 27 pmto : gary w lamphier / hou / ect @ ectcc : kenneth seaman / hou / ect @ ect , kristen j hanson / hou / ect @ ect , tinavaladez / hou / ect @ ect , howard b camp / hou / ect @ ectsubject : lyondell citgogary ,i have been notified that there is a possibility that the buyback was noteffective for lyondell citgo . could you please inform me via cc mail whatthe status of the buyback is once you have reviewed it .hc',

In [7]:
british_dataset = read_file("../Dataset/british_english_sms_corpus.txt")
# for i in british_dataset:
#     print(i)
# british_dataset.index('SMS Ham\n')
# british_dataset.index('SMS Spam\n')
british_ham = [i[:-1] for i in british_dataset[17:480] if i!='\n']
british_spam = [i[:-1] for i in british_dataset[482:] if i!='\n']

In [8]:
british_ham

['Oi when you gonna ring',
 'Oh yes, why is it like torture watching england?',
 "Yes but can we meet in town cos will go to gep and then home. You could text at bus stop. And don't worry we'll have finished by march … ish!",
 'what I meant to say is cant wait to see u again getting bored of this bridgwater banter',
 'V nice! Off 2 sheffield tom 2 air my opinions on categories 2 b used 2 measure ethnicity in next census. Busy transcribing. :-)',
 'See you there! ',
 'Thanks  and ! Or bomb and date as my phone wanted to say! ',
 'hanks lotsly!',
 "I shall book chez jules for half eight, if that's ok with you?",
 "I wonder if you'll get this text?",
 'Oh unintentionally not bad timing. Great. Fingers  the trains play along! Will give fifteen min warning.',
 'Er yep sure. Props?',
 'I have a rather prominent bite mark on my right cheek',
 'Yeah confirmed for you staying at  that weekend',
 'would u fuckin believe it they didnt know i had thurs pre booked off so they re cancelled me AGAIN! that needs to b sacked',
 'No! But we found a diff farm shop to buy some cheese. On way back now, can i call in?',
 "I take it we didn't have the phone callon Friday. Can we assume we won't have it this year now?",
 'Good good, billy mates all gone. Just been jogging, again! Did enjoy concert?',
 "Aah! A cuddle would be lush! I'd need lots of tea and soup before any kind of fumbling!",
 "Hiya , have u been paying money into my account? If so, thanks. Got a pleasant surprise when i checked my balance -u c, i don't get statements 4 that acc",
 'Hows the champ just leaving glasgow!',
 "You'll never believe this but i have actually got off at taunton. Wow",
 ':-( sad puppy noise',
 'Big brother‘s really scraped the barrel with this shower of social misfits',
 "Night sweet, sleep well! I've just been to see The Exorcism of Emily Rose and may never sleep again! Hugs and snogs! ",
 'What time. I‘m out until prob 3 or so',
 'Yeah whatever lol',
 'Kinda. First one gets in at twelve! Aah. Speak tomo',
 'here is my new address -apples&pairs&all that malarky',
 'I had a good time too. Its nice to do something a bit different with my weekends for a change. See ya soon',
 ', ow u dey.i paid 60,400thousad.i told  u would call . ',
 "Not yet. Just i'd like to keep in touch and it will be the easiest way to do that from barcelona. By the way how ru and how is the house?",
 'Yes obviously, but you are the eggs-pert and the potato head… Speak soon! ',
 'Does cinema plus drink appeal tomo? * Is a fr thriller by director i like on at mac at 8.30.',
 'Okay but i thought you were the expert',
 ':) ',
 'Yeah work is fine, started last week, all the same stuff as before, dull but easy and guys are fun!',
 'Well done, blimey, exercise, yeah, i kinda remember wot that is, hmm. ',
 'I just cooked a rather nice salmon a la you',
 "Very strange.  and  are watching the 2nd one now but i'm in bed. Sweet dreams, miss u ",
 'All sounds good. Fingers . Makes it difficult to type',
 'Just hopeing that wasn‘t too pissed up to remember and has gone off to his sisters or something!',
 "Can you let me know details of fri when u find out cos I'm not in tom or fri. mentionned chinese. Thanks",
 'Sorry . I will be able to get to you. See you in the morning.',
 'Okey dokey swashbuckling stuff what oh.',
 'Only just got this message, not ignoring you. Yes, i was. Shopping that is',
 'Well am officially in a philosophical hole, so if u wanna call am at home ready to be saved!',
 ', ,  and  picking them up from various points | going 2 yeovil | and they will do the motor project 4 3 hours | and then u take them home. || 12 2 5.30 max. || Very easy',
 "Forgot you were working today! Wanna chat, but things are ok so drop me a text when you're free / bored etc and i'll ring. Hope all is well, nose essay and all xx",
 'Are we doing the norm tomorrow? I finish just a 4.15 cos of st tests. Need to sort library stuff out at some point tomo - got letter from today - access til end march so i better get move on!',
 'Hi. Hope ur day * good! Back from walk, table booked for half eight. Let me know when ur coming over.',
 'Erm. I thought the contract ran out the4th of october.',
 'Not thought bout it... || Drink in tap & spile at seven. || Is that pub on gas st off broad st by canal. || Ok?',
 'Hello- thanx for taking that call. I got a job! Starts on monday!',
 "Have you heard about that job? I'm going to that wildlife talk again tonight if u want2come. Its that2worzels and a wizzle or whatever it is?! ",
 'Yeah go on then, bored and depressed sittin waitin for phone to ring... Hope the wind drops though, scary',
 'Camera quite good, 10.1mega pixels, 3optical and 5digital dooms. Have a lovely holiday, be safe and i hope you hav a good journey! Happy new year to you both! See you in a couple of weeks! ',
 "Hmm ok, i'll stay for like an hour cos my eye is really sore!",
 '… and don‘t worry we‘ll have finished by march … ish!',
 'Not getting anywhere with this damn job hunting over here!',
 "Hi , where are you? We're at  and they're not keen to go out i kind of am but feel i shouldn't so can we go out tomo, don't mind do you?",
 "It is a good thing I'm now getting the connection to bw",
 "see you then, we're all christmassy here!",
 'I though we shd go out n have some fun so bar in town or something – sound ok?',
 'Hi. Wk been ok - on hols now! Yes on for a bit of a run. Forgot that i have hairdressers appointment at four so need to get home n shower beforehand. Does that cause prob for u?"',
 ', im .. On the snowboarding trip. I was wondering if your planning to get everyone together befor we go..a meet and greet kind of affair? Cheers, ',
 'Perhaps * is much easy give your account identification, so i will tomorrow at UNI',
 'Nationwide auto centre (or something like that) on Newport road. I liked them there',
 'Just got part Nottingham - 3 hrs 63miles. Good thing i love my man so much, but only doing 40mph. Hey ho',
 'Dont flatter yourself... Tell that man of mine two pints of carlin in ten minutes please.... ',
 "My friend, she's studying at warwick, we've planned to go shopping and to concert tmw, but it may be canceled, havn't seen  for ages, yeah we should get together sometime!",
 'Men like shorter ladies. Gaze up into his eyes.',
 'Easy mate, * guess the quick drink was bit ambitious.',
 'I av a new number,  . Wil u only use this one,ta.',
 'And maybe some pressies',
 'Er, hello, things didn‘t quite go to plan – is limping slowly home followed by aa and with exhaust hanging off',
 'Hi its in durban are you still on this number',
 "Ooh, 4got, i'm gonna start belly dancing in moseley weds 6.30 if u want 2 join me, they have a cafe too. ",
 'happened here while you were adventuring',
 'if you text on your way to cup stop that should work. And that should be BUS',
 '* You gonna ring this weekend or wot?',
 'Can you use foreign stamps for whatever you send them off for? ',
 'What time you coming down later? ',
 'Maybe i could get book out tomo then return it immediately ..? Or something.',
 "Have you seen who's back at Holby?!",
 "I jus hope its true that  missin me cos i'm really missin him! You haven't done anything to feel guilty about, yet.",
 'Have you heard from this week?',
 'Please give it 2  or i will pick it up on Tuesday evening about 8 if that is ok.',
 "Thanks honey but still haven't heard anything I will leave it a bit longer so not 2 crowd him and will try later - great advice thanks hope cardiff is still there!",
 'Am not working but am up to eyes in philosophy so will text u later when a bit more free for chat...',
 'Got it. Seventeen pounds for seven hundred ml – hope ok.',
 'PS U no ur a grown up now right?',
 'twenty past five he said will this train have been to durham already or not coz i am in a reserved seat',
 'I got another job! The one at the hospital doing data analysis or something, starts on monday! Not sure when my thesis will got finished',
 'Que pases un buen tiempo or something like that',
 "I'll text now! All creepy like so he won't think that we forgot",
 'Hey! Congrats 2u2. id luv 2 but ive had 2 go home!',
 'I‘ll have a look at the frying pan in case it‘s cheap or a book perhaps. No that‘s silly a frying pan isn‘t likely to be a book',
 'say thanks2. ',
 'I have 2 sleeping bags, 1 blanket and paper and  phone details. Anything else?',
 'swhrt how u dey,hope ur ok, tot about u 2day.love n miss.take care.',
 'It wont b until 2.15 as trying 2 sort house out, is that ok?',
 'I have had two more letters from . I will copy them for you cos one has a message for you. Speak soon',
 "Yes watching footie but worried we're going to blow it - Phil Neville?",
 'We made it! Eta at taunton is 12:30 as planned, hope that‘s still okday?! Good to see you! :-xx',
 'Tee hee. Off to lecture, cheery bye bye.',
 'Can not use foreign stamps in this country. Good lecture .',
 "Hi hope u r both ok, he said he would text and he hasn't, have u seen him, let me down gently please ",
 'I think your mentor is , but not 100 percent sure.',
 "Erm … ill pick you up at about 6.45pm. That'll give enough time to get there, park and that.",
 'Hm good morning, headache anyone? :-)',
 'Pick you up bout 7.30ish? What time are  and that going?',
 'Have you bookedthe hut? And also your time off? How are you by the way?',
 'Bognor it is! Should be splendid at this time of year.',
 'Hi, wlcome back, did wonder if you got eaten by a lion or something, nothing much',
 "This pen thing is beyond a joke. Wont a Biro do? Don't do a masters as can't do this ever again! ",
 'Double eviction this week - Spiral and Michael and good riddance to them!',
 'They can try! They can get lost, in fact. Tee hee',
 "I'm really sorry i won't b able 2 do this friday.hope u can find an alternative.hope yr term's going ok:-)",
 'Urgh, coach hot, smells of chip fat! Thanks again, especially for the duvet (not a predictive text word).',
 'You all ready for * big day tomorrow?',
 "I don't quite know what to do. I still can't get hold of anyone. I cud pick you up bout 7.30pm and we can see if they're in the pub?",
 'Have you been practising your curtsey?',
 'meet you in corporation st outside gap … you can see how my mind is working!',
 'By the way, make sure u get train to worc foregate street not shrub hill. Have fun night x',
 'Yes. Last  practice',
 'Yes i thought so. Thanks.',
 "Unfortunately i've just found out that we have to pick my sister up from the airport that evening so don't think i'll be going out at all. We should try to go out one of th",
 "I like to think there's always the possibility of being in a pub later.",
 "hows my favourite person today? r u workin hard? couldn't sleep again last nite nearly rang u at 4.30",
 'It‘s £6 to get in, is that ok?',
 "What do u reckon as need 2 arrange transport if u can't do it, thanks",
 'Hi did u decide wot 2 get 4 his bday if not ill prob jus get him a voucher frm virgin or sumfing ',
 " gonna let me know cos comes bak from holiday that day.  is coming. Don't4get2text me  number. ",
 "Lol! Nah wasn't too bad thanks. Its good to b home but its been quite a reality check. Hows ur day been? Did u do anything with website?",
 'Cheers for the card ... Is it that time of year already?',
 "Neither [in sterm voice] - i'm studying. All fine with me! Not sure the  thing will be resolved, tho. Anyway. Have a fab hols",
 'Indeed and by the way it was either or - not both !',
 "That's a shame! Maybe cld meet for few hrs tomo?",
 'Oops. 4 got that bit.',
 ':-) :-)',
 'Shall I bring us a bottle of wine to keep us amused? Only joking! I‘ll bring one anyway',
 'Nope thats fine. I might have a nap tho! ',
 'Okay. No no, just shining on. That was meant to be signing, but that sounds better.',
 'Hey mr  and I are going to the sea view and having a couple of gays I mean games! Give me a bell when ya finish ',
 'Is that on the telly? No its Brdget Jones!',
 'I am back. Good journey! Let me know if you need any of the receipts. Shall i tell you like the pendent?',
 "* Am on a train back from northampton so i'm afraid not!",
 "Come round, it's . ",
 'Sorry im getting up now, feel really bad- totally rejected that kinda me thing.',
 '* Will be september by then!',
 'Back in brum! Thanks for putting us up and keeping us all and happy. See you soon ',
 'All done? All handed in? Celebrations in full swing yet?',
 'Was the farm open?',
 'Printer is cool. I mean groovy. Wine is groovying',
 '... Are you in the pub?',
 "No i'm not gonna be able to. || too late notice. || i'll be home in a few weeks anyway. || what are the plans",
 'Are you driving or training?',
 '[…] anyway, many good evenings to u! s',
 "Yeah he got in at 2 and was v apologetic. n had fallen out and she was actin like spoilt child and he got caught up in that. Till 2! But we won't go there! Not doing too badly cheers. You? ",
 'Did he say how fantastic I am by any chance, or anything need a bigger life lift as losing the will 2 live, do you think I would be the first person 2 die from N V Q? ',
 " said kiss, kiss, i can't do the sound effects! He is a gorgeous man isn't he! Kind of person who needs a smile to brighten his day! ",
 'Hello! How r u? Im bored. Inever thought id get bored with the tv but I am. Tell me something exciting has happened there? Anything! =/',
 'Roger that. We‘re probably going to rem in about 20',
 'Hello! Just got here, st andrews-boy its a long way! Its cold. I will keep you posted',
 'Okey dokey, i‘ll be over in a bit just sorting some stuff out.',
 'Have you emigrated or something? Ok maybe 5.30 was a bit hopeful...',
 'Am watching house – very entertaining – am getting the whole hugh laurie thing – even with the stick – indeed especially with the stick.',
 'No. Yes please. Been swimming?',
 'Message from . I am at Truro Hospital on ext. You can phone me here. as I have a phone by my side',
 "Man this bus is so so so slow. I think you're gonna get there before me",
 "All was well until slightly disastrous class this pm with my fav darlings! Hope day off ok. Coffee wld be good as can't stay late tomorrow. Same time + place as always?",
 'yay! finally lol. i missed our cinema trip last week :-(',
 " says that he's quitting at least5times a day so i wudn't take much notice of that. Nah, she didn't mind. Are you gonna see him again? Do you want to come to taunton tonight? U can tell me all about !",
 "I'll pick you up at about 5.15pm to go to taunton if you still want to come.",
 "Hello! How's you and how did saturday go? I was just texting to see if you'd decided to do anything tomo. Not that i'm trying to invite myself or anything!",
 'Yes, my reg is  Ciao!',
 'And you! Will expect you whenever you text! Hope all goes well tomo ',
 "Boo. How's things? I'm back at home and a little bored already :-(",
 'Hey there! Glad u r better now. I hear u treated urself to a digi cam, is it good? We r off at 9pm. Have a fab new year, c u in coupla wks!',
 'Hello. They are going to the village pub at 8 so either come here or there accordingly. Ok?',
 "Sorry, left phone upstairs. OK, might be hectic but would be all my birds with one fell swoop. It's a date.",
 'Been running but only managed 5 minutes and then needed oxygen! Might have to resort to the roller option!',
 'Hey cutie. How goes it? Here in WALES its kinda ok. There is like hills and shit but i still avent killed myself. ',
 'Now thats going to ruin your thesis!',
 'I‘m going to try for 2 months ha ha only joking',
 '1.20 that call cost. Which i guess isnt bad. Miss ya, need ya, want ya, love ya',
 "Well I wasn't available as I washob nobbing with last night so they had to ask Nickey Platt instead of me!;",
 "Dont give a monkeys wot they think and i certainly don't mind. Any friend of mine&all that! Just don't sleep wiv , that wud be annoyin!",
 'Did you show him and wot did he say or could u not c him 4 dust?',
 "My sort code is  and acc no is . The bank is natwest. Can you reply to confirm i've sent this to the right person!",
 'Jordan got voted out last nite!',
 "Oh right, ok. I'll make sure that i do loads of work during the day!  got a really nasty cough today and is dry n shot so that should really help it!",
 "Wow didn't think it was that common. I take it all back ur not a freak! Unless u chop it off:-)",
 'Spoons it is then okay?',
 'Yes fine ',
 'I‘m parked next to a MINI!!!! When are you coming in today do you think?',
 'Ok. Not much to do here though. H&M Friday, cant wait. Dunno wot the hell im gonna do for another 3 weeks! Become a slob- oh wait, already done that! ',
 "I've been barred from all B and Q stores for life!?This twat in orange dungerees came up to me and asked if I wanted decking? So I got the first punch in!!",
 'Miss ya, need ya, want ya, love ya.',
 'Hello. Sort of out in town already. That . So dont rush home, I am eating nachos. Will let you know eta.',
 'Ok cool. See ya then.',
 'R u in this continent?',
 "* Thought I didn't see you.",
 "Yeah right! I'll bring my tape measure fri!",
 "What i mean was i left too early to check, cos i'm working a 9-6.",
 'Ok. Not sure what time tho as not sure if can get to library before class. Will try. See you at some point! Have good eve.',
 'Kind of. Took it to garage. Centre part of exhaust needs replacing. Part ordered n taking it to be fixed tomo morning.',
 'Hmm, too many of them unfortunately... Pics obviously arent hot cakes. Its kinda fun tho',
 'The whole car appreciated the last two! Dad and are having a map reading semi argument but apart from that things are going ok. P.',
 'Shit that is really shocking and scary, cant imagine for a second. Def up for night out. Do u think there is somewhere i could crash for night, save on taxi?',
 "I'm gonna say no. Sorry. I would but as normal am starting to panic about time. Sorry again! Are you seeing on Tuesday?",
 'on hen night. Going with a swing',
 'Bloody hell, cant believe you forgot my surname Mr . Ill give u a clue, its spanish and begins with m... ',
 'Ok but knackered. Just came home and went to sleep! Not good at this full time work lark.',
 "Err... Cud do. I'm going to  at 8pm. I haven't got a way to contact him until then.",
 'Not tonight mate. Catching up on some sleep. This is my new number by the way. ',
 '4 oclock at mine. Just to bash out a flat plan.',
 "Hasn't that been the pattern recently crap weekends?",
 'Hello.How u doing?What u been up 2?When will u b moving out of the flat, cos I will need to arrange to pick up the lamp, etc. Take care. Hello caroline!',
 'Well. You know what i mean. Texting',
 'I think just yourself …Thanks and see you tomo',
 'have * good weekend.',
 'For fear of fainting with the of all that housework you just did? Quick have a cuppa',
 'Oh yes I can speak txt 2 u no! Hmm. Did u get  email?',
 'Cant think of anyone with * spare room off * top of my head',
 'Ok thats cool. Its , just off either raglan rd or edward rd. Behind the cricket ground. Gimme ring when ur closeby see you tuesday.',
 'Just re read it and I have no shame but tell me how he takes it and if he runs I will blame u 4 ever!! Not really 4 ever just a long time ',
 'have got * few things to do. may be in * pub later.',
 "Annoying isn't it.",
 'Velly good, yes please!',
 "Hello, yeah i've just got out of the bath and need to do my hair so i'll come up when i'm done, yeah?",
 "Well good morning mr . Hows london treatin' ya treacle?",
 'HIYA STU WOT U UP 2.IM IN SO MUCH TRUBLE AT HOME AT MOMENT EVONE HATES ME EVEN U! WOT THE HELL AV I DONE NOW? Y WONT U JUST TELL ME TEXT BCK PLEASE LUV DAN ',
 'Lol! Oops sorry! Have fun. ',
 'Lol! U drunkard! Just doing my hair at d moment. Yeah still up 4 tonight. Wats the plan? ',
 'Well, I was about to give up cos they all said no they didn‘t do one nighters. I persevered and found one but it is very cheap so i apologise in advance. It is just somewhere to sleep isnt it?',
 'whatever, im pretty pissed off.',

In [9]:
british_spam

['Hi 07734396839 IBH Customer Loyalty Offer: The NEW NOKIA6600 Mobile from ONLY £10 at TXTAUCTION!Txt word:START to No:81151 & get Yours Now!4T&',
 "I don't know u and u don't know me. Send CHAT to 86688 now and let's find each other! Only 150p/Msg rcvd. HG/Suite342/2Lands/Row/W1J6HL LDN. 18 years or over.",
 'goldviking (29/M) is inviting you to be his friend. Reply YES-762 or NO-762 See him: www.SMS.ac/u/goldviking STOP? Send STOP FRND to 62468',
 "Twinks, bears, scallies, skins and jocks are calling now. Don't miss the weekend's fun. Call 08712466669 at 10p/min. 2 stop texts call 08712460324(nat rate)",
 'Santa calling! Would your little ones like a call from Santa Xmas Eve? Call 09077818151 to book you time. Calls1.50ppm last 3mins 30s T&C www.santacalling.com',
 'Married local women looking for discreet action now! 5 real matches instantly to your phone. Text MATCH to 69969 Msg cost 150p 2 stop txt stop BCMSFWC1N3XX',
 'You have 1 new message. Please call 08712400200.',
 'URGENT!! Your 4* Costa Del Sol Holiday or £5000 await collection. Call 09050090044 Now toClaim. SAE, TC s, POBox334, Stockport, SK38xh, Cost£1.50/pm, Max10mins',
 'U 447801259231 have a secret admirer who is looking 2 make contact with U-find out who they R*reveal who thinks UR so special-call on 09058094597',
 'Text82228>> Get more ringtones, logos and games from www.txt82228.com. Questions: info@txt82228.co.uk',
 'Had your mobile 10 mths? Update to the latest Camera/Video phones for FREE. KEEP UR SAME NUMBER, Get extra free mins/texts. Text YES for a call',
 'Sexy Singles are waiting for you! Text your AGE followed by your GENDER as wither M or F E.G.23F. For gay men text your AGE followed by a G. e.g.23G.',
 'U were outbid by simonwatson5120 on the Shinco DVD Plyr. 2 bid again, visit sms. ac/smsrewards 2 end bid notifications, reply END OUT',
 'This is the 2nd time we have tried 2 contact u. U have won the 750 Pound prize. 2 claim is easy, call 08712101358 NOW! Only 10p per min. BT-national-rate',
 'SMSSERVICES. for yourinclusive text credits, pls goto www.comuk.net login= 3qxj9 unsubscribe with STOP, no extra charge. help 08702840625.COMUK. 220-CM2 9AE',
 'HOT LIVE FANTASIES call now 08707509020 Just 20p per min NTT Ltd, PO Box 1327 Croydon CR9 5WB 0870 is a national rate call',
 "1000's flirting NOW! Txt GIRL or BLOKE & ur NAME & AGE, eg GIRL ZOE 18 to 8007 to join and get chatting!",
 'PRIVATE! Your 2003 Account Statement for shows 800 un-redeemed S. I. M. points. Call 08715203652 Identifier Code: 42810 Expires 29/10/0',
 'U have won a nokia 6230 plus a free digital camera. This is what u get when u win our FREE auction. To take part send NOKIA to 83383 now. POBOX114/14TCR/W1 16',
 'Guess what! Somebody you know secretly fancies you! Wanna find out who it is? Give us a call on 09065394514 From Landline DATEBox1282EssexCM61XN 150p/min 18',
 'Free video camera phones with Half Price line rental for 12 mths and 500 cross ntwk mins 100 txts. Call MobileUpd8 08001950382 or Call2OptOut/674&',
 "Orange customer, you may now claim your FREE CAMERA PHONE upgrade for your loyalty. Call now on 0207 153 9996. Offer ends 14thMarch. T&C's apply. Opt-out availa",
 'Free msg. Sorry, a service you ordered from 81303 could not be delivered as you do not have sufficient credit. Please top up to receive the service.',
 'Want the latest Video handset? 750 anytime any network mins? Half price line rental? Reply or call 08000930705 for delivery tomorrow',
 'SPJanuary Male Sale! Hot Gay chat now cheaper, call 08709222922. National rate from 1.5p/min cheap to 7.8p/min peak! To stop texts call 08712460324 (10p/min)',
 'TBS/PERSOLVO. been chasing us since Sept for£38 definitely not paying now thanks to your information. We will ignore them. Kath. Manchester.',
 'Welcome to Select, an O2 service with added benefits. You can now call our specially trained advisors FREE from your mobile by dialling 402.',
 'Am new 2 club & dont fink we met yet Will B gr8 2 C U Please leave msg 2day wiv ur area 09099726553 reply promised CARLIE x Calls£1/minMobsmore LKPOBOX177HP51FL',
 'Gr8 Poly tones 4 ALL mobs direct 2u rply with POLY TITLE to 8007 eg POLY BREATHE1 Titles: CRAZYIN, SLEEPINGWITH, FINEST, YMCA :getzed.co.uk POBox365O4W45WQ 300p',
 'Romantic Paris. 2 nights, 2 flights from £79 Book now 4 next year. Call 08704439680Ts&Cs apply.',
 "For ur chance to win a £250 wkly shopping spree TXT: SHOP to 80878. T's&C's www.txt-2-shop.com custcare 08715705022, 1x150p/wk",
 'Monthly password for wap. mobsi.com is 391784. Use your wap phone not PC.',
 'FreeMsg: Claim ur 250 SMS messages-Text OK to 84025 now!Use web2mobile 2 ur mates etc. Join Txt250.com for 1.50p/wk. T&C BOX139, LA32WU. 16 . Remove txtX or stop',
 'Hi if ur lookin 4 saucy daytime fun wiv busty married woman Am free all next week Chat now 2 sort time 09099726429 JANINExx Calls£1/minMobsmoreLKPOBOX177HP51FL',
 'URGENT! Your Mobile No 07808726822 was awarded a £2,000 Bonus Caller Prize on 02/09/03! This is our 2nd attempt to contact YOU! Call 0871-872-9758 BOX95QU',
 'Get 3 Lions England tone, reply lionm 4 mono or lionp 4 poly. 4 more go 2 www.ringtones.co.uk, the original n best. Tones 3GBP network operator rates apply.',
 'Someone has contacted our dating service and entered your phone because they fancy you! To find out who it is call from a landline 09111032124 . PoBox12n146tf150p',
 'RECPT 1/3. You have ordered a Ringtone. Your order is being processed...',
 "Do you ever notice that when you're driving, anyone going slower than you is an idiot and everyone driving faster than you is a maniac?",
 "FREE NOKIA Or Motorola with upto 12mths 1/2price linerental, 500 FREE x-net mins&100txt/mth FREE B'tooth*. Call Mobileupd8 on 08001950382 or call 2optout/D3WV",
 "Want 2 get laid tonight? Want real Dogging locations sent direct 2 ur Mob? Join the UK's largest Dogging Network by txting MOAN to 69888Nyt. ec2a. 31p.msg@150p",
 'Do you want 750 anytime any network mins 150 text and a NEW VIDEO phone for only five pounds per week call 08002888812 or reply for delivery tomorrow',
 'FreeMsg:Feelin kinda lnly hope u like 2 keep me company! Jst got a cam moby wanna c my pic?Txt or reply DATE to 82242 Msg150p 2rcv Hlp 08712317606 stop to 82242',
 'Xmas Offer! Latest Motorola, SonyEricsson & Nokia & FREE Bluetooth or DVD! Double Mins & 1000 Txt on Orange. Call MobileUpd8 on 08000839402 or call2optout/4QF2',
 'Spook up your mob with a Halloween collection of a logo & pic message plus a free eerie tone, txt CARD SPOOK to 8007 zed 08701417012150p per logo/pic',
 'You are guaranteed the latest Nokia Phone, a 40GB iPod MP3 player or a £500 prize! Txt word: COLLECT to No: 83355! IBHltd LdnW15H 150p/Mtmsgrcvd18',
 'As a Registered Subscriber yr draw 4 a £100 gift voucher will b entered on receipt of a correct ans. When are the next olympics. Txt ans to 80062',
 '* FREE* POLYPHONIC RINGTONE Text SUPER to 87131 to get your FREE POLY TONE of the week now! 16 SN PoBox202 NR31 7ZS subscription 450pw',
 'What do U want for Xmas? How about 100 free text messages & a new video phone with half price line rental? Call free now on 0800 0721072 to find out more!',
 'Customer service announcement. We recently tried to make a delivery to you but were unable to do so, please call 07099833605 to re-schedule. Ref:9280114',
 '<Forwarded from 21870000>Hi - this is your Mailbox Messaging SMS alert. You have 4 messages. You have 21 matches. Please call back on 09056242159 to retrieve your messages and matches',
 'Our dating service has been asked 2 contact U by someone shy! CALL 09058091870 NOW all will be revealed. POBox84, M26 3UZ 150p',
 'Hottest pics straight to your phone!! See me getting Wet and Wanting, just for you xx Text PICS to 89555 now! txt costs 150p textoperator g696ga 18 XxX',
 'FreeMsg: Txt: CALL to No: 86888 & claim your reward of 3 hours talk time to use from your phone now! Subscribe6GBP/mnth inc 3hrs 16 stop?txtStop',
 'U are subscribed to the best Mobile Content Service in the UK for £3 per 10 days until you send STOP to 82324. Helpline 08706091795',
 'This weeks SavaMob member offers are now accessible. Just call 08709501522 for details! SavaMob, POBOX 139, LA3 2WU. Only £1.50/week. SavaMob - offers mobile!',
 "Xmas & New Years Eve tickets are now on sale from the club, during the day from 10am till 8pm, and on Thurs, Fri & Sat night this week. They're selling fast!",
 'PRIVATE! Your 2003 Account Statement for 07815296484 shows 800 un-redeemed S.I.M. points. Call 08718738001 Identifier Code 41782 Expires 18/11/04 ',
 'FREE RINGTONE text FIRST to 87131 for a poly or text GET to 87131 for a true tone! Help? 0845 2814032 16 after 1st free, tones are 3x£150pw to e£nd txt stop',
 'FREE entry into our £250 weekly comp just send the word ENTER to 84128 NOW. 18 T&C www.textcomp.com cust care 08712405020.',
 'FREE camera phones with linerental from 4.49/month with 750 cross ntwk mins. 1/2 price txt bundle deals also avble. Call 08001950382 or call2optout/J MF',
 "More people are dogging in your area now. Call 09090204448 and join like minded guys. Why not arrange 1 yourself. There's 1 this evening. A£1.50 minAPN LS278BB",
 'Hi babe its Jordan, how r u? Im home from abroad and lonely, text me back if u wanna chat xxSP visionsms.com Text stop to stopCost 150p 08712400603',
 'Want explicit SEX in 30 secs? Ring 02073162414 now! Costs 20p/min Gsex POBOX 2667 WC1N 3XX',
 'SMS SERVICES. for your inclusive text credits, pls goto www.comuk.net login= 3qxj9 unsubscribe with STOP, no extra charge. help 08702840625.COMUK. 220-CM2 9AE',
 'Bears Pic Nick, and Tom, Pete and ... Dick. In fact, all types try gay chat with photo upload call 08718730666 (10p/min). 2 stop texts call 08712460324',
 '3 FREE TAROT TEXTS! Find out about your love life now! TRY 3 FOR FREE! Text CHANCE to 85555 16 only! After 3 Free, Msgs £1.50 each',
 'Your next amazing xxx PICSFREE1 video will be sent to you enjoy! If one vid is not enough for 2day text back the keyword PICSFREE1 to get the next video.',
 'Hi this is Amy, we will be sending you a free phone number in a couple of days, which will give you an access to all the adult parties...',
 'Not heard from U4 a while. Call me now am here all night with just my knickers on. Make me beg for it like U did last time 01223585236 XX Luv Nikiyu4.net',
 'Reply to win £100 weekly! Where will the 2006 FIFA World Cup be held? Send STOP to 87239 to end service',
 'Auction round 4. The highest bid is now £54. Next maximum bid is £71. To bid, send BIDS e. g. 10 (to bid £10) to 83383. Good luck.',
 '-PLS STOP bootydelious (32/F) is inviting you to be her friend. Reply YES-434 or NO-434 See her: www.SMS.ac/u/bootydelious STOP? Send STOP FRND to 62468',
 'Hi babe its Chloe, how r u? I was smashed on saturday night, it was great! How was your weekend? U been missing me? SP visionsms.com Text stop to stop 150p/text',
 'SMS. ac Blind Date 4U!: Rodds1 is 21/m from Aberdeen, United Kingdom. Check Him out http://img. sms. ac/W/icmb3cktz8r7!-4 no Blind Dates send HIDE',
 'Thanks for your subscription to Ringtone UK your mobile will be charged £5/month Please confirm by replying YES or NO. If you reply NO you will not be charged',
 "FreeMsg Today's the day if you are ready! I'm horny & live in your town. I love sex fun & games! Netcollex Ltd 08700621170150p per msg reply Stop to end",
 'You can stop further club tones by replying "STOP MIX" See my-tone.com/enjoy. html for terms. Club tones cost GBP4.50/week. MFL, PO Box 1146 MK45 2WT (2/3)',
 "FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv",
 'Summers finally here! Fancy a chat or flirt with sexy singles in yr area? To get MATCHED up just reply SUMMER now. Free 2 Join. OptOut txt STOP Help08714742804',
 'PRIVATE! Your 2003 Account Statement for <fone no> shows 800 un-redeemed S. I. M. points. Call 08715203656 Identifier Code: 42049 Expires 26/10/04',
 '<Forwarded from 21870000>Hi - this is your Mailbox Messaging SMS alert. You have 40 matches. Please call back on 09056242159 to retrieve your messages and matches cc100p/min',
 'Double mins and txts 4 6months FREE Bluetooth on Orange. Available on Sony, Nokia Motorola phones. Call MobileUpd8 on 08000839402 or call2optout/N9DX',
 'Ur cash-balance is currently 500 pounds - to maximize ur cash-in now send GO to 86688 only 150p/msg. CC: 08718720201 PO BOX 114/14 TCR/W1',
 'U have a Secret Admirer who is looking 2 make contact with U-find out who they R*reveal who thinks UR so special-call on 09065171142-stopsms-08',
 "You've won tkts to the EURO2004 CUP FINAL or £800 CASH, to collect CALL 09058099801 b4190604, POBOX 7876150ppm",
 'Hey I am really horny want to chat or see me naked text hot to 69698 text charged at 150pm to unsubscribe text stop 69698',
 'This message is free. Welcome to the new & improved Sex & Dogging club! To unsubscribe from this service reply STOP. msgs@150p 18 only',
 'Do you want a new Video handset? 750 any time any network mins? UNLIMITED TEXT? Camcorder? Reply or Call now 08000930705 for del Sat AM',
 'For taking part in our mobile survey yesterday! You can now have 500 texts 2 use however you wish. 2 get txts just send TXT to 80160 T&C www.txt43.com 1.50p',
 'Do you want 750 anytime any network mins 150 text and a NEW video phone for only five pounds per week call 08000776320 now or reply for delivery Tomorrow',
 'You have WON a guaranteed £1000 cash or a £2000 prize. To claim yr prize call our customer service representative on 08714712394 between 10am-7pm',
 'Dear Voucher Holder, To claim this weeks offer, at you PC please go to http://www.e-tlp.co.uk/expressoffer Ts&Cs apply. To stop texts, txt STOP to 80062',
 'Hi its LUCY Hubby at meetins all day Fri & I will B alone at hotel U fancy cumin over? Pls leave msg 2day 09099726395 Lucy x Calls£1/minMobsmoreLKPOBOX177HP51FL',
 'Loans for any purpose even if you have Bad Credit! Tenants Welcome. Call NoWorriesLoans.com on 08717111821',
 'Natalie (20/F) is inviting you to be her friend. Reply YES-165 or NO-165 See her: www.SMS.ac/u/natalie2k9 STOP? Send STOP FRND to 62468',
 'Dont forget you can place as many FREE Requests with 1stchoice.co.uk as you wish. For more Information call 08707808226.',
 'Ringtone Club: Gr8 new polys direct to your mobile every week !',
 "Do you realize that in about 40 years, we'll have thousands of old ladies running around with tattoos?",
 'Do you want a new Video phone? 600 anytime any network mins 400 Inclusive Video calls AND downloads 5 per week Free delTOMORROW call 08002888812 or reply NOW',
 'Someone U know has asked our dating service 2 contact you! Cant Guess who? CALL 09058091854 NOW all will be revealed. PO BOX385 M6 6WU',
 '**FREE MESSAGE**Thanks for using the Auction Subscription Service. 18 . 150p/MSGRCVD 2 Skip an Auction txt OUT. 2 Unsubscribe txt STOP CustomerCare 08718726270',
 'Congrats! 2 mobile 3G Videophones R yours. call 09061744553 now! videochat wid ur mates, play java games, Dload polyH music, noline rentl. bx420. ip4. 5we. 150pm',
 'Do you want a NEW video phone750 anytime any network mins 150 text for only five pounds per week call 08000776320 now or reply for delivery tomorrow',
 'Email AlertFrom: Jeri StewartSize: 2KBSubject: Low-cost prescripiton drvgsTo listen to email call 123',
 'Gr8 new service - live sex video chat on your mob - see the sexiest dirtiest girls live on ur phone - 4 details text horny to 89070 to cancel send STOP to 89070',
 "U've been selected to stay in 1 of 250 top British hotels - FOR NOTHING! Holiday valued at £350! Dial 08712300220 to claim - National Rate Call. Bx526, SW73SS",
 'Want to funk up ur fone with a weekly new tone reply TONES2U 2 this text. www.ringtones.co.uk, the original n best. Tones 3GBP network operator rates apply',
 'Ever thought about living a good life with a perfect partner? Just txt back NAME and AGE to join the mobile community. (100p/SMS)',
 'Congrats! 1 year special cinema pass for 2 is yours. call 09061209465 now! C Suprman V, Matrix3, StarWars3, etc all 4 FREE! bx420-ip4-5we. 150pm. Dont miss out!',
 'We tried to contact you re our offer of New Video Phone 750 anytime any network mins HALF PRICE Rental camcorder call 08000930705 or reply for delivery Wed',
 'Call 09094100151 to use ur mins! Calls cast 10p/min (mob vary). Service provided by AOM, just GBP5/month. AOM Box61,M60 1ER until u stop. Ages 18+ only!',
 'URGENT! Your Mobile number has been awarded with a £2000 Bonus Caller Prize. Call 09058095201 from land line. Valid 12hrs only',
 "You will be receiving this week's Triple Echo ringtone shortly. Enjoy it!",
 'Fantasy Football is back on your TV. Go to Sky Gamestar on Sky Active and play £250k Dream Team. Scoring starts on Saturday, so register now!SKY OPT OUT to 88088',
 'FREE entry into our £250 weekly competition just text the word WIN to 80086 NOW. 18 T&C www.txttowin.co.uk',
 'SMS. ac sun0819 posts HELLO:"You seem cool, wanted to say hi. HI!!!" Stop? Send STOP to 62468',
 'Boltblue tones for 150p Reply POLY# or MONO# eg POLY3 1. Cha Cha Slide 2. Yeah 3. Slow Jamz 6. Toxic 8. Come With Me or STOP 4 more tones txt MORE',
 'How about getting in touch with folks waiting for company? Just txt back your NAME and AGE to opt in! Enjoy the community (150p/SMS)',
 'Valentines Day Special! Win over £1000 in our quiz and take your partner on the trip of a lifetime! Send GO to 83600 now. 150p/msg rcvd. CustCare:08718720201.',
 'Got what it takes 2 take part in the WRC Rally in Oz? U can with Lucozade Energy! Text RALLY LE to 61200 (25p), see packs or lucozade.co.uk/wrc & itcould be u!',
 'PRIVATE! Your 2004 Account Statement for 07742676969 shows 786 unredeemed Bonus Points. To claim call 08719180248 Identifier Code: 45239 Expires',
 'Ringtone Club: Get the UK singles chart on your mobile each week and choose any top quality ringtone! This message is free of charge.',
 'Hi, the SEXYCHAT girls are waiting for you to text them. Text now for a great night chatting. send STOP to stop this service',
 'Urgent! Please call 09061213237 from landline. £5000 cash or a luxury 4* Canary Islands Holiday await collection. T&Cs SAE PO Box 177. M227XY. 150ppm. 16+',
 'We have new local dates in your area - Lots of new people registered in YOUR AREA. Reply DATE to start now! 18 only www.flirtparty.us REPLYS150',
 "'RCT' THNQ Adrian for U text. Rgds Vatian",
 'You are being ripped off! Get your mobile content from www.clubmoby.com call 08717509990 poly/true/Pix/Ringtones/Games six downloads for only 3',
 '4mths half price Orange line rental & latest camera phones 4 FREE. Had your phone 11mths ? Call MobilesDirect free on 08000938767 to update now! or2stoptxt',
 "Bored of speed dating? Try SPEEDCHAT, txt SPEEDCHAT to 80155, if you don't like em txt SWAP and get a new chatter! Chat80155 POBox36504W45WQ 150p/msg rcd 16",
 'Do you want a new video handset? 750 anytime any network mins? Half Price Line Rental? Camcorder? Reply or call 08000930705 for delivery tomorrow',
 'CLAIRE here am havin borin time & am now alone U wanna cum over 2nite? Chat now 09099725823 hope 2 C U Luv CLAIRE xx Calls£1/minmoremobsEMSPOBox45PO139WA',
 'FREE for 1st week! No1 Nokia tone 4 ur mob every week just txt NOKIA to 87077 Get txting and tell ur mates. zed POBox 36504 W45WQ norm150p/tone 16+',
 'URGENT! We are trying to contact U. Todays draw shows that you have won a £2000 prize GUARANTEED. Call 09058094507 from land line. Claim 3030. Valid 12hrs only',
 'Sunshine Hols. To claim ur med holiday send a stamped self address envelope to Drinks on Us UK, PO Box 113, Bray, Wicklow, Eire. Quiz Starts Saturday! Unsub Stop',
 'Shop till u Drop, IS IT YOU, either 10K, 5K, £500 Cash or £100 Travel voucher, Call now, 09064011000. NTT PO Box CR01327BT fixedline Cost 150ppm mobile vary',

In [10]:
print(len(british_ham))
print(len(british_spam))

450
425

In [11]:
with open('../Dataset/Singapore_smsCorpus_en_2015.03.09_all.json', 'r') as file:
        singapore_dataset = json.load(file)

In [ ]:
singapore_dataset_all_mesages = []
for i in singapore_dataset['smsCorpus']['message']:
    # print(type(i['text']['$']))
    singapore_dataset_all_mesages.append(i['text']['$'])

In [13]:
singapore_dataset_all_mesages

['Bugis oso near wat...',
 'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...',
 'I dunno until when... Lets go learn pilates...',
 'Den only weekdays got special price... Haiz... Cant eat liao... Cut nails oso muz wait until i finish drivin wat, lunch still muz eat wat...',
 'Meet after lunch la...',
 'm walking in citylink now ü faster come down... Me very hungry...',
 '5 nights...We nt staying at port step liao...Too ex',
 'Hey pple...$700 or $900 for 5 nights...Excellent location wif breakfast hamper!!!',
 'Yun ah.the ubi one say if ü wan call by tomorrow.call 67441233 look for irene.ere only got bus8,22,65,61,66,382. Ubi cres,ubi tech park.6ph for 1st 5wkg days.èn',
 'Hey tmr maybe can meet you at yck',
 'Oh...i asked for fun. Haha...take care. ü',
 'We are supposed to meet to discuss abt our trip... Thought xuhui told you? In the afternoon. Thought we can go for lesson after that',
 't finish my film yet...',
 'm having dinner with my cousin...',
 'Oh... Kay... On sat right?',
 'I need... Coz i never go before',
 's a basic yoga course... at bugis... We can go for that... Pilates intro next sat.... Tell me what time you r free',
 'I am going to sao mu today. Will be done only at 12',
 'Hey gals...U all wanna meet 4 dinner at nìte?',
 'Jos ask if u wana meet up?',
 'Haiyoh... Maybe your hamster was jealous of million',
 'is your hamster dead? Hey so tmr i meet you at 1pm orchard mrt?',
 've booked the pilates and yoga lesson already... Haha',
 'Yup... I havent been there before... You want to go for the yoga? I can call up to book',
 'K... Must book a not huh? so going for yoga basic on sunday?',
 'Hey so this sat are we going for the intro pilates only? Or the kickboxing too?',
 'Sat right? Okay thanks...',
 'Yup... From what i remb... I think should be can book...',
 'm going to get specs. My membership is PX3748',
 'We can go 4 e normal pilates after our intro...',
 'Sun ah... Thk mayb can if dun have anythin on... Thk have to book e lesson... E pilates is at orchard mrt u noe hor...',
 'Thk shld b can... Ya, i wana go 4 lessons... Haha, can go for one whole stretch...',
 'Sounds gd... Haha... Can... Wah, u yan jiu so fast liao...',
 'Wah... Okie okie... Muz make use of e unlimited... Haha...',
 'll go yan jiu den msg u...',
 'K.. I yan jiu liao... Sat we can go 4 bugis vill one frm 10 to 3 den hop to parco 4 nb. Sun can go cine frm 1030 to 2, den hop to orc mrt 4 hip hop at 4...',
 'll go yan jiu too... We can skip ard oso, go cine den go mrt one, blah blah blah...',
 'Nope... Juz off from work...',
 'Oh oh... Wasted... Den muz chiong on sat n sun liao...',
 'Haha... Sounds crazy, dunno can tahan anot...',
 'Hmmm.. Thk sure got time to hop ard... Ya, can go 4 free abt... Muz call u to discuss liao...',
 'Oh... I was thkin of goin yogasana at 10 den no nd to go at 3 den can rush to parco 4 nb... Okie lor, u call me when ready...',
 'After my work ah... Den 6 plus lor... U workin oso rite... Den go orchard lor, no other place to go liao...',
 'Aiyo... U always c our ex one... I dunno abt mei, she haven reply... First time u reply so fast... Y so lucky not workin huh, got bao by ur sugardad ah...gee..',
 's ex wat... No ah, waitin 4 u to treat, somebody shld b rich liao...So gd, den u dun have to work frm tmr onwards...',
 'Oh oh... Den muz change plan liao... Go back have to yan jiu again...',
 's nt much lesson to go if we attend kb on sat...',
 'Den wat will e schedule b lk on sun?',
 'Eh den sat u book e kb liao huh...',
 'Yup... Hey then one day on fri we can ask miwa and jiayin take leave go karaoke',
 'Yup... Ok i go home look at the timings then i msg ü again... Xuhui going to learn on 2nd may too but her lesson is at 8am',
 'Hey i booked the kb on sat already... what other lessons are we going for ah? Keep your sat night free we need to meet and confirm our lodging',
 'Hey... are you going to quit soon? Xuhui and i working till end of the month',
 's a kb lesson tonight',
 'Hey so whats the plan this sat?',
 've woken up...',
 'Hey i will be late ah... Meet you at 945+',
 'Hey tmr meet at bugis 930 ?',
 'Ha... Then we must walk to everywhere... Cannot take tram. My cousin said can walk to vic market from our hotel',
 'Haha... Yup hopefully  we will lose a few kg by mon. after hip hop can go orchard and weigh again',
 've booked the 2 lessons on sun liao...',
 'Hmmm... Guess we can go 4 kb n power yoga... Haha, dunno we can tahan power yoga anot... Thk got lo oso, forgot liao...',
 'Oh... Okie lor...We go on sat...',
 'Oh... Haha... Den we shld had went today too... Gee, nvm la... Kaiez, i dun mind goin jazz oso... Scared hiphop open cant catch up...',
 'll quit yet... Hmmm, can go jazz ? Yogasana oso can... We can go meet em after our lessons den...',
 'm still sleepin, haha... Okie, u go home liao den confirm w me lor...',
 'm nt goin, got somethin on, unless they meetin 4 dinner lor... Haha, i wonder who will go tis time...',
 'm eatin too much n puttin on weight...Haha... So anythin special happened?',
 'Thk some of em find wtc too far... Weiyi not goin... E rest i dunno yet... R ur goin 4 dinner den i might b able to join...',
 'm eatin now lor, but goin back to work soon... E mountain deer show huh... I watch b4 liao, very nice...',
 'Goin to workout lor... Muz lose e fats...',
 've oredi booked slots 4 my weekends liao...',
 'I noe la... U wana pei bf oso rite... K lor, other days den...',
 'U meet other fren dun wan meet me ah... Muz b a guy rite...',
 'Oh... Icic... K lor, den meet other day...',
 'Haha... Where got so fast lose weight, thk muz go 4 a month den got effect... Gee,later we go aust put bk e weight.',
 'U attend ur driving lesson how many times a wk n which day?',
 'Ay wana meet on sat?ü wkg on sat?',
 'Shopping? Eh ger i toking abt syd leh...Haha',
 's é only $140 ard...É rest all ard $180 at least...Which is é price 4 é 2 bedrm ($900)',
 'Hmm...Bad news...Hype park plaza $700 studio taken...Only left 2 bedrm-$900...',
 'Okay... I booked all already... Including the one at bugis.',
 'Yun ah.now ü wkg where?btw if ü go nus sc. Ü wana specialise in wad?',
 'Hey you still want to go for yogasana? Coz if we end at cine then can go bathe and hav the steam bath',
 'Hey we can go jazz power yoga hip hop kb and yogasana',
 'Can meh? Thgt some will clash... Really ah, i dun mind... I dun seen to have lost any weight... Gee...',
 'Oh... Lk tt den we take e one tt ends at cine lor... Dun wan yogasana oso can...',
 'Wa... U so efficient... Gee... Thanx...',
 'Hmmm.... Mayb can try e shoppin area one, but forgot e name of hotel...',
 's e best choice den we juz have to take it...',
 'I only work from mon to thurs but Sat i cant leh... Booked liao... Which other day u free?',
 'Until 545 lor... Ya, can go 4 dinner together...',
 'Mon okie lor... Haha, best is cheap n gd food la, ex oso okie... Depends on whether wana eat western or chinese food... Den which u prefer...',
 'Chinatown got porridge, claypot rice, yam cake, fishhead beehoon... Either we eat cheap den go cafe n tok or go nydc or somethin...',
 's shop ?',
 'My fri ah... Okie lor,goin 4 my drivin den go shoppin after tt...',
 'Hey...Great deal...Farm tour 9am to 5pm $95/pax, $50 deposit by 16 May',
 'haha but no money leh... Later got to go for tuition... Haha and looking for empty slots for driving lessons',
 'My tuition is at 330. Hm we go for the 1120 to 1205 one? Do you mind?',
 'Hey... What time is your driving on fri? We go for evaluation on fri?',
 'm going to be late leh.',
 'Hey are we going for the lo lesson or gym?',
 'Okay... We wait ah',
 'Hey come online! Use msn... We are all there',
 'Oh yah... We never cancel leh... Haha',
 'K. Did you call me just now ah?',
 'Okay lor... Wah... like that def they wont let us go... Haha... What did they say in the terms and conditions?',
 'Okay lor... Will they still let us go a not ah? Coz they will not know until later. We drop our cards into the box right?',
 'You want to go?',
 'Kay... Since we are out already',
 'Haha okay... Today weekend leh...',
 'Haha... They cant what... At the most tmr forfeit... haha so how?',
 'Hey... Why dont we just go watch x men and have lunch... Haha',
 'Haha... Really oh no... How? Then will they deduct your lesson tmr?',
 'm only reaching tp mrt',
 'm goin to be late',
 'Ya! when are ü taking ure practical lessons? I start in june..',
 'Hey... Very inconvenient for your sis a not huh?',
 'm at amk. Need to drink tea or coffee',
 'Hey you gave them your photo when you registered for driving ah? Tmr wanna meet at yck?',
 's on 21 may. Coz thought wanna go out with jiayin. But she isnt free',
 'Haha... dont be angry with yourself... Take it as a practice for the real thing. =)',
 'Haha... Hope ü can hear the receipt sound... Gd luck!',
 'Huh? 6 also cannot? Then only how many mistakes?',
 'Nope... Think i will go for it on monday... Sorry i replied so late',
 'Hey.. Something came up last min.. Think i wun be signing up tmr.. Hee',
 'I am thinking of going down to reg for pract lessons.. Flung my advance.. Haha wat time u going?',
 'Hey gals.. Anyone of u going down to e driving centre tmr?',
 'Ok no prob',
 'Nope i waiting in sch 4 daddy...',
 'Dunno lei he neva say...',
 'Ü called dad oredi...',
 'Me hungry buy some food good lei... But mum n yun dun wan juz buy a little bit...',
 'Dad went out oredi...',
 'Ü still attending da talks?',
 'Then she buying today? Ü no need to c meh...',
 'm free...',
 'Nope... C ü then...',
 'Is fujitsu s series lifebook good?',
 'Is toshiba portege m100 gd?',
 'Yun buying... But school got offer 2000 plus only...',
 'Got fujitsu, ibm, hp, toshiba... Got a lot of model how to say...',
 'Okie... Thanx...',
 'How come i din c ü... Yup i cut my hair...',
 'No wonder... Cos i dun rem seeing a silver car... But i thk i saw a black one...',
 's naughty... Ü so free today? Can go jogging...',
 'Ok... C ya...',
 'm not drivin... I neva develop da photos lei...',
 'I wan but too early lei... Me outside now wun b home so early... Neva mind then...',
 645,
 'Ü dun need to pick ur gf?',
 'Okie...',
 'm at home n ready...',
 'Ok...',
 'Dunno lei... I thk mum lazy to go out... I neva ask her yet...',
 'Mum say we wan to go then go... Then she can shun bian watch da glass exhibition...',
 'Dun need to use dial up juz open da browser n surf...',
 'When did i use soc... I use it only at home... Ü dunno how 2 type it in word ar...',
 'Can a not?',
 'Juz go google n search 4 qet...',
 's hostel?',
 'Ok...',
 'Huh means computational science... Y they like dat one push here n there...',
 'I not at home now lei...',
 'Eatin my lunch...',
 'Ü takin linear algebra today?',
 'Ü bot notes oredi... Cos i juz rem i got...',
 'Wah lucky man... Then can save money... Hee...',
 'Y so late but i need to go n get da laptop...',
 'Where to get those?',
 'Then cant get da laptop? My matric card wif ü lei...',
 'I dunno they close oredi not... Ü v ma fan...',
 'Hi dis is yijue i would be happy to work wif ü all for gek1510...',
 'Ü comin to fetch us oredi...',
 'Got smaller capacity one? Quite ex...',
 'Ok thanx...',
 'Wat ü doing now?',
 'Got meh... When?',
 'm not at home in da aft wat...',
 'Mum ask ü to buy food home...',
 'Leave it wif me lar... Ü wan to carry meh so heavy... Is da num 98321561 familiar to ü?',
 's my group mate... Lucky i havent reply... Wat time do ü need to leave...',
 'm askin if ü leaving earlier or wat mah cos mayb ü haf to walk v far...',
 'Yup...',
 'm stuck in da middle of da row on da right hand side of da lt...',
 'Black shirt n blue jeans... I thk i c ü...',
 'Not directly behind... Abt 4 rows behind ü...',
 'Ü go home liao? Ask dad to pick me up at 6...',
 'm done oredi...',
 'I wait 4 ü inside da car park...',
 'Yup... How ü noe leh...',
 'Oic... I saw him too but i tot he din c me... I found a group liao...',
 'Aiyo a bit pai seh ü noe... Scared he dun rem who i am then die... Hee... But he become better lookin oredi leh...',
 'How i noe... Did ü specify da domain as nusstu... Ü still in sch...',
 'When ü login dat time... Dad fetching ü home now?',
 'I come n pick ü up... Come out immediately aft ur lesson...',
 'Eh ur laptop got no stock lei... He say mon muz come again to take a look c got a not...',
 'Ü ready then call me...',
 'Ü still got lessons?  Ü in sch?',
 'Shall i get my pouch?',
 'm on da bus going home...',
 'm walking home oredi... Ü so late then reply... I oso saw a top dat i like but din buy... Where r ü now?',
 'll take forever to come back...',
 'R ü comin back for dinner?',
 'Eat at old airport road... But now 630 oredi... Got a lot of pple...',
 'Y bishan lei... I tot ü say lavender?',
 'Free any day but i finish at 6 on mon n thurs...',
 'I prefer my free days... Tues, wed, fri oso can... Ü ask those workin lor...',
 'But we havent got da topic yet rite?',
 'So can collect ur laptop?',
 'Ok good then i later come find ü... C lucky i told ü to go earlier... Later pple take finish ü no more again...',
 'Eat jap done oso aft ur lect wat... Ü got lect at 12 rite...',
 'So ü pay first lar... Then when is da stock comin...',
 's ur pin?',
 'Ü collecting ur laptop then going to configure da settings izzit?',
 'Cos daddy arranging time c wat time fetch ü mah...',
 'Juz now havent woke up so a bit blur blur... Can? Dad went out liao... I cant cum now oso...',
 'So li hai... Me bored now da lecturer repeating last weeks stuff waste time...',
 'm wearing shorts...',
 'Huh y lei...',
 'm eatin wif my frens now lei... Ü going home first?',
 'Havent still waitin as usual... Ü come back sch oredi?',
 'No break time one... How... I come out n get my stuff fr ü?',
 'Tmr then ü brin lar... Aiya later i come n c lar... Mayb ü neva set properly ü got da help sheet wif ü...',
 'I dunno lei... Like dun haf...',
 's present ar.',
 'Havent shopping now lor i juz arrive only',
 'Beauty sleep can help ur pimples too.',
 'Up to ü... Ü wan come then come lor... But i din c any stripes skirt...',
 's repent how?',
 'Got c... I lazy to type... I forgot ü in lect... I saw a pouch but like not v nice...',
 'Ok i found dis pierre cardin one which looks normal costs 20 its on sale.',
 'Y ü wan to go there? C doctor?',
 'm wif him now buying tix lar...',
 'How much r ü willing to pay?',
 'm selling it for $50...',
 's at home...',
 'Ok... Thanx... Gd nite 2 ü too...',
 'Wat uniform? In where get?',
 've finished c ü there...',
 'Never y lei... I v lazy... Got wat? Dat day ü send me da url cant work one...',
 're done...',
 'Anything lar...',
 'Go where n buy? Juz buy when we get there lar.',
 'Bishan lar nearer... No need buy so early cos if buy now i gotta park my car...',
 'Do u noe how 2 send files between 2 computers?',
 'I gotta collect da car at 6 lei.',
 '2 laptop... I noe infra but too slow lar... I wan fast one',
 'Dunno da next show aft 6 is 850. Toa payoh got 650.',
 'Tmr timin still da same wat cos i got lesson until 6...',
 'Wat time ü wan today?',
 'Aiya we discuss later lar... Pick ü up at 4 is it?',
 'm in a movie... Collect car oredi...',
 'I anything lor...',
 'Nothin comes to my mind. Ü help me buy hanger lor. Ur laptop not heavy?',
 'Ok lor wat time ü finish?',
 'Huh but i got lesson at 4 lei n i was thinkin of going to sch earlier n i tot of parkin at kent vale...',
 'Ü v ma fan...',
 'Ü come lt 25 n pass to me lar',
 'Y lei?',
 'I wanted to ask ü to wait 4 me to finish lect. Cos my lect finishes in an hour anyway.',
 'Aiyo cos i sms ü then ü neva reply so i wait 4 ü to reply lar. I tot ü havent finish ur lab wat.',
 'Auntie huai juan never pick up her phone',
 'I not free today i haf 2 pick my parents up tonite...',
 'Ok..',
 'Dunno lei... I might b eatin wif my frens... If ü wan to eat then i wait 4 ü lar',
 'How come?',
 'Then ü ask dad to pick ü up lar... Ü wan 2 stay until 6 meh...',
 'Oh ok wait 4 me there... My lect havent finish',
 'm done...',
 'In da car park',
 's sdryb8i',
 'Ü thk of wat to eat tonight.',
 'Aiyo please ü got time meh.',
 'm free...',
 'Ok.',
 'Anything lor. Juz both of us lor.',
 'Ok c ü then.',
 'll be late...',
 'Kent vale lor... Ü wait 4 me there ar?',
 'Ard 530 lor. I ok then message ü lor.',
 'm done. C ü there.',
 'staff.science.nus.edu.sg/~phyhcmk/teaching/pc1323',
 'Dunno lei shd b driving lor cos i go sch 1 hr oni.',
 'Ü wait 4 me in sch i finish ard 5..',
 'Ok can...',
 'Ü dun wan to watch infernal affair?',
 'Cos darren say ü considering mah so i ask ü...',
 's confirmed... I tot they juz say oni... Ok then...',
 'Me n him so funny...',
 'Anything lor is she coming?',
 'm in town now lei.',
 'With my sis lor... We juz watched italian job.',
 'C movie is juz last minute decision mah. Juz watch 2 lar but i tot ü not interested.',
 'Wat so late still early mah. Or we juz go 4 dinner lor. Aiya i dunno...',
 's ok.',
 'Can ü all decide faster cos my sis going home liao..',
 'Yup ü not comin :-(',
 'He neva grumble but i sad lor... Hee... Buy tmr lor aft lunch. But we still meetin 4 lunch tmr a not. Neva hear fr them lei. Ü got a lot of work ar?',
 'I jokin oni lar.. Ü busy then i wun disturb ü.',
 'Ok lor...',
 'm in a movie. Call me 4 wat?',
 's meeting?',
 'Do ü noe if ben is going?',
 'Dunno lei ü all decide lor. How abt leona? Oops i tot ben is going n i msg him.',
 's ok..',
 's da decision?',
 'Then ü wait 4 me at bus stop aft ur lect lar. If i dun c ü then i go get my car then come back n pick ü.',
 'Ok i juz receive..',
 'I borrow ur bag ok.',
 'Can. Dunno wat to get 4 her...',
 'Ok. But i finish at 6.',
 'll b going out shopping 4 my frens present.',
 'Or i go home first lar ü wait 4 me lor.. I put down my stuff first..',
 'll finish buying?',
 'Ok... But bag again..',
 's yijue@hotmail.com',
 'll be in da lab doing some stuff give me a call when ü r done.',
 'Anything lar then ü not going home 4 dinner?',
 'When can ü come out?',
 'I havent lei.. Next mon can?',
 'That day ü say ü cut ur hair at paragon, is it called hair sense? Do ü noe how much is a hair cut?',
 's da one ü cut ur hair.',
 's at paragon... I havent decided whether 2 cut yet... Hee...',
 'Ok lor but not too early. Me still having project meeting now.',
 'Ard 6 like dat lor.',
 'I not busy juz dun wan 2 go so early.. Hee..',
 'm not driving today.',
 'Doing project w frens lor.',
 'm not coming home 4 dinner.',
 'Ard 530 like dat lor. We juz meet in mrt station then ü dun haf to come out.',
 'Ok lor ü reaching then message me.',
 'Happy birthday... May all ur dreams come true...',
 's a card on da present lei... How? Ü all want 2 write smth or sign on it?',
 'Ü give me some time to walk there.',
 'Ü all write or wat..',
 'Then ü come n pick me at 530 ar?',
 'Thanx 4 sending me home...',
 'Is ur lecture over?',
 'Sorry me going home first... Daddy come fetch ü later...',
 'Okie.. Thanx..',
 'Will ü b going to esplanade fr home?',
 'We confirm eating at esplanade?',
 '7 at esplanade.. Do ü mind giving me a lift cos i got no car today..',
 'Ü got wat to buy tell us then ü no need to come in again.',
 's da model num of ur phone?',
 'Hmm thinking lor...',
 'Ok lor... Sony ericsson salesman... I ask shuhui then she say quite gd 2 use so i considering...',
 'Ü say until like dat i dun buy ericsson oso cannot oredi lar...',
 'Jokin only lar... :-) depends on which phone my father can get lor...',
 'No need to buy lunch for me.. I eat maggi mee..',
 'I know she called me',
 's da rest of da project going?',
 'm doing da intro covers energy trends n pros n cons... Brief description of nuclear fusion n oso brief history of iter n jet got abt 7 n half pages..',
 'Yup i shd haf ard 10 pages if i add figures... Ü all got how many pages?',
 's y we haf to combine n c how lor...',
 'll b doing da contents pg n cover pg..',
 'm going out 4 dinner soon..',
 's ur email?',
 've sent ü my part..',
 'I emailed yifeng my part oredi.. Can ü get it fr him..',
 'No need to ke qi... Ü too bored izzit y suddenly thk of this...',

In [14]:
UCI_dataset = read_file('../Dataset/UCI_SMSSpamCollection')

In [15]:
UCI_dataset = [i[:-1] for i in UCI_dataset]

In [16]:
UCI_dataset_ham, UCI_dataset_spam = [], []
for i in UCI_dataset:
    if i[0]=='h':
        UCI_dataset_ham.append(i[4:])
    else:
        UCI_dataset_spam.append(i[5:])

In [17]:
UCI_dataset_ham

['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...',
 'Ok lar... Joking wif u oni...',
 'U dun say so early hor... U c already then say...',
 "Nah I don't think he goes to usf, he lives around here though",
 'Even my brother is not like to speak with me. They treat me like aids patent.',
 "As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune",
 "I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today.",
 "I've been searching for the right words to thank you for this breather. I promise i wont take your help for granted and will fulfil my promise. You have been wonderful and a blessing at all times.",
 'I HAVE A DATE ON SUNDAY WITH WILL!!',
 "Oh k...i'm watching here:)",
 'Eh u remember how 2 spell his name... Yes i did. He v naughty make until i v wet.',
 'Fine if that\x92s the way u feel. That\x92s the way its gota b',
 'Is that seriously how you spell his name?',
 'I‘m going to try for 2 months ha ha only joking',
 'So ü pay first lar... Then when is da stock comin...',
 'Aft i finish my lunch then i go str down lor. Ard 3 smth lor. U finish ur lunch already?',
 'Ffffffffff. Alright no way I can meet up with you sooner?',
 "Just forced myself to eat a slice. I'm really not hungry tho. This sucks. Mark is getting worried. He knows I'm sick when I turn down pizza. Lol",
 'Lol your always so convincing.',
 "Did you catch the bus ? Are you frying an egg ? Did you make a tea? Are you eating your mom's left over dinner ? Do you feel my Love ?",
 "I'm back &amp; we're packing the car now, I'll let you know if there's room",
 'Ahhh. Work. I vaguely remember that! What does it feel like? Lol',
 "Wait that's still not all that clear, were you not sure about me being sarcastic or that that's why x doesn't want to live with us",
 "Yeah he got in at 2 and was v apologetic. n had fallen out and she was actin like spoilt child and he got caught up in that. Till 2! But we won't go there! Not doing too badly cheers. You? ",
 'K tell me anything about you.',
 'For fear of fainting with the of all that housework you just did? Quick have a cuppa',
 'Yup... Ok i go home look at the timings then i msg ü again... Xuhui going to learn on 2nd may too but her lesson is at 8am',
 "Oops, I'll let you know when my roommate's done",
 'I see the letter B on my car',
 'Anything lor... U decide...',
 "Hello! How's you and how did saturday go? I was just texting to see if you'd decided to do anything tomo. Not that i'm trying to invite myself or anything!",
 'Pls go ahead with watts. I just wanted to be sure. Do have a great weekend. Abiola',
 'Did I forget to tell you ? I want you , I need you, I crave you ... But most of all ... I love you my sweet Arabian steed ... Mmmmmm ... Yummy',
 'WHO ARE YOU SEEING?',
 'Great! I hope you like your man well endowed. I am  &lt;#&gt;  inches...',
 'No calls..messages..missed calls',
 "Didn't you get hep b immunisation in nigeria.",
 'Fair enough, anything going on?',
 "Yeah hopefully, if tyler can't do it I could maybe ask around a bit",
 "U don't know how stubborn I am. I didn't even want to go to the hospital. I kept telling Mark I'm not a weak sucker. Hospitals are for weak suckers.",
 'What you thinked about me. First time you saw me in class.',
 'A gram usually runs like  &lt;#&gt; , a half eighth is smarter though and gets you almost a whole second gram for  &lt;#&gt;',
 "K fyi x has a ride early tomorrow morning but he's crashing at our place tonight",
 'Wow. I never realized that you were so embarassed by your accomodations. I thought you liked it, since i was doing the best i could and you always seemed so happy about "the cave". I\'m sorry I didn\'t and don\'t have more to give. I\'m sorry i offered. I\'m sorry your room was so embarassing.',
 'Do you know what Mallika Sherawat did yesterday? Find out now @  &lt;URL&gt;',
 "Sorry, I'll call later in meeting.",
 'Tell where you reached',
 'Yes..gauti and sehwag out of odi series.',
 "Your gonna have to pick up a $1 burger for yourself on your way home. I can't even move. Pain is killing me.",
 'Ha ha ha good joke. Girls are situation seekers.',
 'Its a part of checking IQ',
 'Sorry my roommates took forever, it ok if I come by now?',
 'Ok lar i double check wif da hair dresser already he said wun cut v short. He said will cut until i look nice.',
 'Today is "song dedicated day.." Which song will u dedicate for me? Send this to all ur valuable frnds but first rply me...',
 'I plane to give on this month end.',
 'Wah lucky man... Then can save money... Hee...',
 'Finished class where are you.',
 'HI BABE IM AT HOME NOW WANNA DO SOMETHING? XX',
 'K..k:)where are you?how did you performed?',
 'U can call me now...',
 'I am waiting machan. Call me once you free.',
 'Thats cool. i am a gentleman and will treat you with dignity and respect.',
 'I like you peoples very much:) but am very shy pa.',
 'Does not operate after  &lt;#&gt;  or what',
 "Its not the same here. Still looking for a job. How much do Ta's earn there.",
 "Sorry, I'll call later",
 'K. Did you call me just now ah? ',
 'Ok i am on the way to home hi hi',
 'You will be in the place of that man',
 'Yup next stop.',
 "I call you later, don't have network. If urgnt, sms me.",
 "For real when u getting on yo? I only need 2 more tickets and one more jacket and I'm done. I already used all my multis.",
 "Yes I started to send requests to make it but pain came back so I'm back in bed. Double coins at the factory too. I gotta cash in all my nitros.",
 "I'm really not up to it still tonight babe",
 'Ela kano.,il download, come wen ur free..',
 'Yeah do! Don‘t stand to close tho- you‘ll catch something!',
 "Sorry to be a pain. Is it ok if we meet another night? I spent late afternoon in casualty and that means i haven't done any of y stuff42moro and that includes all my time sheets and that. Sorry. ",
 'Smile in Pleasure Smile in Pain Smile when trouble pours like Rain Smile when sum1 Hurts U Smile becoz SOMEONE still Loves to see u Smiling!!',
 'Havent planning to buy later. I check already lido only got 530 show in e afternoon. U finish work already?',
 'Watching telugu movie..wat abt u?',
 'i see. When we finish we have loads of loans to pay',
 'Hi. Wk been ok - on hols now! Yes on for a bit of a run. Forgot that i have hairdressers appointment at four so need to get home n shower beforehand. Does that cause prob for u?"',
 'I see a cup of coffee animation',
 "Please don't text me anymore. I have nothing else to say.",
 'Okay name ur price as long as its legal! Wen can I pick them up? Y u ave x ams xx',
 "I'm still looking for a car to buy. And have not gone 4the driving test yet.",
 "As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune",
 "wow. You're right! I didn't mean to do that. I guess once i gave up on boston men and changed my search location to nyc, something changed. Cuz on my signin page it still says boston.",
 'Umma my life and vava umma love you lot dear',
 'Thanks a lot for your wishes on my birthday. Thanks you for making my birthday truly memorable.',
 "Aight, I'll hit you up when I get some cash",
 "How would my ip address test that considering my computer isn't a minecraft server",
 'I know! Grumpy old people. My mom was like you better not be lying. Then again I am always the one to play jokes...',
 "Dont worry. I guess he's busy.",
 'What is the plural of the noun research?',
 'Going for dinner.msg you after.',
 "I'm ok wif it cos i like 2 try new things. But i scared u dun like mah. Cos u said not too loud.",
 "Wa, ur openin sentence very formal... Anyway, i'm fine too, juz tt i'm eatin too much n puttin on weight...Haha... So anythin special happened?",
 "As I entered my cabin my PA said, '' Happy B'day Boss !!''. I felt special. She askd me 4 lunch. After lunch she invited me to her apartment. We went there.",
 'Goodo! Yes we must speak friday - egg-potato ratio for tortilla needed! ',
 "Hmm...my uncle just informed me that he's paying the school directly. So pls buy food.",
 'here is my new address -apples&pairs&all that malarky',
 'I am going to sao mu today. Will be done only at 12 ',
 "Ü predict wat time ü'll finish buying?",
 'Good stuff, will do.',
 "Just so that you know,yetunde hasn't sent money yet. I just sent her a text not to bother sending. So its over, you dont have to involve yourself in anything. I shouldn't have imposed anything on you in the first place so for that, i apologise.",
 'Are you there in room.',
 'HEY GIRL. HOW R U? HOPE U R WELL ME AN DEL R BAK! AGAIN LONG TIME NO C! GIVE ME A CALL SUM TIME FROM LUCYxx',
 'K..k:)how much does it cost?',
 "I'm home.",
 'Dear, will call Tmorrow.pls accomodate.',
 'First answer my question.',
 "I only haf msn. It's yijue@hotmail.com",
 'He is there. You call and meet him',
 'No no. I will check all rooms befor activities',
 'Got c... I lazy to type... I forgot ü in lect... I saw a pouch but like not v nice...',
 "K, text me when you're on the way",
 'Sir, Waiting for your mail.',
 'A swt thought: "Nver get tired of doing little things 4 lovable persons.." Coz..somtimes those little things occupy d biggest part in their Hearts.. Gud ni8',
 'I know you are. Can you pls open the back?',
 'Yes see ya not on the dot',
 'Whats the staff name who is taking class for us?',
 'Ummma.will call after check in.our life will begin from qatar so pls pray very hard.',
 'K..i deleted my contact that why?',
 'Sindu got job in birla soft ..',
 "The wine is flowing and i'm i have nevering..",
 'Yup i thk cine is better cos no need 2 go down 2 plaza mah.',
 'Ok... Ur typical reply...',
 "As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune",
 'You are everywhere dirt, on the floor, the windows, even on my shirt. And sometimes when i open my mouth, you are all that comes flowing out. I dream of my world without you, then half my chores are out too. A time of joy for me, lots of tv shows i.ll see. But i guess like all things you just must exist, like rain, hail and mist, and when my time here is done, you and i become one.',
 'Aaooooright are you at work?',
 "I'm leaving my house now...",
 'Hello, my love. What are you doing? Did you get to that interview today? Are you you happy? Are you being a good boy? Do you think of me?Are you missing me ?',
 "Keep yourself safe for me because I need you and I miss you already and I envy everyone that see's you in real life",
 'New car and house for my parents.:)i have only new job in hand:)',
 "I'm so in love with you. I'm excited each day i spend with you. You make me so happy.",
 'I place all ur points on e cultures module already.',
 "Hi frnd, which is best way to avoid missunderstding wit our beloved one's?",
 'Great escape. I fancy the bridge but needs her lager. See you tomo ',
 'Yes :)it completely in out of form:)clark also utter waste.',
 'Sir, I need AXIS BANK account no and bank address.',
 'Hmmm.. Thk sure got time to hop ard... Ya, can go 4 free abt... Muz call u to discuss liao... ',
 'What time you coming down later? ',
 'Bloody hell, cant believe you forgot my surname Mr . Ill give u a clue, its spanish and begins with m... ',
 "Well, i'm gonna finish my bath now. Have a good...fine night.",
 "Let me know when you've got the money so carlos can make the call",
 'U still going to the mall?',
 "Turns out my friends are staying for the whole show and won't be back til ~ &lt;#&gt; , so feel free to go ahead and smoke that $ &lt;#&gt;  worth",
 'Text her. If she doesnt reply let me know so i can have her log in',
 "Hi! You just spoke to MANEESHA V. We'd like to know if you were satisfied with the experience. Reply Toll Free with Yes or No.",
 'You lifted my hopes with the offer of money. I am in need. Especially when the end of the month approaches and it hurts my studying. Anyways have a gr8 weekend',
 'Lol no. U can trust me.',
 'ok. I am a gentleman and will treat you with dignity and respect.',
 'He will, you guys close?',
 'Going on nothing great.bye',
 "Hello handsome ! Are you finding that job ? Not being lazy ? Working towards getting back that net for mummy ? Where's my boytoy now ? Does he miss me ?",
 'Haha awesome, be there in a minute',
 'Have you got Xmas radio times. If not i will get it now',
 'I jus reached home. I go bathe first. But my sis using net tell u when she finishes k...',
 "I'm sorry. I've joined the league of people that dont keep in touch. You mean a great deal to me. You have been a friend at all times even at great personal cost. Do have a great week.|",
 'Hi :)finally i completed the course:)',
 'It will stop on itself. I however suggest she stays with someone that will be able to give ors for every stool.',
 "How are you doing? Hope you've settled in for the new school year. Just wishin you a gr8 day",
 'Gud mrng dear hav a nice day',
 'Did u got that persons story',
 'is your hamster dead? Hey so tmr i meet you at 1pm orchard mrt? ',
 'Hi its Kate how is your evening? I hope i can see you tomorrow for a bit but i have to bloody babyjontet! Txt back if u can. :) xxx',
 'Found it, ENC  &lt;#&gt; , where you at?',
 'I sent you  &lt;#&gt;  bucks',
 'Hello darlin ive finished college now so txt me when u finish if u can love Kate xxx',
 'Your account has been refilled successfully by INR  &lt;DECIMAL&gt; . Your KeralaCircle prepaid account balance is Rs  &lt;DECIMAL&gt; . Your Transaction ID is KR &lt;#&gt; .',
 'Goodmorning sleeping ga.',
 'U call me alter at 11 ok.',
 'Ü say until like dat i dun buy ericsson oso cannot oredi lar...',
 "As I entered my cabin my PA said, '' Happy B'day Boss !!''. I felt special. She askd me 4 lunch. After lunch she invited me to her apartment. We went there.",
 'Aight yo, dats straight dogg',
 'You please give us connection today itself before  &lt;DECIMAL&gt;  or refund the bill',
 'Both :) i shoot big loads so get ready!',
 "What's up bruv, hope you had a great break. Do have a rewarding semester.",
 'Home so we can always chat',
 'K:)k:)good:)study well.',
 'Yup... How ü noe leh...',
 'Sounds great! Are you home now?',
 'Finally the match heading towards draw as your prediction.',
 "Tired. I haven't slept well the past few nights.",
 'Easy ah?sen got selected means its good..',
 'I have to take exam with march 3',
 "Yeah you should. I think you can use your gt atm now to register. Not sure but if there's anyway i can help let me know. But when you do be sure you are ready.",
 'Ok no prob. Take ur time.',
 'There is os called ubandu which will run without installing in hard disk...you can use that os to copy the important files in system and give it to repair shop..',
 "Sorry, I'll call later",
 'U say leh... Of course nothing happen lar. Not say v romantic jus a bit only lor. I thk e nite scenery not so nice leh.',
 'Would really appreciate if you call me. Just need someone to talk to.',
 'Hey company elama po mudyadhu.',
 'Life is more strict than teacher... Bcoz Teacher teaches lesson &amp; then conducts exam, But Life first conducts Exam &amp; then teaches Lessons. Happy morning. . .',
 'Dear good morning now only i am up',
 'Get down in gandhipuram and walk to cross cut road. Right side &lt;#&gt; street road and turn at first right.',
 'Dear we are going to our rubber place',
 "Sorry battery died, yeah I'm here",
 'Yes:)here tv is always available in work place..',
 'I have printed it oh. So  &lt;#&gt;  come upstairs',
 'Or ill be a little closer like at the bus stop on the same street',
 'Where are you?when wil you reach here?',
 "New Theory: Argument wins d SITUATION, but loses the PERSON. So dont argue with ur friends just.. . . . kick them &amp; say, I'm always correct.!",
 'Tomarrow final hearing on my laptop case so i cant.',
 'PLEASSSSSSSEEEEEE TEL ME V AVENT DONE SPORTSx',
 'Okay. No no, just shining on. That was meant to be signing, but that sounds better.',
 "Although i told u dat i'm into baig face watches now but i really like e watch u gave cos it's fr u. Thanx 4 everything dat u've done today, i'm touched...",
 "U don't remember that old commercial?",
 "Too late. I said i have the website. I didn't i have or dont have the slippers",
 'I asked you to call him now ok',
 'Kallis wont bat in 2nd innings.',
 'It didnt work again oh. Ok goodnight then. I.ll fix and have it ready by the time you wake up. You are very dearly missed have a good night sleep.',
 'Ranjith cal drpd Deeraj and deepak 5min hold',
 'Wen ur lovable bcums angry wid u, dnt take it seriously.. Coz being angry is d most childish n true way of showing deep affection, care n luv!.. kettoda manda... Have nice day da.',
 'What you doing?how are you?',
 'Ups which is 3days also, and the shipping company that takes 2wks. The other way is usps which takes a week but when it gets to lag you may have to bribe nipost to get your stuff.',
 "I'm back, lemme know when you're ready",
 "Don't necessarily expect it to be done before you get back though because I'm just now headin out",
 'Mmm so yummy babe ... Nice jolt to the suzy',
 'Where are you lover ? I need you ...',
 'I‘m parked next to a MINI!!!! When are you coming in today do you think?',
 'Yup',
 "Anyway i'm going shopping on my own now. Cos my sis not done yet. Dun disturb u liao.",
 'MY NO. IN LUTON 0125698789 RING ME IF UR AROUND! H*',
 'Why you Dint come with us.',
 'Same. Wana plan a trip sometme then',
 'Not sure yet, still trying to get a hold of him',
 'The evo. I just had to download flash. Jealous?',
 "Come to mu, we're sorting out our narcotics situation",
 'Night has ended for another day, morning has come in a special way. May you smile like the sunny rays and leaves your worries at the blue blue bay.',
 'Usf I guess, might as well take 1 car',
 'No objection. My bf not coming.',
 'Thanx...',
 'Tell rob to mack his gf in the theater',
 "Awesome, I'll see you in a bit",
 'Just sent it. So what type of food do you like?',
 'All done? All handed in? Celebrations in full swing yet?',
 'You got called a tool?',
 '"Wen u miss someone, the person is definitely special for u..... But if the person is so special, why to miss them, just Keep-in-touch" gdeve..',
 'Ok. I asked for money how far',
 'Okie...',
 "Yeah I think my usual guy's still passed out from last night, if you get ahold of anybody let me know and I'll throw down",
 'K, I might come by tonight then if my class lets out early',
 'Ok..',
 'hi baby im cruisin with my girl friend what r u up 2? give me a call in and hour at home if thats alright or fone me on this fone now love jenny xxx',
 'My life Means a lot to me, Not because I love my life, But because I love the people in my life, The world calls them friends, I call them my World:-).. Ge:-)..',
 'Dear,shall mail tonite.busy in the street,shall update you tonite.things are looking ok.varunnathu edukkukayee raksha ollu.but a good one in real sense.',
 'Hey you told your name to gautham ah?',
 'Haf u found him? I feel so stupid da v cam was working.',
 'Oops. 4 got that bit.',
 'Are you this much buzy',
 'I accidentally deleted the message. Resend please.',
 "Unless it's a situation where YOU GO GURL would be more appropriate",
 'Hurt me... Tease me... Make me cry... But in the end of my life when i die plz keep one rose on my grave and say STUPID I MISS U.. HAVE A NICE DAY BSLVYL',
 'I cant pick the phone right now. Pls send a message',
 "Need a coffee run tomo?Can't believe it's that time of week already",
 'Awesome, I remember the last time we got somebody high for the first time with diesel :V',

In [18]:
UCI_dataset_spam

["Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",
 "FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv",
 'WINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.',
 'Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030',
 'SIX chances to win CASH! From 100 to 20,000 pounds txt> CSH11 and send to 87575. Cost 150p/day, 6days, 16+ TsandCs apply Reply HL 4 info',
 'URGENT! You have won a 1 week FREE membership in our £100,000 Prize Jackpot! Txt the word: CLAIM to No: 81010 T&C www.dbuk.net LCCLTD POBOX 4403LDNW1A7RW18',
 'XXXMobileMovieClub: To use your credit, click the WAP link in the next txt message or click here>> http://wap. xxxmobilemovieclub.com?n=QJKGIGHJJGCBL',
 'England v Macedonia - dont miss the goals/team news. Txt ur national team to 87077 eg ENGLAND to 87077 Try:WALES, SCOTLAND 4txt/ú1.20 POBOXox36504W45WQ 16+',
 'Thanks for your subscription to Ringtone UK your mobile will be charged £5/month Please confirm by replying YES or NO. If you reply NO you will not be charged',
 '07732584351 - Rodger Burns - MSG = We tried to call you re your reply to our sms for a free nokia mobile + free camcorder. Please call now 08000930705 for delivery tomorrow',
 'SMS. ac Sptv: The New Jersey Devils and the Detroit Red Wings play Ice Hockey. Correct or Incorrect? End? Reply END SPTV',
 'Congrats! 1 year special cinema pass for 2 is yours. call 09061209465 now! C Suprman V, Matrix3, StarWars3, etc all 4 FREE! bx420-ip4-5we. 150pm. Dont miss out! ',
 'As a valued customer, I am pleased to advise you that following recent review of your Mob No. you are awarded with a £1500 Bonus Prize, call 09066364589',
 'Urgent UR awarded a complimentary trip to EuroDisinc Trav, Aco&Entry41 Or £1000. To claim txt DIS to 87121 18+6*£1.50(moreFrmMob. ShrAcomOrSglSuplt)10, LS1 3AJ',
 'Did you hear about the new "Divorce Barbie"? It comes with all of Ken\'s stuff!',
 'Please call our customer service representative on 0800 169 6031 between 10am-9pm as you have WON a guaranteed £1000 cash or £5000 prize!',
 'Your free ringtone is waiting to be collected. Simply text the password "MIX" to 85069 to verify. Get Usher and Britney. FML, PO Box 5249, MK17 92H. 450Ppw 16',
 'GENT! We are trying to contact you. Last weekends draw shows that you won a £1000 prize GUARANTEED. Call 09064012160. Claim Code K52. Valid 12hrs only. 150ppm',
 'You are a winner U have been specially selected 2 receive £1000 or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810910p/min (18+) ',
 'PRIVATE! Your 2004 Account Statement for 07742676969 shows 786 unredeemed Bonus Points. To claim call 08719180248 Identifier Code: 45239 Expires',
 'URGENT! Your Mobile No. was awarded £2000 Bonus Caller Prize on 5/9/03 This is our final try to contact U! Call from Landline 09064019788 BOX42WR29C, 150PPM',
 'Todays Voda numbers ending 7548 are selected to receive a $350 award. If you have a match please call 08712300220 quoting claim code 4041 standard rates app',
 'Sunshine Quiz Wkly Q! Win a top Sony DVD player if u know which country the Algarve is in? Txt ansr to 82277. £1.50 SP:Tyrone',
 "Want 2 get laid tonight? Want real Dogging locations sent direct 2 ur mob? Join the UK's largest Dogging Network bt Txting GRAVEL to 69888! Nt. ec2a. 31p.msg@150p",
 "You'll not rcv any more msgs from the chat svc. For FREE Hardcore services text GO to: 69988 If u get nothing u must Age Verify with yr network & try again",
 "FreeMsg Why haven't you replied to my text? I'm Randy, sexy, female and live local. Luv to hear from u. Netcollex Ltd 08700621170150p per msg reply Stop to end",
 'Customer service annoncement. You have a New Years delivery waiting for you. Please call 07046744435 now to arrange delivery',
 'You are a winner U have been specially selected 2 receive £1000 cash or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810810',
 '-PLS STOP bootydelious (32/F) is inviting you to be her friend. Reply YES-434 or NO-434 See her: www.SMS.ac/u/bootydelious STOP? Send STOP FRND to 62468',
 'BangBabes Ur order is on the way. U SHOULD receive a Service Msg 2 download UR content. If U do not, GoTo wap. bangb. tv on UR mobile internet/service menu',
 'URGENT! We are trying to contact you. Last weekends draw shows that you have won a £900 prize GUARANTEED. Call 09061701939. Claim code S89. Valid 12hrs only',
 'Please call our customer service representative on FREEPHONE 0808 145 4742 between 9am-11pm as you have WON a guaranteed £1000 cash or £5000 prize!',
 'Are you unique enough? Find out from 30th August. www.areyouunique.co.uk',
 '500 New Mobiles from 2004, MUST GO! Txt: NOKIA to No: 89545 & collect yours today!From ONLY £1 www.4-tc.biz 2optout 087187262701.50gbp/mtmsg18',
 'Will u meet ur dream partner soon? Is ur career off 2 a flyng start? 2 find out free, txt HORO followed by ur star sign, e. g. HORO ARIES',
 'Text & meet someone sexy today. U can find a date or even flirt its up to U. Join 4 just 10p. REPLY with NAME & AGE eg Sam 25. 18 -msg recd@thirtyeight pence',
 'U 447801259231 have a secret admirer who is looking 2 make contact with U-find out who they R*reveal who thinks UR so special-call on 09058094597',
 'Congratulations ur awarded 500 of CD vouchers or 125gift guaranteed & Free entry 2 100 wkly draw txt MUSIC to 87066 TnCs www.Ldew.com1win150ppmx3age16',
 'We tried to contact you re your reply to our offer of a Video Handset? 750 anytime networks mins? UNLIMITED TEXT? Camcorder? Reply or call 08000930705 NOW',
 'Hey I am really horny want to chat or see me naked text hot to 69698 text charged at 150pm to unsubscribe text stop 69698',
 'Ur ringtone service has changed! 25 Free credits! Go to club4mobiles.com to choose content now! Stop? txt CLUB STOP to 87070. 150p/wk Club4 PO Box1146 MK45 2WT',
 'Ringtone Club: Get the UK singles chart on your mobile each week and choose any top quality ringtone! This message is free of charge.',
 'HMV BONUS SPECIAL 500 pounds of genuine HMV vouchers to be won. Just answer 4 easy questions. Play Now! Send HMV to 86688 More info:www.100percent-real.com',
 "T-Mobile customer you may now claim your FREE CAMERA PHONE upgrade & a pay & go sim card for your loyalty. Call on 0845 021 3680.Offer ends 28thFeb.T&C's apply",
 'SMS. ac Blind Date 4U!: Rodds1 is 21/m from Aberdeen, United Kingdom. Check Him out http://img. sms. ac/W/icmb3cktz8r7!-4 no Blind Dates send HIDE',
 'TheMob> Check out our newest selection of content, Games, Tones, Gossip, babes and sport, Keep your mobile fit and funky text WAP to 82468',
 'Think ur smart ? Win £200 this week in our weekly quiz, text PLAY to 85222 now!T&Cs WinnersClub PO BOX 84, M26 3UZ. 16+. GBP1.50/week',
 'December only! Had your mobile 11mths+? You are entitled to update to the latest colour camera mobile for Free! Call The Mobile Update Co FREE on 08002986906',
 'Call Germany for only 1 pence per minute! Call from a fixed line via access number 0844 861 85 85. No prepayment. Direct access!',
 'Valentines Day Special! Win over £1000 in our quiz and take your partner on the trip of a lifetime! Send GO to 83600 now. 150p/msg rcvd. CustCare:08718720201.',
 'Fancy a shag? I do.Interested? sextextuk.com txt XXUK SUZY to 69876. Txts cost 1.50 per msg. TnCs on website. X',
 'Congratulations ur awarded 500 of CD vouchers or 125gift guaranteed & Free entry 2 100 wkly draw txt MUSIC to 87066 TnCs www.Ldew.com1win150ppmx3age16',
 'Ur cash-balance is currently 500 pounds - to maximize ur cash-in now send CASH to 86688 only 150p/msg. CC: 08708800282 HG/Suite342/2Lands Row/W1J6HL',
 'Update_Now - Xmas Offer! Latest Motorola, SonyEricsson & Nokia & FREE Bluetooth! Double Mins & 1000 Txt on Orange. Call MobileUpd8 on 08000839402 or call2optout/F4Q=',
 'Here is your discount code RP176781. To stop further messages reply stop. www.regalportfolio.co.uk. Customer Services 08717205546',
 'Thanks for your Ringtone Order, Reference T91. You will be charged GBP 4 per week. You can unsubscribe at anytime by calling customer services on 09057039994',
 'Double mins and txts 4 6months FREE Bluetooth on Orange. Available on Sony, Nokia Motorola phones. Call MobileUpd8 on 08000839402 or call2optout/N9DX',
 '4mths half price Orange line rental & latest camera phones 4 FREE. Had your phone 11mths ? Call MobilesDirect free on 08000938767 to update now! or2stoptxt',
 'FREE RINGTONE text FIRST to 87131 for a poly or text GET to 87131 for a true tone! Help? 0845 2814032 16 after 1st free, tones are 3x£150pw to e£nd txt stop',
 '100 dating service cal;l 09064012103 box334sk38ch',
 'FREE entry into our £250 weekly competition just text the word WIN to 80086 NOW. 18 T&C www.txttowin.co.uk',
 'Send a logo 2 ur lover - 2 names joined by a heart. Txt LOVE NAME1 NAME2 MOBNO eg LOVE ADAM EVE 07123456789 to 87077 Yahoo! POBox36504W45WQ TxtNO 4 no ads 150p',
 'Someone has contacted our dating service and entered your phone because they fancy you! To find out who it is call from a landline 09111032124 . PoBox12n146tf150p',
 'URGENT! Your Mobile number has been awarded with a £2000 prize GUARANTEED. Call 09058094455 from land line. Claim 3030. Valid 12hrs only',
 'Congrats! Nokia 3650 video camera phone is your Call 09066382422 Calls cost 150ppm Ave call 3mins vary from mobiles 16+ Close 300603 post BCM4284 Ldn WC1N3XX',
 "Loan for any purpose £500 - £75,000. Homeowners + Tenants welcome. Have you been previously refused? We can still help. Call Free 0800 1956669 or text back 'help'",
 "UpgrdCentre Orange customer, you may now claim your FREE CAMERA PHONE upgrade for your loyalty. Call now on 0207 153 9153. Offer ends 26th July. T&C's apply. Opt-out available",
 'okmail: Dear Dave this is your final notice to collect your 4* Tenerife Holiday or #5000 CASH award! Call 09061743806 from landline. TCs SAE Box326 CW25WX 150ppm',
 "Want 2 get laid tonight? Want real Dogging locations sent direct 2 ur Mob? Join the UK's largest Dogging Network by txting MOAN to 69888Nyt. ec2a. 31p.msg@150p",
 'FREE MESSAGE Activate your 500 FREE Text Messages by replying to this message with the word FREE For terms & conditions, visit www.07781482378.com',
 'Congrats! 1 year special cinema pass for 2 is yours. call 09061209465 now! C Suprman V, Matrix3, StarWars3, etc all 4 FREE! bx420-ip4-5we. 150pm. Dont miss out!',
 "+123 Congratulations - in this week's competition draw u have won the £1450 prize to claim just call 09050002311 b4280703. T&Cs/stop SMS 08718727868. Over 18 only 150ppm",
 'You are guaranteed the latest Nokia Phone, a 40GB iPod MP3 player or a £500 prize! Txt word: COLLECT to No: 83355! IBHltd LdnW15H 150p/Mtmsgrcvd18+',
 'Boltblue tones for 150p Reply POLY# or MONO# eg POLY3 1. Cha Cha Slide 2. Yeah 3. Slow Jamz 6. Toxic 8. Come With Me or STOP 4 more tones txt MORE',
 'Your credits have been topped up for http://www.bubbletext.com Your renewal Pin is tgxxrz',
 'URGENT!: Your Mobile No. was awarded a £2,000 Bonus Caller Prize on 02/09/03! This is our 2nd attempt to contact YOU! Call 0871-872-9755 BOX95QU',
 "Today's Offer! Claim ur £150 worth of discount vouchers! Text YES to 85023 now! SavaMob, member offers mobile! T Cs 08717898035. £3.00 Sub. 16 . Unsub reply X",
 'You will recieve your tone within the next 24hrs. For Terms and conditions please see Channel U Teletext Pg 750',
 'PRIVATE! Your 2003 Account Statement for 07815296484 shows 800 un-redeemed S.I.M. points. Call 08718738001 Identifier Code 41782 Expires 18/11/04 ',
 'from www.Applausestore.com MonthlySubscription@50p/msg max6/month T&CsC web age16 2stop txt stop',
 'GENT! We are trying to contact you. Last weekends draw shows that you won a £1000 prize GUARANTEED. Call 09064012160. Claim Code K52. Valid 12hrs only. 150ppm ',
 'You have won ?1,000 cash or a ?2,000 prize! To claim, call09050000327',
 'our mobile number has won £5000, to claim calls us back or ring the claims hot line on 09050005321.',
 'We tried to contact you re your reply to our offer of 750 mins 150 textand a new video phone call 08002988890 now or reply for free delivery tomorrow',
 "For ur chance to win a £250 wkly shopping spree TXT: SHOP to 80878. T's&C's www.txt-2-shop.com custcare 08715705022, 1x150p/wk",
 'You have been specially selected to receive a 2000 pound award! Call 08712402050 BEFORE the lines close. Cost 10ppm. 16+. T&Cs apply. AG Promo',
 'PRIVATE! Your 2003 Account Statement for 07753741225 shows 800 un-redeemed S. I. M. points. Call 08715203677 Identifier Code: 42478 Expires 24/10/04',
 'You have an important customer service announcement. Call FREEPHONE 0800 542 0825 now!',
 'XCLUSIVE@CLUBSAISAI 2MOROW 28/5 SOIREE SPECIALE ZOUK WITH NICHOLS FROM PARIS.FREE ROSES 2 ALL LADIES !!! info: 07946746291/07880867867 ',
 '22 days to kick off! For Euro2004 U will be kept up to date with the latest news and results daily. To be removed send GET TXT STOP to 83222',
 'New TEXTBUDDY Chat 2 horny guys in ur area 4 just 25p Free 2 receive Search postcode or at gaytextbuddy.com. TXT ONE name to 89693',
 'Todays Vodafone numbers ending with 4882 are selected to a receive a £350 award. If your number matches call 09064019014 to receive your £350 award.',
 'Dear Voucher Holder, 2 claim this weeks offer, at your PC go to http://www.e-tlp.co.uk/expressoffer Ts&Cs apply.2 stop texts txt STOP to 80062.',
 'PRIVATE! Your 2003 Account Statement for shows 800 un-redeemed S. I. M. points. Call 08715203694 Identifier Code: 40533 Expires 31/10/04',
 'You have won ?1,000 cash or a ?2,000 prize! To claim, call09050000327. T&C: RSTM, SW7 3SS. 150ppm',
 '88800 and 89034 are premium phone services call 08718711108',
 'SMS. ac sun0819 posts HELLO:"You seem cool, wanted to say hi. HI!!!" Stop? Send STOP to 62468',
 'Get ur 1st RINGTONE FREE NOW! Reply to this msg with TONE. Gr8 TOP 20 tones to your phone every week just £1.50 per wk 2 opt out send STOP 08452810071 16',
 "Hi I'm sue. I am 20 years old and work as a lapdancer. I love sex. Text me live - I'm i my bedroom now. text SUE to 89555. By TextOperator G2 1DA 150ppmsg 18+",
 '<Forwarded from 448712404000>Please CALL 08712404000 immediately as there is an urgent message waiting for you.',
 'To review and KEEP the fantastic Nokia N-Gage game deck with Club Nokia, go 2 www.cnupdates.com/newsletter. unsubscribe from alerts reply with the word OUT',
 '4mths half price Orange line rental & latest camera phones 4 FREE. Had your phone 11mths+? Call MobilesDirect free on 08000938767 to update now! or2stoptxt T&Cs',
 '08714712388 between 10am-7pm Cost 10p',
 '+449071512431 URGENT! This is the 2nd attempt to contact U!U have WON £1250 CALL 09071512433 b4 050703 T&CsBCM4235WC1N3XX. callcost 150ppm mobilesvary. max£7. 50',
 'You have WON a guaranteed £1000 cash or a £2000 prize. To claim yr prize call our customer service representative on 08714712394 between 10am-7pm',
 'Email AlertFrom: Jeri StewartSize: 2KBSubject: Low-cost prescripiton drvgsTo listen to email call 123',
 'Hi. Customer Loyalty Offer:The NEW Nokia6650 Mobile from ONLY £10 at TXTAUCTION! Txt word: START to No: 81151 & get yours Now! 4T&Ctxt TC 150p/MTmsg',
 'U are subscribed to the best Mobile Content Service in the UK for £3 per 10 days until you send STOP to 82324. Helpline 08706091795',
 "Do you realize that in about 40 years, we'll have thousands of old ladies running around with tattoos?",
 'You have an important customer service announcement from PREMIER.',
 'Romantic Paris. 2 nights, 2 flights from £79 Book now 4 next year. Call 08704439680Ts&Cs apply.',
 'Urgent Ur £500 guaranteed award is still unclaimed! Call 09066368327 NOW closingdate04/09/02 claimcode M39M51 £1.50pmmorefrommobile2Bremoved-MobyPOBox734LS27YF',
 'UR awarded a City Break and could WIN a £200 Summer Shopping spree every WK. Txt STORE to 88039 . SkilGme. TsCs087147403231Winawk!Age16 £1.50perWKsub',
 'You have an important customer service announcement from PREMIER. Call FREEPHONE 0800 542 0578 now!',
 'Ever thought about living a good life with a perfect partner? Just txt back NAME and AGE to join the mobile community. (100p/SMS)',
 '5 Free Top Polyphonic Tones call 087018728737, National Rate. Get a toppoly tune sent every week, just text SUBPOLY to 81618, £3 per pole. UnSub 08718727870.',
 "Orange customer, you may now claim your FREE CAMERA PHONE upgrade for your loyalty. Call now on 0207 153 9996. Offer ends 14thMarch. T&C's apply. Opt-out availa",
 'Last Chance! Claim ur £150 worth of discount vouchers today! Text SHOP to 85023 now! SavaMob, offers mobile! T Cs SavaMob POBOX84, M263UZ. £3.00 Sub. 16',
 'FREE for 1st week! No1 Nokia tone 4 ur mobile every week just txt NOKIA to 8077 Get txting and tell ur mates. www.getzed.co.uk POBox 36504 W45WQ 16+ norm150p/tone',
 'You have won a guaranteed £200 award or even £1000 cashto claim UR award call free on 08000407165 (18+) 2 stop getstop on 88222 PHP. RG21 4JX',
 'Congratulations ur awarded either £500 of CD gift vouchers & Free entry 2 our £100 weekly draw txt MUSIC to 87066 TnCs www.Ldew.com1win150ppmx3age16',
 'U were outbid by simonwatson5120 on the Shinco DVD Plyr. 2 bid again, visit sms. ac/smsrewards 2 end bid notifications, reply END OUT',
 'SMSSERVICES. for yourinclusive text credits, pls goto www.comuk.net login= 3qxj9 unsubscribe with STOP, no extra charge. help 08702840625.COMUK. 220-CM2 9AE',
 "25p 4 alfie Moon's Children in need song on ur mob. Tell ur m8s. Txt Tone charity to 8007 for Nokias or Poly charity for polys: zed 08701417012 profit 2 charity.",
 'U have a secret admirer. REVEAL who thinks U R So special. Call 09065174042. To opt out Reply REVEAL STOP. 1.50 per msg recd. Cust care 07821230901',
 'Dear Voucher Holder, To claim this weeks offer, at you PC please go to http://www.e-tlp.co.uk/expressoffer Ts&Cs apply. To stop texts, txt STOP to 80062',
 'Do you want 750 anytime any network mins 150 text and a NEW VIDEO phone for only five pounds per week call 08002888812 or reply for delivery tomorrow',
 'We tried to contact you re our offer of New Video Phone 750 anytime any network mins HALF PRICE Rental camcorder call 08000930705 or reply for delivery Wed',
 'Last chance 2 claim ur £150 worth of discount vouchers-Text YES to 85023 now!SavaMob-member offers mobile T Cs 08717898035. £3.00 Sub. 16 . Remove txt X or STOP',
 'Urgent! call 09066350750 from your landline. Your complimentary 4* Ibiza Holiday or 10,000 cash await collection SAE T&Cs PO BOX 434 SK3 8WP 150 ppm 18+ ',
 "Today's Offer! Claim ur £150 worth of discount vouchers! Text YES to 85023 now! SavaMob, member offers mobile! T Cs 08717898035. £3.00 Sub. 16 . Unsub reply X",
 'Talk sexy!! Make new friends or fall in love in the worlds most discreet text dating service. Just text VIP to 83110 and see who you could meet.',
 'Congratulations ur awarded either a yrs supply of CDs from Virgin Records or a Mystery Gift GUARANTEED Call 09061104283 Ts&Cs www.smsco.net £1.50pm approx 3mins',
 'PRIVATE! Your 2003 Account Statement for 07808 XXXXXX shows 800 un-redeemed S. I. M. points. Call 08719899217 Identifier Code: 41685 Expires 07/11/04',
 'Hello. We need some posh birds and chaps to user trial prods for champneys. Can i put you down? I need your address and dob asap. Ta r',
 'What do U want for Xmas? How about 100 free text messages & a new video phone with half price line rental? Call free now on 0800 0721072 to find out more!',
 'Shop till u Drop, IS IT YOU, either 10K, 5K, £500 Cash or £100 Travel voucher, Call now, 09064011000. NTT PO Box CR01327BT fixedline Cost 150ppm mobile vary',

In [19]:
print(len(UCI_dataset_ham))
print(len(UCI_dataset_spam))

4827
747

In [20]:
UCI_csv = pd.DataFrame()
label, message = [], []
for i in UCI_dataset:
    xx = i.split('\t')
    # print(len(xx),xx)
    label.append(xx[0])
    message.append(xx[1])

UCI_csv['Message'] = message
UCI_csv['Label'] = label

# UCI_csv.to_csv('../Dataset/UCI_Smishing_Dataset.csv', index=None)
UCI_csv.head()

                                             Message Label
0  Go until jurong point, crazy.. Available only ...   ham
1                      Ok lar... Joking wif u oni...   ham
2  Free entry in 2 a wkly comp to win FA Cup fina...  spam
3  U dun say so early hor... U c already then say...   ham
4  Nah I don't think he goes to usf, he lives aro...   ham

In [21]:
mendeley_dataset = pd.read_csv('../Dataset/Mendeley_dataset_5971.csv')
mendeley_dataset.head()

      LABEL                                               TEXT URL EMAIL PHONE
0       ham  Your opinion about me? 1. Over 2. Jada 3. Kusr...  No    No    No
1       ham  What's up? Do you want me to come online? If y...  No    No    No
2       ham                       So u workin overtime nigpun?  No    No    No
3       ham  Also sir, i sent you an email about how to log...  No    No    No
4  Smishing  Please Stay At Home. To encourage the notion o...  No    No    No

In [22]:
mendeley_dataset['LABEL'].value_counts()

LABEL
ham         4844
Smishing     616
spam         466
Spam          23
smishing      22
Name: count, dtype: int64

In [23]:
#full intersection
len(set(UCI_csv['Message']).intersection(set(mendeley_dataset['TEXT'])))

4753

In [24]:
#ham intersection
len(set(UCI_csv[UCI_csv['Label']=='ham']['Message']).intersection(set(mendeley_dataset['TEXT'])))

4199

In [25]:
#spam intersection
len(set(UCI_csv[UCI_csv['Label']=='spam']['Message']).intersection(set(mendeley_dataset['TEXT'])))

554

In [26]:
smishtank_dataset = pd.read_csv('../Dataset/smishtank.csv', encoding='unicode_escape')

In [27]:
smishtank_dataset.head()

,messageid,Fulltext,Sender,SenderType,timeReceived,MainText,Url,Subdomain,Domain,TLD,...,Phishing,Suspicious,Malware,Brand,URL Subcategory,Message Categories,FullyQualifiedDomain,Domain Registrar,Domain Creation Date,Domain Last Update
0,3,"Text Message\nThu, Jul 29, 19:10\nCostco: Dani...",42003,Short Code,"03/31/2022, 21:58:50","Costco: Daniel, the code 42003 printed on your...",f2gpy.info/RzNKEwsZve,NaN,f2gpy,info,...,0,0,0,Costco,Random Domain,Prize/Contest,f2gpy.info,"NameCheap, Inc.",7/28/2021,7/31/2021
1,5,"<\n+1 (872) 279-0672 >\nText Message\nWed, Feb...",+1 (872) 279-0672,Phone Number,"04/02/2022, 02:59:56","Hi, you still owe UPS $4.10 USD in customs fee...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,UPS,NaN,Delivery,NaN,NaN,NaN,NaN
2,6,"<\n+1 (806) 224-7886 >\nText Message\nThu, Sep...",+1 (806) 224-7886,Phone Number,"04/02/2022, 03:03:00",wel01.us/r/rest05 WELLS FARGO(CS):Profile lock...,wel01.us/r/rest05,NaN,wel01,us,...,0,0,0,WELLS FARGO,Random Domain,Account Alert,wel01.us,"NameCheap, Inc.",8/30/2021,8/30/2021
3,7,Text Message\nToday 2:30 PM\nwho played golf\n...,NaN,NaN,"04/02/2022, 23:42:38","Hi, are you who played golf together last time...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Wrong Number/Romance Scam,NaN,NaN,NaN,NaN
4,8,(8\n+1 (775) 537-4497\ncanador to them\nTato m...,+1 (775) 537-4497,Phone Number,"04/02/2022, 23:46:34","(8 Hi Julianne long time no see, I'm Aleen, ho...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Wrong Number/Romance Scam,NaN,NaN,NaN,NaN

In [28]:
smishtank_dataset['MainText']

0       Costco: Daniel, the code 42003 printed on your...
1       Hi, you still owe UPS $4.10 USD in customs fee...
2       wel01.us/r/rest05 WELLS FARGO(CS):Profile lock...
3       Hi, are you who played golf together last time...
4       (8 Hi Julianne long time no see, I'm Aleen, ho...
                              ...
1086    IRS_TAX_RE-FUND_ID_#01Q F20J091.pdf PDF Docume...
1087                 Hey. Amy when are you picking me up?
1088    Hello dear user Your package has arrived at th...
1089    Hey, it's John here, I'm having a hard time de...
1090    Its Jim! Im trying to deliver your parcel. Ple...
Name: MainText, Length: 1091, dtype: object

In [29]:
sp24_dataset = pd.read_csv('../Dataset/sp24-smishing/phishing_messages.csv', encoding='unicode_escape')
# sp24_dataset = pd.read_csv('../Dataset/sp24-smishing/phishing_campaigns.csv', encoding='unicode_escape')
sp24_dataset = sp24_dataset.dropna()
len(sp24_dataset)

68029

In [30]:
sp24_dataset['message']

0        Join today and enjoy 400% casino bonus, START ...
1        Einzigartiges Angebot- 200% bis zu 100 EUR +50...
2        An up to Â£3 FREEBIE has been dropped onto you...
3        We just missed you today! Schedule a redeliver...
4        In order to avoid any loss to you, please corr...
                               ...
68024    New RHRY L0gin ã www.bitoii.com ã Username...
68025    New RHRY L0gin ã www.bitoii.com ã Username...
68026    sms180217@2-tdbanking.sms.com / Zelle Detected...
68027    sms370017@2-tdbanking.sms.com / Zelle Detected...
68028    \nChronopost : Votre colis est en attente d'in...
Name: message, Length: 68029, dtype: object

In [31]:
ExAIS_dataset = pd.read_csv('../Dataset/ExAIS_SMS Spam Dataset/all_ExAIS_SPAM_Dataset.csv', na_values=["null", "NaN"], keep_default_na=True).fillna("")
ExAIS_dataset.head()

,SMS,Occasion,Target1,Target2,Date,Unknown,Label,Message,Unnamed: 8,Unnamed: 9,...,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,SMS,send,127,127,4/9/2014 8:29,1026,SPAM,CANCLE,,,...,,,,,,,,,,
1,SMS,receive,127,127,4/9/2014 8:25,1026,SPAM,Your plan Smallie.is going to be renewed. Plea...,,,...,,,,,,,,,,
2,SMS,receive,127,127,4/9/2014 8:25,1026,SPAM,Dear Glo subscriber,you just passed 80% of your Plan Validity Per...,,...,,,,,,,,,,
3,SMS,receive,127,127,1/9/2014 14:25,1026,SPAM,Welcome to Smallie. It will expire on 04/09/20...,,,...,,,,,,,,,,
4,SMS,send,127,127,25/08/2014 10:13,1026,SPAM,Info,,,...,,,,,,,,,,

In [32]:
ExAIS_dataset.iloc[:, 7] = ExAIS_dataset.iloc[:, 7:].astype(str).agg(" ".join, axis=1)

ExAIS_dataset = ExAIS_dataset.iloc[:, :8]

# ExAIS_dataset.to_csv('../Dataset/ExAIS_SMS Spam Dataset/cleaned_all_ExAIS_SPAM_Dataset.csv')

ExAIS_dataset.head(10)

,SMS,Occasion,Target1,Target2,Date,Unknown,Label,Message
0,SMS,send,127,127,4/9/2014 8:29,1026,SPAM,CANCLE
1,SMS,receive,127,127,4/9/2014 8:25,1026,SPAM,Your plan Smallie.is going to be renewed. Plea...
2,SMS,receive,127,127,4/9/2014 8:25,1026,SPAM,Dear Glo subscriber you just passed 80% of yo...
3,SMS,receive,127,127,1/9/2014 14:25,1026,SPAM,Welcome to Smallie. It will expire on 04/09/20...
4,SMS,send,127,127,25/08/2014 10:13,1026,SPAM,Info
5,SMS,send,127,127,25/08/2014 07:47,1026,SPAM,1
6,SMS,receive,127,127,25/08/2014 07:38,1026,SPAM,Please send :1 for Day Plans2 for Week Plans...
7,SMS,send,127,127,25/08/2014 07:38,1026,SPAM,ACTIVATE
8,SMS,receive,127,127,25/08/2014 07:37,1026,SPAM,Please send ACTIVATE to 127 for a list of opti...
9,SMS,send,127,127,25/08/2014 07:37,1026,SPAM,PAYYOU

In [33]:
ExAIS_dataset['Label'].value_counts()

Label
HAM     2890
SPAM    2350
Name: count, dtype: int64

In [34]:
spamhunter_dataset = pd.read_csv('../Dataset/SPAM-Hunter_full_dataset_messages.csv', delimiter='abcdexyagh')
spamhunter_dataset.head()

C:\Users\mmia43\AppData\Local\Temp\ipykernel_19880\246060161.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  spamhunter_dataset = pd.read_csv('../Dataset/SPAM-Hunter_full_dataset_messages.csv', delimiter='abcdexyagh')

                                            Messages
0  CASH BUY AND HOLD XXXXX SHARES OF ALPSMOTOR XX...
1  Last X hr Left to Activate your Godaddy XX Off...
2  Pongal Gift 1.Opkt be bill on your card on 11....
3  NSE BSE CASH PREMIUM BUY `` MOHITIND `` 58.75 ...
4  XX SPINS be wait for you when you SignUp at Lu...

In [35]:
print(len(spamhunter_dataset))
print(len(set(spamhunter_dataset['Messages'])))

25826
25295

In [36]:
super_dataset = pd.read_csv('../Dataset/super_sms_dataset.csv', encoding='mac_roman')
super_dataset.head()

                                               SMSes  Labels
0  There be an update for your delivery CC 017281...     1.0
1  watch your favorite english movies of all genr...     1.0
2                     aur what is the status for fms     0.0
3  hi shalini sundi thank you for dialling  speci...     1.0
4                       m tryin to understand too...     0.0

In [37]:
super_dataset['Labels'].value_counts()

Labels
0.0    40830
1.0    26178
Name: count, dtype: int64

In [38]:
len(super_dataset)

67010

In [39]:
40830+26178

67008

In [5]:
def message_stat(s,m):
    m_len = [len(str(i)) for i in m]
    print(s,np.mean(m_len), np.median(m_len), st.mode(m_len), np.std(m_len))

In [41]:
'8.30.'.index('.')

1

In [6]:
def contains_korean(text):
    for char in text:
        if ord(char) >= 0xAC00 and ord(char) <= 0xD7A3:
            return True
    return False

In [20]:
import re


def refine_url(url):

    if '.' not in url:
        return ''
    # Trim invalid leading characters (keep only letters, numbers, or valid schemes)
    trimmed_url = re.sub(r"^[^a-zA-Z0-9]+", "", url)
    
    # Trim invalid trailing characters (must end with a letter, digit, `/`, `?`, `#`, or `=`)
    trimmed_url = re.sub(r"[^a-zA-Z0-9/?#=]+$", "", trimmed_url)

    # # Ensure URL starts correctly (with a scheme or valid domain character)
    # if not re.match(r"^(https?://|ftp://|[a-zA-Z0-9])", trimmed_url):
    #     return ""  # Invalid start, return empty

    return trimmed_url

def further_filter(urll):
    url = list(urll)
    if len(url)<1:
        return ''
    chk = set(',.><-*')
    while url and url[-1] in chk:
        url.pop()
        if len(url)==0:
            break

    if 'http' in urll:
        return ''.join(url[urll.index('http'):])
    if 'www' in urll:
        return ''.join(url[urll.index('www'):])
    else:
        return ''.join(url)

    return urll


def find_first_slash_preceded_by_number(s):
    # Regular expression to find the first instance of a number followed by '/'
    match = re.search(r'\d+/', s)
    
    if match:
        return match.start() + len(match.group()) - 1  # Return the index of '/'
    else:
        return -1  # Return -1 if no match is found

def enron_refine(i):
    priority_tld = ['com','edu','org','net','biz','info','co.uk','co.nz','gov']
    other_tld = ['ru','su','uk','us','ws','ie']
    first = -1
    first = str(i).find('http')
    if first==-1:
        first = str(i).find('www.')
    last = -1
    for j in priority_tld:
        if '.'+str(j) in str(i):
            last = str(i).find(str(j))+len(j)
            break
    if last!=-1:
        return i[first:last]
    else:
        xxx = find_first_slash_preceded_by_number(i)
        if xxx!=-1:
            return i[first:xxx]
    return i

In [ ]:
# if we want to consider multiple URLs ina single website // need to change with the current extracttion code below


# def url_count(s,m):
#     filename = s
#     urls = []
#     url_idx = []
#     s = s.lower()
#     has_url = 0
#     hjbrl = '@,£'
#     for ind,i in enumerate(m):
#         token = str(i).split()
#         flg = 0
#         for idx,j in enumerate(token):

#             if len(j)<4 or any(c.isalpha() for c in j)==False or any(c in hjbrl for c in j):
#                 continue

#             if 'http' in j:
#                 flg =1
#                 if len(j)<9:
#                     urls.append(j+''.join(token[idx+1:idx+15]))
#                 else:
#                     urls.append(j)
                

#             if 'www.' in j:
#                 flg =1
#                 if len(j)<6:
#                     urls.append(j+''.join(token[idx+1:idx+10]))
#                 else:
#                     urls.append(j)

#             elif '.' in j:
#                 n = j.index('.')
#                 x=j.split()

#                 if contains_korean(j):
#                     continue
#                 elif j[0]=='.' or j[1]=='.' or j[-1]=='.' or j[-2]=='.' or any(c.isalnum() for c in j)==False:
#                     continue
                
#                 elif len(x[0])==1 or any(c.isalpha() for c in x[0])==False:
#                     continue
                
#                 # elif j[n+1].isalnum() and j[n-1].isalnum():
#                 #     flg =1
#                     #these are actually not url or incomplete
#                     # urls.append(i)
#         if flg:
#             url_idx.append(ind)
#             has_url+=1
#             flg=0
                    
#     url_list = pd.DataFrame()
#     url_list['URL'] = urls
#     # url_list.to_csv('../Dataset/URL Data/'+filename+'.csv', index=None)
#     print(s,has_url,round(100*has_url/len(m),2))

In [8]:
def any_uppercase(s):
    for char in s:
        if char.isupper():
            return True
    return False

In [9]:
all_tlds = set(pd.read_csv('../Dataset/tld-list-basic.csv')['TLD'].to_list())
all_tlds

{'mh',
 'origins',
 'kddi',
 'nikon',
 'ye',
 'chintai',
 'able',
 'boehringer',
 'mit',
 'bzh',
 'supply',
 'trv',
 'sarl',
 'claims',
 'honda',
 'bharti',
 'horse',
 'gbiz',
 'shaw',
 'doctor',
 'yamaxun',
 'ruhr',
 'sapo',
 'ferrari',
 'airbus',
 'emerck',
 'nz',
 'clothing',
 'voting',
 'nextdirect',
 'bauhaus',
 'credit',
 'onl',
 'bs',
 'meo',
 'contractors',
 'forum',
 'uk',
 'party',
 'tools',
 'gs',
 'express',
 'unicom',
 'sca',
 'fidelity',
 'java',
 'barclaycard',
 'otsuka',
 'aetna',
 'bg',
 'insurance',
 'cbre',
 'builders',
 'sale',
 'toshiba',
 'pnc',
 'supplies',
 'site',
 'art',
 'yt',
 'asia',
 'io',
 'sandvik',
 'mov',
 'joy',
 'cl',
 'dentist',
 'ag',
 'sy',
 'brussels',
 'seek',
 'services',
 'starhub',
 'frogans',
 'iq',
 'nu',
 'secure',
 'mo',
 'sa',
 'ceo',
 'one',
 'viking',
 'cab',
 'is',
 'limited',
 'cam',
 'vanguard',
 'vision',
 'intuit',
 'int',
 'website',
 'info',
 'fox',
 'nadex',
 'bh',
 'cars',
 'uconnect',
 'xihuan',
 'weatherchannel',
 'tn',
 'tj',
 'realtor',
 'ky',
 'saarland',
 'ar',
 'fedex',
 'dental',
 'hamburg',
 'theatre',
 'hughes',
 'enterprises',
 'ist',
 'swiftcover',
 'cg',
 'domains',
 'ch',
 'talk',
 'boots',
 'fast',
 'school',
 'vermögensberater',
 'lt',
 'fish',
 'villas',
 'jcp',
 'kiwi',
 'jm',
 'blackfriday',
 'expert',
 'philips',
 'rw',
 'globo',
 'graphics',
 'rs',
 'sl',
 'gmo',
 'zara',
 'bom',
 'memorial',
 'consulting',
 'skype',
 'an',
 'alfaromeo',
 'shopping',
 'stream',
 'icbc',
 'gi',
 'fm',
 'ipiranga',
 'walter',
 'goldpoint',
 'seat',
 'pohl',
 'ga',
 'estate',
 'aeg',
 'lincoln',
 'case',
 'fujitsu',
 'jewelry',
 'mcd',
 'amex',
 'datsun',
 'np',
 'tirol',
 'energy',
 'citic',
 'baidu',
 'zero',
 'top',
 'careers',
 'vu',
 'beats',
 'uy',
 'su',
 'rwe',
 'hyatt',
 'works',
 'camp',
 'pw',
 'support',
 'kw',
 'schmidt',
 'aigo',
 'afamilycompany',
 'shriram',
 'hoteles',
 'hiphop',
 'show',
 'bestbuy',
 'hisamitsu',
 'creditunion',
 'surgery',
 'windows',
 'rugby',
 'ups',
 'voto',
 'gq',
 'goodyear',
 'nexus',
 'exchange',
 'kpn',
 'kh',
 'hyundai',
 'gb',
 'style',
 'archi',
 'active',
 'money',
 'vistaprint',
 'travelers',
 'gold',
 'merckmsd',
 'tjmaxx',
 'tech',
 'bet',
 'clinique',
 'tips',
 'moto',
 'wales',
 'fr',
 'hot',
 'et',
 'broadway',
 'abogado',
 'axa',
 'hockey',
 'sz',
 'dz',
 'am',
 'bbc',
 'airtel',
 'istanbul',
 'organic',
 'st',
 'nyc',
 'canon',
 'lighting',
 'melbourne',
 'goo',
 'international',
 'srt',
 'ck',
 'holdings',
 'duck',
 'srl',
 'sg',
 'nico',
 'digital',
 'bond',
 'photography',
 'yachts',
 'partners',
 'ggee',
 'zuerich',
 'extraspace',
 'eh',
 'tt',
 'cheap',
 'goodhands',
 'km',
 'mobi',
 'lasalle',
 'ht',
 'nissay',
 'sener',
 'kinder',
 'smart',
 'si',
 'intel',
 'direct',
 'blue',
 'aco',
 'london',
 'stc',
 'beer',
 'next',
 'mcdonalds',
 'jaguar',
 'kim',
 'fire',
 'courses',
 'afl',
 'um',
 'ad',
 'email',
 'town',
 'ricoh',
 'med',
 'company',
 'lease',
 'la',
 'shangrila',
 'country',
 'taxi',
 'audible',
 'telefonica',
 'ma',
 'pid',
 've',
 'repair',
 'ntt',
 'xperia',
 'army',
 'dupont',
 'accountant',
 'jot',
 'network',
 'blanco',
 'beauty',
 'ping',
 'toys',
 'doha',
 'dnp',
 'grainger',
 'chanel',
 'xbox',
 'qvc',
 'yokohama',
 'sex',
 'mutuelle',
 'coffee',
 'sucks',
 'voyage',
 'sling',
 'wang',
 'politie',
 'lk',
 'solar',
 'hotels',
 'restaurant',
 'tw',
 'analytics',
 'ly',
 'symantec',
 'mckinsey',
 'menu',
 'maison',
 'security',
 'gmx',
 'clubmed',
 'church',
 'total',
 'pl',
 'dish',
 'raid',
 'sakura',
 'bosch',
 'mtpc',
 'tmall',
 'tkmaxx',
 'gop',
 'ie',
 'passagens',
 'ceb',
 'ikano',
 'winners',
 'volkswagen',
 'sport',
 'nfl',
 'scb',
 'budapest',
 'investments',
 'sexy',
 'mom',
 'lifeinsurance',
 'lancome',
 'film',
 'sj',
 'baseball',
 'bible',
 'tci',
 'godaddy',
 'camera',
 'crown',
 'promo',
 'fi',
 'final',
 'ua',
 'nc',
 'bn',
 'tiaa',
 'mp',
 'sandvikcoromant',
 'catholic',
 'ng',
 'ws',
 'dtv',
 'kg',
 'meet',
 'de',
 'esq',
 'mobily',
 'bar',
 'markets',
 'by',
 'creditcard',
 'lancia',
 'cw',
 'dog',
 'gent',
 'genting',
 'rehab',
 'bing',
 'vc',
 'tr',
 'alstom',
 'museum',
 'tatamotors',
 'cy',
 'tl',
 'attorney',
 'ninja',
 'flowers',
 'nec',
 'ee',
 'bnl',
 'mango',
 'nr',
 'berlin',
 'land',
 'itv',
 'mitsubishi',
 'buzz',
 'coupons',
 'doosan',
 'lilly',
 'paris',
 'vote',
 'quebec',
 'tienda',
 'americanexpress',
 'cf',
 'boutique',
 'infiniti',
 'kerryhotels',
 'ngo',
 'gift',
 'ladbrokes',
 'eco',
 'scor',
 'drive',
 'abb',
 'eu',
 'wf',
 'firestone',
 'lds',
 'tours',
 'racing',
 'watches',
 'moe',
 'business',
 'buy',
 'ford',
 'rightathome',
 'iwc',
 'locker',
 'zip',
 'cruise',
 'pwc',
 'book',
 'cipriani',
 'lamborghini',
 'club',
 'plus',
 'fujixerox',
 'toyota',
 'android',
 'audio',
 'marketing',
 'va',
 'scjohnson',
 'firmdale',
 'epost',
 'ke',
 'barefoot',
 'osaka',
 'open',
 'guardian',
 'ally',
 'pharmacy',
 'quest',
 'ferrero',
 'men',
 'pro',
 'warman',
 'walmart',
 'mba',
 'netbank',
 'amica',
 'bl',
 'vn',
 'spreadbetting',
 'build',
 'codes',
 'everbank',
 'saxo',
 'science',
 'mn',
 'auspost',
 'boston',
 'tokyo',
 'auto',
 'blog',
 'circle',
 'ru',
 'gallup',
 'bid',
 'virgin',
 'cat',
 'hospital',
 'bt',
 'xerox',
 'rexroth',
 'apartments',
 'at',
 'vana',
 'calvinklein',
 'latino',
 'comsec',
 'lol',
 'bf',
 'airforce',
 'je',
 'cafe',
 'dj',
 'anz',
 'th',
 'gt',
 'commbank',
 'exposed',
 'pub',
 'tunes',
 'schaeffler',
 'design',
 'liaison',
 'juegos',
 'wtc',
 'mm',
 'cu',
 'suzuki',
 'netflix',
 'webcam',
 'coupon',
 'games',
 'bw',
 'sc',
 'yahoo',
 'equipment',
 'off',
 'omega',
 'athleta',
 'al',
 'aero',
 'amazon',
 'chloe',
 'ifm',
 'radio',
 'aarp',
 'wolterskluwer',
 'cool',
 'jll',
 'nowruz',
 'onyourside',
 'wow',
 'trade',
 'uz',
 'kpmg',
 'orientexpress',
 'love',
 'jmp',
 'play',
 'wanggou',
 'host',
 'navy',
 'sk',
 'tk',
 'skin',
 'abudhabi',
 'yun',
 'cologne',
 'vlaanderen',
 'holiday',
 'lpl',
 'kyoto',
 'link',
 'homesense',
 'ong',
 'llc',
 'lexus',
 'how',
 'finance',
 'td',
 'frontdoor',
 'sbs',
 'id',
 'kred',
 'earth',
 'mk',
 'bq',
 'sm',
 'esurance',
 'teva',
 'plumbing',
 'observer',
 'pn',
 'gd',
 'dealer',
 'statefarm',
 'cba',
 'li',
 'softbank',
 'md',
 'aol',
 'app',
 'monster',
 'corsica',
 'edu',
 'joburg',
 'ca',
 'shiksha',
 'giving',
 'toray',
 'na',
 'delta',
 'er',
 'deal',
 'mtr',
 'smile',
 'george',
 'sbi',
 'swatch',
 'you',
 'gp',
 'tz',
 'mq',
 'fan',
 'rmit',
 'ubank',
 'cuisinella',
 'institute',
 'mt',
 'cookingchannel',
 'immo',
 'praxi',
 'cfd',
 'citadel',
 'capetown',
 'dclk',
 'florist',
 'sew',
 'ge',
 'hm',
 'visa',
 'eg',
 'football',
 'safety',
 'to',
 'ps',
 'dating',
 'channel',
 'rogers',
 'lancaster',
 'kfh',
 'abbott',
 'aig',
 'sony',
 'bloomberg',
 'bms',
 'cm',
 'gg',
 'piaget',
 'booking',
 'salon',
 'makeup',
 'iinet',
 'mf',
 'net',
 'mobile',
 'mz',
 'cd',
 'fitness',
 'pccw',
 'helsinki',
 'dell',
 'ms',
 'audi',
 'farm',
 'desi',
 'fly',
 'shia',
 'rip',
 'phd',
 'bananarepublic',
 'zone',
 'statoil',
 'data',
 'poker',
 'cr',
 'space',
 'bostik',
 'realestate',
 'statebank',
 'trust',
 'xyz',
 'bingo',
 'gm',
 'cruises',
 'spiegel',
 'as',
 'kerryproperties',
 'flights',
 'house',
 'tm',
 'epson',
 'homedepot',
 'law',
 'gu',
 'computer',
 'food',
 'band',
 'lixil',
 'target',
 'redstone',
 'kn',
 'so',
 'chrome',
 'ml',
 'kerrylogistics',
 'cymru',
 'study',
 'kitchen',
 'wiki',
 'man',
 'store',
 'world',
 'olayan',
 'live',
 'pm',
 'shoes',
 'pictet',
 'tatar',
 'yodobashi',
 'capitalone',
 'got',
 'wme',
 'chrysler',
 'prudential',
 'nagoya',
 'eurovision',
 'ril',
 'kids',
 'actor',
 'press',
 'playstation',
 'jlc',
 'ovh',
 'healthcare',
 'ac',
 'sanofi',
 'diamonds',
 'ec',
 'fiat',
 'limo',
 'discount',
 'sx',
 'tiffany',
 'maserati',
 'org',
 'video',
 'amsterdam',
 'dubai',
 'iveco',
 'forsale',
 'luxury',
 'vi',
 'au',
 'aq',
 'deals',
 'chat',
 'vodka',
 'vuelos',
 'itau',
 'win',
 'zm',
 'cz',
 'jo',
 'accenture',
 'pramerica',
 'glass',
 'panerai',
 'duns',
 'prod',
 'pay',
 'post',
 'etisalat',
 'co',
 'vacations',
 'black',
 'mr',
 'chase',
 'comcast',
 'dev',
 'cyou',
 'kr',
 'software',
 'shell',
 'cartier',
 'az',
 'social',
 'schule',
 'blockbuster',
 'dk',
 'golf',
 'hr',
 'lotto',
 'ph',
 'lawyer',
 'versicherung',
 'casino',
 'boats',
 'reisen',
 'jnj',
 'autos',
 'tv',
 'allstate',
 'fido',
 'gallery',
 'vermögensberatung',
 'jobs',
 'pizza',
 'pink',
 'richardli',
 'online',
 'tdk',
 'abbvie',
 'zw',
 'ne',
 'dad',
 'hiv',
 'bcn',
 'university',
 'monash',
 'sb',
 'orange',
 'recipes',
 'gmbh',
 'management',
 'jpmorgan',
 'select',
 'travelersinsurance',
 'crs',
 'boo',
 'avianca',
 'tushu',
 'room',
 'feedback',
 'samsung',
 'mu',
 'clinic',
 'rsvp',
 'office',
 'cbs',
 'cricket',
 'cooking',
 'industries',
 'center',
 'bio',
 'cc',
 're',
 'ice',
 'lc',
 'xfinity',
 'jetzt',
 'community',
 'sohu',
 'mortgage',
 'nl',
 'glade',
 'gucci',
 'tickets',
 'aw',
 'mg',
 'mopar',
 'tjx',
 'photos',
 'fit',
 'car',
 'like',
 'rest',
 'marshalls',
 'family',
 'studio',
 'hdfcbank',
 'watch',
 'ventures',
 'hair',
 'coach',
 'catering',
 'accountants',
 'parts',
 'arab',
 'stockholm',
 'ollo',
 'life',
 'movie',
 'tf',
 'us',
 'tc',
 'gh',
 'ss',
 'christmas',
 'il',
 'thd',
 'gy',
 'in',
 'locus',
 'bike',
 'properties',
 'gw',
 'uno',
 'fresenius',
 'nowtv',
 'box',
 'help',
 'travelchannel',
 'gea',
 'mlb',
 'sina',
 'bofa',
 'moda',
 'scot',
 'northwesternmutual',
 'wtf',
 'bo',
 'photo',
 'gap',
 'americanfamily',
 'mw',
 'gripe',
 'nab',
 'ba',
 'pictures',
 'bridgestone',
 'bj',
 'af',
 'lifestyle',
 'caravan',
 'ski',
 'mtn',
 'dm',
 'review',
 'ki',
 'news',
 'akdn',
 'oldnavy',
 'youtube',
 'farmers',
 'prof',
 'tab',
 'it',
 'msd',
 'storage',
 'jp',
 'newholland',
 'metlife',
 'academy',
 'mv',
 'garden',
 'ae',
 'gal',
 'reviews',
 'tattoo',
 'prime',
 'flsmidth',
 'htc',
 'cpa',
 'fairwinds',
 'weather',
 'cal',
 'hn',
 'vin',
 'kosher',
 'fun',
 'delivery',
 'nf',
 'dot',
 'ibm',
 'career',
 'lotte',
 'mint',
 'flickr',
 'ls',
 'mma',
 'cx',
 'viva',
 'mls',
 'showtime',
 'tube',
 'game',
 ...}

In [25]:
def url_count(s,m):
    filename = s
    urls = []
    url_idx = []
    s = s.lower()
    has_url = 0
    hjbrl = '@,£'
    for ind,i in enumerate(m):
        token = str(i).split()
        flg = 0
        xkjk = ''
        for idx,j in enumerate(token):


            if len(j)<4 or any(c.isalpha() for c in j)==False or any(c in hjbrl for c in j):
                continue


            if 'http' in j:
                flg =1
                if len(j)<=9:
                    xkjk = j+''.join(token[idx+1:idx+min(len(token)-idx+1,15)])
                else:
                    xkjk = j
                break
               


            elif 'www.' in j:
                flg =1
                if len(j)<=6:
                    xkjk = j+''.join(token[idx+1:min(len(token)-idx+1,15)])
                else:
                    xkjk = j
                break


            elif '.' in j:
                n = j.index('.')
                x=j.split()


                if contains_korean(j):
                    continue
                elif j[0]=='.' or j[1]=='.' or j[-1]=='.' or j[-2]=='.':
                    continue
               
                elif len(x[0])==1 or len(x[-1])==1:
                    continue

                elif x[-1] not in all_tlds:
                    continue
               
                # this following logic is problematic
                # specially for the NUS dataset because i.love this will be considered as a url
                elif j[n+1].isalpha() and j[n-1].isalnum():
                    flg = 1
                    xkjk = j


        if flg or xkjk:
            url_idx.append(ind)
            has_url+=1
            flg=0

        if len(xkjk)>0:
            urls.append(xkjk)
                   
    url_list = pd.DataFrame()
    urls = [further_filter(i) for i in urls]
    urls = [refine_url(i) for i in urls]
    # if enron_flag==False:
    #     urls = [further_filter(i) for i in urls]
    #     urls = [refine_url(i) for i in urls]
    # else:
    #     urls = [enron_refine(i) for i in urls]
    #     urls = [further_filter(i) for i in urls]
    #     urls = [refine_url(i) for i in urls]
    url_list['URL'] = urls
    url_list.to_csv('../Dataset/URL Data/'+filename+'.csv', index=None)
    print(s,len(urls)-urls.count(''),round(100*(len(urls)-urls.count(''))/len(m),2))

In [67]:
def phone_number_count(s,m):
    filename = s
    phone_numbers = []
    has_phn_number = 0
    for i in m:
        token = str(i).split()
        for j in token:
            if j.isnumeric() and len(j)>14:
                continue
            if j.isnumeric() and len(str(j))>7:
                has_phn_number += 1
                phone_numbers.append(j)
                # print(j)
            elif j[0]=='+' and j[1:].isnumeric() and len(str(j))>7:
                has_phn_number += 1
                phone_numbers.append(j)
                # print(j)
    
    Phone_list = pd.DataFrame()
    Phone_list['Phone Number'] = phone_numbers
    Phone_list.to_csv('../Dataset/Phone Data/'+filename+'.csv', index=None)
    print(s,has_phn_number,round(100*has_phn_number/len(m),2))

In [68]:
import re

def email_count(s,m):
    filename = s
    emails = []
    has_email = 0
    for i in m:
        token = str(i).split()
        for idx,j in enumerate(token):
            if ('@' in j and '.' in j and '/' not in j and (j[0]!='@' or j[-1]!='@')) :
                has_email += 1
                if len(j)<7:
                    emails.append(''.join(token[idx-7:idx-1])+j+''.join(token[idx+1:idx+8]))
                
                else:
                    emails.append(j)
                
                break
                # print(j)

    Email_list = pd.DataFrame()
    Email_list['Email'] = emails
    Email_list.to_csv('../Dataset/Email Data/'+filename+'.csv', index=None)
    print(s,has_email,round(100*has_email/len(m),2))

In [ ]:
email = "my.ownsite@our-earth.org"
valid = re.match(r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$', email)

print("Valid email address." if valid else "Invalid email address.")

Valid email address.

In [ ]:
# # print('------------------------------------------------ Full Dataset -------------------------------------------\n')
# print(len(british_ham+british_spam))
# print(len(singapore_dataset_all_mesages))
# print(len(UCI_dataset_ham+UCI_dataset_spam))
# print(len(mendeley_dataset))
# print(len(smishtank_dataset['MainText']))
# print(len(sp24_dataset))
# print(len(enron_dataset['ham']+enron_dataset['spam']))
# print(len(kor_smishing['content']))
# print(len(ExAIS_dataset))
# print(len(spamhunter_dataset))
# print(len(super_dataset))
# print(len(ban_spam))

875
55835
5574
5971
1091
68029
33715
43209
5240
25826
67010

In [42]:
print(len(ban_spam))
print(len(rev_india))

2602
4567

In [ ]:
list(mendeley_dataset[mendeley_dataset['LABEL']=='spam']['TEXT']) + list(mendeley_dataset[mendeley_dataset['LABEL']=='Spam']['TEXT'])

['lyricalladie(21/F) is inviting you to be her friend. Reply YES-910 or NO-910. See her: www.SMS.ac/u/hmmross STOP? Send STOP FRND to 62468',
 "Hello from Orange. For 1 month's free access to games, news and sport, plus 10 free texts and 20 photo messages, reply YES. Terms apply: www.orange.co.uk/ow",
 'New Offer! Save upto 40\\% electricity bill with Power Saver(GOVT. LAB TESTED), Rs. 1050/-(free home delivery) 3 Yr. Guarantee Call 9891943823,9891943780',
 'You will recieve your tone within the next 24hrs. For Terms and conditions please see Channel U Teletext Pg 750',
 'Overcome programming challenges for multicore and learn the techniques to scale reliability. Attend Intel session at 3.45 PM at Microsoft Community TechDays',
 '\t5 Free Top Polyphonic Tones call 087018728737, National Rate. Get a toppoly tune sent every week, just text SUBPOLY to 81618, £3 per pole. UnSub 08718727870.',
 'Noida Commercial Wave Sec-18  Silver @ 11500/- PSF  Gold @ 12500/- PSF,  Logix Sec-124 @ 8200/- PSF For Best Deal Call 9711131802 /3',
 'HMV BONUS SPECIAL 500 pounds of genuine HMV vouchers to be won. Just answer 4 easy questions. Send HMV to 86688 More info:www.100percent-real.com',
 'Welcome to UK-mobile-date this msg is FREE giving you free calling to 08719839835. Future mgs billed at 150p daily. To cancel send "go stop" to 89123',
 'ASKED 3MOBILE IF 0870 CHATLINES INCLU IN FREE MINS. INDIA CUST SERVs SED YES. L8ER GOT MEGA BILL. 3 DONT GIV A SHIT. BAILIFF DUE IN DAYS. I O £250 3 WANT £800',
 "RCT' THNQ Adrian for U text. Rgds Vatian",
 'Ever thought about living a good life with a perfect partner? Just txt back NAME and AGE to join the mobile community. (100p/SMS)',
 '0A$NETWORKS allow companies to bill for SMS, so they are responsible for their "suppliers", just as a shop has to give a guarantee on what they sell. B. G.',
 'oor Step Service for Passport Assistance/PAN Card/Income Tax Return/VAT Return/Service Tax Return Contact M/s ONS 9650669988 Jwala Heri Mkt Paschim Viha',
 'FreeMsg Hey U, i just got 1 of these video/pic fones, reply WILD to this txt & ill send U my pics, hurry up Im so bored at work xxx (18 150p/rcvd STOP2stop)',
 'Text82228>> Get more ringtones, logos and games from www.txt82228.com. Questions: info@txt82228.co.uk',
 '87077: Kick off a new season with 2wks FREE goals & news to ur mobile! Txt ur club name to 87077 eg VILLA to 87077',
 "I don't know u and u don't know me. Send CHAT to 86688 now and let's find each other! Only 150p/Msg rcvd. HG/Suite342/2Lands/Row/W1J6HL LDN. 18 years or over.",
 'Plots available at greater noida near pari chowk, regn ok. @ 2600/-per gauge.booking  starts with 30000/-onwards or full down.instalments also.call 9213241451.',
 'Gr8 Poly tones 4 ALL mobs direct 2u rply with POLY TITLE to 8007 eg POLY BREATHE1 Titles: CRAZYIN, SLEEPINGWITH, FINEST, YMCA :getzed.co.uk POBox365O4W45WQ 300p',
 "Dear 0776xxxxxxx U've been invited to XCHAT. This is our final attempt to contact u! Txt CHAT to 86688 150p/MsgrcvdHG/Suite342/2Lands/Row/W1J6HL LDN 18yrs",
 'We tried to contact you re your reply to our offer of a Video Phone 750 anytime any network mins Half Price Line Rental Camcorder Reply or call 08000930705',
 'Do you want a new Video handset? 750 any time any network mins? UNLIMITED TEXT? Camcorder? Reply or Call now 08000930705 for del Sat AM',
 'Get your garden ready for summer with a FREE selection of summer bulbs and seeds worth £33:50 only with The Scotsman this Saturday. To stop go2 notxt.co.uk',
 'Thanks 4 your continued support Your question this week will enter u in2 our draw 4 £100 cash. Name the NEW US President? txt ans to 80082',
 'You are now unsubscribed all services. Get tons of sexy babes or hunks straight to your phone! go to http://gotbabes.co.uk. No subscriptions.',
 'FreeMsg>FAV XMAS TONES!Reply REAL',
 'Do you want a New Nokia 3510i colour phone DeliveredTomorrow? With 300 free minutes to any mobile + 100 free texts  call 08000930705',
 'Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question call  08452810075',
 "For ur chance to win a £250 wkly shopping spree TXT: SHOP to 80878. T's&C's www.txt-2-shop.com",
 'price revising soon for urbtech xaviers fully loaded tallest tower in noida few units left for more details call 9891205199',
 'pdate_Now - Double mins and 1000 txts on Orange tariffs. Latest Motorola, SonyEricsson & Nokia & Bluetooth FREE! Call MobileUpd8 on 08000839402 or call2optout/!YHL',
 'The current leading bid is 151. To pause this auction send OUT. Customer Care: 08718726270',
 'Want to funk up ur fone with a weekly new tone reply TONES2U 2 this text. www.ringtones.co.uk, the original n best. Tones 3GBP network operator rates apply',
 "LookAtMe!: Thanks for your purchase of a video clip from LookAtMe!, you've been charged 35p. Think you can do better? Why not send a video in a MMSto 32323.",
 'XXXMobileMovieClub: To use your credit, click the WAP link in the next txt message or click here>> http://wap. xxxmobilemovieclub.com?n=QJKGIGHJJGCBL',
 'January Male Sale! Hot Gay chat now cheaper, call 08709222922. National rate from 1.5p/min cheap to 7.8p/min peak! To stop texts call 08712460324 (10p/min)',
 'HOT LIVE FANTASIES call now 08707509020 Just 20p per min NTT Ltd, PO Box 1327 Croydon CR9 5WB 0870..k',
 'England v Macedonia - dont miss the goals/team news. Txt ur national team to 87077 eg ENGLAND to 87077 Try:WALES, SCOTLAND 4txt/ú1.20 POBOXox36504W45WQ 16+',
 'Update for FREE to Oranges latest colour camera mobiles & unlimited weekend calls. Call 08718738034',
 'Call Germany for only 1 pence per minute! Call from a fixed line via access number 0844 861 85 86.',
 'We know someone who you know that fancies you. Call 09058097218 to find out who. POBox 6, LS15HB 150p',
 "I don't know u and u don't know me. Send CHAT to 86688 now and let's find each other! Only 150p/Msg rcvd.",
 'Free Msg: get Gnarls Barkleys "Crazy" ringtone TOTALLY FREE just reply GO to this message right now!',
 "Ur balance is now £500. Ur next question is: Who sang 'Uptown Girl' in the 80's ? 2 answer txt ur ANSWER to 83600. Good luck!",
 'Free Msg: Ringtone!From: http://tms. widelive.com/index. wml?id=1b6a5ecef91ff9*37819&first=true18:0430-JUL-05',
 'Hottest pics straight to your phone!! See me getting and Wanting, just for you xx Text PICS to 89555 now! txt costs 150p textoperator g696ga 18 XxX',
 'Sunshine Quiz Wkly Q! Win a top Sony DVD player if u know which country the Algarve is in? Txt ansr to 82277.',
 'Free tones Hope you enjoyed your new content. text stop to 61610 to unsubscribe. help:08712400602450p Provided by tones2you.co.uk',
 'Wan2 win a Meet+Greet with Westlife 4 U or a m8? They are currently on what tour? 1)Unbreakable, 2)Untamed, 3)Unkempt. Text 1,2 or 3 to 83049. ',
 'TheMob> Check out our newest selection of content, Games, Tones, Gossip, babes and sport, Keep your mobile fit and funky text WAP to 82468',
 'Now Get*SAUNA SLIM BELT(Rs650)&VIBRATION+SAUNA BELT(Rs999)NCR(Rs50 Extra)LoseFAT(5 inch)+FreeSLIM.TEA PH:9311304872/9268250573',
 "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",
 "Join the UK's horniest Dogging service and u can have sex 2nite!. Just sign up and follow the instructions. Txt ENTRY to 69888 now! Nyt.EC2A.3LP.msg@150p",
 'FREE RING TONE just text "POLYS" to 87131. Then every week get a new tone. 0870737910216yrs only £1.50/wk.',
 'Hi babe its Jordan, how r u? Im home from abroad and lonely, text me back if u wanna chat xxSP visionsms.com Text stop to stopCost 150p 08712400603',
 "Do you ever notice that when you're driving, anyone going slower than you is an idiot and everyone driving faster than you is a maniac?",
 '\thttp//tms. widelive.com/index. wml?id=820554ad0a1705572711&first=true¡C C Ringtone¡',
 'Sunshine Quiz Wkly Q! Win a top Sony DVD player if u know which country Liverpool played in mid week? Txt ansr to 82277. £1.50 SP:Tyrone',
 "For ur chance to win a £250 cash every wk TXT: ACTION to 80608. T's&C's www.movietrivia.tv custcare 08712405022, 1x150p/wk.",
 'Free video camera phones with Half Price line rental for 12 mths and 500 cross ntwk mins 100 txts. Call MobileUpd8 08001950382',
 'Thanks for your ringtone order, reference number X49.Your mobile will be charged 4.50. Should your tone not arrive please call customer services 09065989182',
 'Swayamvara By David Hair,�Swayamvara� (The Return of Ravana Book 2) by David Hair is a story of reincarnation, two swayamvaras, 800 years apart, that sees four lives knotted forever & one rigid force, Ravana reborn.',
 'From next month get upto 50% More Calls 4 Ur standard network charge 2 activate Call 9061100010 C Wire3.net 1st4Terms PoBox84 M26 3UZ Cost £1.50 min MobcudB more',
 'Get 3 Lions England tone, reply lionm 4 mono or lionp 4 poly. 4 more go 2 www.ringtones.co.uk, the original n best. Tones 3GBP network operator rates apply.',
 'Well done ENGLAND! Get the official poly ringtone or colour flag on yer mobile! text TONE or FLAG to 84199 NOW! Opt-out txt ENG STOP. Box39822 W111WX £1.50',
 'ringtoneking 84484',
 'New Tones This week include: 1)McFly-All Ab.., 2) Sara Jorge-Shock.. 3) Will Smith-Switch.. To order follow instructions on next message',
 'Call Germany for only 1 pence per minute! Call from a fixed line via access number 0844 861 85 85. No prepayment. Direct access! www.telediscount.co.uk',
 'Kit Strip - you have been billed 150p. Netcollex Ltd. PO Box 1013 IG11 OJA',
 'Your free ringtone is waiting to be collected. Simply text the password "MIX" to 85069 to verify. Get Usher and Britney. ',
 'Free Top ringtone -sub to weekly ringtone-get 1st week free-send SUBPOLY to 81618-?3 per week-stop sms-08718727870',
 'This message is free. Welcome to the new & improved Sex & Dogging club! To unsubscribe from this service reply STOP. msgs@150p 18+only',
 '\tFree Top ringtone -sub to weekly ringtone-get 1st week free-send SUBPOLY to 81618-?3 per week-stop sms-08718727870',
 'U were outbid by simonwatson5120 on the Shinco DVD Plyr. 2 bid again, visit sms. ac/smsrewards 2 end bid notifications, reply END OUT',
 'Had your mobile 11mths+? You are entitled to update to the latest colour camera mobile for Free! Call The Mobile Update Co FREE on 08002986907',
 'Double mins and txts 4 6monthsAvailable on Sony, Nokia Motorola phones. Call MobileUpd8 on 08000839403 or call2optout/N9DX',
 "Xmas & New Years Eve tickets are now on sale from the club, during the day from 10am till 8pm, and on Thurs, Fri & Sat night this week. They're selling fast!",
 'Navratra Special Launching 9th oct. CHD presnts Phase-3 of Avenue71,  Shona Road,  Gurgaon *@Rs.4150/- Lease Rs.400/- as Inaugural discount Sms ICD to 54999',
 'Fantasy Football is back on your TV. Go to Sky Gamestar on Sky Active and play £250k Dream Team. Scoring starts on Saturday, so register now!SKY OPT OUT to 88088',
 'Will u meet ur dream partner soon? Is ur career off 2 a flyng start? 2 find out free, txt HORO followed by ur star sign, e. g. HORO ARIES',
 'Free 1st week entry 2 TEXTPOD 4 a chance 2 win 40GB iPod or £250 cash every wk. Txt POD to 84128 Ts&Cs www.textpod.net',
 'SMS. ac Blind Date 4U!: Rodds1 is 21/m from Aberdeen, United Kingdom. Check Him out http://img. sms. ac/W/icmb3cktz8r7!-4 no Blind Dates send HIDE',
 'Ur HMV Quiz cash-balance is currently £500 - to maximize ur cash-in now send HMV1 to 86688 only 150p/msg',
 'Do you want 750 anytime any network mins 150 text and a NEW VIDEO phone for only five pounds per week call 08002888812 or reply for delivery tomorrow',
 'SPJanuary Male Sale! Hot Gay chat now cheaper, call 08709222922. National rate from 1.5p/min cheap to 7.8p/min peak! To stop texts call 08712460324 (10p/min)',
 'Sppok up ur mob with a Halloween collection of nokia logo&pic message plus a FREE eerie tone, txt CARD SPOOK to 8007',
 'Eerie Nokia tones 4u, rply TONE TITLE to 8007 eg TONE DRACULA to 8007 www.getzed.co.uk POBox36504W45WQ 150p',
 "You won't believe it but it's true. It's Incredible Txts! Reply G now to learn truly amazing things that will blow your mind. From O2FWD only 18p/txt",
 "I'd like to tell you my deepest darkest fantasies. Call me 09094646631 just 60p/min. To stop texts call 08712460324 (nat rate)",
 'Save money on wedding lingerie at www.bridal.petticoatdreams.co.uk Choose from a superb selection with national delivery. Brought to you by WeddingFriend',
 'Burger King - Wanna play footy at a top stadium? Get 2 Burger King before 1st Sept and go Large or Super with Coca-Cola and walk out a winner',
 'Ur cash-balance is currently 500 pounds - to maximize ur cash-in now send GO to 86688 only 150p/meg. CC: 08718720201',
 'Get 3 Lions England tone, reply lionm 4 mono or lionp 4 poly. 4 more go 2 www.ringtones.co.uk, the original n best. ',
 'For sale - arsenal dartboard. Good condition but no doubles or trebles!',
 'Double Mins & 1000 txts on Orange tariffs. Latest Motorola, SonyEricsson & Nokia with Bluetooth FREE! Call MobileUpd8 on 08000839402 or call2optout/HF8',
 'December only! You are entitled to update to the latest colour camera mobile for Free! Call The Mobile Update Co FREE on 08002986906',
 "FREE2DAY sexy St George's Day pic of Jordan!Txt PIC to 89080 dont miss out, then every wk a saucy celeb!4 more pics c PocketBabe.co.uk 0870241182716 £3/wk",
 'With airtel 3G watch over 90 TV channels across Entertainment, Sports, Music, News on your phone- http://apalyaps15.com/tv/TV.jsp .To activate 3G, SMS 3G to 121',
 'FREE entry into our £250 weekly comp just send the word ENTER to 84128 NOW. 18 T&C www.textcomp.com cust care 08712405020.',
 'sports fans - get the latest sports news str* 2 ur mobile 1 wk FREE PLUS a FREE TONE Txt SPORT ON to 8007 www.getzed.co.uk 0870141701216+ norm 4txt/120p',
 "GSOH? Good with the ladies?U could b a male gigolo? 2 join the uk's fastest growing mens club reply ONCALL. mjzgroup. 08714342399.2stop reply STOP. msg@£1.50rcvd",
 'FREE entry into our £250 weekly comp just send the word WIN to 80086 NOW. 18 T&C www.txttowin.co.uk',
 'Moby Pub Quiz.Win a £200 High Street prize if u know who the new Duchess of Cornwall will be? Txt her first name to 82277.',
 '\tThanks for your ringtone order, reference number X49. Your mobile will be charged 4.50. Should your tone not arrive please call customer services 09065989182. From: [colour=red]text[/colour]TXTstar',
 'Reply to win £100 weekly! Where will the 2006 FIFA World Cup be held? Send STOP to 87239 to end service',
 'Call 09094100151 to use ur mins! Calls cast 10p/min (mob vary). Service provided by AOM, just GBP5/month. AOM Box61,M60 1ER until u stop. Ages 18+ only!',
 '(Bank of Granite issues Strong-Buy) EXPLOSIVE PICK FOR OUR MEMBERS *****UP OVER 300% *********** Nasdaq Symbol CDGT That is a $5.00 per..',
 '8007 FREE for 1st week! No1 Nokia tone 4 ur mob every week just txt NOKIA to 8007 Get txting and tell ur mates www.getzed.co.uk POBox 36504 W4 5WQ norm 150p/tone 16+',
 'u r subscribed 2 TEXTCOMP 250 wkly comp. 1st wk?s free question follows, subsequent wks charged@150p/msg.2 unsubscribe txt STOP 2 84128,custcare 08712405020',
 'YES! The only place in town to meet exciting adult singles is now in the UK. Txt CHAT to 86688 now! 150p/Msg.',
 'Spook up your mob with a Halloween collection of a logo & pic message plus a free eerie tone, txt CARD SPOOK to 8007 zed 08701417012150p per logo/pic ',
 'Adult 18 Content Your video will be with you shortly',
 'New TEXTBUDDY Chat 2  guys in ur area 4 just 25p Free 2 receive Search postcode or at gaytextbuddy.com. TXT ONE name to 89693',
 'TheMob>Hit the link to get a premium Pink Panther game, the new no. 1 from Sugababes, a crazy Zebra animation or a badass Hoody wallpaper-all 4 FREE!',
 'Monthly password for wap. mobsi.com is 391784. Use your wap phone not PC.',
 'EASTENDERS TV Quiz. What FLOWER does DOT compare herself to? D= VIOLET E= TULIP F= LILY txt D E or F to 84025 NOW 4 chance 2 WIN £100 Cash WKENT/150P16+',
 'SIX chances to win CASH! From 100 to 20,000 pounds txt> CSH11 and send to 87575. Cost 150p/day, 6days, 16+ TsandCs apply Reply HL 4 info',
 "25p 4 alfie Moon's Children in need song on ur mob. Tell ur m8s. Txt Tone charity to 8007 for Nokias or Poly charity for polys: zed 08701417012 profit 2 charity.",
 'Tone Club: Your subs has now expired 2 re-sub reply MONOC 4 monos or POLYC 4 polys 1 weekly @ 150p per week Txt STOP 2 stop This msg free Stream 0871212025016',
 'Double your mins & txts on Orange or 1/2 price linerental - Motorola and SonyEricsson with B/Tooth FREE-Nokia FREE Call MobileUpd8 on 08000839402 or2optout/HV9D',
 'Reduce Upto 6 Kgs in 30 Days with *ORIGINAL SAUNA SLIM BELT* MRP 1499 Com Direct Price 750 Book today & Get Acupressure Mat Free! For Booking Sms: SLIM to 57333',
 'You can stop further club tones by replying "STOP MIX" See my-tone.com/enjoy. html for terms. Club tones cost GBP4.50/week. MFL, PO Box 1146 MK45 2WT (2/3)',
 'Hungry gay guys feeling hungry and up 4 it, now. Call 08718730555 just 10p/min. To stop texts call 08712460324 (10p/min)',
 'SplashMobile: Choose from 1000s of gr8 tones each wk! This is a subscrition service with weekly tones costing 300p. U have one credit - kick back and ENJOY',
 'HMV BONUS SPECIAL 500 pounds of genuine HMV vouchers to be won.  Play Now! Send HMV to 86688 More info:www.100percent-real.com',
 'SMS SERVICES For your inclusive text credits pls gotto www.comuk.net login 3qxj9 unsubscribe with STOP no extra charge help 08702840625 comuk.220cm2 9AE',
 'wamma get laid?want real doggin locations sent direct to your mobile? join the UKs largest dogging network. txt dogs to 69696 now!nyt. ec2a. 3lp £1.50/msg.',
 'Goal! Arsenal 4 (Henry, 7 v Liverpool 2 Henry scores with a simple shot from 6 yards from a pass by Bergkamp to give Arsenal a 2 goal margin after 78 mins.',
 'moneycontrol.com now on your BlackBerry! Get stock quotes,  track your portfolio,  watch LIVE TV & more.Get the FREE app at http://m.moneycontrol.com/MoM',
 'Free Top ringtone -sub to weekly ringtone-send SUBPOLY to 81618-?3 per week-stop sms-08718727870',
 'New TEXTBUDDY Chat 2  guys in ur area 4 just 25p Free 2 receive Search postcode or at gaytextbuddy.com. TXT ONE name to 89693. 08715500022 rpl Stop 2 cnl',
 'Email AlertFrom: Jeri StewartSize: 2KBSubject: Low-cost prescripiton drvgsTo listen to email call 123',
 'Warner Village 83118 C Colin Farrell in SWAT this wkend @Warner Village & get 1 free med. Popcorn!Just show msg+ticket@kiosk.Valid 4-7/12. C t&c @kiosk. Reply SONY 4 mre film offers',
 'cmon babe,  Txt me your fantasy now babe -) need you now. All replies cost £1.50. 2 cancel send STOP',
 'U are subscribed to the best Mobile Content Service in the UK for £3 per 10 days Helpline 08706091795',
 'Hi there, 2nights ur lucky night! Uve been invited 2 XCHAT, the Uks wildest chat! Txt CHAT to 86688 now! 150p/MsgrcvdHG/Suite342/2Lands/Row/W1J6HL LDN 18yrs',
 'No 1 POLYPHONIC tone 4 ur mob every week! Just txt PT2 to 87575. 1st Tone FREE ! so get txtin now and tell ur friends. 150p/tone. 16 reply HL 4info',
 "8007 25p 4 Alfie Moon's Children in Need song on ur mob. Tell ur m8s. Txt TONE CHARITY to 8007 for nokias or POLY CHARITY for polys :zed 08701417012 profit 2 charity",
 'it to 80488. Your 500 free text messages are valid until 31 December 2005.',
 'SMS. ac sun0819 posts HELLO:"You seem cool, wanted to say hi. HI!!!" Stop? Send STOP to 62468',
 'Rental  Helpline  9999991155 1000-100, 000 sq.ft. In Noida & Gr.Noida  OFFICE & INDUSTRIAL Use Goldenberg estates pvt.ltd. sandeep@goldenberg.in 999 999 1155',
 'Ur cash-balance is currently 500 pounds - to maximize ur cash-in now send GO to 86688 only 150p/msg. CC 08718720201 HG/Suite342/2Lands Row/W1J6HL',
 '\tText82228>> Get more ringtones, logos and games from www.txt82228.com. Questions: info@txt82228.co.uk',
 'You have an important customer service announcement from PREMIER.',

In [50]:
message_stat('bangla_spam', ban_spam['text'])
message_stat('bangla_spam_ham', ban_spam[ban_spam['type']=='ham']['text'])
message_stat('bangla_spam_spam', ban_spam[ban_spam['type']=='spam']['text'])

bangla_spam 90.99807840122982 70.0 ModeResult(mode=array([130]), count=array([85])) 85.50738152077625
bangla_spam_ham 100.38865721434529 93.0 ModeResult(mode=array([130]), count=array([78])) 81.64283208876734
bangla_spam_spam 82.97291518175338 68.0 ModeResult(mode=array([70]), count=array([73])) 87.88506137782119

/tmp/ipykernel_276050/722172428.py:3: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print(s,np.mean(m_len), np.median(m_len), st.mode(m_len), np.std(m_len))

In [62]:
message_stat('bangla_barta', ban_barta['text'])
message_stat('bangla_barta_ham', ban_barta[(ban_barta['label']=='promo') | (ban_barta['label']=='normal')]['text'])
message_stat('bangla_barta_spam', ban_barta[ban_barta['label']=='smish']['text'])

bangla_barta 75.3102453102453 67.0 ModeResult(mode=array([70]), count=array([169])) 59.14814718101521
bangla_barta_ham 55.59145021645022 51.0 ModeResult(mode=array([70]), count=array([157])) 38.25559507584255
bangla_barta_spam 114.7478354978355 96.0 ModeResult(mode=array([69]), count=array([25])) 72.35705602027346

/tmp/ipykernel_276050/722172428.py:3: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print(s,np.mean(m_len), np.median(m_len), st.mode(m_len), np.std(m_len))

In [51]:
message_stat('revised_indian', rev_india['msg'])
message_stat('revised_indian_ham', rev_india[rev_india['label']=='ham']['msg'])
message_stat('revised_indian_spam', rev_india[rev_india['label']=='spam']['msg'])

revised_indian 140.64221589664987 139.0 ModeResult(mode=array([160]), count=array([189])) 82.87180602606213
revised_indian_ham 140.86084624553038 132.0 ModeResult(mode=array([160]), count=array([100])) 93.26275889986965
revised_indian_spam 140.03633360858794 146.0 ModeResult(mode=array([160]), count=array([89])) 42.370435929936264

/tmp/ipykernel_276050/722172428.py:3: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print(s,np.mean(m_len), np.median(m_len), st.mode(m_len), np.std(m_len))

In [ ]:
# #message length stat
# print('------------------------------------------------ Full Dataset -------------------------------------------\n')
# message_stat("British Dataset",british_ham+british_spam)
# message_stat("NUS Dataset",singapore_dataset_all_mesages)
# message_stat("UCI Dataset",UCI_dataset_ham+UCI_dataset_spam)
# message_stat("Mendeley Dataset",mendeley_dataset['TEXT'])
# message_stat("Smishtank Dataset",smishtank_dataset['MainText'])
# message_stat("sp24 Dataset",sp24_dataset['message'])
# message_stat("Enron Dataset",enron_dataset['ham']+enron_dataset['spam'])
# message_stat("Korean Dataset",kor_smishing['content'])
# message_stat('ExAIS_dataset', ExAIS_dataset['Message'])
# message_stat('super_dataset', super_dataset['SMSes'])

# print('\n------------------------------------------------Annotated Dataset Ham -------------------------------------------\n')
# message_stat("British Dataset",british_ham)
# message_stat("UCI Dataset",UCI_dataset_ham)
# message_stat("Mendeley Dataset",mendeley_dataset[mendeley_dataset['LABEL']=='ham']['TEXT'])
# message_stat("Enron Dataset",enron_dataset['ham'])
# message_stat("Korean Dataset",kor_smishing[kor_smishing['class']==0]['content'])
# message_stat('ExAIS_dataset', ExAIS_dataset[ExAIS_dataset['Label']=='HAM']['Message'])
# message_stat('super_dataset', super_dataset[super_dataset['Labels']==0]['SMSes'])

# print('\n------------------------------------------------ Annotated Dataset Spam -------------------------------------------\n')
# message_stat("British Dataset",british_spam)
# message_stat("UCI Dataset",UCI_dataset_spam)
# message_stat("Mendeley Dataset",list(mendeley_dataset[mendeley_dataset['LABEL']=='spam']['TEXT']) + list(mendeley_dataset[mendeley_dataset['LABEL']=='Spam']['TEXT']))
# message_stat("Enron Dataset",enron_dataset['spam'])
# message_stat('ExAIS_dataset', ExAIS_dataset[ExAIS_dataset['Label']=='SPAM']['Message'])
# message_stat("spamhunter Dataset",spamhunter_dataset['Messages'])
# message_stat('super_dataset', super_dataset[super_dataset['Labels']==1]['SMSes'])


# print('\n------------------------------------------------ Annotated Dataset Smishing -------------------------------------------\n')
# message_stat("Mendeley Dataset",list(mendeley_dataset[mendeley_dataset['LABEL']=='smishing']['TEXT']) + list(mendeley_dataset[mendeley_dataset['LABEL']=='Smishing']['TEXT']))
# message_stat("Korean Dataset",kor_smishing[kor_smishing['class']==1]['content'])

------------------------------------------------ Full Dataset -------------------------------------------

British Dataset 106.82857142857142 115.0 ModeResult(mode=155, count=23) 46.78703465966718
NUS Dataset 52.01423838094385 36.0 ModeResult(mode=20, count=972) 54.16755290390322
UCI Dataset 80.47829207032652 62.0 ModeResult(mode=22, count=120) 59.842933505874676
Mendeley Dataset 83.23982582481996 66.0 ModeResult(mode=32, count=94) 58.677030418615146
Smishtank Dataset 176.96058661778184 140.0 ModeResult(mode=3, count=31) 121.28296486588144
sp24 Dataset 112.44622146437548 101.0 ModeResult(mode=101, count=6393) 31.788352477520014
Enron Dataset 1446.8421770725197 661.0 ModeResult(mode=0, count=371) 4245.89551370607
Korean Dataset 44.827165636788635 22.0 ModeResult(mode=200, count=1921) 86.09652606323212
ExAIS_dataset 136.8824427480916 151.0 ModeResult(mode=176, count=155) 70.40524408048722
super_dataset 96.09441874347112 89.0 ModeResult(mode=138, count=649) 68.75635951513296

------------------------------------------------Annotated Dataset Ham -------------------------------------------

British Dataset 78.89777777777778 73.0 ModeResult(mode=38, count=8) 42.33709426280084
UCI Dataset 71.47192873420344 52.0 ModeResult(mode=22, count=120) 58.320601078167975
Mendeley Dataset 70.70458298926508 53.0 ModeResult(mode=32, count=94) 56.14853682055032
Enron Dataset 1651.670534904805 751.0 ModeResult(mode=230, count=196) 5728.303946325299
Korean Dataset 41.199159506033716 22.0 ModeResult(mode=200, count=1919) 72.9032774331489
ExAIS_dataset 132.41695501730104 140.0 ModeResult(mode=179, count=94) 83.13468575452227
super_dataset 65.19025226549105 50.0 ModeResult(mode=27, count=625) 56.57603436069381

------------------------------------------------ Annotated Dataset Spam -------------------------------------------

British Dataset 136.40235294117647 147.0 ModeResult(mode=156, count=22) 30.138433451894212
UCI Dataset 138.6760374832664 149.0 ModeResult(mode=158, count=43) 28.85191849597169
Mendeley Dataset 133.89775051124744 143.0 ModeResult(mode=156, count=23) 34.15491256319527
Enron Dataset 1249.4697146185206 590.0 ModeResult(mode=0, count=319) 1923.7002816150505
ExAIS_dataset 142.3740425531915 157.0 ModeResult(mode=176, count=88) 49.986262864382304
spamhunter Dataset 147.35793386509718 140.0 ModeResult(mode=151, count=515) 68.33027424808054
super_dataset 144.298227519291 136.0 ModeResult(mode=138, count=565) 57.40409186699341

------------------------------------------------ Annotated Dataset Smishing -------------------------------------------

Mendeley Dataset 139.58620689655172 146.0 ModeResult(mode=158, count=28) 32.516327189401764
Korean Dataset 296.0975609756098 125.0 ModeResult(mode=67, count=13) 297.7406252306701

In [ ]:
# print('------------------------------------------------ Full Dataset -------------------------------------------\n')
# print('D_Name', "         Cnt", " %")
# url_count("British Dataset",british_ham+british_spam)
# url_count("NUS Dataset",singapore_dataset_all_mesages)
# url_count("UCI Dataset",UCI_dataset_ham+UCI_dataset_spam)
# # url_count("Smishtank Dataset",smishtank_dataset['MainText'])
# print("Smishtank Dataset",len(smishtank_dataset)-smishtank_dataset['Url'].fillna('-1').to_list().count('-1'), round(100*(len(smishtank_dataset)-smishtank_dataset['Url'].fillna('-1').to_list().count('-1'))/len(smishtank_dataset),2))
# smishtank_dataset['Url'].dropna().to_csv('../Dataset/URL Data/'+'Smishtank Dataset'+'.csv', index=None)
# url_count('sp24 Dataset', sp24_dataset['message'])
# url_count('enron Dataset', enron_dataset['ham']+enron_dataset['spam'])
# url_count('Korean Dataset', kor_smishing['content']) 
# url_count('ExAIS_dataset', ExAIS_dataset['Message'])
# url_count('super_dataset', super_dataset['SMSes'])

super_dataset 13799 20.59

In [28]:
url_count('bangla_spam', ban_spam['text'])
url_count('bangla_spam_ham', ban_spam[ban_spam['type']=='ham']['text'])
url_count('bangla_spam_spam', ban_spam[ban_spam['type']=='spam']['text'])

bangla_spam 179 6.88
bangla_spam_ham 90 7.51
bangla_spam_spam 89 6.34

In [63]:
url_count('bangla_barta', ban_barta['text'])
url_count('bangla_barta_ham', ban_barta[(ban_barta['label']=='promo') | (ban_barta['label']=='normal')]['text'])
url_count('bangla_barta_spam', ban_barta[ban_barta['label']=='smish']['text'])

bangla_barta 410 14.79
bangla_barta_ham 138 7.47
bangla_barta_spam 272 29.44

In [47]:
url_count('revised_indian', rev_india['msg'])
url_count('revised_indian_ham', rev_india[rev_india['label']=='ham']['msg'])
url_count('revised_indian_spam', rev_india[rev_india['label']=='spam']['msg'])

revised_indian 1441 31.55
revised_indian_ham 876 26.1
revised_indian_spam 565 46.66

In [180]:
xo = 0
for i in enron_dataset['ham']+enron_dataset['spam']:
    if 'http' in i:
        xo+=1
xo

6442

In [209]:
print('------------------------------------------------ Full Dataset -------------------------------------------\n')
print('D_Name', "         Cnt", " %")
url_count("British Dataset_",british_ham+british_spam)
url_count("NUS Dataset_",singapore_dataset_all_mesages)
url_count("UCI Dataset_",UCI_dataset_ham+UCI_dataset_spam)
# url_count("Smishtank Dataset_",smishtank_dataset['MainText'])
# # print("Smishtank Dataset",len(smishtank_dataset)-smishtank_dataset['Url'].fillna('-1').to_list().count('-1'), round(100*(len(smishtank_dataset)-smishtank_dataset['Url'].fillna('-1').to_list().count('-1'))/len(smishtank_dataset),2))
# # smishtank_dataset['Url'].dropna().to_csv('../Dataset/URL Data/'+'Smishtank Dataset'+'.csv', index=None)
url_count('sp24 Dataset_', sp24_dataset['message'])
url_count('enron Dataset_', enron_dataset['ham']+enron_dataset['spam'])
url_count('Korean Dataset_', kor_smishing['content']) 
url_count('ExAIS_dataset_', ExAIS_dataset['Message'])
url_count('super_dataset_', super_dataset['SMSes'])
url_count("Mendeley Dataset_",mendeley_dataset['TEXT'])
url_count("spamhunter Dataset_",spamhunter_dataset['Messages'])

------------------------------------------------ Full Dataset -------------------------------------------

D_Name          Cnt  %
british dataset_ 55 6.29
nus dataset_ 25 0.04
uci dataset_ 96 1.72
sp24 dataset_ 41676 61.26
enron dataset_ 5922 17.56
korean dataset_ 127 0.29
exais_dataset_ 193 3.68
super_dataset_ 5283 7.88
mendeley dataset_ 172 2.88
spamhunter dataset_ 11123 43.07

In [104]:
# # 'http://doit'.split('//')
# '//' in 'http://doit'

In [155]:
# print('------------------------------------------------ Part by Part Dataset -------------------------------------------\n')
# print('D_Name', "         Cnt", " %")

url_count("British Dataset Ham_",british_ham)
url_count("British Dataset Spam_",british_spam)

url_count("UCI Dataset Ham_",UCI_dataset_ham)
url_count("UCI Dataset Spam_",UCI_dataset_spam)

url_count('enron Dataset Ham_', enron_dataset['ham'])
url_count('enron Dataset Spam_', enron_dataset['spam'])

url_count('Korean Dataset Ham_', kor_smishing[kor_smishing['class']==0]['content'])
url_count('Korean Dataset Spam_', kor_smishing[kor_smishing['class']==1]['content'])

url_count('ExAIS_dataset_Ham_', ExAIS_dataset[ExAIS_dataset['Label']=='HAM']['Message'])
url_count('ExAIS_dataset_Spam_', ExAIS_dataset[ExAIS_dataset['Label']=='SPAM']['Message'])

url_count('super_dataset_Ham_', super_dataset[super_dataset['Labels']==0]['SMSes'])
url_count('super_dataset_Spam_', super_dataset[super_dataset['Labels']==1]['SMSes'])

british dataset ham_ 0 0.0
british dataset spam_ 60 12.94
uci dataset ham_ 2 0.04
uci dataset spam_ 101 12.58
enron dataset ham_ 1249 7.17
enron dataset spam_ 5169 26.75
korean dataset ham_ 3 0.01
korean dataset spam_ 127 20.16
exais_dataset_ham_ 68 2.35
exais_dataset_spam_ 125 5.32
super_dataset_ham_ 20 0.04
super_dataset_spam_ 9671 19.97

In [128]:
xyx = set(pd.read_csv('../Dataset/URL Data/'+'enron Dataset_'+'.csv')['URL'])
xzx = set(pd.read_csv('../Dataset/URL Data/'+'enron Dataset'+'.csv', delimiter='\t')['URL'])

# xzx-xyx
len(xyx-xzx)

2688

In [ ]:
# ------------------------------------------------ Full Dataset -------------------------------------------

# D_Name          Cnt  %
# british dataset 90 10.29
# nus dataset 1804 3.23
# uci dataset 305 5.47
# Smishtank Dataset 938 85.98
# sp24 dataset 67365 99.02
# enron dataset 6440 19.1
# korean dataset 195 0.45
# exais_dataset 1271 24.26
# super_dataset 13799 20.59

In [ ]:
# print('------------------------------------------------ Part by Part Dataset -------------------------------------------\n')
# print('D_Name', "         Cnt", " %")

# url_count("British Dataset Ham",british_ham)
# url_count("British Dataset Spam",british_spam)

# url_count("UCI Dataset Ham",UCI_dataset_ham)
# url_count("UCI Dataset Spam",UCI_dataset_spam)

# url_count('enron Dataset Ham', enron_dataset['ham'])
# url_count('enron Dataset Spam', enron_dataset['spam'])

# url_count('Korean Dataset Ham', kor_smishing[kor_smishing['class']==0]['content'])
# url_count('Korean Dataset Spam', kor_smishing[kor_smishing['class']==1]['content'])

# url_count('ExAIS_dataset_Ham', ExAIS_dataset[ExAIS_dataset['Label']=='HAM']['Message'])
# url_count('ExAIS_dataset_Spam', ExAIS_dataset[ExAIS_dataset['Label']=='SPAM']['Message'])

# url_count('super_dataset_Ham', super_dataset[super_dataset['Labels']==0]['SMSes'])
# url_count('super_dataset_Spam', super_dataset[super_dataset['Labels']==1]['SMSes'])

super_dataset_ham 1415 3.47
super_dataset_spam 12383 47.3

In [70]:
phone_number_count('bangla_spam', ban_spam['text'])
phone_number_count('bangla_spam_ham', ban_spam[ban_spam['type']=='ham']['text'])
phone_number_count('bangla_spam_spam', ban_spam[ban_spam['type']=='spam']['text'])

bangla_spam 66 2.54
bangla_spam_ham 1 0.08
bangla_spam_spam 65 4.63

In [71]:
phone_number_count('bangla_barta', ban_barta['text'])
phone_number_count('bangla_barta_ham', ban_barta[(ban_barta['label']=='promo') | (ban_barta['label']=='normal')]['text'])
phone_number_count('bangla_barta_spam', ban_barta[ban_barta['label']=='smish']['text'])

bangla_barta 442 15.95
bangla_barta_ham 127 6.87
bangla_barta_spam 315 34.09

In [72]:
phone_number_count('revised_indian', rev_india['msg'])
phone_number_count('revised_indian_ham', rev_india[rev_india['label']=='ham']['msg'])
phone_number_count('revised_indian_spam', rev_india[rev_india['label']=='spam']['msg'])

revised_indian 1132 24.79
revised_indian_ham 988 29.44
revised_indian_spam 144 11.89

In [ ]:
# print('------------------------------------------------ Full Dataset -------------------------------------------\n')
# print('D_Name', "         Cnt", " %\n\n")
# phone_number_count("British Dataset",british_ham+british_spam)
# phone_number_count("NUS Dataset",singapore_dataset_all_mesages)
# phone_number_count("UCI Dataset",UCI_dataset_ham+UCI_dataset_spam)
# phone_number_count("Mendeley Dataset",mendeley_dataset['TEXT'])
# phone_number_count("Smishtank Dataset",smishtank_dataset['MainText'])
# phone_number_count("sp24 Dataset",sp24_dataset['message'])
# phone_number_count('enron Dataset', enron_dataset['ham']+enron_dataset['spam'])
# phone_number_count('Korean Dataset', kor_smishing['content'])
# phone_number_count('ExAIS_dataset', ExAIS_dataset['Message'])
# phone_number_count("spamhunter Dataset",spamhunter_dataset['Messages'])
# phone_number_count('super_dataset', super_dataset['SMSes'])

------------------------------------------------ Full Dataset -------------------------------------------

super_dataset 703 1.05

In [ ]:
# print('------------------------------------------------ Full Dataset -------------------------------------------\n')
# print('D_Name', "         Cnt", " %\n\n")
# email_count("British Dataset",british_ham+british_spam)
# email_count("NUS Dataset",singapore_dataset_all_mesages)
# email_count("UCI Dataset",UCI_dataset_ham+UCI_dataset_spam)
# email_count("Mendeley Dataset",mendeley_dataset['TEXT'])
# email_count("Smishtank Dataset",smishtank_dataset['MainText'])
# email_count("sp24 Dataset",sp24_dataset['message'])
# email_count('enron Dataset', enron_dataset['ham']+enron_dataset['spam'])
# email_count('Korean Dataset', kor_smishing['content'])
# email_count('ExAIS_dataset', ExAIS_dataset['Message'])
# email_count("spamhunter Dataset",spamhunter_dataset['Messages'])
# email_count('super_dataset', super_dataset['SMSes'])

------------------------------------------------ Full Dataset -------------------------------------------

super_dataset 81 0.12

In [74]:
email_count('bangla_spam', ban_spam['text'])
email_count('bangla_spam_ham', ban_spam[ban_spam['type']=='ham']['text'])
email_count('bangla_spam_spam', ban_spam[ban_spam['type']=='spam']['text'])

bangla_spam 0 0.0
bangla_spam_ham 0 0.0
bangla_spam_spam 0 0.0

In [75]:
email_count('bangla_barta', ban_barta['text'])
email_count('bangla_barta_ham', ban_barta[(ban_barta['label']=='promo') | (ban_barta['label']=='normal')]['text'])
email_count('bangla_barta_spam', ban_barta[ban_barta['label']=='smish']['text'])

bangla_barta 45 1.62
bangla_barta_ham 45 2.44
bangla_barta_spam 0 0.0

In [76]:
email_count('revised_indian', rev_india['msg'])
email_count('revised_indian_ham', rev_india[rev_india['label']=='ham']['msg'])
email_count('revised_indian_spam', rev_india[rev_india['label']=='spam']['msg'])

revised_indian 134 2.93
revised_indian_ham 36 1.07
revised_indian_spam 98 8.09