In [2]:
import requests 
from bs4 import BeautifulSoup as bs
import pandas as pd
import tldextract
import numpy as np
import matplotlib.pylab as plt
import os
import re
import json

In [3]:
def on_sale_chk(text):
    if len(text)<1:
        return False
    return 'domain' in text and 'sale' in text

def on_parked_chk(text):
    if len(text)<1:
        return True
    return 'domain' in text and 'park' in text

def on_Parked(text):
    if len(text)<1:
        return True
    return (('website' in text or 'content' in text) and 'unavailable' in text) or ('will' in text and 'soon' in text)

In [4]:
#returns html contents, textual character length, website size, status code, parked or on sale

def soupFromUrl(scrapeUrl):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.1; zh-CN) AppleWebKit/533+ (KHTML, like Gecko)'}
    try:
        req = requests.get(scrapeUrl, headers=headers, timeout=5)
        # print(req.status_code)
        req.close()
        if req.status_code == 200:
            # print(bs(req.text, 'html.parser').get_text().strip().replace('\n',' '))
            soup = bs(req.text,'html.parser')

            # print(soup)

            text = ''

            if soup.body:
                text = re.sub(r'[^\w]', ' ',soup.body.get_text(' ', strip=True).lower())

            # print(soup)

            # print('text',text)
            # print(bs(req.text, 'html.parser'))
            # return [bs(req.text, 'html.parser'),len(req.text), len(req.content), req.status_code]
            # print([len(req.content), len(text), req.status_code, 0+(on_sale_chk(text) or on_Parked(text) or on_parked_chk(text))])
            return [len(req.content), len(text), req.status_code, 0+(on_sale_chk(text) or on_Parked(text) or on_parked_chk(text))]
        else:
            # return [-1,0,0,req.status_code]
            return [0,0,req.status_code,0]
    except:
        # return [-1,0,0,-1]
        return [0,0,-1,0]

In [5]:
headers = {'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.1; zh-CN) AppleWebKit/533+ (KHTML, like Gecko)'}
req = requests.get('https://www.lycos.com/', headers=headers, timeout=5)
print(req.status_code)
req.close()
if req.status_code == 200:
    # print(bs(req.text, 'html.parser').get_text().strip().replace('\n',' '))
    soup = bs(req.text,'html.parser')

    # print(soup)
    text = ''

    if soup.body:
        text = re.sub(r'[^\w]', ' ',soup.body.get_text(' ', strip=True).lower())

    print(soup)
    print('text',text)
    print([len(req.content), len(text), req.status_code, 0+(on_sale_chk(text) or on_Parked(text) or on_parked_chk(text))])

200
<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta content="Lycos, Inc., is a web search engine and web portal established in 1994, spun out of Carnegie Mellon University. Lycos also encompasses a network of email, webhosting, social networking, and entertainment websites." name="description"/>
<meta content="" name="author"/>
<link href="https://ly.lygo.net/static/lycos/img/favicon.ico" rel="icon" type="image/png"/>
<title>Lycos.com</title>
<link href="//fonts.googleapis.com/css?family=Lato:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css"/>
<link href="/css/in/fonts.css" rel="stylesheet" type="text/css">
<link href="https://ly.lygo.net/static/lycos/css/in/font-awesome.css" rel="stylesheet" type="text/css">
<!-- Bootstrap core CSS -->
<link href="https://ly.lygo.net/static/lycos/css/in/bootstrap.css" rel="stylesheet"/>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<link href="https://ly.lygo.net/static/lycos/css/in/ie10-viewport-bug-workaround.css" rel="stylesheet"/>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<!-- Custom styles for this template -->
<link href="https://ly.lygo.net/static/lycos/css/in/slider_prev.css" rel="stylesheet" type="text/css">
<link href="https://ly.lygo.net/static/lycos/css/in/carousel.css" rel="stylesheet" type="text/css">
<link href="https://ly.lygo.net/static/lycos/css/in/custom.css" rel="stylesheet" type="text/css"/>
<link href="https://ly.lygo.net/static/lycos/css/us/newadd.css" rel="stylesheet" type="text/css"/>
<link href="https://ly.lygo.net/static/lycos/css/uvtHamburger.css" rel="stylesheet"/>
<script src="https://ly.lygo.net/static/lycos/js/jquery-1.10.1.min.js"></script>
<script src="https://ly.lygo.net/static/lycos/js/jquery.autocomplete.js"></script>
<script src="https://ly.lygo.net/static/lycos/js/universal.js"></script>
<script src="//scripts.lycos.com/jquery-addons/jquery.cookie-1.4.1.js"></script></link></link></link></link></head>
<!-- NAVBAR
================================================== -->
<body>
<header>
<div class="container">
<div class="nav navHome">
<div class="navbar-left">
<div class="uvt-logo-block">
<div class="prop-logo">
<!-- click and mouseover show network panel -->
<div class="uvt-dog network-toggle"></div>
<div class="network-panel">
<ul class="nw-properties">
<li><a href="https://www.lycos.com"><span class="icon icon-lycos"></span><span class="name">Lycos.com</span></a></li>
<li><a href="http://www.mail.lycos.com"><span class="icon icon-mail"></span><span class="name">Mail</span></a></li>
<li><a href="http://weather.lycos.com"><span class="icon icon-weather"></span><span class="name">Lycos Weather</span></a></li>
<li><a href="http://www.tripod.lycos.com"><span class="icon icon-tripod"></span><span class="name">Tripod</span></a></li>
<li><a href="http://angelfire.com"><span class="icon icon-angelfire"></span><span class="name">Angelfire</span></a></li>
<li><a href="http://domains.lycos.com"><span class="icon icon-domains"></span><span class="name">Domains</span></a></li>
</ul>
<!-- end proeprties -->
</div>
<!-- end Network Panel -->
</div>
</div>
<!-- end Logo-network -->
</div>
<div class="navbar-left">
<a href="http://weather.lycos.com" title="Launch Lycos Weather">
<span class="weather-text">

Cookeville 29° F
				</span> <span class="icon weather-icon"> <img alt="night_mostly_cloudy" src="https://ly.lygo.net/static/lycos/images/weather/frontpage/night_mostly_cloudy.png"/>
</span>
</a>
</div>
<div class="network uvt uvth">
<div class="lang-selector">
<div class="ls-parent">
<span class="lang-icon"><img alt="Select Your Language" src="https://ly.lygo.net/static/lycos/img/lang-icon.png"/></span>
<script type="text/javascript">
                            function setDefaultLanguage(lang) {
                                $.cookie('defaultLanguage', lang, { path: '/', expires: 3650, domain: 'lycos.com' });
                            }
                        </script>
<ul class="ls-children">
<li class="selectedLang"><a href="/" onclick="setDefaultLanguage('en'); return true;" title="English">English</a></li>
<li><a href="/" onclick="setDefaultLanguage('es'); return true;" title="Spanish">Español</a></li>
<li><a href="/" onclick="setDefaultLanguage('ja'); return true;" title="Japanese">日本語</a></li>
<li><a href="/" onclick="setDefaultLanguage('de'); return true;" title="German">Deutsch</a></li>
<li><a href="/" onclick="setDefaultLanguage('ko'); return true;" title="Korean">한국어</a></li>
<li><a href="/" onclick="setDefaultLanguage('fr'); return true;" title="French">Français</a></li>
<li><a href="/" onclick="setDefaultLanguage('it'); return true;" title="Italian">Italiano</a></li>
<li><a href="/" onclick="setDefaultLanguage('nl'); return true;" title="Dutch">Nederlands</a></li>
<li><a href="/" onclick="setDefaultLanguage('sv'); return true;" title="Swedish">Svenska</a></li>
<li><a href="/" onclick="setDefaultLanguage('da'); return true;" title="Danish">Dansk</a></li>
<li><a href="/" onclick="setDefaultLanguage('fi'); return true;" title="Finnish">Suomi</a></li>
<li><a href="/" onclick="setDefaultLanguage('no'); return true;" title="Norwegian">Norsk</a></li>
<li><a href="/" onclick="setDefaultLanguage('ga'); return true;" title="Irish">Gaeilge</a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</header>
<!-- Carousel
    ================================================== -->
<div class="search_slider">
<div class="col-sm-12">
<div class="carousel slide" data-ride="carousel" id="myCarousel">
<div class="searc_box">
<div class="lycos">
<a href="#"><img alt="" src="https://ly.lygo.net/static/lycos/img/in/lycoslogo.png"/></a>
</div>
<div class="searc_input">
<script type="text/javascript"><!--//--><![CDATA[//><!--
    function checkSubmit() {
      var queryBox = document.getElementById('query');

      if(( queryBox.value == 'Enter search term...' ) || ( queryBox.value.trim() == '' )) {
	  queryBox.value = '';
	  queryBox.focus()
	  return false;
      }
      return true;
    }
    //--><!]]></script>
<form action="https://search.lycos.com/web" id="form_query" method="get" onsubmit="return checkSubmit();">
<fieldset>
<input autofocus="" class="search-input" id="query" name="q" placeholder="Enter search term..." type="text" value=""/>
<button class="search"></button>
</fieldset>
<input id="keyvol" name="keyvol" type="hidden" value="FA02D34CE00ABC10FE"/>
</form>
</div>
<div id="autocomplete-suggestions"></div>
</div>
<!-- Indicators -->
<ol class="carousel-indicators">
<li class="active" data-slide-to="0" data-target="#myCarousel"></li>
<li data-slide-to="1" data-target="#myCarousel"></li>
<li data-slide-to="2" data-target="#myCarousel"></li>
</ol>
<div class="carousel-inner" role="listbox">
<div class="item active">
<img alt="First slide" class="first-slide" src="https://ly.lygo.net/static/lycos/img/us/slider/slider_us1.jpg"/>
</div>
<div class="item">
<img alt="Second slide" class="second-slide" src="https://ly.lygo.net/static/lycos/img/us/slider/slider_us2.jpg"/>
</div>
<div class="item">
<img alt="Third slide" class="third-slide" src="https://ly.lygo.net/static/lycos/img/us/slider/slider_us3.jpg"/>
</div>
</div>
</div>
</div>
</div>
<!-- /.carousel -->
<section class="content" style="padding-bottom: 20px;">
<div class="container">
<div class="navbar-left">
<ul class="nav nav-tabs">
<li><a href="https://lycos.itemorder.com/sale" style="display: inline;" target="_blank"><img src="https://ly.lygo.net/static/lycos/images/lycos_swag_mug.png" style="display: inline;
	height: 60px;
	width: 60px;"> Lycos
						SWAG</img></a></li>
</ul>
</div>
<div class="navbar-right">
<ul class="nav nav-tabs">
<li><a href="http://www.mail.lycos.com">Mail</a></li>
<li><a href="http://www.tripod.lycos.com">Tripod</a></li>
<li><a href="http://domains.lycos.com">Domains</a></li>
<li><a href="http://weather.lycos.com">Weather</a></li>
<li><a href="http://www.angelfire.com/">Angelfire</a></li>
</ul>
</div>
</div>
</section>
<footer>
<div style="float: left; width: 100%;">
<div style="margin-left: auto; margin-right: auto; height: 95px; width: 733px; margin-bottom: 5px;">
</div>
</div>
<div class="container">
<ul class="navbar-left">
<li>
<p>Copyright © 2025 Lycos</p>
</li>
<li><a href="https://info.lycos.com" title="About Lycos">About</a></li>
<li><a href="https://info.lycos.com/career-opportunities/job-openings" title="Careers at Lycos">Careers</a></li>
<li><a href="https://advertising.lycos.com" title="Advertise with Lycos">Advertise With Us</a></li>
<li><a href="https://info.lycos.com/resources/terms-of-service" rel="nofollow" title="Lycos Network Legal">Legal</a></li>
<li><a href="https://info.lycos.com/resources/privacy-policy" rel="nofollow" title="Lycos Privacy Policy">Privacy</a></li>
<li><a href="https://registration.lycos.com/helpcenter_passthrough.php?m_PR=1" rel="nofollow" title="Lycos Help Portal">Help</a></li>
<li class="search-provider modern-browsers"><a href="https://info.lycos.com/resources/lycos-search/#Chrome" onclick="window.external.AddSearchProvider('https://search.lycos.com/opensearch.xml')" title="Make Lycos Search the Default Search Provider"><span>Add
						Lycos Search to Browser</span></a></li>
</ul>
<ul class="navbar-right">
<li><a href="https://www.facebook.com/lycos.search" target="_blank" title="Friend Lycos on Facebook"><img alt="Facebook" src="https://ly.lygo.net/static/lycos/images/facebook.png"/></a></li>
<li><a href="https://twitter.com/SearchLycos" target="_blank" title="Follow Lycos on Twitter"><img alt="Twitter" src="https://ly.lygo.net/static/lycos/images/twitter.png"/></a></li>
</ul>
</div>
</footer>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-0WY0KPH0ZW"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-0WY0KPH0ZW');
</script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-76FJGHQNN6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-76FJGHQNN6');
</script><script type="text/javascript">//<![CDATA[
  $('#keyvol').val('00a8ee5c16756a2b1dee');
//--><!]]>
</script>
<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ly.lygo.net/static/lycos/js/in/bootstrap.min.js" type="text/javascript"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="https://ly.lygo.net/static/lycos/js/in/ie10-viewport-bug-workaround.js"></script>
<script src="https://ly.lygo.net/static/lycos/js/in/prev_next.js" type="text/jscript"></script>
<script>

$(document).ready(function(e) {

	   $("#owl-demo1").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });
	    $("#owl-demo2").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });
	    $("#owl-demo3").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });
	    $("#owl-demo4").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });



});


</script>
<script src="https://ly.lygo.net/static/lycos/js/in/dog_in.js"></script>
<script>$(function() {
	'use strict';

	// Initialize ajax autocomplete:
	$('#query').autocomplete({
		serviceUrl : 'https://us.search.yahoo.com/sugg/gossip/gossip-us-partner?output=sd1&appid=lycos',
        dataType: 'jsonp',
		paramName : 'command',
		onSearchComplete : function(originalQuery, suggestion) {
			var re = new RegExp('\b' + $.Autocomplete.utils.escapeRegExChars(originalQuery), 'gi');
			return re.test(suggestion.value);
		},
		onSelect : function(suggestion) {
			$('#form_query').submit();
		},
		onInvalidateSelection : function() {
			$('#selction-ajax').html('You selected: none');
		},
		transformResult : function(_response) {
			var response = typeof _response === 'string' ? $.parseJSON(_response) : _response;
			return {
				query : response.q,
				suggestions : $.map(response.r, function(dataItem) {
					return dataItem.k;
				})
			};
		}
	});
});
</script></body>
</html>

text lycos com mail lycos weather tripod angelfire domains cookeville 29  f english español 日本語 deutsch 한국어 français italiano nederlands svenska dansk suomi norsk gaeilge lycos       swag mail tripod domains weather angelfire copyright   2025 lycos about careers advertise with us legal privacy help add       lycos search to browser
[13609, 328, 200, 0]

In [6]:
# print(soupFromUrl('https://www.delinian.com/'))
# print(soupFromUrl('https://www.makecashonline.com/'))
print(soupFromUrl('https://www.lycos.com/'))

[13613, 328, 200, 0]

In [8]:
smishtank_data = pd.read_csv('../Dataset/smishtank.csv', encoding='unicode_escape')

smishtank_data.head()

# for i in smishtank_data['smsCorpus']['message']:
#     # print(type(i['text']['$']))
#     singapore_dataset_all_mesages.append(i['text']['$'])

# nus_url = []
# for i in singapore_dataset_all_mesages:
#     if type(i)!=type('str'):
#         continue
#     xx=re.split('www, http', i)[0]
#     for j in xx.split():
#         if 'www' in j:
#             if len(j)<8:
#                 nus_url.append(j+xx[xx.index(j):])
#             else:
#                 nus_url.append(j)
#         if 'http' in j:
#             if len(j)<15:
#                 nus_url.append(j+xx[xx.index(j):])
#             else:
#                 nus_url.append(j)
#     # for j in xx:
#     #     print(j)

# for i in nus_url:
#     print(i)

,messageid,Fulltext,Sender,SenderType,timeReceived,MainText,Url,Subdomain,Domain,TLD,...,Phishing,Suspicious,Malware,Brand,URL Subcategory,Message Categories,FullyQualifiedDomain,Domain Registrar,Domain Creation Date,Domain Last Update
0,3,"Text Message\nThu, Jul 29, 19:10\nCostco: Dani...",42003,Short Code,"03/31/2022, 21:58:50","Costco: Daniel, the code 42003 printed on your...",f2gpy.info/RzNKEwsZve,NaN,f2gpy,info,...,0,0,0,Costco,Random Domain,Prize/Contest,f2gpy.info,"NameCheap, Inc.",7/28/2021,7/31/2021
1,5,"<\n+1 (872) 279-0672 >\nText Message\nWed, Feb...",+1 (872) 279-0672,Phone Number,"04/02/2022, 02:59:56","Hi, you still owe UPS $4.10 USD in customs fee...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,UPS,NaN,Delivery,NaN,NaN,NaN,NaN
2,6,"<\n+1 (806) 224-7886 >\nText Message\nThu, Sep...",+1 (806) 224-7886,Phone Number,"04/02/2022, 03:03:00",wel01.us/r/rest05 WELLS FARGO(CS):Profile lock...,wel01.us/r/rest05,NaN,wel01,us,...,0,0,0,WELLS FARGO,Random Domain,Account Alert,wel01.us,"NameCheap, Inc.",8/30/2021,8/30/2021
3,7,Text Message\nToday 2:30 PM\nwho played golf\n...,NaN,NaN,"04/02/2022, 23:42:38","Hi, are you who played golf together last time...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Wrong Number/Romance Scam,NaN,NaN,NaN,NaN
4,8,(8\n+1 (775) 537-4497\ncanador to them\nTato m...,+1 (775) 537-4497,Phone Number,"04/02/2022, 23:46:34","(8 Hi Julianne long time no see, I'm Aleen, ho...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Wrong Number/Romance Scam,NaN,NaN,NaN,NaN

In [13]:
smishtank_dataset = pd.read_csv('../Dataset/smishtank.csv', encoding='unicode_escape')
smishtank_data = {'URL':[i for i in smishtank_dataset['Url'] if str(i)!='nan']}
smishtank_url = smishtank_data['URL']
smishtank_url[:10]

['f2gpy.info/RzNKEwsZve',
 'wel01.us/r/rest05',
 'https://chat.whatsapp.com/Djci PB8b7gTGGt16QJ5mJm',
 'http://citibsec.com',
 'secbofa.page.link/NLt',
 'https://rebrand.ly/grppwwr',
 'http://klkln.cc/vnbcbtd',
 'https://b.link/h21bc',
 'lksr.link/9pvvbF',
 'https://wwj4w-fedex.us/jWXHwj?47965169']

In [15]:
print(len(smishtank_dataset), len(smishtank_url))

1091 938

In [16]:
import re

def find_first_slash_preceded_by_number(s):
    # Regular expression to find the first instance of a number followed by '/'
    match = re.search(r'\d+/', s)
    
    if match:
        return match.start() + len(match.group()) - 1  # Return the index of '/'
    else:
        return -1  # Return -1 if no match is found

# Example usage
string = "example77/test 88/test2 99/test3"
index = find_first_slash_preceded_by_number(string)
print(index)  # Outputs the index of the first '/' preceded by a number

9

In [28]:
# unique_enron_url = set()

# priority_tld = ['com','edu','org','net','biz','info','co.uk','co.nz','gov']
# other_tld = ['ru','su','uk','us','ws','ie']

In [17]:
unique_smishtank_url = set(smishtank_url)

In [18]:
smishtank_data

{'URL': ['f2gpy.info/RzNKEwsZve',
  'wel01.us/r/rest05',
  'https://chat.whatsapp.com/Djci PB8b7gTGGt16QJ5mJm',
  'http://citibsec.com',
  'secbofa.page.link/NLt',
  'https://rebrand.ly/grppwwr',
  'http://klkln.cc/vnbcbtd',
  'https://b.link/h21bc',
  'lksr.link/9pvvbF',
  'https://wwj4w-fedex.us/jWXHwj?47965169',
  'storage.googleapis.com/jzoxubc/1fhg3lf',
  'mentioningdears.com/nzWjdtrM93',
  'sirreeprematurely.com/X9cSSE4SfA',
  'xyzthriftyquotes.com/60ef6eec47',
  'https://jf245-fedex.me/y.jDxio?37588372',
  'wepay-topvalue.com/bf2f414d45',
  'vocalsprolonged.com/ZSgingd6vi',
  'reamvino.com/SvjMeq1eKD',
  'slappingtasting.com/Hamw6PokCc',
  'http://VERIFYWELLSFARGO.GA',
  'flimsyfooting.com/RugSJP91a6',
  'clowningbacking.com/ZOKNSJFtJT',
  'catererhunger.com/Okk7d5ha2y',
  'fritzclosets.com/PV06ExwSdV',
  'http://www.webpage.ren/b/lc/?bfX.08&08z-mkq',
  'holdingspothere.com/8930er',
  'settclss.com/Ccn26dr',
  'warrantgeneration.com/RsCoLlrDrs',
  'unselfishdumplings.com/LKXH4N4WZ3',
  'purposeliberals.com/yF70SNqOKV',
  'https://bit.ly/35Xs2rW',
  'http://gs80xb1u7wy5vb.deals',
  'http://www.cxes.click/2JkZZoeX',
  'www.citibankaccount.info',
  'bit.ly/89BNsg81289',
  'http://bit.ly/WHO-Jobs-Offer',
  'https://chat.whatsapp.com/E29ZpfVxDLCDU0lz6g5Pju',
  'https://saveonautocoverage3.me/1nhQEbD4FaH6',
  'https://usdt777.vip',
  'consensuscelebrated.com/5hTSjydwTh',
  'citi-actvity.org',
  'http://r2s9hq82ne.mmnrxeqmcv.nikxc.org',
  'sexyjessie.us',
  'https://chat.whatsapp.com/DzeAqjxgNbi6S4cuCFchXN',
  '5dexqo.com/82a103',
  'https://bit.ly/3NR5x9f',
  'https://chat.whatsapp.com/F6Wo68CcSRq88C9LSdsGcN',
  'https://express.adobe.com/page/IkvuZSZq2z1lj/',
  'Regions-PROTECT.com',
  'https://rebrand.ly/v7qj08h',
  'https://wa.me/+639162024192',
  'kzrp1h.com/bff4948af7 ',
  'http://www.xprswebsite.com/free/userf111/redirf111/?=5826865',
  'https://upspups.com',
  'boaeddprepaidservices.com',
  'https://wfveri-info.com',
  'citizens-security01.com',
  'http://prettyplump.directory/DFzOyZtj',
  'https://secur06-chase-verify.my03.com/?Verify',
  'WellsfargoVerify.com/act',
  'https://s.id/1fXBI',
  'http://flatterlaud.cricket/0VH9A5',
  'https://www.assistance-usrprocess.com',
  'http://surveysens.yokohama/9vePTP',
  'http://indianelder.business/hBF734',
  'http://apartnerve.florist/Qd8qKU',
  'http://leaseill.associates/b42TrX',
  'http://processingprotection.me/JaZcP',
  'http://eddphelp.info',
  'http://rgjgj.capital/i16nf0',
  'GetaPrizeBrand.com',
  'https://unblockbofaeddprepaid.meeha.com.bd/asdfghjkl.html',
  'https://romualdo.exe.it/AKARA.html',
  'www.pyr-upsi.website//isr1i2pF19389',
  'ee2r.info',
  'http://pricesever.financial/j07mFgmb',
  'http://fireelse.community/nm6pkc',
  'poelacnewu33sdf.us',
  'W3NGZ.COM/6blDog8jzc',
  'disciplepurse.com/HvMe3JH',
  'http://abusenat.associates/mKd6NG',
  'https://cp2we.app.link/iur',
  'igyre.cc/Kky7RkR',
  'https://poiasj5.cf/wellsfargo.com/?restore',
  'https://citi-06.com',
  'gps.ru/98hXb',
  'https://usa-exchange-us.com',
  'http://marginaljo.shopping/v3E6qB',
  'http://fotag.xpddg.com',
  'http://eddbofaprocess.info',
  'http://wealthaccept.financial/94T4CvdP',
  'http://cyntrothm.shop/ipadP.php ',
  'http://zireesso.shop/cl/5233_md/555/57333/1230/70/53367 ',
  'http://tbmuy.ncmie.com',
  'https://bit.ly/3v9zXuH',
  'http://esteemcomm.shopping/vtsk9N',
  'uEZF2.Com/GDI2hthgG1',
  'https://sec03boa.com/bRZQK',
  'http://summe.shopping/Hhj0J3',
  'www.92wbj4jzupst.com//49epb8Rw17003#',
  'https://docs.google.com/forms/d/e/1FAlpQLSeUlz-jIFAYDmtl2s9pEJSgVUHX_S33qw9twmXUqoO7_OCLkw/viewform?usp=sf_link?WuRW',
  'http://catchingbudding.directory/8BWT1REM',
  'f4RSX.COM/8vxyyUpY4d',
  'BankOfAmericaDebit05.com',
  'http://obliquerupture.directory/rvgFs6Ae',
  'postalportal.site',
  'http://denywhence.network/DOqxdH9d ',
  'BankOfAmericaDebit05.com',
  'AugustSurveys.com',
  'http://neckadvice.financial/PWvk1Wpa',
  'nfcualert.site',
  'vnnim.cc/mNGtaOl',
  'https://oasioa.cf/wellsfargo.com/?restore',
  'www.nibtt9-upse.us//vofxbnno224123#',
  'du9k3.com/rvirONcqBD',
  'surveypurpose.com/wv95u',
  'http://attorneyent.limited/S7cW3A',
  'https://bit.ly/3dRoiZe',
  'https://me2.do/GBIOwzEt?V4ZGKR',
  'https://wsends.com/go/Tracking/R2H9',
  'http://www.xprswebsite.com/free/dev2/support?=7455071',
  'https://wua.soundestlink.com/link/62ec0819e7239400160765f9/62ec07fec03d7d001dc835c5/62ec07eb316b48001c631e48?signature=9914fff38c28a734939ec6ad3c3f038680fa15f715f60 9593c985923dadb61fe',
  'https://lnkd.in/ekwVSzPa',
  'like2playnow.com/fi5dbp',
  'Xeo6.me/8ek26N',
  'giddybreasts.com/DSRRmEAccl',
  '61uxsyo.qmrWM.Com/zyd8',
  'chaselocked.com/web',
  'https://win22.org/r.wr?id=9wJ8pTXh',
  'Pbpls.COM/E5JyPE6w5t',
  'https://profib04.com',
  'http://slzbyy.com/GvR0t2ZV',
  'http://hygrjv.com/2oyhOQV',
  'http://ywrfyp.com/VkwuzqG',
  'http://zglptv.com/no2hrZB',
  'http://yjpgbx.com/mn1lkyE',
  'http://ytdbby.com/A2RsGxy',
  'https://bit.ly/3RQ1z1n',
  'http://zvsjxy.com/4qAcRgK',
  'http://kbzjgb.com/N2lswyl',
  'http://fkggnl.com/gGRI4Zw',
  'http://y.jgdfr.com/ZoAhX9Z',
  'http://mzjxyk.com/N2lsw3m',
  'http://ypzvtd.com/OmwsYW8',
  'http://carecondemn.com/BYMRKW',
  'http://cgmfdk.com/E2Ysk70',
  'http://ypzvtd.com/OmwsYW8',
  'http://zytdgx.com/G21s2n0',
  'http://cgmfdk.com/E2Ysk70',
  'http://augmentreversed.com/KIZWr1',
  'http://prmytz.com/9yJfrBg',
  'http://jkyrlw.com/YnzljRD',
  'https://brightvision.edu.pk/ca/verifyedd',
  'http://dcydpl.com/grguJq2',
  'http://wbfmqs.com/M2ksvNA',
  'http://gfxmth.com/6vDFZpW',
  'https://bit.ly/3shWipe',
  'http://ntswkf.com/Q2osg6L',
  'http://relateversion.com/1DvMxP',
  'https://secur-34b0a-protect.duckdns.org/auth/',
  'http://tvmscy.com/B2VSOWO',
  'http://dtwxzf.com/003u52r',
  'http://pslajs.com/ROpuoXO',
  'http://psjzzw.com/no2hgVq',
  'http://ryjlvn.com/P9nu967',
  'http://swhcdt.com/zErCE7I',
  'http://crglhy.com/3pzFoOA',
  'http://hnkmrb.com/WIXTZAO',
  'http://mphrbt.com/J24sIRz',
  'http://tftjrl.com/8xGFWIB',
  'http://cvvwbt.com/P9nu9lx',
  'http://vqljmq.com/ImZsm7g',
  'http://tmgcrg.com/5rBu34D',
  'http://brdcry.com/D2Xswv0',
  'http://kjhcmb.com/7wEf2VN',
  'http://vcljcy.com/rvjF706',
  'http://csrlvl.com/X0yujpo',
  'mustardobvious.com/Ouyhk7',
  'http://jryxlz.com/8xGFWJD',
  'http://lxhtwb.com/G21sEyA',
  'http://xtfpnp.com/Q2osg44',
  'http://xqgpft.com/mn118G9',
  'http://gghcfp.com/ImZsmDB',
  'http://rfhy.ps.com/6vDF7Xx',
  'http://kxqghk.com/ROpuoNr',
  'http://cggcvt.com/J24sll9',
  'http://yrvdnd.com/OmwsQQJ',
  'https://scre-bollafca.live/login',
  'http://www.xprswebsite.com/free/usere444/redire444/?=3458455',
  'https://a-use192.vev.site/redirecting/?=8651140',
  '1X3.me/3WJ0mm',
  'http://5ot.short.gy/yQLk4sUm2dKc',
  'http://statebenefitalertsedd.com/help',
  'http://resolveeddcards.com/reopennow',
  'http://www.billing-customer.kfx65hci-app.zwbq.shop',
  'jpmorgan9webio.com/',
  'https://cltl-00.herokuapp.com/login',
  'boaonlineverified.com',
  'uspalterigt.info/wt2e',
  'https://user-bo2faedd.com/edd',
  'senatedoublet.com/HU8KRY',
  'areanitrogen.com/Leye1E',
  'http://balancediameter.com/H10QLy',
  'https://ishurl.info',
  'https://visa-reactivate.info/index2.html',
  'http://moreshrill.shopping/PkRvik',
  'http://arsenicbon.shopping/tFet5j',
  'https://tinyurl.llc/FAtW7F',
  'http://tinyurl.com/u8bvs55',
  'mim342.com/e1630/75b822a',
  'bdhicy.com/okrWt',
  'chl8vo.com/ykrrb',
  'comfortstale.com/elPdWW',
  'wlness21.com/3qOV',
  'b806l.me/duNccdX',
  'veilknitting.com/y8mXEyk',
  'spongelowering.com/fxxgMDq',
  'https://oldrow.vias.ms/jo8sP',
  'yrt1x.info/RbGWPZ6FRQ',
  'cpqsz.cc/DwFK192',
  'meF92.COM/xMvLZnnJvP',
  'https://nfcu01login6h.finixp.org',
  'https://nfcu01b-sign00.gipsitv.org',
  'https://miborealityasociate.wixsite.com/mibor',
  'http://jmp.su/vrfy',
  'himeji.sutekinet.info/rank.cgi?mode=link&id=201&url=//nxm.us/ivXmv',
  'https://e.vg/GJZPS',
  'NU711.iNfo/ph9mqgxzrR',
  'https://network3.blob.core.windows.net/twhqvz/twhqvz.html',
  'https://mobile1.blob.core.windows.net/25897/25897.html',
  'Oprahstoday.com',
  'oprahstoday.com',
  'http://www.web.billing problem3868.b3k5h.com',
  'www.OprahDeals.sbs',
  'laughramble.com/67YLUw',
  'www.Oprahs.diet',
  'http://qr.co6.info/ui69',
  'http://sidedeity.finance/lgUzySA5',
  'http://e-d-d-safety022.duckdns.org/a',
  '3woe.xyz/bApNnm3lur',
  'https://l.ead.me/Amazon-Account-Verify-ID9517453',
  'https://lindsy352.preview.softr.app/?t=1659623895934',
  'https://notification-accountid.lnk.to/resolveaccount?secure-acoount&?=https://amazon.com',
  'swellingcipher.com/wnX1r9',
  'appliedtriumph.com/HW3SV3',
  'encumberrapidit.com/b4xUQc',
  'slanderchapter.com/LC6JHd',
  'spikefibrous.com/TrarTX',
  'quotienteminent.com/UbMa99',
  'http://lossfighting.com/5D2wSz',
  'http://securitywe.yokohama/s4Wm9i',
  'http://seizingblessing.directory/BZnYMyug',
  'aaprmm6pc2.co/5zoily',
  'http://addressknowing.digital/UOCLWkls',
  'http://voicetabular.boutique/ju67rmG2',
  'ng4kaszp8.co/4apued3m',
  'jkigr.cc/IB5sXLZ',
  'idwaxp51og.co/a09c',
  'egxi6aqx8r.co/zz5welj',
  '5wac5ltscn.co/oaktfqv',
  'a56cyklri.co/1hyv3',
  'kh5niapbp4.co/fs4h',
  'https://gotommbr.myclickfunnels.com/',
  'https://lnkd.in/eZXKcEdF',
  'https://kstu.hair/rbZ4A68x',
  'https://bit.ly/3NhkqSn',
  'https://s.id/1tuDl',
  'https://profib04.com',
  'https://usp-sptcn.top',
  'upsshipping.io/keGL6LxbyYpQN8z',
  'uspstrack-ot.info',
  'http://boardingma.shopping/fEXyQZ',
  'https://sec03boa.com/bRZQK',
  'scnv.io/vbVM',
  'http://usedps.com/go/Tracking/Q11U3',
  'ptycglvlogd.info/Rdeu',
  'Https://www.UnionBank.Org_@bit.ly/3T1lhlE',
  'http://s953782679.onlinehome.us/custapp',
  'upsshipping.io/keGL6Lxb21O9aom',
  'http://myverifylink.cf',
  'http://mobile.vzw.com/paybill',
  'b2gxv.info/5ssC5f2SEG',
  'https://zgz.nu/df9aoZbT',
  'thomasanquetin.com/wVAFt7',
  'https://ee.uk.billing45.com/?ee=2',
  'dawlmterreabrbie.com/phone.html',
  'www.ClaimRefund.info',
  'Inkd.in/gHghxQ3U',
  'https://www.weblaunch.hu/free/main38/mail?=749000072',
  'http://s955064170.onlinehome.us/itsy?_glbsas',
  'http://s954844695.onlinehome.us/act?_recovrAccount',
  'POSC9.XYZ/YgSpZZjZoh',
  'http://restart-membership.com:911@s956455895.onlinehome.us/atcc/?_pagesxacctx',
  'WOTw1W3X.safelinkamz.us/?UserID-IAIUF',
  'https://website.roomraccoon.com/free/help96/mail?=70352032',
  'http://s953495841.onlinehome.us/fix?_recovrAccount',
  'whatsapp://chat/?code=GOCVGBKOzmb0FmmQBgwddb',
  'http://s953223476.onlinehome.us/',
  'http://s954845653.onlinehome.us/global-umbrella/?_wof2fjhboo',
  'http://s952788954.onlinehome.us/?snpl_2_1_db77b4d1',
  'http://conquerpassing.com/L7NHjn',
  'http://s950712130.onlinehome.us',
  'http://healthdoor.boutique/d8uGZhsJ',
  'mla0q2djmf.co/jszuy',
  'nearhonor.com/dZDijo',
  'oprahstoday.com/',
  'https://forms.gle/wfmtmZUfZ7d5bcJX6?XujiLSn',
  'chatwhatsapp.me/aXclhpU4CXfm5',
  'idlenessflame.com/rJRcsY',
  'oprahstoday.com',
  'nearhonor.com/dZDij0',
  'www.xuwk4v-upsa.us//6qj9ihch18920#',
  'centurysever.com/2MbuXy',
  'hub7news.com/s',
  'www.CelebTMZ.buzz',
  'http://wreathcrossbow.com/ZpRotm',
  'http://ups.comw-ykgedh.world//1qsyl3rv21',
  'x0ang.info/hYE427wAom',
  '9qr.de/itCwLh',
  'https://wellsfargo-zellepayment.com',
  'whatsapp://chat/?code=15Ro5nXJ3Eml36gE3JZk7Taf',
  'https://web21cen.in/boal/',
  'www.nlrhc5m-upsi.us//na76f5Cg48967#',
  'http://hireprevio.shopping/ybFO3G',
  'http://profaneblo.yokohama/DhA4u1',
  'https://tinyurl.com/2e2e85bw',
  'eb4.us/a4f64a26',
  'http://tonestrength.financial/7Mu7T15C',
  'https://forms.gle/tmfZY2iQzA9T6x557',
  'https://app.mailingboss.com/index.php/campaigns /63857c6fb397b/track-url/637fa8badd3d6/3143bbe318bdc11cead986a59dae0d6178a579c8',
  'https://mortgageassociatescc.com/acr/Alturacu',
  'http://inflatecoupling.ventures/10EcgOrr',
  'juytrplmwsaqz.us',
  'e103c-ups.com/?=bej',
  'lnkd.in/g7jb5b_7',
  '6psf.solvemember24.us/?sign',
  'https://tinyurl.com/23wkrzag',
  'https://bacindustries.net/alco/Alturacu',
  'https://t.sidekickopen08.com/Ctc/ZW+23284/d2L62N04/Jks2-6q7W69sMD-61Z3n9Vdtpvg7LJvhMW5jSbD87kc71kW103fBL4gPLTCW3K91zv2ytvNsW1fx5Cd3Zqjk7W6FfBYc8IRJblW8XpKWs2sSQBW5nWF306GCrzmW5t4C4v5fQwXqW2K9qlp66PXLN24kyHb5t 9MYW5nqwB51mh8SQW3Xb6jk7tX9bnW7kQV7k5-K0XtN4ZF-VJmKRFSN5wlqLPkwpBVW4F59Gr2CbBpMW62YzRH7mqGj8W3nchGr3Xq-YZVzV_dk43ys-Gf1pMH7604',
  'eb4.app/dfd5982b',
  'https://api.hubapi.com/Ctc /ZW+23284/d2L62N04/Jk82-6q7W5BW0B061Z3plW6qjYVj6j Nbb9W75Vnln5G61ZvW1vhZtP53vtK-W8vnQN336nW6KW556BxQt7bXvSXW7bbhZ06Vfc7W4p1C3V6ILh0sN7wPGFJDs5RVW277m1-1vHbvXW2mS7Fj1q2c LYVCHGwQ40KIpqW515nb68m6k r2W1xmilR64Z56HW6hqvCf6MpBRmW2n9YNB8cLk0ZW461PgF8KdXJTf1tQhmP04',
  'fartherpgmonarch.com/PbjiVby',
  'https://bit.ly/3SIKE1M',
  'http://www.bizzapp.co.uk/free/apps51/service?=61513',
  'https://usp-swexy.top',
  'http://www.bizzapp.co.uk/free/apps51/service?=61513',
  'buyelect.co',
  'tidenet.co',
  'http://justizama.mx/visaprepaid/edd/first.htm?dKWrvyq1b2pKb7EyPv6T40yvce gR6EsgyEXA1ljmb0YYboEnsGvFXUwAslrbUhofCix4TnfW1c2KvWNSAm4alG30Khf2Rn9NamNMguHpHSQof8T6U3zDECrWiCrpe96umQHD3',
  'theusaloanhunters.ai',
  'https://tiny.one/myfedex871',
  'sdgfhd.com/egMo5mz',
  'http://stupiduneasy.financial/RBMwGXCm',
  'http://considerstill.ventures/gPRjYtsl',
  'http://intriguehardy.directory/TTjI4KRA',
  'http://tenorlegal.directory/VHGtoA8j',
  'Https://www.UnionBank.Org_@nx.tn/EjmCx',
  'http://s956826982.onlinehome.us/wbsspc/?_undrscan',
  'https://s.id/1rAQj',
  'https://td.my-authentics-easyweb.com/t?d',
  'consensuscelebrated.com/5hTSjyzHWc',
  'https://accessrestorenow.netlify.app/',
  'regionscardalerts.com',
  'https://si-rbcroyalbank.com/',
  'uspdelmvsub.info/Resd',
  'https://gosq.me/u/kNS5i2GG',
  'https://cya.nz/4UJQ',
  'https://usp-snavn.top',
  'oprahyes.com',
  'Kp7C1.shoP/GTxulg9ld',
  'v4.hvg.in/.861G6',
  'https://groupme.prizeforyou.site/',
  'groupm.è.to/wfELH?id=2f57943',
  'http://winner@3117711444/tpi23?id=2f57943',
  'help3720.pagetroubleamzcustomer.us/?id367',
  'supr.link/hrXyP',
  'twistedcapsule.com/dRBILnD',
  'geologypassive.com/PYNMIIL',
  'imperialautumn.com/QNmNNbJ',
  'vpmEvening49tw.4k1pkmal.in/#?.fkz2',
  '83hm2uaj.kzra.in/?/OVA013',
  'http://www.usinps.com/go/Tracking/D18P4',
  'https://pagesntflix.ffm.to/pb6d2yo',
  'm.eitdi.uspsdi.site',
  'https://is.gd/Ybkgm2',
  'unusa.id/4mx6',
  'https://wellsvalidate-0502.ddns.net/?online',
  'https://jenshade.com/onpoint/on/org',
  'https://visitusbnks1.com',
  'whatsapp://chat/?code=FefWD5h8rsd5u4qlcZlelk',
  'https://rb.gy/00dc0',
  'whatsapp://chat/?code=BjRONw5G6rTFovXUNQ799f',
  'http://updatebillingpage.us:911@s957584550.onlinehome.us/nod',
  'http://s956826982.onlinehome.us/wbsspc/?_undrscan',
  'http://s953131863.onlinehome.us/authcust',
  'http://membershipnetflix:911@s955861601.onlinehome.us/mo',
  'https://billingupdate.tvymdlywoxxc.com:911@normaly-run.000webhostapp.com/gac',
  'http://netflixaccount.node:911@env-7112168.node.cloudlets.zone/',
  'https://restartmmberswebsite.uscreen.io/',
  'http://s953340691.onlinehome.us/sport/?InfoAccnt-9xzlmd7nv7',
  'http://s953190961.onlinehome.us/?_recovrAccount',
  'www.linkedin.com/slink?code=d8KfdKXY',
  'http://s948917531.onlinehome.us/',
  'https://gotoupdtmembershp.dotcompal.co/gotoupdtmembershp',
  'https://mmbrshipupdtflix.myclickfunnels.com/?renews',
  'http://unbouncepages.com/accnt-sginupcontinues12512/',
  'oprahstoday.com',
  'http://unbouncepages.com/multor-1431245305/',
  'http://unbouncepages.com/9cab67538ed2d7d7dc4606a61d2d4ba1/',
  'https://qr.io/r/GJ1jvX?amazon-billing-update&?=https://amazon.com',
  'https://chat.whatsapp.com/IbhbaL5NHtbDyMz910Jumj',
  'https://wa.me/13213360655',
  'https://wa.me/1607599596',
  'https://chat.whatsapp.com/',
  'https://chat.whatsapp.com/HqlT2mgLcHQCOwoq4vJ62N',
  'https://tinyurl.com/TOR7zfT',
  'whatsapp://chat/?code=Jhg4JbfHxgplRPfeSxakwK',
  'whatsapp://chat/join/?code=KitRluT3zBxDiLCOMxnDsN&nkdc-qafokl',
  'https://storage.googleapis.com/nvulmar/bbbd4mo',
  'http://107.175.219.12/ipad.php',
  'http://107.175.219.12/Depot.php',
  'https://bit.ly/3ErwRWW',
  'http://109.236.50.8/CST.php',
  'http://194.87.140.6#yfuy.php',
  'http://3260518391/co.php',
  'http://3260518168///i13.php',
  'http://194.87.143.43///w.php',
  'http://194.87.141.136///E.php',
  'e3fmr.info/onAyXsVfomA',
  'bedy13.com/V3n4Ovhcqw',
  'offer.1nuniyaz25qx.co',
  'https://gov-tax.refundpr.com/',
  'netflixhelpsupport.lpages.co/support',
  'u5fxc.info/ZEJTTZmY3Z',
  'https://app.atlcunion.org/a0c418',
  'https://tinyurl.com/q2Zn514',
  'whatsapp://chat/?code=BB18Umbcmbp3v5H6pu9igX',
  'whatsapp://chat/?code=Du6Jp7K4UmH8f7pi1rGeys',
  'n5d4q.info/KmxyTy5uNN',
  'SG201.com/OwWSP7qcg6',
  'https://urlsr.com/LY9llxL ',
  'https://kirjaudu.latodesign.fi/free/main15/usa?=541996820',
  'https://is.gd/Ybkgm2',
  'https://223ncitihelp.com',
  'https://cberrorfix.me/3NX',
  'https://bit.ly/3Nx3ar6',
  'https://bit.ly/3wl5Dzg',
  'acct.encryptbegin.com/d8bcm',
  'https://go.cb-w.com/gz3J1Hsfjpb',
  'https://rebrand.ly/x9ui63o',
  'https://vons.onelink.me/MuHG/s37kcrr2',
  'https://onelink.to/memberbils.com_dir.p',
  'https://is.gd/ZjGmy4',
  'https://msgdeal.co/G2j9w',
  'unusa.id/2u3l',
  '8pt21.scr-tyalrt5.us/?UserID-IOCDCZKFAK',
  'o15z5.hcya-svka.us/?UserID-ODPCRHZKOR',
  'https://msgdeal.co/G6CLH',
  'http://s957290943.onlinehome.us/ foldkws/?_rswasscs',
  'bit.ly/profileGB12RD',
  'notbankofamerica.com/XJY23VB',
  'bit.ly/yourprize001',
  'loweringpriest.com/9jEIG8y',
  'suitaccess.com/EWRB6DF',
  'https://stews.mom/JTsRpeLZ',
  't.ly/IqtWq',
  'n6u.me/RIBSH',
  'f94.us/VrVwq',
  'https://www.2netflix-mybilling.com',
  'apt8413-wellsfargo.3utilities.com/bcouu',
  'hse.service-report.com/?book',
  'prhomitaddr.info/Mfwe',
  'https://pmx565wc7sg5.swipepages.net/KrFSt25',
  'https://manage-acrwg.drr.ac/?confirm',
  'Oprahsgiveaway.com',
  'https://securfyied.000webhostapp.com/auth2',
  'http://s953909557.onlinehome.us/servweb',
  'http://s953643025.onlinehome.us/preprefix?_recovrAccount',
  'bq034a.989e.co',
  'http://s952880411.onlinehome.us',
  'http://venmoaccount.node:911@env-2404935.node.cloudlets.zone/',
  'http://s950928458.onlinehome.us',
  'https://fix-account.ffm.to/limited',
  'https://ffm.to/plans-membership',
  'http://www.netflix.com:911@s955054819.onlinehome.us/mo',
  'http://s954071710.onlinehome.us/fixacs?logs',
  'http://membership-normally.com:911@s956520694.onlinehome.us/atcc',
  'https://bit.ly/3xmZNuq',
  'kztpr.cc/toDJoir',
  'bitly.com/helpEDD',
  'http://chat.whatsapp.com/HLdIKFgZf72BZh3CM5Q5sO',
  'http://drilldeliver.com/xbgssimr/BmzxcMn',
  't.me/JRE7708',
  't.me/+447864529328 Janey6583',
  'tinyurl.com/Kelseygame52',
  'https://twtr.to/YOLA',
  'https://wa.me/77788385297',
  'tinyurl.com/Rauchk',
  'c7dvr.info/FGdGtk12vilM',
  'unusa.id/csv8',
  'kxy.ps34.xyz/DfVPnmbxXR',
  'www.citibankvalidation.com',
  'l.ead.me/Vg8TrwQG',
  'https://tinyurl.com/1tr77g0',
  'http://usedps.com/go/Tracking/Q11U3',
  'http://xn--80aaahorunoimsf3p.xn-p1ai/authcus/',
  'http://updatebillingpage.us:911@s956956807.onlinehome.us/swg',
  'https://accscrues.ffm.to/wzd7jar',
  'https://onelink.to/mmbershippos.co_di.p',
  'https://tki.lol/rd/c8095gMcsB282065YswP1678Ydc4104XBky417',
  'http://pmbox.online/4UWqiD288PcPb7meokxwnhfo1YYRFWVNSQEUQXDH101630/79654a11',
  'qrco.de/bdn5yo',
  'Xbfool.com/2bJUlu',
  'https://onlinefrontwavedata.web.app',
  'https://chat.whatsapp.com/LJDHNf8VNXpFOYjK6QQOaB',
  'http://www.uskps.com/go/Tracking/G2T22',
  'a4nrv.info/YCdfXPIKIp',
  'whatsapp://chat/?code=KGGDbfgVo337hX6umWORvx',
  'sec1urd3-deprtmnt12.com/index.php?sy1t90 ',
  'https://ab.gl/CMSbi',
  'shorte.be//f?$=62344?2619646 ',
  'bit.ly/3hmasAg',
  'https://bit.ly/42GN8U0',
  'https://chase01bsec.com/?dpck',
  's.id/1vjjp',
  'https://wwww.soporteappleld.ocppl-com.de/25t6r/',
  'wowgo.app.link/luAzIC',
  '7knfu.za.com',
  'http://voicetabular.boutique/3djn3c6x',

In [19]:
smishtank_data.pop('URL')
smishtank_data['Unique Url'] = list(unique_smishtank_url)

In [20]:
import tldextract

def FQDN(Url):
    
    url_extract_res = tldextract.extract(Url)
    fqdn = ''
    if url_extract_res.subdomain:
        fqdn = url_extract_res.subdomain + '.' + url_extract_res.domain + '.' + url_extract_res.suffix
        # fqdn = url_extract_res.domain + '.' + url_extract_res.suffix
    else:
        fqdn = url_extract_res.domain + '.' + url_extract_res.suffix
    
    return fqdn

In [21]:
smishtank_data['FQDN'] = [FQDN(i) for i in smishtank_data['Unique Url']]

len(set(smishtank_data['FQDN']))

740

In [22]:
a = soupFromUrl('https://facebook.com')

print(a)

[73360, 645, 200, 0]

In [55]:
# nus_dataset = pd.read_csv('../Dataset/URL Data/NUS Websites Analysis.csv')

The below query last ran on 9 Jan 2025

In [23]:
website_size, text_content_length, status_code, parked = [],[],[],[]

for i in smishtank_data['FQDN']:
    a = soupFromUrl('https://'+i)

    website_size.append(a[0])
    text_content_length.append(a[1])
    status_code.append(a[2])
    parked.append(a[3])


# parked = [0]*len(nus_dataset)

# for idx,i in enumerate(nus_dataset['FQDN']):
#     if nus_dataset['Status Code'][idx]==200:
#         a = soupFromUrl('https://'+i)
#         parked[idx] = a[3]
#         # break

# print(parked)

In [24]:
smishtank_data['Website Size in KB'] = website_size
smishtank_data['Website Textual Content Length'] = text_content_length
smishtank_data['Status Code'] = status_code

smishtank_data['Parked'] = parked

In [25]:
for i in smishtank_data:
    print(len(smishtank_data[i]))

860
860
860
860
860
860

In [26]:
smishtank_data

{'Unique Url': ['83hm2uaj.kzra.in/?/OVA013',
  'https://usps-intend.shop',
  'https://aritc.yru.ac.th/redirect/78?url=bit.do/jmelgrud',
  'http://site.rdv360.com/free/main45/mail?=924514',
  'https://urlsr.com/LY9llxL ',
  'https://delivery-customscharges.com/',
  'https://rebrand.ly/grppwwr',
  'https://irs.gov.secure-fundhub.com',
  'https://unzups.com',
  'http://xtfpnp.com/Q2osg44',
  'https://groupme.prizeforyou.site/',
  'tidenet.co',
  'http://107.175.219.12/Depot.php',
  'reamvino.com/SvjMeq1eKD',
  'www.ClaimRefund.info',
  'remedyfr.com/index.php?key=d2jqpwg6d7a2uz7cs98z&h=GOGlqvlGm',
  'chatwhatsapp.me/aXclhpU4CXfm5',
  'lksr.link/9pvvbF',
  'n5d4q.info/KmxyTy5uNN',
  'http://pslajs.com/ROpuoXO',
  'https://api.hubapi.com/Ctc /ZW+23284/d2L62N04/Jk82-6q7W5BW0B061Z3plW6qjYVj6j Nbb9W75Vnln5G61ZvW1vhZtP53vtK-W8vnQN336nW6KW556BxQt7bXvSXW7bbhZ06Vfc7W4p1C3V6ILh0sN7wPGFJDs5RVW277m1-1vHbvXW2mS7Fj1q2c LYVCHGwQ40KIpqW515nb68m6k r2W1xmilR64Z56HW6hqvCf6MpBRmW2n9YNB8cLk0ZW461PgF8KdXJTf1tQhmP04',
  'https://onelink.to/mmbershippos.co_di.p',
  'www.awqvfz.rip/16logt',
  'whatsapp://chat/join/?code=KitRluT3zBxDiLCOMxnDsN&nkdc-qafokl',
  'http://www.xprswebsite.com/free/usere444/redire444/?=3458455',
  'unusa.id/9rua',
  'saismbb.com/03bMrEEM',
  'https://rebrand.ly/tw0ajjr',
  'https://secur-34b0a-protect.duckdns.org/auth/',
  'https://jf245-fedex.me/y.jDxio?37588372',
  'https://chat.whatsapp.com/K106E9p3FvgAhOIYE5MA8v',
  'getcash.hellofunds.space',
  'https://Cibc-security-department2023.com',
  'help3720.pagetroubleamzcustomer.us/?id367',
  'https://rb.gy/00dc0',
  '2ax.com/K0gU1',
  'BankOfAmericaDebit05.com',
  'https://scre-bollafca.live/login',
  'https://link.aftership.com/3SeJ6',
  'http://zvsjxy.com/4qAcRgK',
  'http://194.87.141.136///E.php',
  'ptycglvlogd.info/Rdeu',
  'puX30.com/5q5PfG9Xhm',
  'https://www.hympes.com?token=kLiSsmaTxrkYPhNN',
  'https://usps.trckingstamp.com',
  'http://cggcvt.com/J24sll9',
  'https://unileverplcpromo01.wixsite.com/wrap',
  'https://bit.ly/3SIKE1M',
  'warrantgeneration.com/RsCoLlrDrs',
  'http://account.my-profile-33923332.com',
  'risu.io/e75CA',
  'https://citizen3.swaratechnology.com/indexs.php?inc',
  'https://tools.usps-type-in.com',
  'http://kjhcmb.com/7wEf2VN',
  'http://winner@3117711444/tpi23?id=2f57943',
  'flimsyfooting.com/RugSJP91a6',
  'https://me2.do/GBIOwzEt?V4ZGKR',
  'https://tinyurl.com/7jvV5nL',
  'https://uspspgcm.com',
  'https://usps.myservice-tracking.com',
  'hwqpzhm.com/QVdV9ppD',
  'sexyjessie.us',
  'https://accessrestorenow.netlify.app/',
  'ju11n.xyz/hXwQ9T2DpP',
  'anniversarys-mag.jp/urls?mode=go&pageid=2660&url=golnk.eu/fPjTwhgdgdgzjgfjdg#pihcl',
  'approvedlink.info/pvKdPvhsrMpn',
  'https://uqfups.com',
  'jpmorgan9webio.com/',
  'http://prmytz.com/9yJfrBg',
  'o15z5.hcya-svka.us/?UserID-ODPCRHZKOR',
  'http://checkthis1.info/g5L6DJmM2F',
  'https://chat.whatsapp.com/E29ZpfVxDLCDU0lz6g5Pju',
  'd8iHL.Com/RjS6w33AXD',
  'spikefibrous.com/TrarTX',
  'vocalsprolonged.com/ZSgingd6vi',
  'YR431.coM/KDO0JQ9MWE',
  'https://s.id/1rAQj',
  'Xbfool.com/2bJUlu',
  'https://billingupdate.tvymdlywoxxc.com:911@normaly-run.000webhostapp.com/gac',
  'http://gs80xb1u7wy5vb.deals',
  'https://cashrequestonline.com/?cguid=eae2fef9-2d38-4ae3-bec4-e4084991f38d',
  'https://my-trufl.com/TZWF37FdJ05',
  'https://usps.address-trace.shop',
  'https://uspyk.top',
  'http://www.usinps.com/go/Tracking/D18P4',
  'risu.io/fTVXM',
  'https://wsends.com/go/Tracking/R2H9',
  'whatsapp://chat/?code=BjRONw5G6rTFovXUNQ799f',
  'http://194.87.140.6#yfuy.php',
  'boaonlineverified.com',
  'https://frontiershopper.com/apply-now/',
  'https://citi-06.com',
  'prhomitaddr.info/Mfwe',
  'http://wealthaccept.financial/94T4CvdP',
  'http://wQXr2BUNaEJEntqhluMkYi.media',
  '6psf.solvemember24.us/?sign',
  'https://flexalert.link/fourtonine?id=66ZA',
  'http://gghcfp.com/ImZsmDB',
  'http://healthdoor.boutique/d8uGZhsJ',
  'https://irs.gov.direct-paying.com',
  'http://tftjrl.com/8xGFWIB',
  'http://justizama.mx/visaprepaid/edd/first.htm?dKWrvyq1b2pKb7EyPv6T40yvce gR6EsgyEXA1ljmb0YYboEnsGvFXUwAslrbUhofCix4TnfW1c2KvWNSAm4alG30Khf2Rn9NamNMguHpHSQof8T6U3zDECrWiCrpe96umQHD3',
  'irs.gov.direct-capitals.com',
  'gh196.COM/79HAVH1xY8',
  'http://www.web.billing problem3868.b3k5h.com',
  'aprpok.com/2pRGFz',
  'http://uspsdeliveryrd.ga/',
  'regionscardalerts.com',
  'f2gpy.info/RzNKEwsZve',
  'http://neckadvice.financial/PWvk1Wpa',
  'http://augmentreversed.com/KIZWr1',
  'https://si-rbcroyalbank.com/',
  'wowgo.app.link/luAzIC',
  'irs.gov.direct-paying.com',
  'http://arsenicbon.shopping/tFet5j',
  'Inkd.in/etiYT6vd',
  'wepay-topvalue.com/bf2f414d45',
  'http://s953131863.onlinehome.us/authcust',
  'https://ffm.to/plans-membership',
  'https://chat.whatsapp.com/',
  'https://www.after-salescenter.win',
  '2.approvedurls1.info',
  'https://rb.gy/x178u',
  'usps.uspsgu.com',
  'http://ywrfyp.com/VkwuzqG',
  'u1.mnge.co/DJ8PKA',
  'https://ab.gl/CMSbi',
  'areanitrogen.com/Leye1E',
  'https://bit.ly/35Xs2rW',
  'disciplepurse.com/HvMe3JH',
  'https://uspxzpl.top',
  'state.goo.gl/tap-',
  'https://tinyurl.com/23wkrzag',
  'Kp7C1.shoP/GTxulg9ld',
  'nearhonor.com/dZDijo',
  'http://eddphelp.info',
  'Regions-PROTECT.com',
  'https://bit.ly/3shWipe',
  'https://mortgageassociatescc.com/acr/Alturacu',
  'http://netflixaccount.node:911@env-7112168.node.cloudlets.zone/',
  'POSC9.XYZ/YgSpZZjZoh',
  'https://usps.trckspost.com',
  'http://www.xprswebsite.com/free/userf111/redirf111/?=5826865',
  'http://pricesever.financial/j07mFgmb',
  'https://cheapauto.coverages4.me/XL1isumEsTX3',
  'https://oasioa.cf/wellsfargo.com/?restore',
  'https://win22.org/r.wr?id=9wJ8pTXh',
  'yrt1x.info/RbGWPZ6FRQ',
  'https://tinyurl.com/2e2e85bw',
  'chl8vo.com/ykrrb',
  'wfmobi1r3st.com',
  'https://mobile1.blob.core.windows.net/25897/25897.html',
  'http://pqlhvds.in/40611',
  'https://website.roomraccoon.com/free/help96/mail?=70352032',
  'https://bit.ly/3ErwRWW',
  'http://nfcucardservices.org',
  'https://nfcu01b-sign00.gipsitv.org',
  'https://chat.whatsapp.com/IbhbaL5NHtbDyMz910Jumj',
  't.me/+447864529328 Janey6583',
  'https://fix-account.ffm.to/limited',
  'https://wwww.soporteappleld.ocppl-com.de/25t6r/',
  'usps.upspb.com',
  'http://broug.training/lu89eN',
  'https://shb52.app.link/K5KjPGI',
  'spongelowering.com/fxxgMDq',
  'http://updatebillingpage.us:911@s957584550.onlinehome.us/nod',
  'hub7news.com/s',
  'c7dvr.info/FGdGtk12vilM',
  'https://wfveri-info.com',
  'naturalcbdcoffee.xyz/1X0g3jAK5n',
  'x0ang.info/hYE427wAom',
  'https://tinyurl.com/TOR7zfT',
  '61uxsyo.qmrWM.Com/zyd8',
  'tc60gwozak.co/vyrgtrgd',
  'rebrand.ly/usp36',
  'notbankofamerica.com/XJY23VB',
  'https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIKWdsW0yxEjajBLZtrQAAAAAAAAAAAAMAAFKUZBIURFg1TU8wQlhSTVBSSKJHSIhRSU1YROJHUS4u',
  'nfcualert.site',
  'https://cberrorfix.me/3NX',
  'https://photo.a4d8.us/xnhbmikwu',
  'http://seizingblessing.directory/BZnYMyug',
  'http://194.87.143.43///w.php',
  'https://wa.me/8801909866268',
  'https://www.assistance-usrprocess.com',
  'whatsapp://chat/?code=Jhg4JbfHxgplRPfeSxakwK',
  'mentioningdears.com/nzWjdtrM93',
  'http://pmbox.online/4UWqiD288PcPb7meokxwnhfo1YYRFWVNSQEUQXDH101630/79654a11',
  'https://uspbb.top',
  'bit.ly/89BNsg81289',
  'https://chat.whatsapp.com/DwgaJGaBiUW3PLPfszRsuf',
  'https://tinyurl.llc/FAtW7F',
  'https://onelink.to/memberbils.com_dir.p',
  'igyre.cc/Kky7RkR',
  'http://prettyplump.directory/DFzOyZtj',
  'http://www.netflix.com:911@s955341113.onlinehome.us/ven',
  'v4.hvg.in/.861G6',
  'gt33.pw/snlXXnncQ3',
  'onx.la/00cfc',
  'slp2.xyz/sPldg93jsOW7',
  'e103c-ups.com/?=bej',
  'http://tvmscy.com/B2VSOWO',
  'tinyurl.com/Rauchk',
  'https://miborealityasociate.wixsite.com/mibor',
  'https://chat.whatsapp.com/HqlT2mgLcHQCOwoq4vJ62N',
  'rlwrr.info/d4csZAeztK',
  'quotienteminent.com/UbMa99',
  'https://www.rodvsps.com/go/Tracking/U1A21',
  'http://nfH5FwiU9mht56ku.homes',
  'https://saveonautocoverage3.me/1nhQEbD4FaH6',
  'ibii.me/JA9wQ3',
  '8pt21.scr-tyalrt5.us/?UserID-IOCDCZKFAK',
  'http://vcljcy.com/rvjF706',
  'whatseehere2.info/fDoWou',
  'https://romualdo.exe.it/AKARA.html',
  'http://abundantbis.limited/x7iLqJ',
  'encumberrapidit.com/b4xUQc',
  'https://rebrand.ly/v7qj08h',
  '7knfu.za.com',
  'chaselocked.com/web',
  'https://t.snapchat.com/ruoK9x3T',
  'https://lnkd.in/eZXKcEdF',
  'http://hygrjv.com/2oyhOQV',
  'http://voicetabular.boutique/3djn3c6x',
  'http://alert-comerica.com',
  'wklnv.me/nK7NWdxQXN',
  'http://r2s9hq82ne.mmnrxeqmcv.nikxc.org',
  'http://psjzzw.com/no2hgVq',
  'http://attorneyent.limited/S7cW3A',
  'iziroz.online/92N1ZWO',
  'http://obliquerupture.directory/rvgFs6Ae',
  'http://pendulumexchange.directory/MVanC60M',
  'clickherenow.me/YSOHESIZ',
  'https://t.co/qVM5acOYOu?qrxxsviswlr',
  'j2xnc.info/Nqc7tV1FoELv',
  'https://www.ussoton.com/best',
  'http://tbmuy.ncmie.com',
  'chatatwhatsapp.me/higiKhAE9VALifa',
  'https://www.utpht.com',
  'https://network3.blob.core.windows.net/twhqvz/twhqvz.html',
  'http://wreathcrossbow.com/ZpRotm',
  'https://usps.com.uspqq.shop',
  'upsshipping.io/keGL6Lxb21O9aom',
  'l.ead.me/Vg8TrwQG',
  'http://apartnerve.florist/Qd8qKU',
  'http://rgjgj.capital/i16nf0',
  'http://s953782679.onlinehome.us/custapp',
  'https://upspups.com',
  'http://slzbyy.com/GvR0t2ZV',
  'himeji.sutekinet.info/rank.cgi?mode=link&id=201&url=//nxm.us/ivXmv',
  'https://www.weblaunch.hu/free/main38/mail?=749000072',
  'https://ee.uk.billing45.com/?ee=2',
  'https://jenshade.com/onpoint/on/org',
  'Oprahstoday.com',
  'bit.ly/navyauth',
  'uspalterigt.info/wt2e',
  'http://s950928458.onlinehome.us',
  'bit.ly/FCCHsurvey',
  'dirqzoc.com/xAW58d60',
  'https://brightvision.edu.pk/ca/verifyedd',
  'https://bit.ly/3wl5Dzg',
  'http://inflatecoupling.ventures/10EcgOrr',
  'https://ideastransparentes.com.ar/cabz/verifyedd',
  'aib-onlinesecurity-access.com',
  'qrco.de/bdn5yo',
  'https://visitusbnks1.com',
  'https://bit.ly/3v9zXuH',
  'http://operateepidemic.com/sotelQ',
  'ct-id2.me/?verify',
  'pbizzz.com/J44rCi',
  'gpmkg0.online/Ym5Yb',
  'tinyurl.com/y22vnsel',
  'gpnmxqy.com/D1GN3RBE',
  'Us5nn.com/T201tztu1A',
  'vbvnejt.com/rNG9GKNN',
  'unusa.id/4mx6',
  'https://canadaclimateincentive.ca',
  'http://ytdbby.com/A2RsGxy',
  'qinpwhe.com/xA9dXLMD',
  't.ly/IqtWq',
  'https://accounts.snapchat.com',
  'http://resolveeddcards.com/reopennow',
  'senatedoublet.com/HU8KRY',
  'http://dtwxzf.com/003u52r',
  'https://kirjaudu.latodesign.fi/free/main15/usa?=541996820',
  'https://irs.gov.safe-ordering.com',
  'https://usps.tirckposts.com',
  'slanderchapter.com/LC6JHd',
  'du9k3.com/rvirONcqBD',
  'https://usvnwcy.top',
  'http://zireesso.shop/cl/5233_md/555/57333/1230/70/53367 ',
  'http://107.175.219.12/ipad.php',
  'kmhgsq98am.co/3injuan',
  'http://s953190961.onlinehome.us/?_recovrAccount',
  'kztpr.cc/toDJoir',
  'http://s952880411.onlinehome.us',
  'http://s954845653.onlinehome.us/global-umbrella/?_wof2fjhboo',
  'https://tki.lol/rd/c8095gMcsB282065YswP1678Ydc4104XBky417',
  'https://uqbaos.cc',
  'http://s953643025.onlinehome.us/preprefix?_recovrAccount',
  'www.nibtt9-upse.us//vofxbnno224123#',
  'l.coincircle.com/ajSb',
  'http://tinyurl.com/u8bvs55',
  'http://voicetabular.boutique/ju67rmG2',
  'http://jmp.su/vrfy',
  'setmade.online/4jdEbEK',
  'https://usps.com@bit.ly/30FnJ7c ',
  'http://myverifylink.cf',
  'https://usps.mytrackr-uspcex.shop',
  'http://ryjlvn.com/P9nu967',
  'https://usuasco.top',
  'https://forms.gle/gxXAfiJ2Gc2GvDLs6?JSRAOJLDWYJS',
  'https://wwj4w-fedex.us/jWXHwj?47965169',
  'www.citibankvalidation.com',
  'https://msgdeal.co/G2j9w',
  'https://usps.track-pkg.com',
  'whatsapp://chat/?code=BB18Umbcmbp3v5H6pu9igX',
  'http://unbouncepages.com/accnt-sginupcontinues12512/',
  'https://uspsair.com',
  'hlkdved.com/JZeAgzn5',
  'https://msgdeal.co/G6CLH',
  'sqanzq.com/cb8183',
  'http://gkkn.site?USBANK',
  'http://processingprotection.me/JaZcP',
  'n6u.me/RIBSH',
  'http://scienceb.associates/QN70Lb',
  'https://institutohaquira.ed',
  'v4fzc.info/CKQpOZrVXi',
  'http://rfhy.ps.com/6vDF7Xx',
  'https://sec03boa.com/bRZQK',
  '1',
  'https://usp-s.searchtd.top',
  'b2gxv.info/5ssC5f2SEG',
  'https://irs.gov.easy-transaction.com',
  'supr.link/hrXyP',
  'ng4kaszp8.co/4apued3m',
  'sirreeprematurely.com/X9cSSE4SfA',
  'affiliation.software/agrieuro/c47604-98571?url=https://Isto.me/n29v1?emfafu',
  'like2playnow.com/fi5dbp',
  'http://carecondemn.com/BYMRKW',
  'https://www.upotps.com/go/Tracking/G01U6',
  'kzrp1h.com/bff4948af7 ',
  'https://secur06-chase-verify.my03.com/?Verify',
  'http://moreshrill.shopping/PkRvik',
  'http://membership-normally.com:911@s956520694.onlinehome.us/atcc',
  'https://vons.onelink.me/MuHG/s37kcrr2',
  'http://s955064170.onlinehome.us/itsy?_glbsas',
  'https://poiasj5.cf/wellsfargo.com/?restore',
  'https://usppsn.top',
  'http://RBC-CANADA-Verify-Secure-Online.Com',
  'http://swhcdt.com/zErCE7I',
  'storage.googleapis.com/jzoxubc/1fhg3lf',
  'https://usps.intertrck.com',
  'http://cgmfdk.com/E2Ysk70',
  'http://restart-membership.com:911@s956455895.onlinehome.us/atcc/?_pagesxacctx',
  'http://leaseill.associates/b42TrX',
  'http://s953223476.onlinehome.us/',
  'ubavul.online/vT3LWrR',
  'k2ecs.info/jqC2Js4She',
  'https://usapsz.com',
  'https://t.co/o5v07fefr1?fmuxtuprck',
  'https://usqmvj.top',
  'ssg.gl/27130d',
  'f4RSX.COM/8vxyyUpY4d',
  'https://authority-ustesters.top/ ',
  'gps.ru/98hXb',
  'W3NGZ.COM/6blDog8jzc',
  'http://jryxlz.com/8xGFWJD',
  'http://www.netflix.com:911@s955054819.onlinehome.us/mo',
  'unusa.id/2u3l',
  'https://opnarchitects.wixsite.com/opn-architects',
  'https://www.2netflix-mybilling.com',
  'http://venmoaccount.node:911@env-2404935.node.cloudlets.zone/',
  'g3svc.info/0iSFCyr6Lb',
  'https://sotop-usps.top',
  'mustardobvious.com/Ouyhk7',
  'http://boardingma.shopping/fEXyQZ',
  'http://bit.ly/WHO-Jobs-Offer',
  'liftfor.online/t3W6FsY',
  'https://unblockbofaeddprepaid.meeha.com.bd/asdfghjkl.html',
  'http://wbfmqs.com/M2ksvNA',
  'whatsapp://chat/?code=GOCVGBKOzmb0FmmQBgwddb',
  'https://expected-uspg.com',
  'holdadorn.com/OK2ROKY',
  'https://qvay.app.link/e/VVhoag801tb',
  'https://pmx565wc7sg5.swipepages.net/KrFSt25',
  'https://uspuss.xyz',
  'bq034a.989e.co',
  'frische-lieferung-de.com',
  ' https://iaqwqqit.com/6ycyEm',
  'approved.rent2owncheaps.com',
  'https://uspsverify.org',
  'laughramble.com/67YLUw',
  'https://ishurl.info',
  'https://colegioina.edu.pe/nfcu/',
  'http://e-d-d-safety022.duckdns.org/a',
  'https://cltl-00.herokuapp.com/login',
  'b806l.me/duNccdX',
  'https://bit.ly/acpin',
  'https://iepsantodomingosavio.edu.pe/metama',
  'https://t.sidekickopen08.com/Ctc/ZW+23284/d2L62N04/Jks2-6q7W69sMD-61Z3n9Vdtpvg7LJvhMW5jSbD87kc71kW103fBL4gPLTCW3K91zv2ytvNsW1fx5Cd3Zqjk7W6FfBYc8IRJblW8XpKWs2sSQBW5nWF306GCrzmW5t4C4v5fQwXqW2K9qlp66PXLN24kyHb5t 9MYW5nqwB51mh8SQW3Xb6jk7tX9bnW7kQV7k5-K0XtN4ZF-VJmKRFSN5wlqLPkwpBVW4F59Gr2CbBpMW62YzRH7mqGj8W3nchGr3Xq-YZVzV_dk43ys-Gf1pMH7604',
  'm.address.dfxwpnxh33ko.site',
  'http://zytdgx.com/G21s2n0',
  'https://gofund.me/8a078279',
  'bit.ly/yourprize001',
  'https://chase01bsec.com/?dpck',
  'https://rb.gy/1esm1',
  'https://axtras.cc',
  'dawlmterreabrbie.com/phone.html',
  'https://usp-snavn.top',
  'http://limitsucceed.directory/KI5AudhL',
  'twistedcapsule.com/dRBILnD',
  'https://wellsvalidate-0502.ddns.net/?online',
  'https://usp-sbuxt.top',
  'https://usps-address-amend.com',
  'https://chat.whatsapp.com/DzeAqjxgNbi6S4cuCFchXN',
  'bit.ly/312QwOn',
  'bargainreed.info/Deut',
  'http://mzjxyk.com/N2lsw3m',
  'AGO8D.COM/hViaOS66VB',
  'd3f7a.info/6CVRmQm71',
  'mastermulticentro.com/ss',
  'propertyacademy.net/na.html#23',
  'Oprahsgiveaway.com',
  'https://gotoupdtmembershp.dotcompal.co/gotoupdtmembershp',
  'https://deutschepost-pack.net',
  'https://accscrues.ffm.to/wzd7jar',
  'u5fxc.info/ZEJTTZmY3Z',
  'http://www.uuusps.com/X13B6W',
  'https://chat.whatsapp.com/FH4euuc6Usj3Jryg1zGOQs',
  'centurysever.com/2MbuXy',
  'http://3260518168///i13.php',
  'r9ljg.info/spCdY46rle',
  'http://zglptv.com/no2hrZB',
  'meF92.COM/xMvLZnnJvP',
  'https://rwdz.us/jQ7V5u2w',
  'https://usphm.top',
  'https://viait.net/index.htm',
  'giddybreasts.com/DSRRmEAccl',
  'http://ups.comw-ykgedh.world//1qsyl3rv21',
  'bit.ly/3hmasAg',
  'https://usps.uspskkc.com',
  'https://223ncitihelp.com',
  'https://notification-accountid.lnk.to/resolveaccount?secure-acoount&?=https://amazon.com',
  'exposurepavemen.com/080p6L',
  'upsshipping.io/keGL6LxbyYpQN8z',
  'lightlypainter.com/wlp4ZK',
  'https://wua.soundestlink.com/link/62ec0819e7239400160765f9/62ec07fec03d7d001dc835c5/62ec07eb316b48001c631e48?signature=9914fff38c28a734939ec6ad3c3f038680fa15f715f60 9593c985923dadb61fe',
  'http://tonestrength.financial/7Mu7T15C',
  'http://klkln.cc/vnbcbtd',
  'https://wa.me/77788385297',
  'www.pyr-upsi.website//isr1i2pF19389',
  'https://oldrow.vias.ms/jo8sP',
  'https://bit.ly/3RQ1z1n',
  'https://form.jotform.com/222355830979062',
  'www.xuwk4v-upsa.us//6qj9ihch18920#',
  'whatsapp://chat/?code=Du6Jp7K4UmH8f7pi1rGeys',
  'https://bit.ly/3xmZNuq',
  'http://www.uskps.com/go/Tracking/G2T22',
  'odxhh.cc/a3ikL66',
  'http://dcydpl.com/grguJq2',
  'https://app.mailingboss.com/index.php/campaigns /63857c6fb397b/track-url/637fa8badd3d6/3143bbe318bdc11cead986a59dae0d6178a579c8',
  'http://hnter.ml',
  'packagetrace.biz/d54pv',
  'http://answerurge.network/J4rzuzfR',
  'https://bacindustries.net/alco/Alturacu',
  'imperialautumn.com/QNmNNbJ',
  'https://onlinefrontwavedata.web.app',
  'http://fotag.xpddg.com',
  'whatseenow3.info/ltZSCGnozp',
  'https://vxa-upsp.com',
  'netflixhelpsupport.lpages.co/support',
  'http://s957290943.onlinehome.us/ foldkws/?_rswasscs',
  'https://usps.com@bit.ly/3Yy29Ws ',
  'https://nfcu01login6h.finixp.org',
  'm.eitdi.uspsdi.site',
  'groupm.è.to/wfELH?id=2f57943',
  'http://kbzjgb.com/N2lswyl',
  'broadoblong.com/PXPRjLI',
  'https://wa.me/959799484233',
  'egxi6aqx8r.co/zz5welj',
  'http://fierceseventh.boutique/XEQWCSCm',
  'http://tmgcrg.com/5rBu34D',
  'oprahstoday.com/',
  'whatsapp://chat/?code=15Ro5nXJ3Eml36gE3JZk7Taf',
  'https://forms.gle/GNAKEJJhwCiKSqcP9',
  'Https://www.UnionBank.Org_@bit.ly/3T1lhlE',
  'https://forms.office.com/r/Oc71GAVPIJ',
  'https://wa.me/1607599596',
  'http://conquerpassing.com/L7NHjn',
  'https://storage.googleapis.com/nvulmar/bbbd4mo',
  'https://go.cb-w.com/gz3J1Hsfjpb',
  'https://uspsxt.com',
  'www.92wbj4jzupst.com//49epb8Rw17003#',
  'http://www.bizzapp.co.uk/free/apps51/service?=61513',
  'http://s953340691.onlinehome.us/sport/?InfoAccnt-9xzlmd7nv7',
  'mi08w.com/2kbKsPoeVQ',
  'https://safe-eddprocess3527.duckdns.org/',
  'https://usp-swexy.top',
  'buyelect.co',
  'https://track-tols-usopst.top',
  'geologypassive.com/PYNMIIL',
  'v41qle.jz4721.net',
  'http://catchingbudding.directory/8BWT1REM',
  'secbofa.page.link/NLt',
  'https://pagesntflix.ffm.to/pb6d2yo',
  'mtnl.eu///5EyN6',
  'bedy13.com/V3n4Ovhcqw',
  'https://chat.whatsapp.com/LJDHNf8VNXpFOYjK6QQOaB',
  'vpmEvening49tw.4k1pkmal.in/#?.fkz2',
  'wlness21.com/3qOV',
  'https://cp2we.app.link/iur',
  '06ya2.za.com',
  'shrtco.de/nllx01',
  'https://usps.trckmypost.com',
  'uwntow.com/65VPat',
  'bdhicy.com/okrWt',
  'oprahyes.com',
  'e5sml.info/48GZ3swdBn',
  'theusaloanhunters.ai',
  'citi-actvity.org',
  'https://is.gd/ERR1293',
  'https://is.gd/Ybkgm2',
  'SG201.com/OwWSP7qcg6',
  'acct.encryptbegin.com/d8bcm',
  'storage.googleapis.com/getaca/getaca.html?fbluxyR7Z4',
  'bit.ly/87VBJ987',
  'https://bit.ly/3dRoiZe',
  'zjlesnt.com/ajWje8BZ',
  'ebgicer.com/mDWj392A',
  'https://uspgfs.top',
  'https://uspsusa-us.com',
  'soliditycheek.com/QCq620',
  'http://marginaljo.shopping/v3E6qB',
  'http://mobile.vzw.com/paybill',
  'kh5niapbp4.co/fs4h',
  'https://cya.nz/4UJQ',
  'http://www.americanexpress-message.com',
  'https://upp.edu.pe/nfcu',
  'GetaPrizeBrand.com',

In [27]:
smishtank_data = pd.DataFrame.from_dict(smishtank_data)
smishtank_data.head()

,Unique Url,FQDN,Website Size in KB,Website Textual Content Length,Status Code,Parked
0,83hm2uaj.kzra.in/?/OVA013,83hm2uaj.kzra.in,0,0,-1,0
1,https://usps-intend.shop,usps-intend.shop,0,0,-1,0
2,https://aritc.yru.ac.th/redirect/78?url=bit.do...,aritc.yru.ac.th,0,0,403,0
3,http://site.rdv360.com/free/main45/mail?=924514,site.rdv360.com,14187,89,200,0
4,https://urlsr.com/LY9llxL,urlsr.com,310,12,200,0

In [28]:
smishtank_data['Status Code'].value_counts()

Status Code
-1      631
 200    171
 404     23
 403     22
 400     11
 502      1
 405      1
Name: count, dtype: int64

In [29]:
numbers_to_replace = [501,403, 401]

# Value to replace with
new_value = 200

# Update the column
smishtank_data.loc[smishtank_data['Status Code'].isin(numbers_to_replace), 'Status Code'] = new_value

In [30]:
smishtank_data['Status Code'].value_counts()

Status Code
-1      631
 200    193
 404     23
 400     11
 502      1
 405      1
Name: count, dtype: int64

In [31]:
smishtank_data.to_csv('../Dataset/URL Data/Smishtank Websites Analysis.csv', index=None)