In [1]:
import requests 
from bs4 import BeautifulSoup as bs
import pandas as pd
import tldextract
import numpy as np
import matplotlib.pylab as plt
import os
import re

In [2]:
def on_sale_chk(text):
    if len(text)<1:
        return False
    return 'domain' in text and 'sale' in text

def on_parked_chk(text):
    if len(text)<1:
        return True
    return 'domain' in text and 'park' in text

def on_Parked(text):
    if len(text)<1:
        return True
    return (('website' in text or 'content' in text) and 'unavailable' in text) or ('will' in text and 'soon' in text)

In [3]:
#returns html contents, textual character length, website size, status code, parked or on sale

def soupFromUrl(scrapeUrl):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.1; zh-CN) AppleWebKit/533+ (KHTML, like Gecko)'}
    try:
        req = requests.get(scrapeUrl, headers=headers, timeout=5)
        # print(req.status_code)
        req.close()
        if req.status_code == 200:
            # print(bs(req.text, 'html.parser').get_text().strip().replace('\n',' '))
            soup = bs(req.text,'html')

            # print(soup)

            text = ''

            if soup.body:
                text = re.sub(r'[^\w]', ' ',soup.body.get_text(' ', strip=True).lower())

            # print(soup)

            # print('text',text)
            # print(bs(req.text, 'html.parser'))
            # return [bs(req.text, 'html.parser'),len(req.text), len(req.content), req.status_code]
            # print([len(req.content), len(text), req.status_code, 0+(on_sale_chk(text) or on_Parked(text) or on_parked_chk(text))])
            return [len(req.content), len(text), req.status_code, 0+(on_sale_chk(text) or on_Parked(text) or on_parked_chk(text))]
        else:
            # return [-1,0,0,req.status_code]
            return [0,0,req.status_code,0]
    except:
        # return [-1,0,0,-1]
        return [0,0,-1,0]

In [4]:
headers = {'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.1; zh-CN) AppleWebKit/533+ (KHTML, like Gecko)'}
req = requests.get('https://www.lycos.com/', headers=headers, timeout=5)
print(req.status_code)
req.close()
if req.status_code == 200:
    # print(bs(req.text, 'html.parser').get_text().strip().replace('\n',' '))
    soup = bs(req.text,'html')

    # print(soup)
    text = ''

    if soup.body:
        text = re.sub(r'[^\w]', ' ',soup.body.get_text(' ', strip=True).lower())

    print(soup)
    print('text',text)
    print([len(req.content), len(text), req.status_code, 0+(on_sale_chk(text) or on_Parked(text) or on_parked_chk(text))])

200
<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta content="Lycos, Inc., is a web search engine and web portal established in 1994, spun out of Carnegie Mellon University. Lycos also encompasses a network of email, webhosting, social networking, and entertainment websites." name="description"/>
<meta content="" name="author"/>
<link href="https://ly.lygo.net/static/lycos/img/favicon.ico" rel="icon" type="image/png"/>
<title>Lycos.com</title>
<link href="//fonts.googleapis.com/css?family=Lato:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css"/>
<link href="/css/in/fonts.css" rel="stylesheet" type="text/css">
<link href="https://ly.lygo.net/static/lycos/css/in/font-awesome.css" rel="stylesheet" type="text/css">
<!-- Bootstrap core CSS -->
<link href="https://ly.lygo.net/static/lycos/css/in/bootstrap.css" rel="stylesheet"/>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<link href="https://ly.lygo.net/static/lycos/css/in/ie10-viewport-bug-workaround.css" rel="stylesheet"/>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<!-- Custom styles for this template -->
<link href="https://ly.lygo.net/static/lycos/css/in/slider_prev.css" rel="stylesheet" type="text/css">
<link href="https://ly.lygo.net/static/lycos/css/in/carousel.css" rel="stylesheet" type="text/css">
<link href="https://ly.lygo.net/static/lycos/css/in/custom.css" rel="stylesheet" type="text/css"/>
<link href="https://ly.lygo.net/static/lycos/css/us/newadd.css" rel="stylesheet" type="text/css"/>
<link href="https://ly.lygo.net/static/lycos/css/uvtHamburger.css" rel="stylesheet"/>
<script src="https://ly.lygo.net/static/lycos/js/jquery-1.10.1.min.js"></script>
<script src="https://ly.lygo.net/static/lycos/js/jquery.autocomplete.js"></script>
<script src="https://ly.lygo.net/static/lycos/js/universal.js"></script>
<script src="//scripts.lycos.com/jquery-addons/jquery.cookie-1.4.1.js"></script></link></link></link></link></head>
<!-- NAVBAR
================================================== -->
<body>
<header>
<div class="container">
<div class="nav navHome">
<div class="navbar-left">
<div class="uvt-logo-block">
<div class="prop-logo">
<!-- click and mouseover show network panel -->
<div class="uvt-dog network-toggle"></div>
<div class="network-panel">
<ul class="nw-properties">
<li><a href="https://www.lycos.com"><span class="icon icon-lycos"></span><span class="name">Lycos.com</span></a></li>
<li><a href="http://www.mail.lycos.com"><span class="icon icon-mail"></span><span class="name">Mail</span></a></li>
<li><a href="http://weather.lycos.com"><span class="icon icon-weather"></span><span class="name">Lycos Weather</span></a></li>
<li><a href="http://www.tripod.lycos.com"><span class="icon icon-tripod"></span><span class="name">Tripod</span></a></li>
<li><a href="http://angelfire.com"><span class="icon icon-angelfire"></span><span class="name">Angelfire</span></a></li>
<li><a href="http://domains.lycos.com"><span class="icon icon-domains"></span><span class="name">Domains</span></a></li>
</ul>
<!-- end proeprties -->
</div>
<!-- end Network Panel -->
</div>
</div>
<!-- end Logo-network -->
</div>
<div class="navbar-left">
<a href="http://weather.lycos.com" title="Launch Lycos Weather">
<span class="weather-text">

Cookeville 52° F
				</span> <span class="icon weather-icon"> <img alt="showers" src="https://ly.lygo.net/static/lycos/images/weather/frontpage/showers.png"/>
</span>
</a>
</div>
<div class="network uvt uvth">
<div class="lang-selector">
<div class="ls-parent">
<span class="lang-icon"><img alt="Select Your Language" src="https://ly.lygo.net/static/lycos/img/lang-icon.png"/></span>
<script type="text/javascript">
                            function setDefaultLanguage(lang) {
                                $.cookie('defaultLanguage', lang, { path: '/', expires: 3650, domain: 'lycos.com' });
                            }
                        </script>
<ul class="ls-children">
<li class="selectedLang"><a href="/" onclick="setDefaultLanguage('en'); return true;" title="English">English</a></li>
<li><a href="/" onclick="setDefaultLanguage('es'); return true;" title="Spanish">Español</a></li>
<li><a href="/" onclick="setDefaultLanguage('ja'); return true;" title="Japanese">日本語</a></li>
<li><a href="/" onclick="setDefaultLanguage('de'); return true;" title="German">Deutsch</a></li>
<li><a href="/" onclick="setDefaultLanguage('ko'); return true;" title="Korean">한국어</a></li>
<li><a href="/" onclick="setDefaultLanguage('fr'); return true;" title="French">Français</a></li>
<li><a href="/" onclick="setDefaultLanguage('it'); return true;" title="Italian">Italiano</a></li>
<li><a href="/" onclick="setDefaultLanguage('nl'); return true;" title="Dutch">Nederlands</a></li>
<li><a href="/" onclick="setDefaultLanguage('sv'); return true;" title="Swedish">Svenska</a></li>
<li><a href="/" onclick="setDefaultLanguage('da'); return true;" title="Danish">Dansk</a></li>
<li><a href="/" onclick="setDefaultLanguage('fi'); return true;" title="Finnish">Suomi</a></li>
<li><a href="/" onclick="setDefaultLanguage('no'); return true;" title="Norwegian">Norsk</a></li>
<li><a href="/" onclick="setDefaultLanguage('ga'); return true;" title="Irish">Gaeilge</a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</header>
<!-- Carousel
    ================================================== -->
<div class="search_slider">
<div class="col-sm-12">
<div class="carousel slide" data-ride="carousel" id="myCarousel">
<div class="searc_box">
<div class="lycos">
<a href="#"><img alt="" src="https://ly.lygo.net/static/lycos/img/in/lycoslogo.png"/></a>
</div>
<div class="searc_input">
<script type="text/javascript"><!--//--><![CDATA[//><!--
    function checkSubmit() {
      var queryBox = document.getElementById('query');

      if(( queryBox.value == 'Enter search term...' ) || ( queryBox.value.trim() == '' )) {
	  queryBox.value = '';
	  queryBox.focus()
	  return false;
      }
      return true;
    }
    //--><!]]></script>
<form action="https://search.lycos.com/web" id="form_query" method="get" onsubmit="return checkSubmit();">
<fieldset>
<input autofocus="" class="search-input" id="query" name="q" placeholder="Enter search term..." type="text" value=""/>
<button class="search"></button>
</fieldset>
<input id="keyvol" name="keyvol" type="hidden" value="FA02D34CE00ABC10FE"/>
</form>
</div>
<div id="autocomplete-suggestions"></div>
</div>
<!-- Indicators -->
<ol class="carousel-indicators">
<li class="active" data-slide-to="0" data-target="#myCarousel"></li>
<li data-slide-to="1" data-target="#myCarousel"></li>
<li data-slide-to="2" data-target="#myCarousel"></li>
<li data-slide-to="3" data-target="#myCarousel"></li>
</ol>
<div class="carousel-inner" role="listbox">
<div class="item active">
<img alt="First slide" class="first-slide" src="https://ly.lygo.net/static/lycos/img/us/slider/slider_valentines_us1.jpg"/>
</div>
<div class="item">
<img alt="Second slide" class="second-slide" src="https://ly.lygo.net/static/lycos/img/us/slider/slider_valentines_us2.jpg"/>
</div>
<div class="item">
<img alt="Third slide" class="third-slide" src="https://ly.lygo.net/static/lycos/img/us/slider/slider_valentines_us3.jpg"/>
</div>
<div class="item">
<img alt="Fourth slide" class="fourth-slide" src="https://ly.lygo.net/static/lycos/img/us/slider/slider_valentines_us4.jpg"/>
</div>
</div>
</div>
</div>
</div>
<!-- /.carousel -->
<section class="content" style="padding-bottom: 20px;">
<div class="container">
<div class="navbar-left">
<ul class="nav nav-tabs">
<li><a href="https://lycos.itemorder.com/sale" style="display: inline;" target="_blank"><img src="https://ly.lygo.net/static/lycos/images/lycos_swag_mug.png" style="display: inline;
	height: 60px;
	width: 60px;"> Lycos
						SWAG</img></a></li>
</ul>
</div>
<div class="navbar-right">
<ul class="nav nav-tabs">
<li><a href="http://www.mail.lycos.com">Mail</a></li>
<li><a href="http://www.tripod.lycos.com">Tripod</a></li>
<li><a href="http://domains.lycos.com">Domains</a></li>
<li><a href="http://weather.lycos.com">Weather</a></li>
<li><a href="http://www.angelfire.com/">Angelfire</a></li>
</ul>
</div>
</div>
</section>
<footer>
<div style="float: left; width: 100%;">
<div style="margin-left: auto; margin-right: auto; height: 95px; width: 733px; margin-bottom: 5px;">
</div>
</div>
<div class="container">
<ul class="navbar-left">
<li>
<p>Copyright © 2025 Lycos</p>
</li>
<li><a href="https://info.lycos.com" title="About Lycos">About</a></li>
<li><a href="https://info.lycos.com/career-opportunities/job-openings" title="Careers at Lycos">Careers</a></li>
<li><a href="https://advertising.lycos.com" title="Advertise with Lycos">Advertise With Us</a></li>
<li><a href="https://info.lycos.com/resources/terms-of-service" rel="nofollow" title="Lycos Network Legal">Legal</a></li>
<li><a href="https://info.lycos.com/resources/privacy-policy" rel="nofollow" title="Lycos Privacy Policy">Privacy</a></li>
<li><a href="https://registration.lycos.com/helpcenter_passthrough.php?m_PR=1" rel="nofollow" title="Lycos Help Portal">Help</a></li>
<li class="search-provider modern-browsers"><a href="https://info.lycos.com/resources/lycos-search/#Chrome" onclick="window.external.AddSearchProvider('https://search.lycos.com/opensearch.xml')" title="Make Lycos Search the Default Search Provider"><span>Add
						Lycos Search to Browser</span></a></li>
</ul>
<ul class="navbar-right">
<li><a href="https://www.facebook.com/lycos.search" target="_blank" title="Friend Lycos on Facebook"><img alt="Facebook" src="https://ly.lygo.net/static/lycos/images/facebook.png"/></a></li>
<li><a href="https://twitter.com/SearchLycos" target="_blank" title="Follow Lycos on Twitter"><img alt="Twitter" src="https://ly.lygo.net/static/lycos/images/twitter.png"/></a></li>
</ul>
</div>
</footer>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-0WY0KPH0ZW"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-0WY0KPH0ZW');
</script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-76FJGHQNN6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-76FJGHQNN6');
</script><script type="text/javascript">//<![CDATA[
  $('#keyvol').val('00e8ab029b35023e0bb1');
//--><!]]>
</script>
<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ly.lygo.net/static/lycos/js/in/bootstrap.min.js" type="text/javascript"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="https://ly.lygo.net/static/lycos/js/in/ie10-viewport-bug-workaround.js"></script>
<script src="https://ly.lygo.net/static/lycos/js/in/prev_next.js" type="text/jscript"></script>
<script>

$(document).ready(function(e) {

	   $("#owl-demo1").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });
	    $("#owl-demo2").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });
	    $("#owl-demo3").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });
	    $("#owl-demo4").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });



});


</script>
<script src="https://ly.lygo.net/static/lycos/js/in/dog_in.js"></script>
<script>$(function() {
	'use strict';

	// Initialize ajax autocomplete:
	$('#query').autocomplete({
		serviceUrl : 'https://us.search.yahoo.com/sugg/gossip/gossip-us-partner?output=sd1&appid=lycos',
        dataType: 'jsonp',
		paramName : 'command',
		onSearchComplete : function(originalQuery, suggestion) {
			var re = new RegExp('\b' + $.Autocomplete.utils.escapeRegExChars(originalQuery), 'gi');
			return re.test(suggestion.value);
		},
		onSelect : function(suggestion) {
			$('#form_query').submit();
		},
		onInvalidateSelection : function() {
			$('#selction-ajax').html('You selected: none');
		},
		transformResult : function(_response) {
			var response = typeof _response === 'string' ? $.parseJSON(_response) : _response;
			return {
				query : response.q,
				suggestions : $.map(response.r, function(dataItem) {
					return dataItem.k;
				})
			};
		}
	});
});
</script></body>
</html>

text lycos com mail lycos weather tripod angelfire domains cookeville 52  f english español 日本語 deutsch 한국어 français italiano nederlands svenska dansk suomi norsk gaeilge lycos       swag mail tripod domains weather angelfire copyright   2025 lycos about careers advertise with us legal privacy help add       lycos search to browser
[13852, 328, 200, 0]

In [5]:
# print(soupFromUrl('https://www.delinian.com/'))
# print(soupFromUrl('https://www.makecashonline.com/'))
print(soupFromUrl('https://www.lycos.com/'))

[13852, 328, 200, 0]

In [7]:
spamhunter_url = list(pd.read_csv('../Dataset/URL Data/Spam-Hunter.csv',delimiter='\t')['URL'])
spamhunter_url[:10]

['bit.ly/BantuanDanaBPJS',
 'http://www.ethinfo.net',
 'bit.ly/2JTIngsungATM',
 'googl.com/?coin',
 'post.com/?=es2938456',
 'https://bit.ly/36900m8',
 'http://umu.link/raboscanner',
 'bit.ly/tiktok-7947',
 'http://rewardspayout.com/',
 'cy9.co/tpo']

In [8]:
import re

def find_first_slash_preceded_by_number(s):
    # Regular expression to find the first instance of a number followed by '/'
    match = re.search(r'\d+/', s)
    
    if match:
        return match.start() + len(match.group()) - 1  # Return the index of '/'
    else:
        return -1  # Return -1 if no match is found

# Example usage
string = "example77/test 88/test2 99/test3"
index = find_first_slash_preceded_by_number(string)
print(index)  # Outputs the index of the first '/' preceded by a number

9

In [13]:
unique_spamhunter_url = list(set(spamhunter_url))

In [14]:
for idx,i in enumerate(unique_spamhunter_url):
    if '..' in i:
        if 'www' in i:
            unique_spamhunter_url[idx] = ''
        else:
            unique_spamhunter_url[idx] = unique_spamhunter_url[idx].replace('..','.')

In [25]:
def refine_url(url):
    # Trim invalid leading characters (keep only letters, numbers, or valid schemes)
    trimmed_url = re.sub(r"^[^a-zA-Z0-9]+", "", url)
    
    # Trim invalid trailing characters (must end with a letter, digit, `/`, `?`, `#`, or `=`)
    trimmed_url = re.sub(r"[^a-zA-Z0-9/?#=]+$", "", trimmed_url)

    # Ensure URL starts correctly (with a scheme or valid domain character)
    if not re.match(r"^(https?://|ftp://|[a-zA-Z0-9])", trimmed_url):
        return ""  # Invalid start, return empty

    return trimmed_url


unique_spamhunter_url = [refine_url(i) for i in unique_spamhunter_url]
print(unique_spamhunter_url)

['http://www.kycpaytm.com/in.php', 'points.co.in', 'bit.ly/im3', 'https://bit.ly/3goHo9H', 'privee.com', '3.uk/18e', 'argops.com', 'http://www.karamozyar.ir/dhl/?10iztoui77wo', 'http://c.p9tj.com', '33700.fr', 'https://paypal.co.uk.yn5e.eu/m/', 'bit.ly/', 's.id/8080spor7', 'amb.web.id', 'bit.ly/anular-recibos', 'bit.ly/39fUjHk', 'n.n1m.in/41tiup', 'https://t.co/hukvau4hrp', 'http://gs.im/n', 'http://mor.at/qlq/ad8udhi', 'com.preview-domain.com', 'http://www.hkj.buzz/65slwiav', 'HK42753.info', 'http://bit.ly/2isSKeE', 'www.gebyarshopee2019.tk', 'm9s.in/hut3q1ct', 'claro-e.com/4yksm', 'https://aceessink.com/eEHLagt', 'www.bankislam.com', 'https://y.uber.com/1охКwl84', 'www.tim.com.br/applemusic/eesiarls', 'https://docs.google.com/forms/d/e/1FAIlpQLScXa5h', 'bharatpe.in/bharatswipe', 'rml.lu/NPA9NZ', 'https://royalmail.co/schedule-delivery/?GV670517065GB', 'https://bit.ly/2txk2yc?=santander', 'whois.nic.top', 'bitlyk.com/cac11w397', 'http://bit.ly/33ZUxP', 'westpac.account-access.in/', 'https://bit.ly/2ZpRhMM', 'http://w1998.xyz/s/cifsik', 'https://cutt.ly/did9rjv', 'http://tiny.cc/kejutan-isipulsa-mkios', 'https://cutt.ly/osigb8j', 'tinyurl.com/2efwn9sa', 'https://gov.xm.app/ilw2seo', 'https://telenetfactuur.me/aanrekening/c4xlgshje?id=42aa26cc19ec', 'http://wnut.in/GetBillAlert', 'https://tsky.in/s/dvGUmSC', 'V.whatsapp.com/768329', 'https://www.singaporebudget.gov.sg/sgbonus?sign', 'https://onlinepasvervangen.info/', 'https://bit.ly/3ucQaya', 'https://registrobbva7.com/5554321560', 'http://bit.ly/2QGDOIR', 'http://sm.sg/32x45', 'https://apply-licence-dvla.com', 'http://n0u.us/UKCHM', 'www.und-wa.blogspot.com', 'http://bit.ly/superlinea', 'Colicoli.fr', 'http://kotakrewardpoint.co.in', 'https://informate-aqui.ml/colo', 'https://bankieren.ch/', 'https://bit.ly/36js4hq', 'https://dk.trustpilot.com/evaluinta', 'informatie-teruggave.info', 'X.co/MijnING', 'myads.id/Mercedes', 'http://clientisantanderarea-es.com', 'sindhgifts.com/belasting-aanmaning', '985efeedeex.com/?uqlcc-your', 'tsel.me/hotoffer', 'accesobankiaes.com', 'https://bit.ly/2YTlkvs', 'billpayid33.com/vz/i', 'http://beta40.popsmoke.pw/abc123/', '7kb.in/lix/lxy4569', 'http://nmc.sg/gvbJKg', 'bit.ly/1Jtcicil1Bulan', 'tessa.live69chat.site', 'eurowings.com/erstattung', 'https://bit.ly/2n7klsd', 'http://pvrc.in/', 'zafxmobile.cf', 'https://bit.ly/30q1ruh', 'bit.ly/cyber-attack18', 'yt5po.com/s/as3890', 'www.maybank2umy.com', 'bit.ly/tiktok-7947', 'chat-v.com/s/9cjir', 'https://wordpresssocial.com/s/?258000ybyazl', 'https://mobile-account-au.web.app/', 'optus.com.au/optus-4g-internet', 'http://www.vivo.tl/vm1101', 'ing.avg-web.nl', 'https://bit.ly/2zbJkB9', 'https://govapplication.ga', 'http://bit.do/sehkd', 'att.com/armorapp', 'att.com/cyberaware', 'is.ga/bbva', 'siteground.eu', 'http://bit.ly/w88', 'https://cutt.ly/yze8h6a', 'gps.ut9.co', 'http://8d269466000d.ngrok.io/sbibank', 'https://hsbc.uk.authpayee.com', 'www.infoptwhatsapp-2019.blog', 'http://bit.ly/20TFt3v?', 'https://cd18b76d24f7.ngrok.io/sbibank', 'solidclarification.com', 'm9s.in/gi4or', 'https://postoffice-express-parcel.com', 'HK38427.info', 'https://goo.gl/i33v4c', 'https://is.gd/eZXjop', 'https://online.hmrc.gov.uk.mob2.co.uk', 'http://cepdenizbank.com', 'my-jcb-co-jp-iss-pc.top', 'rml.lu/bGJd6p', 'http://1j7.me/CoLhr', 'https://2raboalert.com/', 'http://bit.ly/Daftar', 'https://ameli-rembo.com/A80022W', 'bit.ly/PT-pusatpegadaian', 'p6szr.info/', 'http://bit.ly/postnl-zending', 'mijn-wereldpas.com/', 'https://f17a8c33ff92.ngrok.io/', 'https://postnl.icu', 'http://www.onelogin.com', 'http://gg.gg/_-bbva', 'www.uidai.gov.in', 'personal.com', 'wa.me/628114445829', 'http://www.netflix.com.memberupdate.info/', '3STGVT002294913.ht', 'https://actualizacion-perosonale.duckdns.org/e.php', 'https://www.ing.nl/particulier/betaalverzoek/index.html?trxid%=a794Xi0EjogCSbRH4hznW2TxrikxEtp0', 'Asiataipan.com/', 'https://toktok.ph/delivery', 'www.bit.ly/2ZovBI6', 'u8-n3tf11x-613.com', 'www.dizisinemacast.com', 'http://myuktaxback.com/', 'https://zcb.fr/z60cM', 'go.vodafone.es/tiendas', 'tsel.me/tcashsentraponsel', 'mygovaustralia.com/govAu/?Sign-in', 'https://bit.ly/3vkbxtk', 'http://www.365boi.net/', 'http://www.bestfirecrackers.in/pcmloe.php?mizjf449', 'cuenta.in', 'https://tny.sh/4januari', 'https://animalpolitico.com', 'https://rb.gy/i3neai', 'https://gl.tc/b/w9l9pyua', 'www.telekom.de/', 'https://bit.ly/3paqdlqy', 'https://bfin.in/?gd27uf11', 'http://update12.com/9Pd', 'https://bit.ly/3ausybb.thank', 'www.entel.pe/8rF', 'http://mkrbherzmf.duckdns.org', 'https://cutt.ly/mzewnny', 'https://cutt.ly/ct9eryo', 'www.gebyarbrisimpedes.blogspot.com', 'http://movi.st/touroc', 'https://cutt.ly/betaalmiddelverlopen', 'auspost.item-location.com', '9ind.in/s/46603257', 'https://han.gl/twutx', 'bit.ly/3a5Nfga', 'govuk.ref7911.com', 'https://payee-verify-alert.com/hsbc', 'touchngo.life', 'https://api.whatsapp.com/send?phone=56989222042', 'https://bit.ly/BCP-Alertas', 'http://bit.ly/tatacominterviewInfo', 'https://carwale.page.link/qFrfQ', 'www.wasap.my/', 'http://aggiornaredatipost.com', 'uma1.in/m/?1v8av6?igsa4', 'https://bit.ly/3jbxyfl', 'https://apple.co/20010Rx', 'bkmp.me/?3navh7?159', 'https://u1.mnge.co', 'https://s.id/rabobank-pas', 'https://hsbc.banking-payee.co.uk', 'bit.ly/pesugihanuuang', 'htts://u’.mnge.co/pl1¥nsn', 'https://paypal.yamahatrisaktimotor.com/', '1va.top/raboNL', 'https://forms.gle/FDPr1RZd1RboXJiDA', 'https://bit.ly/2HSMDDQ', 'https://od.vg/KBkoiL', 'https://bankiaonlineweb.com/es', 'http://oapk.hopto.org/sbikyc', 'https://wa.me/628563321979', 'https://cutt.ly/do855jd', 'https://bit.ly/3pucsnd', 'https://bit.ly/2W9Pqb9', 'wa.me/919754242845', 't.cn/', 'ly6u.com/PtNgO', '3renews.com', 'ngifo.com/wi̇ymzz2vt', 'https://sntdr.co/nlqqsd/In', 'cutt.us/pw4tN', 'www-knab.org', 'https://completarddwalosdatos.online', 'https://bit.ly/3c]wd6i', 'https://shortology.it/x', 'www.bri7377.blogspot.com', 'https://bit.ly/2XQU96K', 'www.bankofmaharashtra.in', 'www.ups.fr', 'https://bit.ly/3q1vsnn', 'https://bit.ly/Vodafone-nl', 'http://bit.do/ltaxrefund', 'www.Raboscanner.net', 'xb.inh1.in/nHcV5', 'https://ib.nabaccount.info/login', '4kr.me/15emc', 'http://t.uber.com/delish9', 'https://vergoeding-brussel.me/pay/607d8a2d846e6', 'im3.do/m3', 'www.shopee818.blogspot.com', 'worsleyelectricalservices.co.uk/', 'http://oabvarginha.org.br/web/?tmy1eur95x', 'https://ee.uk.myaccinf10.com?e=3', 'split.to/nieuwe-betaalpas', 'jgk-888.com', 'bit.ly/danahgoib77', 'tsel.me/nsp', 'kjkt77kmxlst.com/jso5aiy', 'i.airtel.in/cc2806_lonb', 'nhs.uk-ordertestkits.com/nhs', 'http://trackmail.club/gNM', 'www.bit.ly/3eMJKhj', 'https://info-aggiornamenti.com/', 'https://cutt.ly/9qvuoy4', 'https://www.raboklant.com/bankpas', 'https://re.niki.ai/39lz7Pl6-2', 'https://92e55955ba64.ngrok.io/sbibank', 'raiffeisen-blokace.xyz', 'hitps://transitoitagui.site/', 'www.creditouruguayo.uy', 'https://co-mpleta-mod-bp-link.preview-domain.com', 'http://ideal-paylink.com', 'http://clickitl.com/1xA', 'http://m.bajfin.in/ksf___xel', 'https://bit.ly/im3dtk24', 'ebay.com.au', 'bit.ly/elsa987', 'https://myhermes.online', 'secure.gov-refunduktax.org', 'www.indusindpropoints.in', 'bit.ly/3zx8fss', 'http://bit.ly/festival-shopee2019', '81ltc.cn/jp', 'whois.discount-domain.com', 'http://vwgsixl.com/F1c', 'http://hsng.co/4iDP8mUngXNU', 'att.com/freemobilesecurity', 'http://lavozislamica.com/www/?2e3vdk4c7v', 'https://cutt.ly/oa1jc31', 'chat-v.com/s/9swru6', 'https://wa.link/clarochileclaudia', 'https://bendigobank.com.au.review-security.info/login/thanks', 'BankBazaar.com', 'http://muwaji.com/pkge/?uahqjxq6t507', 'http://rq9.us/Hmtsi', 'anzregisterlogin.com', 'https://myitems-pay-tracking.com', 'noussommespour.fr', 'https://bit.ly/21JUYWZ', 'duckdns.org/', 'https://we.tl/t-Puu5LcVYw9', 'https://myherm.es/forvku', 'https://mypo.st/HQRJYS-5NIS', 'http://xu5.us/YZSVE', 'internet.pin', 'https://ik.tc/vbxut', 'https://bit.ly/2TSfbiP', 'https://gpo.ca/gogreen', 'informacion-cliente.serveirc.com/', 'bit.ly/Ahliparanormal', 'https://is.gd/vnpvceSMS-Nachricht', 'bit.ly/34OND10', 'sky-mobile-verify.com', 'https://maforma.cc/eligibilitenoSMS=Stop', 'urlz.fr', 'https://cutt.ly/Kws099B', 'http://go.hanrec.com/t/c/MP9VYW', 'bit.ly/2Tsguka', 'https://s.id/rembors', 'https://denizinbankasi.online/TR/', 'linkwww.pacogavidiaalcongreso.com/propuestas.html', 'goo.gl/g', 'https://bit.ly/BancoBankia-Particulares', 'http://icloud.cor.in/zwmvobR', 'https://bit.ly/tselbk221', 'https://bit.ly/2VKVAYC', 'http://wu.is/', 'http://bit.ly/2lpmyod', 'ants-gouv-cartevital.fr', 'https://eby-kleinazeigen-de-anzeige-710938713.000webhostapp.com', 'http://m.bajfin.in/dhtippsc', 'www.layanan-callbpjs.blogspot.com', 'volksbank.de', 'bit.ly/ics-nl', 'kpn.com/', 'https://go.onelink.me/LXPZ?pid=tianbei', 'https://wa.me/919786647612', 'bit.ly/2KEi009', 'hitps://bit.ly/376qzlp', 'http://sclu.es/x3vTo', 'https://bit.ly/3eqb6ru', '7caixa.com/?d2d54tt', 'http://www.smscaster.com', 'http://acl.cc/GL3amLO', 'bit.ly/1jtproses', 'https://bankieren.network/', 'vodafone.de/l/c/3rcg68bg', 'http://32.ngrok.io/sbilbank', 'https://www.ibhifi.com.au/', 's.id/shopeeid178', 'http://info-wells-departament.online', 'https://t-mo.co/sms-spam', 'https://bit.ly/34liijg', 'https://bit.ly/3ainubo', 'http://tsel.me/ROLI', 'www.verifyyono-update.info', 'https://linkaj.me/uewm2', 'www.uinuin.com.uy', 'https://unicaja.actualizacion-personal.com', 'chat-v.com/s/9tjprx', 'http://surveys1.10thousandfeet.com.au/s3/CSSFeb2018?sguid=OSHMK', 'http://b.link/KBC-2', 'https://goo.gl/hbrypn', 'achterstand.online', 'chat-v.com/s/b9io7d', 'booking.com/df646d0df6a28b4', 'bit.ly/acctoto', 'https://fraudesantander.info', 'https://fuck55hard.page.link/', 'thegoodgoodiz.com', 'https://accesslnk.com/IX161XL', 'company.com', 'https://seguridadbbva.app', 'smsg.io/NHCha', 'bit.ly/shopee1237', 'https://myhermes.ref82.com', 'https://hsbc-signin.site', 'https://covid.census.gov/jfe/form/sv_3en1hx9u1rwlp38?q_dl=smsd_cbppiw6ict1jtd5_3', 'http://ru.tc/', 'www.zdocp.cz', 'https://www.cibconline.net', 'https://tlp.news/zand5m', 'https://google.com', 'http://www.vodafone.nl/app/link/mijnrekening', 'http://acl.cc/Oxdl1ax', 'cockpump.co', 'bit.ly/2IW1wkA', 'no.id', 'https://bit.ly/tselbk12', 'wa.me/919681686366', 'https://mesdroits3.com/116', 'https://armx.page.link/app', 'http://11.ddns.me/', 'http://bit.ly/2VOJRUC', 'eastleigh.gov.uk/pay-ct', 'https://www.onlinedegree.iitm.ac.in/', 'https://bit.ly/2XatEa2', 'cardstop.be-9.in/reactiveer', 'https://bit.ly/3m7aD3L', 'http://f60.me/ukSOc', 'https://docs.google.com/forms/d/e/1FAlpQLSdbRnB3Zwwh2Vz9U7', 'https://oto.eaut.edu.vn/b/hk/?673', 'ing-es-accesso.com/?pwd=ing', 'cashredeem.com', 'http://bawagpsk.id41783.com', 'https://picniclifeinternational.com/w/?105d-2b8', 'tiny.cc/C890122', 'https://rabobank.nl-verouderd.info/procedure-stap/inloggen', 'rb-cz.net/cz', 'https://volks-tegemoetkoming.com/servibe/mymfweb/premmie', 'https://cutt.ly/uiwgzhm', 'www.iLOTTE.com', 'ot.com', 'tinyurl.com/wib-pedia2021', 'http://bit.do/bancoestadoApp', 'm9sxv.info/IbJOnVq6Ft', 'http://areaprivada.unaux.com/bbva/', 'nj7.us/VAqFv4', 'rse-oran-dz.com/pkg/?ogtaor1olvcp', 'bircj.com/956guo', 'https://bit.ly/2kqpw5L', 'http://1r.cm/', 'Autotrader.co.za', 'https://goo.gl/KF1FR1', 'https://goo.gl/N8uSjC', 's.id/wghQf', 'p24sj43.site/FLOS', 'www.ingmobiel.nl/ING', 'jxgt.duckdns.org', '888.cl', 't.cn/EUJE7ql', 'www.txd.io/ZAufeB', 'j9hsv.info/otecqyguoo', 'Imes.es/bajasms', 'http://pmny.in/FI6L8HEhtoCj', 'wwW.BBVAon.es', 'zfw.apr12.cc', 'https://vivo.tl/meusaldo', 'https://m.renfe.com/bidi/ftc?c=livc7%2fb2j0jwcmmku115zq', 'wallpaperdk.com/95jzct4', 'https://rabo-betaalpas.website/sms/', 'w6fvc.info/x7dzipra3n', 'verificatie-ing.com', 'bit.ly/2S96xx2', 'nab-ib.online', 'https://bit.ly/210q2F4', 'https://suivipick.fr/3hYI', 'https://icloudsupport.co/?e=hHul', 'http://flyzomhvgb.duckdns.org', 'http://x.co/6nULN', 'hitps://bit.ly/3c2xyd4', 'bbvaa.me/?pwd=bbva-bbva', 'http://tiny.cc/COVID-VACCINE', 'https://cy.tc/MBUU', 'www.Raboscanner.com', 'http://3cm.top/LexJ', 'https://www.anugo.ca/-/royalmail-uk951490/', 'bit.ly/hadiah-mkios5677', 'https://bit.ly/3edpo2N', 'sr7.in/132b8-23c4b90a8', 'cutt.ly/jok3rnet88-daftar', 'http://bit.ly/2PLFtx1', 'https://bloccaoperazioni.yo.fr/', 'http://espace-carrefour.eu/france', 'trackorder-update.com', 'https://bbva.app-protect.info', 'cy9.co/hhb', 'https://halifaxdevices.cc/cancel/', 'https://albertahealthservices-login.org', 'cardpointz.com', 'https://83c027093404.ngrok.io/sbibank/', 'revolut.uk.com', 'http://coinbase-mobileg.xyz/index.php?id%=35799121577', 'https://sant-ander-movil.app/?sms=santander', 'https://v4switch.com/parcel/?rrig', 'hrtZ.info', 'http://bit.ly/hadiah-resmi32', 'bit.ly/2VSdp1M', 'www.tracking.singpost.fit/6bu7f', 'http://www.continentalsegurope.com', 'https://bit.ly/32M0OU1', 'http://2by7.com/gnp', 'www.gs.im/n/spa=', 'www.allcard.in', 'https://sak38.app.goo.gl/mdzkb', 'https://bit.do/Rabobank98', 'http://bit.ly/2SiAlVy', 'http://bit.ly/yes8hoki38', 'https://t.co/frbrpgt9nh', 'www.aki-rhoso.com', 'www.t-sel-2018.blogspot.com', 'http://supaviceprojects.com.ng/go.php?swlulkvgo', 'https://t.me/mi@ml', 'https://tny.sh/bdgt9', 'https://s.id/IngBetaalpas', 'https://elad84170e7a.ngrok.io/sbibank', 'https://wereldpas-particulier.website/secure/', 'g6fzr.info/', 'https://postelta-is.preview-domain.com', 'https://revolut-helpcentre-uk.co', 'open-bank.com', 'https://moey.pt-nu.in', 'https://dgo.link/kbhtxto', 'https://bit.ly/tselbk211', 'https://airasialtd.com/Interview', 'http://www.recoff.jp/s/?0', 'http://tmobileverificatie.nl/', 'http://pmapp.nic.in/ee.jsp', 'http://peyasaw.000webhostapp.com/ig', 'Iskt.me/u9', 'https://www.endx.io/GEqlXwc', 'bit.ly/ahligoib5779', 'https://dewsa.tiiny.host', 'www.facebook.com/100075997457473/posts/153291510547430/c', 'https://19ffb41b38ac.ngrok.io/sbibank', 'f.ut9.co/s/', 'www.ing.be', 'bit.ly/2Vb83fe', 'http://bit.ly/30irn9k', 'to1.me/7lovna', 'http://m.kgn.cm/kr7cruxe', 'tiny1.jio.com/MyJioS', 'https://hyfwa.site/', 'https://goo.gl/GJEAxh', 'wallpaperzi.com', 'https://bit.ly/3pakxqt', 'http://kmbpoint.com/', 'http://tiny.cc/danagaib75', '8u7s.xyz/yEfCWGoHkn', 'ref560.mv', 'https://bom.so/fzw', 'https://bit.ly/3asQ5NI', 'inloggen-omgeving.info/portal', 'https://bit.ly/helpcenterfr', 'www.kejutan-shopee789.blogspot.com', 'https://bit.ly/3oaroof', 'https://urlz.fr/AAYZ', 'http://bit.ly/2Lz0Scs', 'anz.com/', 'https://cutt.ly/amexpress', 'https://whatsapp-foto.com/c/d?i=4AnWraEB1s', 'http://mp0.co/xytff', 'paypal.supportuk-accountservices.com', 'www.rewardcash.in', 'https://www.tatacard.com/DisputeRaise', 'https://bit.ly/3nkfjuf', 'https://t.ly/x01e', 'nbgupdate.shoplineapp.com/nbg-group', 'https://cutt.ly/flfytbb', 'https://boi365servicesupport.com/', 'https://santander.apoyo-clientes-esp.ru/ceo', 'https://particulares-personasbbvase.duckdns.org/?bbva.es', 'http://oxr.me/dt2yo', 'https://go.fun8x.com/4a3', 'https://monzo-app.me/', 'bit.ly/Cslsna', 'bit.ly/2BXJQXA', 'in-terac.indykathak.com/', 'tanla.com', 'https://o2.uk.ac5g70.com/?o2=2', 'uqasr.com/luXJnyB0qQ', 'bit.ly/3q27515', 'clic-ici.fr/hKiPq', 'www.galeri24katalog.tk', 'https://adobe-update.store', '2xz.us/3IVwfp', 'bit.ly/infoper-tamina775', 'applypass.com', 'https://prx.ms/verrassing', 'www.neues-handyticket.de', 'https://goo.gl/p7hjHWe', 'http://newlineinteractive.in/trck/?5q109ajkiohfn', 'whats-app2017.blogspot.com', 'http://bit.ly/shopeetbk223', 'www.agrobazaar.com.my', 'http://ideal-pay.xyz', 'cutt.ly/ah483t', 'https://inink.ru/9przaa', 'access-blocked.info', 'https://mysejahtera.malaysia.gov.my/home/#/reset-password/xsajh5j9i1d5xt1atbcxszkhit', 'wWw.wallet.v-notify.cf', '2x1p.com/46lp5', 'ijegob.com/', 'goo.gl/UD5Sok', 'https://es-correosarea.com/', 'https://ee.bill323.com/?ee=2', 'https://icloud-live-info.com/m2/53-14', 'http://app-servizioclienti.info/2', 'https://t.co/hmUVFzjk0k?amp=1', 'https://bit.ly/2oaHMBu', 'http://48t.us/doWPJ', 'www.mysmbcojp.us', 'https://www-klant-rabo.info/klanten/inloggen', 'https://bit.ly/2HlooZU', 'my.toucngo.com', 'http://qfnst.com/2ts', 'http://rnvbii.com/cglet', 'http://movi.st/tourocba', 'http://chenspanda.com/track/?vk2fuxu855e', 'https://bit.ly/2egxhvc', 'V.whatsapp.com/409865', 'https://controlebe.info/pay/614bel', 'http://2my.top/Bfy', 't4d2.xyz/qxswyTg33S', 'https://dojo.my/kontendigital/koa', 'https://jook.li/Cst.R4J.E', 'http://icopab.com/sg4xuxt', '8qe.org', 'ocgeneral-e.com/activation', 'device.services', 'WWw.correos.cl', 'http://www.imaybank.com', 'http://surl.li/bmjsu', 'https://bit.ly/2vjmSB4', 'https://cutt.ly/KPN', 'https://wa.me/+6285656440697', 'https://4tl5.short.gy/vyny7m', 'caixa.dispositivoapps.com', 'https://rzp.io/i/6afq8nks7t', 'https://vodafone-nl.net/index.php', 'https://ebanking.ingbe.overzicht.site/', 'https://santaander.app/?sms=1', 'https://cutt.ly/PSDLEY', '1su2f.com/s/ayc97n', 'https://t.co/', 'bit.ly/pinjamCepat2Jt', 'https://map.ms/rb8jy', 'intrenets.com/', 'g2fzs.info/', 'http://bit.ly/2xgSHgT', 'https://hdfc-in-net.preview-domain.com', 'https://es.unicaja-avisos-movil.com', 'https://78038b5dfa65.ngrok.io/sbibank', 'https://gouv-espace.site', 'hbhmachine.com/b/le/networkprotectionstandar', 'ektc-online.preview-domain.com', 'https://nab.manage-device.app', 'covidpass.com', 'hermes-deliveryfees.com', 'revolut.support.rslne.com', 'http://phon.pe/lhpheaqg', 'bit.ly/xxlsport', 'https://afsprk.nl/c/WsEp4q7', 's.id/aangifte-digid', 'https://t.co/uNgMxApEBE', 'www.bothner.co.za', 'https://tp.aero/', 'www.undianjutawanlazada.cf', 'https://paypal-safety-payment.org', 's.id/ABN-Betaalpas', 'hitos://pcr.test.status-33.com', 'supports-tel.com', 'http://adsi.in/I.s?KXP3DY10', 'https://docs.google.com/forms/d/el', 'https://mijnsimverlengen.info/t-mobile/index.html', 'http://i3fq.com/NiG9T', 'https://cutt.ly/rokibh4', 'https://tinyurl.com/unspro', 'https://recycle-bankkaart.website', 'vb7.me/', 'https://blockchainsms.info', 'www.osi.es', 'https://data-login-info4-com.preview-domain.com/', 'https://cli.co/platnosc-pge-online', 'https://mijn-ing-verificatie.nl/Login', 'https://bbva.esp-com.win/', 'https://goo.gl/Tk3zYn', 'wereldpas-aanvragen.nl', 'resolve-my-device.com', 'https://fancythatantigues.com/pkg/?8nuw2nogcwt', 'n.n1m.in/1p85hx', 'http://mpago.li/2ir2wte', 'hmrc.gov.uk.signin2-uk.com', 't.me/jqk888bet', 'hitp://bitly.ws/oipl', 'o0o0webhostapp.com/', 'https://envolve.adv.br/dhl/?pbj46vtas286', 'http://selectionindia.in/b.php?b5qmart', 'www.hadiahptlazada.gq', 'https://s.id/poin777', 'https://tan-ing.nl/id197', 'https://ee-update.ref084.com?ee=2', 'www.bpolsicurezzaweb.com', 'http://tiny.cc/peletpemikat0853-42731-277', 'http://8b1.me/EJtkV', 'lloyds-online-service.me', 'bit.ly/infopertamina', 'screensteward.com/mooslju', 'bnzauthenticatelogin.com', 'https://france-cpf.fr/b/stop', 'http://g6f.us/DYHOJ', 'om.br', 'tpgi.com.au', 'http://bit.ly/java303', 'hitps://byrl.me/ovnjtwww', 'https://i3ymq.app.link/recovery18a', 'https://imagin.com-web-es.ru/el', 'tsel.me/pestahadiahSMSbanking', 'http://wa.me/639997163428', 'https://aib-secured.com', 'edf-remb.eu', 'https://aanvraag-abnamro.nl', 'intensifyrsvp.com.au/p2', 'htts://tramite-cliente.com', 'https://bit.ly/3gxtxw3', 'norj.me/0343N', 'Estonia.zip', 'http://Ov7.org/35VHDX', 'https://px2.in/PC7SL3C', 'https://s.id/ST242', 'nhs-pass.com', 'https://casestyle.com.mx/3mnyw9.php?m', 'www.global-teleshop.site', 'mygovreturn.com', 'https://ameli-r.com/H13022W/', 'http://Зсm.top/A51', 'tiny.cc/rabowereld', 'https://fb.com/|/1FMQgSFmEmonL3Z', 'https://bit.ly/3da3dcV', 'http://www.cimbclickisw.cc', 'seguridad-particulares-esp.xyz/ee', 'kuronamtot.com', 'https://app.niki.ai/HYz4v4pvP3', 'htps://doi.org/10', 'hdfcbk.io/d89bnok7yx2u', 'https://www.amazon.in/gp/payment/statement', 'http://tinyurl.com/ydf6vqkc', 'id.com/nhs/apply', 'su2f.com/s/awbnlc', 'http://8b1.me/EGg0G', 'https://schuld-aflossing.nl/schuld/financien.php?trxid=5ec7e87236a3a', 'secretsanta.al/b/qw/?', 'http://s.id/abnamro-opdracht', 'https://goo.gl/tmNo

In [26]:
unique_spamhunter_url = [i for i in unique_spamhunter_url if i!='']

In [27]:
spamhunter_dataset = pd.DataFrame()
spamhunter_dataset['Unique Url'] = unique_spamhunter_url

In [28]:
import tldextract

def FQDN(Url):
    
    url_extract_res = tldextract.extract(Url)
    fqdn = ''
    if url_extract_res.subdomain:
        fqdn = url_extract_res.subdomain + '.' + url_extract_res.domain + '.' + url_extract_res.suffix
        # fqdn = url_extract_res.domain + '.' + url_extract_res.suffix
    else:
        fqdn = url_extract_res.domain + '.' + url_extract_res.suffix
    
    return fqdn

In [29]:
spamhunter_dataset['FQDN'] = [FQDN(i) for i in spamhunter_dataset['Unique Url']]

len(set(spamhunter_dataset['FQDN']))

8615

In [30]:
a = soupFromUrl('https://facebook.com')

print(a)

[75963, 645, 200, 0]

The below query last ran on 12 Feb 2025

In [31]:
# website_size, text_content_length, status_code, parked = [],[],[],[]

# for i in spamhunter_dataset['FQDN']:
#     a = soupFromUrl('https://'+i)

#     website_size.append(a[0])
#     text_content_length.append(a[1])
#     status_code.append(a[2])
#     parked.append(a[3])


# # parked = [0]*len(spamhunter_dataset)

# # for idx,i in enumerate(spamhunter_dataset['FQDN']):
# #     if spamhunter_dataset['Status Code'][idx]==200:
# #         a = soupFromUrl('https://'+i)
# #         parked[idx] = a[3]
# #         # break

# # print(parked)

C:\Users\mmia43\AppData\Local\Temp\ipykernel_16376\3359563719.py:11: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = bs(req.text,'html')

In [43]:
spamhunter_dataset = pd.read_csv('../Dataset/URL Data/spamhunter Websites Analysis.csv')

In [32]:
# spamhunter_dataset['Website Size in KB'] = website_size
# spamhunter_dataset['Website Textual Content Length'] = text_content_length
# spamhunter_dataset['Status Code'] = status_code

# spamhunter_dataset['Parked'] = parked

In [44]:
for i in spamhunter_dataset:
    print(len(spamhunter_dataset[i]))

15531
15531
15531
15531
15531
15531

In [45]:
spamhunter_dataset

,Unique Url,FQDN,Website Size in KB,Website Textual Content Length,Status Code,Parked
0,http://www.kycpaytm.com/in.php,www.kycpaytm.com,0,0,-1,0
1,points.co.in,points.co.in,0,0,200,0
2,bit.ly/im3,bit.ly,126176,8761,200,1
3,https://bit.ly/3goHo9H,bit.ly,126176,8761,200,1
4,privee.com,privee.com,114,0,200,1
...,...,...,...,...,...,...
15526,https://apple.com.submit-userdata.services/,apple.com.submit-userdata.services,0,0,-1,0
15527,https://bbva.gestlon-online-es.ru/,bbva.gestlon-online-es.ru,0,0,-1,0
15528,www.bristolrhythms.com,www.bristolrhythms.com,0,0,-1,0
15529,http://www.sccb.inth.icu/,www.sccb.inth.icu,0,0,-1,0
15530,parsonsevent.eventbrite.com,parsonsevent.eventbrite.com,227063,5551,200,0

In [46]:
# spamhunter_dataset = pd.read_csv('../Dataset/URL Data/spamhunter Websites Analysis.csv')
spamhunter_dataset = pd.DataFrame.from_dict(spamhunter_dataset)
spamhunter_dataset.head()

,Unique Url,FQDN,Website Size in KB,Website Textual Content Length,Status Code,Parked
0,http://www.kycpaytm.com/in.php,www.kycpaytm.com,0,0,-1,0
1,points.co.in,points.co.in,0,0,200,0
2,bit.ly/im3,bit.ly,126176,8761,200,1
3,https://bit.ly/3goHo9H,bit.ly,126176,8761,200,1
4,privee.com,privee.com,114,0,200,1

In [36]:
spamhunter_dataset['Status Code'].value_counts()

Status Code
-1      7646
 200    6808
 404     478
 403     457
 400      88
 500      23
 503      12
 501       3
 502       3
 406       2
 410       2
 402       2
 526       1
 429       1
 405       1
 525       1
 434       1
 401       1
 204       1
Name: count, dtype: int64

In [37]:
numbers_to_replace = [501,403, 401]

# Value to replace with
new_value = 200

# Update the column
spamhunter_dataset.loc[spamhunter_dataset['Status Code'].isin(numbers_to_replace), 'Status Code'] = new_value

In [38]:
spamhunter_dataset['Status Code'].value_counts()

Status Code
-1      7646
 200    7269
 404     478
 400      88
 500      23
 503      12
 502       3
 406       2
 410       2
 402       2
 526       1
 429       1
 405       1
 525       1
 434       1
 204       1
Name: count, dtype: int64

In [39]:
spamhunter_dataset['Parked'].value_counts()

Parked
0    11479
1     4052
Name: count, dtype: int64

In [40]:
spamhunter_dataset.head()

,Unique Url,FQDN,Website Size in KB,Website Textual Content Length,Status Code,Parked
0,http://www.kycpaytm.com/in.php,www.kycpaytm.com,0,0,-1,0
1,points.co.in,points.co.in,0,0,200,0
2,bit.ly/im3,bit.ly,126176,8761,200,1
3,https://bit.ly/3goHo9H,bit.ly,126176,8761,200,1
4,privee.com,privee.com,114,0,200,1

In [41]:
# spamhunter_dataset.to_csv('../Dataset/URL Data/spamhunter Websites Analysis.csv', index=None)

In [42]:
spamhunter_dataset.drop_duplicates(subset='FQDN', inplace=True)
print(len(spamhunter_dataset))
print(spamhunter_dataset['Status Code'].value_counts())
print(spamhunter_dataset['Parked'].value_counts())

8615
Status Code
-1      6528
 200    1665
 404     337
 400      45
 500      19
 503       8
 502       3
 402       2
 406       1
 526       1
 429       1
 410       1
 405       1
 525       1
 434       1
 204       1
Name: count, dtype: int64
Parked
0    8169
1     446
Name: count, dtype: int64