In [1]:
import requests 
from bs4 import BeautifulSoup as bs
import pandas as pd
import tldextract
import numpy as np
import matplotlib.pylab as plt
import os
import re

In [2]:
def on_sale_chk(text):
    if len(text)<1:
        return False
    return 'domain' in text and 'sale' in text

def on_parked_chk(text):
    if len(text)<1:
        return True
    return 'domain' in text and 'park' in text

def on_Parked(text):
    if len(text)<1:
        return True
    return (('website' in text or 'content' in text) and 'unavailable' in text) or ('will' in text and 'soon' in text)

In [12]:
#returns html contents, textual character length, website size, status code, parked or on sale

def soupFromUrl(scrapeUrl):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.1; zh-CN) AppleWebKit/533+ (KHTML, like Gecko)'}
    try:
        req = requests.get(scrapeUrl, headers=headers, timeout=5)
        # print(req.status_code)
        req.close()
        if req.status_code == 200:
            # print(bs(req.text, 'html.parser').get_text().strip().replace('\n',' '))
            soup = bs(req.text,'html')

            # print(soup)

            text = ''

            if soup.body:
                text = re.sub(r'[^\w]', ' ',soup.body.get_text(' ', strip=True).lower())

            # print(soup)

            # print('text',text)
            # print(bs(req.text, 'html.parser'))
            # return [bs(req.text, 'html.parser'),len(req.text), len(req.content), req.status_code]
            # print([len(req.content), len(text), req.status_code, 0+(on_sale_chk(text) or on_Parked(text) or on_parked_chk(text))])
            return [len(req.content), len(text), req.status_code, 0+(on_sale_chk(text) or on_Parked(text) or on_parked_chk(text))]
        else:
            # return [-1,0,0,req.status_code]
            return [0,0,req.status_code,0]
    except:
        # return [-1,0,0,-1]
        return [0,0,-1,0]

In [5]:
headers = {'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.1; zh-CN) AppleWebKit/533+ (KHTML, like Gecko)'}
req = requests.get('https://www.lycos.com/', headers=headers, timeout=5)
print(req.status_code)
req.close()
if req.status_code == 200:
    # print(bs(req.text, 'html.parser').get_text().strip().replace('\n',' '))
    soup = bs(req.text,'html')

    # print(soup)
    text = ''

    if soup.body:
        text = re.sub(r'[^\w]', ' ',soup.body.get_text(' ', strip=True).lower())

    print(soup)
    print('text',text)
    print([len(req.content), len(text), req.status_code, 0+(on_sale_chk(text) or on_Parked(text) or on_parked_chk(text))])

200
<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta content="Lycos, Inc., is a web search engine and web portal established in 1994, spun out of Carnegie Mellon University. Lycos also encompasses a network of email, webhosting, social networking, and entertainment websites." name="description"/>
<meta content="" name="author"/>
<link href="https://ly.lygo.net/static/lycos/img/favicon.ico" rel="icon" type="image/png"/>
<title>Lycos.com</title>
<link href="//fonts.googleapis.com/css?family=Lato:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css"/>
<link href="/css/in/fonts.css" rel="stylesheet" type="text/css">
<link href="https://ly.lygo.net/static/lycos/css/in/font-awesome.css" rel="stylesheet" type="text/css">
<!-- Bootstrap core CSS -->
<link href="https://ly.lygo.net/static/lycos/css/in/bootstrap.css" rel="stylesheet"/>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<link href="https://ly.lygo.net/static/lycos/css/in/ie10-viewport-bug-workaround.css" rel="stylesheet"/>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<!-- Custom styles for this template -->
<link href="https://ly.lygo.net/static/lycos/css/in/slider_prev.css" rel="stylesheet" type="text/css">
<link href="https://ly.lygo.net/static/lycos/css/in/carousel.css" rel="stylesheet" type="text/css">
<link href="https://ly.lygo.net/static/lycos/css/in/custom.css" rel="stylesheet" type="text/css"/>
<link href="https://ly.lygo.net/static/lycos/css/us/newadd.css" rel="stylesheet" type="text/css"/>
<link href="https://ly.lygo.net/static/lycos/css/uvtHamburger.css" rel="stylesheet"/>
<script src="https://ly.lygo.net/static/lycos/js/jquery-1.10.1.min.js"></script>
<script src="https://ly.lygo.net/static/lycos/js/jquery.autocomplete.js"></script>
<script src="https://ly.lygo.net/static/lycos/js/universal.js"></script>
<script src="//scripts.lycos.com/jquery-addons/jquery.cookie-1.4.1.js"></script></link></link></link></link></head>
<!-- NAVBAR
================================================== -->
<body>
<header>
<div class="container">
<div class="nav navHome">
<div class="navbar-left">
<div class="uvt-logo-block">
<div class="prop-logo">
<!-- click and mouseover show network panel -->
<div class="uvt-dog network-toggle"></div>
<div class="network-panel">
<ul class="nw-properties">
<li><a href="https://www.lycos.com"><span class="icon icon-lycos"></span><span class="name">Lycos.com</span></a></li>
<li><a href="http://www.mail.lycos.com"><span class="icon icon-mail"></span><span class="name">Mail</span></a></li>
<li><a href="http://weather.lycos.com"><span class="icon icon-weather"></span><span class="name">Lycos Weather</span></a></li>
<li><a href="http://www.tripod.lycos.com"><span class="icon icon-tripod"></span><span class="name">Tripod</span></a></li>
<li><a href="http://angelfire.com"><span class="icon icon-angelfire"></span><span class="name">Angelfire</span></a></li>
<li><a href="http://domains.lycos.com"><span class="icon icon-domains"></span><span class="name">Domains</span></a></li>
</ul>
<!-- end proeprties -->
</div>
<!-- end Network Panel -->
</div>
</div>
<!-- end Logo-network -->
</div>
<div class="navbar-left">
<a href="http://weather.lycos.com" title="Launch Lycos Weather">
<span class="weather-text">

Cookeville 68° F
				</span> <span class="icon weather-icon"> <img alt="mostly_cloudy" src="https://ly.lygo.net/static/lycos/images/weather/frontpage/mostly_cloudy.png"/>
</span>
</a>
</div>
<div class="network uvt uvth">
<div class="lang-selector">
<div class="ls-parent">
<span class="lang-icon"><img alt="Select Your Language" src="https://ly.lygo.net/static/lycos/img/lang-icon.png"/></span>
<script type="text/javascript">
                            function setDefaultLanguage(lang) {
                                $.cookie('defaultLanguage', lang, { path: '/', expires: 3650, domain: 'lycos.com' });
                            }
                        </script>
<ul class="ls-children">
<li class="selectedLang"><a href="/" onclick="setDefaultLanguage('en'); return true;" title="English">English</a></li>
<li><a href="/" onclick="setDefaultLanguage('es'); return true;" title="Spanish">Español</a></li>
<li><a href="/" onclick="setDefaultLanguage('ja'); return true;" title="Japanese">日本語</a></li>
<li><a href="/" onclick="setDefaultLanguage('de'); return true;" title="German">Deutsch</a></li>
<li><a href="/" onclick="setDefaultLanguage('ko'); return true;" title="Korean">한국어</a></li>
<li><a href="/" onclick="setDefaultLanguage('fr'); return true;" title="French">Français</a></li>
<li><a href="/" onclick="setDefaultLanguage('it'); return true;" title="Italian">Italiano</a></li>
<li><a href="/" onclick="setDefaultLanguage('nl'); return true;" title="Dutch">Nederlands</a></li>
<li><a href="/" onclick="setDefaultLanguage('sv'); return true;" title="Swedish">Svenska</a></li>
<li><a href="/" onclick="setDefaultLanguage('da'); return true;" title="Danish">Dansk</a></li>
<li><a href="/" onclick="setDefaultLanguage('fi'); return true;" title="Finnish">Suomi</a></li>
<li><a href="/" onclick="setDefaultLanguage('no'); return true;" title="Norwegian">Norsk</a></li>
<li><a href="/" onclick="setDefaultLanguage('ga'); return true;" title="Irish">Gaeilge</a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</header>
<!-- Carousel
    ================================================== -->
<div class="search_slider">
<div class="col-sm-12">
<div class="carousel slide" data-ride="carousel" id="myCarousel">
<div class="searc_box">
<div class="lycos">
<a href="#"><img alt="" src="https://ly.lygo.net/static/lycos/img/in/lycoslogo.png"/></a>
</div>
<div class="searc_input">
<script type="text/javascript"><!--//--><![CDATA[//><!--
    function checkSubmit() {
      var queryBox = document.getElementById('query');

      if(( queryBox.value == 'Enter search term...' ) || ( queryBox.value.trim() == '' )) {
	  queryBox.value = '';
	  queryBox.focus()
	  return false;
      }
      return true;
    }
    //--><!]]></script>
<form action="https://search10.lycos.com/web" id="form_query" method="get" onsubmit="return checkSubmit();">
<fieldset>
<input autofocus="" class="search-input" id="query" name="q" placeholder="Enter search term..." type="text" value=""/>
<button class="search"></button>
</fieldset>
<input id="keyvol" name="keyvol" type="hidden" value="FA02D34CE00ABC10FE"/>
</form>
</div>
<div id="autocomplete-suggestions"></div>
</div>
<!-- Indicators -->
<ol class="carousel-indicators">
<li class="active" data-slide-to="0" data-target="#myCarousel"></li>
<li data-slide-to="1" data-target="#myCarousel"></li>
<li data-slide-to="2" data-target="#myCarousel"></li>
</ol>
<div class="carousel-inner" role="listbox">
<div class="item active">
<img alt="First slide" class="first-slide" src="https://ly.lygo.net/static/lycos/img/us/slider/slider_us1.jpg"/>
</div>
<div class="item">
<img alt="Second slide" class="second-slide" src="https://ly.lygo.net/static/lycos/img/us/slider/slider_us2.jpg"/>
</div>
<div class="item">
<img alt="Third slide" class="third-slide" src="https://ly.lygo.net/static/lycos/img/us/slider/slider_us3.jpg"/>
</div>
</div>
</div>
</div>
</div>
<!-- /.carousel -->
<section class="content" style="padding-bottom: 20px;">
<div class="container">
<div class="navbar-left">
<ul class="nav nav-tabs">
<li><a href="https://lycos.itemorder.com/sale" style="display: inline;" target="_blank"><img src="https://ly.lygo.net/static/lycos/images/lycos_swag_mug.png" style="display: inline;
	height: 60px;
	width: 60px;"> Lycos
						SWAG</img></a></li>
</ul>
</div>
<div class="navbar-right">
<ul class="nav nav-tabs">
<li><a href="http://www.mail.lycos.com">Mail</a></li>
<li><a href="http://www.tripod.lycos.com">Tripod</a></li>
<li><a href="http://domains.lycos.com">Domains</a></li>
<li><a href="http://weather.lycos.com">Weather</a></li>
<li><a href="http://www.angelfire.com/">Angelfire</a></li>
</ul>
</div>
</div>
</section>
<footer>
<div style="float: left; width: 100%;">
<div style="margin-left: auto; margin-right: auto; height: 95px; width: 733px; margin-bottom: 5px;">
</div>
</div>
<div class="container">
<ul class="navbar-left">
<li>
<p>Copyright © 2025 Lycos</p>
</li>
<li><a href="https://info.lycos.com" title="About Lycos">About</a></li>
<li><a href="https://info.lycos.com/career-opportunities/job-openings" title="Careers at Lycos">Careers</a></li>
<li><a href="https://advertising.lycos.com" title="Advertise with Lycos">Advertise With Us</a></li>
<li><a href="https://info.lycos.com/resources/terms-of-service" rel="nofollow" title="Lycos Network Legal">Legal</a></li>
<li><a href="https://info.lycos.com/resources/privacy-policy" rel="nofollow" title="Lycos Privacy Policy">Privacy</a></li>
<li><a href="https://registration.lycos.com/helpcenter_passthrough.php?m_PR=1" rel="nofollow" title="Lycos Help Portal">Help</a></li>
<li class="search-provider modern-browsers"><a href="https://info.lycos.com/resources/lycos-search/#Chrome" onclick="window.external.AddSearchProvider('https://search10.lycos.com/opensearch.xml')" title="Make Lycos Search the Default Search Provider"><span>Add
						Lycos Search to Browser</span></a></li>
</ul>
<ul class="navbar-right">
<li><a href="https://www.facebook.com/lycos.search" target="_blank" title="Friend Lycos on Facebook"><img alt="Facebook" src="https://ly.lygo.net/static/lycos/images/facebook.png"/></a></li>
<li><a href="https://twitter.com/SearchLycos" target="_blank" title="Follow Lycos on Twitter"><img alt="Twitter" src="https://ly.lygo.net/static/lycos/images/twitter.png"/></a></li>
</ul>
</div>
</footer>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-0WY0KPH0ZW"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-0WY0KPH0ZW');
</script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-76FJGHQNN6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-76FJGHQNN6');
</script><script type="text/javascript">//<![CDATA[
  $('#keyvol').val('00974ee0f045690d2264');
//--><!]]>
</script>
<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ly.lygo.net/static/lycos/js/in/bootstrap.min.js" type="text/javascript"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="https://ly.lygo.net/static/lycos/js/in/ie10-viewport-bug-workaround.js"></script>
<script src="https://ly.lygo.net/static/lycos/js/in/prev_next.js" type="text/jscript"></script>
<script>

$(document).ready(function(e) {

	   $("#owl-demo1").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });
	    $("#owl-demo2").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });
	    $("#owl-demo3").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });
	    $("#owl-demo4").owlCarousel({
        items :6,
        lazyLoad : true,
        navigation : true
      });



});


</script>
<script src="https://ly.lygo.net/static/lycos/js/in/dog_in.js"></script>
<script>$(function() {
	'use strict';

	// Initialize ajax autocomplete:
	$('#query').autocomplete({
		serviceUrl : 'https://us.search.yahoo.com/sugg/gossip/gossip-us-partner?output=sd1&appid=lycos',
        dataType: 'jsonp',
		paramName : 'command',
		onSearchComplete : function(originalQuery, suggestion) {
			var re = new RegExp('\b' + $.Autocomplete.utils.escapeRegExChars(originalQuery), 'gi');
			return re.test(suggestion.value);
		},
		onSelect : function(suggestion) {
			$('#form_query').submit();
		},
		onInvalidateSelection : function() {
			$('#selction-ajax').html('You selected: none');
		},
		transformResult : function(_response) {
			var response = typeof _response === 'string' ? $.parseJSON(_response) : _response;
			return {
				query : response.q,
				suggestions : $.map(response.r, function(dataItem) {
					return dataItem.k;
				})
			};
		}
	});
});
</script></body>
</html>

text lycos com mail lycos weather tripod angelfire domains cookeville 68  f english español 日本語 deutsch 한국어 français italiano nederlands svenska dansk suomi norsk gaeilge lycos       swag mail tripod domains weather angelfire copyright   2025 lycos about careers advertise with us legal privacy help add       lycos search to browser
[13601, 328, 200, 0]

In [13]:
print(soupFromUrl('https://www.delinian.com/'))
print(soupFromUrl('https://www.makecashonline.com/'))
print(soupFromUrl('https://www.lycos.com/'))

[38173, 1863, 200, 0]
[114, 0, 200, 1]
[13597, 328, 200, 0]

In [24]:
super_dataset_url = pd.read_csv('../Dataset/URL Data/super_dataset.csv', encoding='mac_roman')
super_dataset_url[:10]

                            URL
0           http://olo.me/3i6xF
1         http://bit.ly/3CloxIZ
2                  http://XXXXX
3                https://k1s.in
4         http://bit.ly/2NfDtSn
5               httpgooglhsocyr
6    http://ysmrtlnk.in/vaylpjl
7        httpysmrtlnkinllkwpdym
8        http://onelink.to/kmxk
9  http://f6109ddbe549.ngrok.io

In [25]:
import re

def find_first_slash_preceded_by_number(s):
    # Regular expression to find the first instance of a number followed by '/'
    match = re.search(r'\d+/', s)
    
    if match:
        return match.start() + len(match.group()) - 1  # Return the index of '/'
    else:
        return -1  # Return -1 if no match is found

# Example usage
string = "example77/test 88/test2 99/test3"
index = find_first_slash_preceded_by_number(string)
print(index)  # Outputs the index of the first '/' preceded by a number

9

In [31]:
unique_super_dataset_url = list(set(super_dataset_url['URL']))

In [32]:
for idx,i in enumerate(unique_super_dataset_url):
    if '..' in i:
        if 'www' in i:
            unique_super_dataset_url[idx] = ''
        else:
            unique_super_dataset_url[idx] = unique_super_dataset_url[idx].replace('..','.')

In [39]:
unique_super_dataset_url = [i for i in unique_super_dataset_url if i!='']
# unique_super_dataset_url = set(unique_super_dataset_url)
unique_super_dataset_url

['http://50ca13b44a4d.ngrok.io/sbibank',
 'httpysmrtlnkinurvqwr',
 'httpbitlynysdiy',
 'www.imsindia.co',
 'httpbitlywfwixn',
 'http://apple.id.auth-client',
 'http://uk-royalmail.com/',
 'http://l.jazzmobilemag.pk/dHTDPLS/27cd',
 'http://byrl.me/o5Lq8Hy',
 'http://bit.ly/3bkEnWk',
 'http://nsm.sg/6YbUKX',
 'httpysmrtlnkinddxidsa',
 'http://www.jbhifi.com.au/receipts/',
 'httptbkbzjjvjyncy',
 'httpgooglyfyzzd',
 'http://chat.whatsapp.com/',
 'www.lons.in/C05C696E4',
 'httpbitlynkvj',
 'http://namzx.com/e0v',
 'http://l.jazzmobilemag.pk/1U1V0RH/aa54',
 'httpgooglnvtsgn',
 'http://passform.co',
 'http://bit.ly/22491PG',
 'httpsgooglekyj',
 'http://2xz.us/3/Vwfp',
 'httpgooglcrzy',
 'http://RedCross-mask.ca',
 'http://relianceindustrieslimitedapp',
 'http://Santander.account',
 'http://boi',
 'httpgooglymhukb',
 'downloadhttpgoogldkg',
 'httpbitlykfcweb',
 'http://bit.ly/2MtdmSZ',
 'httpbitlyodqxuw',
 'httpipruconpyoxmpn',
 'http://92d0bc8a5',
 'httptinyurlcomhqtypd',
 'www.natursanhealth.com',
 'httpmjabngpnqcikk',
 'http://bhwrmo',
 'http://go.fyndi.ng/100k',
 'http://bit.ly/3JzNtom',
 'http://ekycsbi.com',
 'http://l.jazzmobilemag.pk/GZR9CFn/2365',
 'http://bit.ly/3pEZ87d',
 'https://bit.ly/45uc9TQ',
 'http://ow.ly/VkaOd.',
 'httpgooglthahj',
 'http://covid-application.com',
 'http://komo.ph/4percentpromo',
 'http://hsbc.secure-new-attempt.com',
 'http://bit.ly/1shAC',
 'httpbitlyicnas',
 'www.tat',
 'www.zarcasino.co.za',
 'https://identity.com.au',
 'http://sbstore.ru/dh/',
 'httpysmrtlnkincelvxj',
 'http://bmh.uno/FBRER4',
 'http://p.jazzmobilemag.pk/USswu38/2ff7',
 'httpwaphandygocombsnlnfeveroffer',
 'httpwwwmtsindiainrechargehtml',
 'http://sbieupdates.com',
 'http://Indusbank.in/',
 'https://rollover.cc/eidsale',
 'http://dlg.lk/nfbps',
 'http://dssf',
 'http://nmc.sg/dok4K9',
 'www.snapdeal.com',
 'httpysmrtlnkinwrgconc',
 'httpmsgmndpkgkxzoqzrr',
 'http://barclays',
 'httplimeroadmepcmrso',
 'http://adobe-update.store',
 'httpmsgmnjwdjlfobamlfdkd',
 'http://redelivery-h-secure.com/',
 'httpbitlykwikind',
 'http://paypal.case-id1099.com',
 'http://utipointz.com/',
 'httpsgooglmutnm',
 'https//www.gov.uk/report',
 'www.acmvip.com/f/dvwa8Hp',
 'httpgooglyisulc',
 'httpbitlymjanv',
 'http://cutt.ly/rwZGbW6',
 'httpbitlycubedogood',
 'httpgooglnkbmy',
 'httpgooglsnlyb',
 'http://8116136763f1.ngrok.io/sbibank/',
 'http://youtu.be/fXqJj_zEoGo',
 'httpysmrtlnkinbjqdxx',
 'http://ee.uk.myaccinf10.com',
 'http://bill.vz.to/',
 'https//hopscotch.app.link/ahNmHADW6Q',
 'http://trkru.com/6ET',
 'httppytmezb',
 'www.britishgas.co.uk/solr/neon',
 'http://lloyds-mobilesecure.com/uk',
 'httpmjabngmuodyd',
 'http://l.jazzmobilemag.pk/mOzHofH/948b',
 'httpgooglerxw',
 'http://141.255.151.129/sbibankDear',
 'http://l.jazzmobilemag.pk/yeagPEG/ca38',
 'http://mrjanju',
 'http://phon.pe/qjclpuey',
 'httpsliqbitscomsliq',
 'httpbitlyokmqwp',
 'httpbitlylgilbm',
 'www.bitlyredeemtoday.in.net',
 'httpgoogleljqr',
 'httpgooglxpdgi',
 'http://icicipayback.com/',
 'http://28c12a168cbc.ngrok.io',
 'http://manager',
 'httpbitlydfstxh',
 'httplandingiairescomicicipruamazonofferjpg',
 'http://myhermes',
 'https//bit.ly/3C1YWDI',
 'http://fnsth.com/1Kx',
 'httplimeroadmesnntr',
 'httpwwwshaadicomdlsms',
 'http://nab.manage-device.app',
 'http://goo.gl/LHCS9W',
 'http://m.BajFin.in/H3JeD-20',
 'www.unileverweb.com',
 'httpysmrtlnkinokqornqc',
 'httpsfbcomltencymqtxr',
 'http://wa',
 'http://bit.ly/3mynBd2',
 'http://bit.ly/340XMJV',
 'http://t.co/hmUVEzjkok',
 'http://cutt.ly/oA1JC31',
 'httplimeroadmesnglls',
 'http://bit.ly/3BuOfg5',
 'http://phwsappm.com',
 'https://bit.ly/2QAvCgx',
 'www.bofa-qhw.com',
 'http://gov.cgfund.uk/apply',
 'http://k2p.in/PWKPHKPYHQQ',
 'http://dispatch',
 'http://currs26d.top',
 'http://tiny.jio.com/',
 'http://bit.ly/20XaOxU',
 'http://t.co/8jnBfl2cix',
 'httpjsdlinazhuiupx',
 'http://p.jazzmobilemag.pk/jD5Flru/6cc3',
 'http://eej.at/FGEsf7Zb',
 'httpgooglnlqg',
 'http://p.jazzmobilemag.pk/2WUcUcm/a84b',
 'http://myo2.bill210.com',
 'http://l.jazzmobilemag.pk/Sd6YOpW/8513',
 'http://is.gd/KUEKVn',
 'online:https://bit.ly/3HzEGLR',
 'http://apple.location-device.in/',
 'httpgooglxsrlfq',
 'http://gl.tc/b',
 'http://sbik.great-site',
 'https://is.gd/HoqALBtoactasstatedontheletter.',
 'http://bit.ly/voteANCapp',
 'http://bit.ly/2qPeTer',
 'http://onelink.to/j39tqk',
 'http://bharatpe.in/vpSto~',
 'www.ngpay.com/dominoswap',
 'http://p.jazzmobilemag.pk/5j2v5ai/a7de',
 'httpmsgmnqesocpkadjyyhqifp',
 'http://sbicardredeem.com',
 'httpmjabngwdgtkbe',
 'www.sbipro.co.in',
 'http://l.jazzmobilemag.pk/amIaKz7/bccb',
 'httpbitlyyojek',
 'http://m.BajFin.in/DhTIPpsc',
 'http://l.jazzmobilemag.pk/nI5L6MB/f652',
 'http://l.jazzmobilemag.pk/nXeq4pZ/18de',
 'http://apple.com.store',
 'http://wu.is/aPlyi',
 'http://m.rgic.in/aJpykvN',
 'httpgooglaodzn',
 'httpgooglkldysk',
 "https//bit.ly/3qgyBggToday'sto-dolistOwntheOlascooterThefinalpaymentwindowtomake",
 'httpbitlymzogs',
 'https//humplanet.com/whattoseeanddoingibraltarurgentvisittodeletethem',
 'httpmonelinkme',
 'httpgooglhhszui',
 'httpbitlybugi',
 'http://5fi.in/NX8QOLxb',
 'http://uvwmk2.com/3eZUY',
 'httpgooglpdzo',
 'https://bit.ly/3L5EFU5',
 'http://plan-ref.info/dpd',
 'httpgooglfqmu',
 'https://bit.ly/3Yt8PDI',
 'httpmsgmndychmoyeagqjkfovl',
 'http://px2.in',
 'http://ee-special-offer.com/EE',
 'httpgoiminimapptodownloadindiamartappforfreeandgeteasilyconnectedwith',
 'http://dr-c.in/TU4Kp/',
 'http://t.co/3hiXCplZsw',
 'http://id',
 'httpgooglvbyxt',
 'http://bit.ly/3EqB6RU',
 'experiencehttp://www.vouch4me.com/etlp/dining.asp',
 'httpmynttomvw',
 'http://l.jazzmobilemag.pk/0sUrk2G/f270',
 'here:https://echdfc.in/gkk6g-eVJY4',
 'http://l.jazzmobilemag.pk/tX5KofH/baca',
 'infohttponelinktomusms',
 'http://l.jazzmobilemag.pk/9RZOUvU/b545',
 'http://wa.me/message/',
 'httpgoogleliqa',
 'http://www.artantapar.com/7/',
 'httpgoogltzpyhr',
 'http://deldh',
 'http://eservices.durban.gov.za/',
 'http://f17a8c33ff92.ngrok.io/',
 'http://me.cies.cc/api',
 'http://t-mo.co/sms-spamTruth',
 'http://185.244.213.78/',
 'http://tiny.cc/3otdez',
 'httpmsgmnnanjcstgbmmx',
 'http//tms.',
 'http://4012c64f2e08',
 'http://178.159.7.14/ITRef',
 'http://durajobs.in/a/',
 'http://goo.gl/BGmfnW',
 'http://bit.ly/2VgUtqo',
 'http://nmc.sg/bzDPv3',
 'http://absltj.com/2',
 'http://nmc.sg/b2yu6D',
 'http://p.jazzmobilemag.pk/hzqUfa5/ea1a',
 'http://dmn.page.link',
 'www.grthub.in',
 'https://chat.whatsapp.com/FM3h1w8YGQ94EjpPcRu1VN',
 'http://cutt.ly/61Qk7g9',
 'httpmpytmgrof',
 'http://bit.ly/2M74fbS',
 'http://parceltracking',
 'http://update-icloud.com',
 'www.idinfo-ee.services',
 'http://sbiupdatekyc.in',
 'https://www.elo.fashion/Jackets',
 'www.rcmkt.in',
 'nowhttps//q8d5n.app.goo.gl/LYvPprecloseanytimewithzerochargeRegardsCapitalFloat',
 'httpmpytmpp',
 'httpgoogllfdco',
 'https://cutt.ly//p4EciqF',
 'httpgooglwomon',
 'http://l.jazzmobilemag.pk/cVHfn2t/02b1',
 'httpgooglpqyzionlytoday',
 'httpjsdlinfrxvkv',
 'http://l.jazzmobilemag.pk/0ZuVlVI/4801',
 'http://we.tl/t-T8QpojpMtb',
 'http://p.jazzmobilemag.pk/zUfzTND/6ad3',
 'http://rzp.io/i/Jd11g0qg',
 'http://bitly.ws/s6AH',
 'https//cutt.ly/CGa641C',
 'httpsgooglbecsf',
 'http://qz6.in/ejhQXb',
 'http://www.metro.onlinebank-couk.com',
 'www.iCloud.Signed',
 'http://nrcc.news/3gg',
 'http://paypal.co.uk.xso4.icu/n/',
 'httpmjabngiqtvexa',
 'https://westpac-mobile.cc/?updateorcalluson132032.',
 'www.netflix',
 'httpbitlyodv',
 'http://coin.uday.live/g/',
 'C.http://onlineshoppingwinners',
 'httpmsggdsophdawktrg',
 'httpbitlyphny',
 'http://l.jazzmobilemag.pk/ZV5U7rK/a56b',
 'http://nmc.sg/gt7Yiq',
 'http://bit.ly/3vHtoRM.NuVinyl',
 'httpgoiminbatodownloadindiamartappforfreeandfindtherightsuppliers',
 'http://u1.mnge.co/',
 'http://idapplecs.page.link',
 'httpideacontestzonein',
 'http://gouve.page',
 'http://urlz.fr/iuM6',
 'http://bit.ly/pay2you',
 'http://ab4ac2e14688.ngrok.io',
 'https://bit.ly/3DrcEz',
 'http://bit.ly/2ktMUUW',
 'www.verycd.com',
 'http://anz.comau.im',
 'http://bit.ly/3t3g321',
 'httpsitunesapplecomusappmohanastroidmt',
 'httpjmprymy',
 'httpstxglrsdwgndkvgbjbsea',
 'http://sbikyu-tech.preview-domain.com/',
 'http://digitaltalentspro.com/au',
 'http://open',
 'http://anpost.ie-secure',
 'https://onelink.to/JazzCash',
 'http://northeastlondonccg.nhs.uk/We',
 'http://http://a1e69d607dc6.ngrok.iol',
 'http://accounts',
 'http://bit.ly/2rJnAoZ',
 'http://eeredirect.info/',
 'http://h.dlhvr.in',
 'http://img.',
 'http://asip8.app.link',
 'httpgooglfxxep',
 'http://cx.indianoil.in/webcenter/portal/Your',
 'http://medicare-pcr-test.com',
 'httpjmprcgy',
 'http://cd18b76d24f7.ngrok.io/sbibank',
 'httpgooglfdtx',
 'http://nmc.sg/IIAK84',
 'www.EaseMyTrip.com',
 'https://103.208.86.96',
 'http://bit.ly/3INCMOK',
 'http://mpesaapp.page.link/NSSFEnd',
 'www.mygp.io/app',
 'http://onlineluckydrawlist.com',
 'httpsgooglcvgvkh',
 'httpgooglxgnll',
 'http://paypal.co.uk',
 ':http://vgredwoodre.me/',
 'http://govapplication.ga',
 '‚àö¬¢¬¨√ú¬¨√≠http://3i|9u.fund82.com/jp/',
 'http://nmc.sg/ValhHFej',
 'httpgoogltxsqtj',
 'http://hsbc.digital',
 'https//bit.do/hdfcmnc1toavoidanyloss',
 'http://rzp.io/i',
 'httpmjabngfbjcjsou',
 'httpgoogldwswxf',
 'http://a98b7fcc493c.ngrok.io/sbibank',
 'http://deny-app-access.com/',
 'http://l.jazzmobilemag.pk/fCj7FtC/5061',
 'httpgoogltytfmd',
 'httpwynkinmujk',
 'www.onlineshoppingluckidraw.in',
 'http://cx.indianoil.in/webcenter/portal/Invoice',
 'http://l.jazzmobilemag.pk/0WBo1v7/2d60',
 'http://m.BajFin.in/GWKKgOYS',
 'http://online.hmrc.gov.uk.mob2',
 'http://ptrnf.com/1SPg',
 'http://l.jazzmobilemag.pk/fgxG9SN/ea95',
 'httpordershalimarmumbaicom',
 'http://mysejahtera.malaysia',
 'httpgoogltwgz',
 'http://l.jazzmobilemag.pk/005duzo/62a4',
 'http://tejus.info/l9YVHOvjyk',
 'httpgooglicuymv',
 'http://cutt.ly/H158Cp8',
 'http://is.gd/ITAwcz',
 'httpairtelinfree',
 'httpgooglcnco',
 'httpappstorejiocom',
 'httpysmrtlnkinpnvqnkt',
 'https//m.rbi.org.in',
 'https//bit.ly/2UyYC80toverifyanddeposityourfundToOptoutsendSTOP',
 'http://f8e79cce0247.ngrok.io',
 'http://t.uber.com/delish9',
 'http://bit.ly/2ZrKF3Q',
 'httpbitlyqfbb',
 'http://hfvcdscvgt.online',
 'https://centralink-review.info/access/.',
 'http://bit.do/fogzo',
 'httpgooglboniu',
 'http://rolpoint.com/',
 'http://l.jazzmobilemag.pk/Li2MZKw/e372',
 'httpplussiomeds',
 'http://bitly.ws/ozQT',
 'https://m.rbi.org.in/./Scripts/',
 'http://m.BajFin.in/KsF_XEI',
 'http://n39.in/K252od',
 'http://www.crushco',
 'httpofferssmartbuyhdfcbankcomofferdeffbbaffadafcblsccsubscriptionsoffervalidtillstaugtcapply',
 'http://l.jazzmobilemag.pk/qKn5LLt/7624',
 'https://telenor.page.link/2JaF.',
 'http://baOea35c.ngrok.io/cashbackpaytm/',
 'http://l.jazzmobilemag.pk/2h5Kpb2/57f4',
 'www.dominos.co.in/orderonline.',
 'http://bit.ly/2ZnAWUL',
 'http://198.12.90.111/',
 'http://railmadad.indianrailways.gov.in',
 'http://l.jazzmobilemag.pk/VCEW9Xg/e430',
 'http://ukdelivery',
 'http://bit.ly/mgotrend',
 'httpbitlywaynws',
 'httpgooglxhfsg',
 'http://l.jazzmobilemag.pk/oQY4yH0/22d0',
 'https://www.yisdt90.top/',
 'www.NetJobsGuide.com',
 'http://cutt.ly/VD87630',
 'www.potful.in',
 'http://l.jazzmobilemag.pk/uNCXWkc/7f62',
 'httpgooglqtttbp',
 'http://bit.ly/2HWOKEL',
 'www.Ldew.com1win150ppmx3age16subscription',
 'http://bit.ly/312ZpYy',
 'httpbitlyoujzz',
 'www.dhlindia-kyc.com',
 'http://cowin',
 'httpgooglygxq',
 'http://goo.gl/SU0SqP',
 'www.smartraveller',
 'http://p.jazzmobilemag.pk/pRc8BoH/6be8',
 'httpwwwlibertyshoesonlinecomcustomeraccountloginreferer',
 'httpysmrtlnkindtdhvsf',
 'http://aramex-payment.com',
 'http://t.co/H8BJaKqEny',
 'http://wpb.device',
 'httpubrtonxory',
 'httpysmrtlnkintiufl',
 'www.almirah.com.pk',
 'http://e72c62b8ac21.ngrok.io',
 'http://shoppepay.in/',
 'http://ekrt.in/P9Ggn1OuuuN',
 '//www.fedex.com/gb/delivery',
 'http://lloyds-online-service.meBANK',
 'http://bit.ly/3rd',
 'https//s.id/1cjy0',
 '.https//questionnaire-displayed-mono-magazines.trycloudflare',
 'httpjsdlinmapvkh',
 'http://bit.ly/2rU3ysl',
 'http://tx3.in/NHmQ',
 'http://cutt.ly/cwSOMfg',
 'http://cutt.ly/qlfUyqV',
 'http://worldinsider.live/dhl/',
 'http://bit.ly/3DbyDR',
 'https://bit.ly/gamebirdgg',
 'https://xxxxx',
 'www.freebee.eu/',
 'http://5.135.174.209/',
 'http://chs-b.app.link/1',
 'https//bit.ly/2nbPmvP',
 'httpgoogljkrzro',
 'httppytmedd',
 'www.fullontrip.com',
 'http://My',
 'http://rb.gy/6xa5fq',
 'http://o2.uk.bill442.com/',
 'httpsplaygooglecomstoreappsdetailsidcomtatatatapower',
 'httpsgoogljdqe',
 'httpbitlysecretd',
 'httpgooglkyj',
 'http://relianceindustrieslimitedindiacellr',
 'httptinyurlcomzmhurm',
 'http://ukhmrc-tax',
 'httpgoogliq',
 'clickhttpbitlymamjit',
 'http://bit.ly/2aHtv3w',
 'http://pcr.test.status-33.com',
 'http://payit',
 'httpbitlycomgetconfirmtkt',
 'httpbitlypastr',
 'http://u1.mnge.co/91KQZk6',
 'http://www.t5.ai/s',
 'https//cutt.ly/D6pJx9andsubmitarequestfortheremittanceofyourapprovedrefundof',
 'httpjsdlinmapurklodging',
 'httpmsggdsxjybrzjugd',
 'http://datakart.online',
 'www.FullOnInsurance.com',
 'http://bit.ly/3yBN7C‚àö√ë¬¨‚àû',
 'http://l.jazzmobilemag.pk/Jb4Soe5/f67b',
 'https://Ibpiaccessaccount.com/?',
 'http://nhs.yourpass-info',
 'http://dvla.co.uk.vehicle-tax',
 'httpgooglefkssk',
 'httpgooglcmxgqo',
 'http://bit.ly/2UIZPDk',
 'http://l.jazzmobilemag.pk/Tfo4tIA/589e',
 'http://id-helpdesk.com',
 'https://bit.ly/3hLgWaQ',
 'httpmsgmndf',
 'http://uspsresolve.com',
 'http://hdfclife.insurepay',
 'www.netflxtvreminder-paymnt.com',
 'httpysmrtlnkinbgclflii',
 'http://is.gd/LW1Sb4',
 'http://simpek.com',
 'www.fb.com/tripleoneburger',
 'httpbitlysrbc',
 'httplybratapppqs',
 'http://iec-seva.com',
 'http://bit.ly/3wxQK9r',
 'http://nsm.sg/6PAkd5',
 'http://hsbc.uk',
 'http://www.3355881.com/',
 'http://nsm.sg/6c7h7T',
 'https://bit.ly/42P5HoZ',
 'http://tinyurl.com/e',
 'http://www.mylicenceuk.com',
 'http://i3fq.com/N1Txw',
 'http://rb.gy/tyzwho',
 'http://maxis.novelplus.co.To',
 'httpscontentgoindigoincorporatemobile',
 'httpgooglovqn',
 'httpgooglkfc',
 'http://mtn',
 'httpbitlyriebjs',
 '//www.gov.uk',
 'httpgooglncttd',
 'http://sbiccxpaid.com/',
 'http://cashbackkmb.com/',
 'www.iskconmeal.in',
 'www.lavasafuturecities.indiatimes.com',
 'www.textcomp.com',
 'http://ee-update.ref0145.com',
 'http://rblpropoints.co.in',
 'httpgooglgbxg',
 'http://l.jazzmobilemag.pk/usysZVT/eb17',
 'www.justtrade.i',
 'httpmsgmnjmqkoravnhiai',
 'httplimeroadmepwvzb',
 'www.SMS.ac/u/hmmross',
 'httpbitlyufiqer',
 'httpbitlyfurnitureshop',
 'http://l.jazzmobilemag.pk/BovXWGR/41ae',
 'http://m.BajFin.in/Q3S12ZIM',
 'http://peasy.in',
 'http://l.jazzmobilemag.pk/5XF4GHS/48b6',
 'http://wa.me/918968608277',
 'httpsnpdlininzty',
 'https//santander.account-reset3.com',
 'httppeppertapcom',
 'httpbitlymycwj',
 'httpgooglyifhtm',
 'http://bit.ly/3uY80HV',
 'httpsbitlycomiileo',
 'http://nobr.kr/sv/whjxq',
 'https://bit.ly/414RulX',
 'http://goo.gl',
 'http://bit.do/incomtax',
 'httpysmrtlnkinsucpjrap',
 'http://365',
 'http://p.jazzmobilemag.pk/0zZKGu1/73a5',
 'httpjsdlinsfdigpzg',
 'http://ul.mnge.co/RJKLEJ',
 'http://sbipoints.co.in',
 'httpysmrtlnkinmgvgzrv',
 'http://k2p.in/PHHWAKQYKNA',
 'httpgoogljemkp',
 'http://1kx.in/DfhL1vE1ZW9',
 'https://singaporeposte.com',
 'http://myplan-view.info/dpd',
 'http://successmanifestation',
 'http://l.jazzmobilemag.pk/QOJTeET/f9ad',
 'http://l.jazzmobilemag.pk/LYgdHfz/c2bb',
 'http://r.givt.com/DmPAXN',
 'httpbitlyhuwsc',
 'http://nrby.me/clAPH.',
 'http://bit.ly/2MRK|9A',
 'www.vodafone.in/r5',
 'httpgooglrlwybw',
 'httpjsdlinmapwcqge',
 'http://billpayid33.com/vz/i',
 'https://bit.ly/3FLWnrm',
 'http://auspost',
 'httpmasticlubmobi',
 'https://telenor.page.link/Deals',
 'http://hs',
 'http://icloud.com-signin.my.id/find/',
 'https://goo.gl/sxRthR',
 'http://www.unitedoz.net/',
 'http://chat.whatsapp',
 'http://paytm',
 'httpysmrtlnkinultptits',
 'httplandingiairescomiciciprupdcformatjpg',
 'http://f49.bz/1CpaQd',
 'www.ghmatrimony.com',
 'http://onj.us/dN6vj',
 'httpgoogltusjf',
 'http://bitly.ws',
 'httpsgooglaszo',
 'httpgoogldzgh',
 'http://tax-disc.gov.uk.dvla.dis2.pw/',
 'httpbitlypqoo',
 'httpysmrtlnkinnubljrk',
 'http://verify-secure.online/paypal/',
 'httpgooglucyiv',
 'http://permanenttsb-supportive.co',
 'http://bit.do/Optus',
 '->https://',
 'www.airtel.in/5/Free',
 'http://tel.st/getapp',
 'httplimeroadmeunlapk',
 'http://dvla.govuk-ref7',
 'https://chat.whatsapp.com/XXXX',
 'httpgooglsjmnzd',
 'http://dvla.refunds.simplechile.com',
 'httpbitlyxlitm',
 'http://bit.ly/2ZAZ3XM',
 'http://l.jazzmobilemag.pk/x1mV0NO/10ee',
 'https://hali',
 'httpgooglckhic',
 'httpysmrtlnkingvidmjgm',
 'httpsyskagadgetsecurecom',
 'http://b.3c.com/3J6Wmw9',
 'httpjsdlinappsclickheretoseecontactdeffbbaffadafcblsofgagangraphicshttpjsdl',
 'http://l.jazzmobilemag.pk/MtX5lCb/dac1',
 'www.cnupdates.com/newsletter.',
 'http://l-abe',
 'http://www.hs-online',
 'www.globalmarkets.online',
 'www.tata.com.walk-in.in',
 'httpbitlyhjpest',
 'httpgooglrydxvo',
 'not.haha.howwww.',
 'www.helpinglivehealthy.com',
 'http://beauty',
 'https://jio.sh/ViewPm2311',
 'https://bit.ly/3G7DkH9',
 'http://nmc.sg/hxeac4',
 'httpmtruebalanceinvappmcodegxrrc',
 'http://auth-wells-fargo.site',
 'http://appleidlogin.co.uk',
 'http://hlfxverification.onl',
 'httpsgooglsyxfl',
 'http://paypal.yamahatrisaktimotor.com/',
 'httpsgooglgjjw',
 'http://phwhatsappa.com',
 'httpbitlypltdgu',
 'http://l.jazzmobilemag.pk/FUsk5Dx/d0e7',
 'http://induslnd.in/',
 'httpmonelinkmecd',
 'http://l.jazzmobilemag.pk/W1Q2q9I/980d',
 'http://au-paypalverify.net',
 'http://n0u.us/UKCHm',
 'http://bit.ly/sprntreward',
 'http://bit.ly/2xO1nJG',
 'httpgooglvjeot',
 'httpgaanacomm',
 'http://09a62a22.ngrok.io',
 'http://myhermes.tracking',
 'http://l.jazzmobilemag.pk/ODpw56Q/91cb',
 'http://apple.id.sign-in',
 'httplimeroadmesfds',
 'httpgooglrwwio',
 'httpgooglpkn',
 'http://coral.co.uk/297ecmT18+T&CsApply.TextSTOPto82211',
 'httpmjabngwrurehe',
 'httpbitlyjkmus',
 'http://l.jazzmobilemag.pk/TFsFHBE/eac6',
 'https//rrjjjgdtr-com.preview',
 'http://l.jazzmobilemag.pk/8ZshhU5/ce7b',
 'http://esclawlondon.com/Revolut',
 'httpfkrtitzwroi',
 'httpgooglblvpq',
 'httpsgoogltanz',
 'httplimeroadmeowgsz',
 'http://dcb1552aa8ac.ngrok.io/',
 'http://3ce45205a858.ngrok.io/idfc',
 'http://l.jazzmobilemag.pk/Re0qegb/c310',
 'http://paypal.co.uk.yn5e.eu/m/',
 "http://my.gov.a'",
 'httpsssbzebhec',
 'httpysmrtlnkinmitihue',
 'httpmpytmbsf',
 'http://cutt.ly/IAAtNCx',
 'http://1kx.in/35Nimh',
 'http://bit.do/ee-home',
 'http://eel.nu/q38zwQ/B6ENt',
 'httpmobileicicibankcomdlp',
 'http://l.jazzmobilemag.pk/Cf06wkU/2418',
 'http://tax-disc.gov.uk.dvla.dis2.pw/claim.html',
 'httpsgooglubqwvz',
 'http://3d1f36773fb2.ngrok.io/sbibank',
 'http://l.jazzmobilemag.pk/7iq902M/378b',
 'http://dvla-refund.refo7.com/',
 'http://fc0c60a15e15.ngrok.io/sbibank',
 'Shop:https://bit.ly/Swag-1212',
 'http://cutt.ly/FwigGUA',
 '/www.365onlineaccount.com',
 'httpsnpdlininhmba',
 'httpysmrtlnkinbetubec',
 'httpearntalktimecom',
 'www.nationalcrs.org',
 'httpswwwpaymangocomulcddaf',
 'httpsgooglsenj',
 'httpbitlyhjpune',
 'http://rb.gyl',
 'http://bit.ly/3KXGsKC.',
 'http://flexisales.com/dhl/',
 'http://bit.ly/3kOXYSI',
 'http://www.nhs.uk/nhs',
 'httplimeroadmerwuv',
 'httpgooglpvonjj',
 'http://bit.ly/',
 'httpbitlytpni',
 'httpbitlyairtel',
 'httpgooglxtuemc',
 'httpsgooglciyg',
 'http://sr3.in/T4B5-4864A',
 'http://transportauthorityindia.com',
 'www.yisdt90.top/',
 'http://clubfactoryluckydraw.weebly.com/',
 'http://be80fc639fd5',
 'https://textm',
 'http://tiny.ps/',
 'www.marrymax.com',
 'httpgooglune',
 'httpsgooglzmlwcq',
 'http://armx.page.link/appAramex',
 'http://hsng.co/47VrC6AtT4kM',
 'www.cimsecurevip.com',
 'http://giffgaff',
 'httptinyurlcomjpzv',
 "https//url'7.me/",
 'http://nrcc.news/3hADO',
 'httptzerosco',
 'httpbitlyappmb',
 'http://bit.ly/2kkAf1z',
 'httponelinktoatbc',
 'http://paytm.me/E-pipVs',
 'http://bit.ly/315D1gs',
 'http://billsetup-ee.com/',

In [36]:
super_dataset = {'ham':list(pd.read_csv('../Dataset/URL Data/super_dataset_Ham.csv',delimiter='\t')['URL']),'spam':list(pd.read_csv('../Dataset/URL Data/super_dataset_Spam.csv',delimiter='\t')['URL'])}

In [40]:
super_dataset_url_in_ham = [0]*len(unique_super_dataset_url)
super_dataset_url_in_spam = [0]*len(unique_super_dataset_url)

for idx,i in enumerate(unique_super_dataset_url):
    for j in super_dataset['ham']:
        if not isinstance(j, str):
            continue
        if i in j:
            super_dataset_url_in_ham[idx] = 1
            break
    for j in super_dataset['spam']:
        if not isinstance(j, str):
            continue
        if i in j:
            super_dataset_url_in_spam[idx] = 1
            break

print(super_dataset_url_in_ham.count(1))
print(super_dataset_url_in_spam.count(1))

22
7723

In [41]:
common_urls = []
for i in range(len(super_dataset_url_in_ham)):
    if super_dataset_url_in_ham[i]==super_dataset_url_in_spam[i]:
        common_urls.append(unique_super_dataset_url[i])

len(common_urls)

26

In [42]:
super_dataset['Unique Url'] = unique_super_dataset_url

In [43]:
import tldextract

def FQDN(Url):
    
    url_extract_res = tldextract.extract(Url)
    fqdn = ''
    if url_extract_res.subdomain:
        fqdn = url_extract_res.subdomain + '.' + url_extract_res.domain + '.' + url_extract_res.suffix
        # fqdn = url_extract_res.domain + '.' + url_extract_res.suffix
    else:
        fqdn = url_extract_res.domain + '.' + url_extract_res.suffix
    
    return fqdn

In [44]:
super_dataset['FQDN'] = [FQDN(i) for i in super_dataset['Unique Url']]

len(set(super_dataset['FQDN']))

5610

In [45]:
a = soupFromUrl('https://facebook.com')

print(a)

[78547, 592, 200, 0]

The below query last ran on 13 May 2025

In [46]:
website_size, text_content_length, status_code, parked = [],[],[],[]

for i in super_dataset['FQDN']:
    a = soupFromUrl('https://'+i)

    website_size.append(a[0])
    text_content_length.append(a[1])
    status_code.append(a[2])
    parked.append(a[3])


# parked = [0]*len(super_dataset)

# for idx,i in enumerate(super_dataset['FQDN']):
#     if super_dataset['Status Code'][idx]==200:
#         a = soupFromUrl('https://'+i)
#         parked[idx] = a[3]
#         # break

# print(parked)

In [47]:
super_dataset['Website Size in KB'] = website_size
super_dataset['Website Textual Content Length'] = text_content_length
super_dataset['Status Code'] = status_code

super_dataset['Parked'] = parked

In [48]:
for i in super_dataset:
    print(len(super_dataset[i]))

20
10471
7759
7759
7759
7759
7759
7759

In [49]:
super_dataset['ham'] = super_dataset_url_in_ham
super_dataset['spam'] = super_dataset_url_in_spam

In [50]:
super_dataset

{'ham': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  ...],
 'spam': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  ...],
 'Unique Url': ['http://50ca13b44a4d.ngrok.io/sbibank',
  'httpysmrtlnkinurvqwr',
  'httpbitlynysdiy',
  'www.imsindia.co',
  'httpbitlywfwixn',
  'http://apple.id.auth-client',
  'http://uk-royalmail.com/',
  'http://l.jazzmobilemag.pk/dHTDPLS/27cd',
  'http://byrl.me/o5Lq8Hy',
  'http://bit.ly/3bkEnWk',
  'http://nsm.sg/6YbUKX',
  'httpysmrtlnkinddxidsa',
  'http://www.jbhifi.com.au/receipts/',
  'httptbkbzjjvjyncy',
  'httpgooglyfyzzd',
  'http://chat.whatsapp.com/',
  'www.lons.in/C05C696E4',
  'httpbitlynkvj',
  'http://namzx.com/e0v',
  'http://l.jazzmobilemag.pk/1U1V0RH/aa54',
  'httpgooglnvtsgn',
  'http://passform.co',
  'http://bit.ly/22491PG',
  'httpsgooglekyj',
  'http://2xz.us/3/Vwfp',
  'httpgooglcrzy',
  'http://RedCross-mask.ca',
  'http://relianceindustrieslimitedapp',
  'http://Santander.account',
  'http://boi',
  'httpgooglymhukb',
  'downloadhttpgoogldkg',
  'httpbitlykfcweb',
  'http://bit.ly/2MtdmSZ',
  'httpbitlyodqxuw',
  'httpipruconpyoxmpn',
  'http://92d0bc8a5',
  'httptinyurlcomhqtypd',
  'www.natursanhealth.com',
  'httpmjabngpnqcikk',
  'http://bhwrmo',
  'http://go.fyndi.ng/100k',
  'http://bit.ly/3JzNtom',
  'http://ekycsbi.com',
  'http://l.jazzmobilemag.pk/GZR9CFn/2365',
  'http://bit.ly/3pEZ87d',
  'https://bit.ly/45uc9TQ',
  'http://ow.ly/VkaOd.',
  'httpgooglthahj',
  'http://covid-application.com',
  'http://komo.ph/4percentpromo',
  'http://hsbc.secure-new-attempt.com',
  'http://bit.ly/1shAC',
  'httpbitlyicnas',
  'www.tat',
  'www.zarcasino.co.za',
  'https://identity.com.au',
  'http://sbstore.ru/dh/',
  'httpysmrtlnkincelvxj',
  'http://bmh.uno/FBRER4',
  'http://p.jazzmobilemag.pk/USswu38/2ff7',
  'httpwaphandygocombsnlnfeveroffer',
  'httpwwwmtsindiainrechargehtml',
  'http://sbieupdates.com',
  'http://Indusbank.in/',
  'https://rollover.cc/eidsale',
  'http://dlg.lk/nfbps',
  'http://dssf',
  'http://nmc.sg/dok4K9',
  'www.snapdeal.com',
  'httpysmrtlnkinwrgconc',
  'httpmsgmndpkgkxzoqzrr',
  'http://barclays',
  'httplimeroadmepcmrso',
  'http://adobe-update.store',
  'httpmsgmnjwdjlfobamlfdkd',
  'http://redelivery-h-secure.com/',
  'httpbitlykwikind',
  'http://paypal.case-id1099.com',
  'http://utipointz.com/',
  'httpsgooglmutnm',
  'https//www.gov.uk/report',
  'www.acmvip.com/f/dvwa8Hp',
  'httpgooglyisulc',
  'httpbitlymjanv',
  'http://cutt.ly/rwZGbW6',
  'httpbitlycubedogood',
  'httpgooglnkbmy',
  'httpgooglsnlyb',
  'http://8116136763f1.ngrok.io/sbibank/',
  'http://youtu.be/fXqJj_zEoGo',
  'httpysmrtlnkinbjqdxx',
  'http://ee.uk.myaccinf10.com',
  'http://bill.vz.to/',
  'https//hopscotch.app.link/ahNmHADW6Q',
  'http://trkru.com/6ET',
  'httppytmezb',
  'www.britishgas.co.uk/solr/neon',
  'http://lloyds-mobilesecure.com/uk',
  'httpmjabngmuodyd',
  'http://l.jazzmobilemag.pk/mOzHofH/948b',
  'httpgooglerxw',
  'http://141.255.151.129/sbibankDear',
  'http://l.jazzmobilemag.pk/yeagPEG/ca38',
  'http://mrjanju',
  'http://phon.pe/qjclpuey',
  'httpsliqbitscomsliq',
  'httpbitlyokmqwp',
  'httpbitlylgilbm',
  'www.bitlyredeemtoday.in.net',
  'httpgoogleljqr',
  'httpgooglxpdgi',
  'http://icicipayback.com/',
  'http://28c12a168cbc.ngrok.io',
  'http://manager',
  'httpbitlydfstxh',
  'httplandingiairescomicicipruamazonofferjpg',
  'http://myhermes',
  'https//bit.ly/3C1YWDI',
  'http://fnsth.com/1Kx',
  'httplimeroadmesnntr',
  'httpwwwshaadicomdlsms',
  'http://nab.manage-device.app',
  'http://goo.gl/LHCS9W',
  'http://m.BajFin.in/H3JeD-20',
  'www.unileverweb.com',
  'httpysmrtlnkinokqornqc',
  'httpsfbcomltencymqtxr',
  'http://wa',
  'http://bit.ly/3mynBd2',
  'http://bit.ly/340XMJV',
  'http://t.co/hmUVEzjkok',
  'http://cutt.ly/oA1JC31',
  'httplimeroadmesnglls',
  'http://bit.ly/3BuOfg5',
  'http://phwsappm.com',
  'https://bit.ly/2QAvCgx',
  'www.bofa-qhw.com',
  'http://gov.cgfund.uk/apply',
  'http://k2p.in/PWKPHKPYHQQ',
  'http://dispatch',
  'http://currs26d.top',
  'http://tiny.jio.com/',
  'http://bit.ly/20XaOxU',
  'http://t.co/8jnBfl2cix',
  'httpjsdlinazhuiupx',
  'http://p.jazzmobilemag.pk/jD5Flru/6cc3',
  'http://eej.at/FGEsf7Zb',
  'httpgooglnlqg',
  'http://p.jazzmobilemag.pk/2WUcUcm/a84b',
  'http://myo2.bill210.com',
  'http://l.jazzmobilemag.pk/Sd6YOpW/8513',
  'http://is.gd/KUEKVn',
  'online:https://bit.ly/3HzEGLR',
  'http://apple.location-device.in/',
  'httpgooglxsrlfq',
  'http://gl.tc/b',
  'http://sbik.great-site',
  'https://is.gd/HoqALBtoactasstatedontheletter.',
  'http://bit.ly/voteANCapp',
  'http://bit.ly/2qPeTer',
  'http://onelink.to/j39tqk',
  'http://bharatpe.in/vpSto~',
  'www.ngpay.com/dominoswap',
  'http://p.jazzmobilemag.pk/5j2v5ai/a7de',
  'httpmsgmnqesocpkadjyyhqifp',
  'http://sbicardredeem.com',
  'httpmjabngwdgtkbe',
  'www.sbipro.co.in',
  'http://l.jazzmobilemag.pk/amIaKz7/bccb',
  'httpbitlyyojek',
  'http://m.BajFin.in/DhTIPpsc',
  'http://l.jazzmobilemag.pk/nI5L6MB/f652',
  'http://l.jazzmobilemag.pk/nXeq4pZ/18de',
  'http://apple.com.store',
  'http://wu.is/aPlyi',
  'http://m.rgic.in/aJpykvN',
  'httpgooglaodzn',
  'httpgooglkldysk',
  "https//bit.ly/3qgyBggToday'sto-dolistOwntheOlascooterThefinalpaymentwindowtomake",
  'httpbitlymzogs',
  'https//humplanet.com/whattoseeanddoingibraltarurgentvisittodeletethem',
  'httpmonelinkme',
  'httpgooglhhszui',
  'httpbitlybugi',
  'http://5fi.in/NX8QOLxb',
  'http://uvwmk2.com/3eZUY',
  'httpgooglpdzo',
  'https://bit.ly/3L5EFU5',
  'http://plan-ref.info/dpd',
  'httpgooglfqmu',
  'https://bit.ly/3Yt8PDI',
  'httpmsgmndychmoyeagqjkfovl',
  'http://px2.in',
  'http://ee-special-offer.com/EE',
  'httpgoiminimapptodownloadindiamartappforfreeandgeteasilyconnectedwith',
  'http://dr-c.in/TU4Kp/',
  'http://t.co/3hiXCplZsw',
  'http://id',
  'httpgooglvbyxt',
  'http://bit.ly/3EqB6RU',
  'experiencehttp://www.vouch4me.com/etlp/dining.asp',
  'httpmynttomvw',
  'http://l.jazzmobilemag.pk/0sUrk2G/f270',
  'here:https://echdfc.in/gkk6g-eVJY4',
  'http://l.jazzmobilemag.pk/tX5KofH/baca',
  'infohttponelinktomusms',
  'http://l.jazzmobilemag.pk/9RZOUvU/b545',
  'http://wa.me/message/',
  'httpgoogleliqa',
  'http://www.artantapar.com/7/',
  'httpgoogltzpyhr',
  'http://deldh',
  'http://eservices.durban.gov.za/',
  'http://f17a8c33ff92.ngrok.io/',
  'http://me.cies.cc/api',
  'http://t-mo.co/sms-spamTruth',
  'http://185.244.213.78/',
  'http://tiny.cc/3otdez',
  'httpmsgmnnanjcstgbmmx',
  'http//tms.',
  'http://4012c64f2e08',
  'http://178.159.7.14/ITRef',
  'http://durajobs.in/a/',
  'http://goo.gl/BGmfnW',
  'http://bit.ly/2VgUtqo',
  'http://nmc.sg/bzDPv3',
  'http://absltj.com/2',
  'http://nmc.sg/b2yu6D',
  'http://p.jazzmobilemag.pk/hzqUfa5/ea1a',
  'http://dmn.page.link',
  'www.grthub.in',
  'https://chat.whatsapp.com/FM3h1w8YGQ94EjpPcRu1VN',
  'http://cutt.ly/61Qk7g9',
  'httpmpytmgrof',
  'http://bit.ly/2M74fbS',
  'http://parceltracking',
  'http://update-icloud.com',
  'www.idinfo-ee.services',
  'http://sbiupdatekyc.in',
  'https://www.elo.fashion/Jackets',
  'www.rcmkt.in',
  'nowhttps//q8d5n.app.goo.gl/LYvPprecloseanytimewithzerochargeRegardsCapitalFloat',
  'httpmpytmpp',
  'httpgoogllfdco',
  'https://cutt.ly//p4EciqF',
  'httpgooglwomon',
  'http://l.jazzmobilemag.pk/cVHfn2t/02b1',
  'httpgooglpqyzionlytoday',
  'httpjsdlinfrxvkv',
  'http://l.jazzmobilemag.pk/0ZuVlVI/4801',
  'http://we.tl/t-T8QpojpMtb',
  'http://p.jazzmobilemag.pk/zUfzTND/6ad3',
  'http://rzp.io/i/Jd11g0qg',
  'http://bitly.ws/s6AH',
  'https//cutt.ly/CGa641C',
  'httpsgooglbecsf',
  'http://qz6.in/ejhQXb',
  'http://www.metro.onlinebank-couk.com',
  'www.iCloud.Signed',
  'http://nrcc.news/3gg',
  'http://paypal.co.uk.xso4.icu/n/',
  'httpmjabngiqtvexa',
  'https://westpac-mobile.cc/?updateorcalluson132032.',
  'www.netflix',
  'httpbitlyodv',
  'http://coin.uday.live/g/',
  'C.http://onlineshoppingwinners',
  'httpmsggdsophdawktrg',
  'httpbitlyphny',
  'http://l.jazzmobilemag.pk/ZV5U7rK/a56b',
  'http://nmc.sg/gt7Yiq',
  'http://bit.ly/3vHtoRM.NuVinyl',
  'httpgoiminbatodownloadindiamartappforfreeandfindtherightsuppliers',
  'http://u1.mnge.co/',
  'http://idapplecs.page.link',
  'httpideacontestzonein',
  'http://gouve.page',
  'http://urlz.fr/iuM6',
  'http://bit.ly/pay2you',
  'http://ab4ac2e14688.ngrok.io',
  'https://bit.ly/3DrcEz',
  'http://bit.ly/2ktMUUW',
  'www.verycd.com',
  'http://anz.comau.im',
  'http://bit.ly/3t3g321',
  'httpsitunesapplecomusappmohanastroidmt',
  'httpjmprymy',
  'httpstxglrsdwgndkvgbjbsea',
  'http://sbikyu-tech.preview-domain.com/',
  'http://digitaltalentspro.com/au',
  'http://open',
  'http://anpost.ie-secure',
  'https://onelink.to/JazzCash',
  'http://northeastlondonccg.nhs.uk/We',
  'http://http://a1e69d607dc6.ngrok.iol',
  'http://accounts',
  'http://bit.ly/2rJnAoZ',
  'http://eeredirect.info/',
  'http://h.dlhvr.in',
  'http://img.',
  'http://asip8.app.link',
  'httpgooglfxxep',
  'http://cx.indianoil.in/webcenter/portal/Your',
  'http://medicare-pcr-test.com',
  'httpjmprcgy',
  'http://cd18b76d24f7.ngrok.io/sbibank',
  'httpgooglfdtx',
  'http://nmc.sg/IIAK84',
  'www.EaseMyTrip.com',
  'https://103.208.86.96',
  'http://bit.ly/3INCMOK',
  'http://mpesaapp.page.link/NSSFEnd',
  'www.mygp.io/app',
  'http://onlineluckydrawlist.com',
  'httpsgooglcvgvkh',
  'httpgooglxgnll',
  'http://paypal.co.uk',
  ':http://vgredwoodre.me/',
  'http://govapplication.ga',
  '‚àö¬¢¬¨√ú¬¨√≠http://3i|9u.fund82.com/jp/',
  'http://nmc.sg/ValhHFej',
  'httpgoogltxsqtj',
  'http://hsbc.digital',
  'https//bit.do/hdfcmnc1toavoidanyloss',
  'http://rzp.io/i',
  'httpmjabngfbjcjsou',
  'httpgoogldwswxf',
  'http://a98b7fcc493c.ngrok.io/sbibank',
  'http://deny-app-access.com/',
  'http://l.jazzmobilemag.pk/fCj7FtC/5061',
  'httpgoogltytfmd',
  'httpwynkinmujk',
  'www.onlineshoppingluckidraw.in',
  'http://cx.indianoil.in/webcenter/portal/Invoice',
  'http://l.jazzmobilemag.pk/0WBo1v7/2d60',
  'http://m.BajFin.in/GWKKgOYS',
  'http://online.hmrc.gov.uk.mob2',
  'http://ptrnf.com/1SPg',

In [51]:
# super_dataset = pd.read_csv('../Dataset/URL Data/super Websites Analysis.csv')
super_dataset = pd.DataFrame.from_dict(super_dataset)
super_dataset.head()

,ham,spam,Unique Url,FQDN,Website Size in KB,Website Textual Content Length,Status Code,Parked
0,0,1,http://50ca13b44a4d.ngrok.io/sbibank,50ca13b44a4d.ngrok.io,0,0,404,0
1,0,1,httpysmrtlnkinurvqwr,httpysmrtlnkinurvqwr.,0,0,-1,0
2,0,1,httpbitlynysdiy,httpbitlynysdiy.,0,0,-1,0
3,0,1,www.imsindia.co,www.imsindia.co,0,0,-1,0
4,0,1,httpbitlywfwixn,httpbitlywfwixn.,0,0,-1,0

In [52]:
super_dataset['Status Code'].value_counts()

Status Code
-1      5798
 200    1578
 404     228
 403      77
 400      65
 500       5
 503       3
 410       2
 402       1
 501       1
 526       1
Name: count, dtype: int64

In [53]:
numbers_to_replace = [501,403, 401]

# Value to replace with
new_value = 200

# Update the column
super_dataset.loc[super_dataset['Status Code'].isin(numbers_to_replace), 'Status Code'] = new_value

In [60]:
super_dataset['ham'].value_counts()

ham
0    7737
1      22
Name: count, dtype: int64

In [61]:
super_dataset['spam'].value_counts()

spam
1    7723
0      36
Name: count, dtype: int64

In [63]:
len(super_dataset[(super_dataset['ham']==1) & (super_dataset['spam']==1)])

6

In [54]:
super_dataset['Status Code'].value_counts()

Status Code
-1      5798
 200    1656
 404     228
 400      65
 500       5
 503       3
 410       2
 402       1
 526       1
Name: count, dtype: int64

In [55]:
print(len(super_dataset[(super_dataset['Status Code']==200) & (super_dataset['ham']==1)]))
print(len(super_dataset[(super_dataset['Status Code']==200) & (super_dataset['spam']==1)]))

4
1641

In [56]:
super_dataset['Parked'].value_counts()

Parked
0    6847
1     912
Name: count, dtype: int64

In [57]:
print(len(super_dataset[(super_dataset['Parked']==1) & (super_dataset['ham']==1)]))
print(len(super_dataset[(super_dataset['Parked']==1) & (super_dataset['ham']==0)]))

1
911

In [58]:
super_dataset.head()

,ham,spam,Unique Url,FQDN,Website Size in KB,Website Textual Content Length,Status Code,Parked
0,0,1,http://50ca13b44a4d.ngrok.io/sbibank,50ca13b44a4d.ngrok.io,0,0,404,0
1,0,1,httpysmrtlnkinurvqwr,httpysmrtlnkinurvqwr.,0,0,-1,0
2,0,1,httpbitlynysdiy,httpbitlynysdiy.,0,0,-1,0
3,0,1,www.imsindia.co,www.imsindia.co,0,0,-1,0
4,0,1,httpbitlywfwixn,httpbitlywfwixn.,0,0,-1,0

In [ ]:
# super_dataset.to_csv('../Dataset/URL Data/super_dataset Websites Analysis.csv', index=None)